[package]
name = "nbd-cow"
version = "0.4.80"
edition.workspace = true

[[bin]]
name = "bench"
path = "src/bin/bench/main.rs"
required-features = ["bench"]

[features]
bench = ["dep:serde_json", "dep:tempfile", "dep:which"]

[dependencies]
bitvec = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["fs", "socket", "uio"] }
serde_json = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
which = { workspace = true, optional = true }

[dev-dependencies]
nix = { workspace = true, features = ["user"] }
tempfile = { workspace = true }
tracing-subscriber.workspace = true
tracing-test-support.workspace = true

[lints]
workspace = true
