[package]
name = "nbd-cow"
version = "0.4.85"
edition.workspace = true

[[bin]]
name = "bench"
path = "src/bin/bench/main.rs"
required-features = ["bench"]

[features]
bench = ["dep:serde_json", "dep:tempfile", "dep:which"]

[dependencies]
bitvec = { workspace = true, features = ["atomic", "std"] }
libc = { workspace = true, features = ["std"] }
nix = { workspace = true, features = ["fs", "socket", "uio"] }
serde_json = { workspace = true, features = ["std"], optional = true }
tempfile = { workspace = true, features = ["getrandom"], optional = true }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
tracing = { workspace = true, features = ["attributes", "std"] }
uuid = { workspace = true, features = ["std", "v4"] }
which = { workspace = true, features = ["real-sys"], optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
nix = { workspace = true, features = ["user"] }
tempfile = { workspace = true, features = ["getrandom"] }
tracing-subscriber = { workspace = true, features = ["ansi", "fmt", "smallvec", "std", "tracing-log"] }
tracing-test-support.workspace = true

[lints]
workspace = true
