import { optionalEnv } from "../../../lib/env";
import { logger } from "../../../lib/log";
import { settle } from "../../utils";

const log = logger("api:automations:describe");

const OPENROUTER_CHAT_COMPLETIONS_URL =
  "https://openrouter.ai/api/v1/chat/completions";
const LIGHTWEIGHT_MODEL = "google/gemini-3.1-flash-lite-preview";

interface ChatMessage {
  readonly role: "system" | "user";
  readonly content: string;
}

interface OpenRouterResponse {
  readonly choices: readonly {
    readonly message: {
      readonly content: string;
    };
  }[];
}

/**
 * The trigger facts the description prompt summarizes. Optional fields mirror
 * the deploy/create request shapes: exactly one of them is set for a time
 * trigger, none for a triggerless automation.
 */
interface DescribeAutomationInput {
  readonly name: string;
  readonly instruction: string;
  readonly cronExpression?: string;
  readonly atTime?: string;
  readonly intervalSeconds?: number;
}

function stripMarkdown(text: string): string {
  return text
    .replace(/(\*{1,3}|_{1,3})(.+?)\1/g, "$2")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/^[-*_]{3,}\s*$/gm, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^["'](.+)["']$/, "$1")
    .trim();
}

async function generateText(
  messages: readonly ChatMessage[],
  maxTokens: number,
): Promise<string | null> {
  const apiKey = optionalEnv("OPENROUTER_API_KEY");
  if (!apiKey) {
    return null;
  }

  const response = await fetch(OPENROUTER_CHAT_COMPLETIONS_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: LIGHTWEIGHT_MODEL,
      messages,
      max_tokens: maxTokens,
      temperature: 0.3,
    }),
  });

  if (!response.ok) {
    const settled = await settle(response.text());
    const text = settled.ok ? settled.value : "unknown error";
    throw new Error(`OpenRouter request failed: ${response.status} ${text}`);
  }

  const data = (await response.json()) as OpenRouterResponse;
  const content = data.choices[0]?.message.content.trim();
  if (!content) {
    throw new Error("OpenRouter returned empty content");
  }
  return stripMarkdown(content);
}

function buildTemplateDescription(
  input: DescribeAutomationInput,
  agentName: string,
): string {
  const triggerLabel = input.cronExpression
    ? "recurring"
    : input.atTime
      ? "one-time"
      : "loop";
  return `${agentName} ${triggerLabel} task: ${input.instruction.slice(0, 100)}`;
}

function triggerSummary(input: DescribeAutomationInput): string {
  if (input.cronExpression) {
    return `cron: ${input.cronExpression}`;
  }
  if (input.atTime) {
    return `once at ${input.atTime}`;
  }
  if (input.intervalSeconds !== undefined) {
    return `loop every ${input.intervalSeconds}s`;
  }
  return "unknown trigger";
}

/**
 * One-sentence automation description for list views, generated by a
 * lightweight model with a deterministic template fallback (also used when no
 * OPENROUTER_API_KEY is configured).
 */
export async function generateAutomationDescription(
  input: DescribeAutomationInput,
  agentName: string,
): Promise<string> {
  const result = await settle(
    generateText(
      [
        {
          role: "system",
          content:
            "Write a one-sentence summary (max 120 chars) for a scheduled task as plain text -- no markdown, no quotes, no special formatting. Return only the summary.",
        },
        {
          role: "user",
          content: `Agent: ${agentName}\nSchedule: ${input.name}\nTrigger: ${triggerSummary(input)}\nPrompt: ${input.instruction.slice(0, 200)}`,
        },
      ],
      30,
    ),
  );

  if (!result.ok) {
    log.warn("Automation description generation failed, using fallback", {
      error:
        result.error instanceof Error
          ? result.error.message
          : String(result.error),
      automationName: input.name,
    });
    return buildTemplateDescription(input, agentName);
  }

  return result.value ?? buildTemplateDescription(input, agentName);
}
