/**
 * Feature switch keys
 *
 * Defines all available feature switch identifiers.
 */
export enum FeatureSwitchKey {
  Dummy = "dummy",
  AhrefsConnector = "ahrefsConnector",
  Base44Connector = "base44Connector",
  BentomlConnector = "bentomlConnector",
  CanvaConnector = "canvaConnector",
  ComputerConnector = "computerConnector",
  DeelConnector = "deelConnector",
  DocuSignConnector = "docusignConnector",
  DropboxConnector = "dropboxConnector",
  FigmaConnector = "figmaConnector",
  MercuryConnector = "mercuryConnector",
  NeonConnector = "neonConnector",
  GarminConnectConnector = "garminConnectConnector",
  RedditConnector = "redditConnector",
  SupabaseConnector = "supabaseConnector",
  WebflowConnector = "webflowConnector",
  CloseConnector = "closeConnector",
  OutlookMailConnector = "outlookMailConnector",
  OutlookCalendarConnector = "outlookCalendarConnector",
  GoogleAdsConnector = "googleAdsConnector",
  MetaAdsConnector = "metaAdsConnector",
  StripeConnector = "stripeConnector",
  CliAuthStripe = "cliAuthStripe",
  CodexDeviceAuth = "codexDeviceAuth",
  PosthogConnector = "posthogConnector",
  PwaOfflineCache = "pwaOfflineCache",
  MailchimpConnector = "mailchimpConnector",
  ResendConnector = "resendConnector",
  DataExport = "dataExport",
  SpotifyConnector = "spotifyConnector",
  GitHubIntegration = "githubIntegration",
  ZeroDebug = "zeroDebug",
  ComputerUse = "computerUse",
  LocalBrowserUse = "localBrowserUse",
  LocalAgentConnector = "localAgentConnector",
  DesktopLocalAgent = "desktopLocalAgent",
  Lab = "lab",
  AuditLink = "auditLink",
  AudioOutput = "audioOutput",
  AutoSkill = "autoSkill",
  TestOauthConnector = "testOauthConnector",
  ChatHeaderNewButton = "chatHeaderNewButton",

  ChatMessageStartButton = "chatMessageStartButton",
  ChatThreadRename = "chatThreadRename",
  DocsSite = "docsSite",
  FreshdeskConnector = "freshdeskConnector",
  StabilityAiConnector = "stabilityAiConnector",
  ZoomConnector = "zoomConnector",
  ApiKeys = "apiKeys",
  ApiBackend = "apiBackend",
  ConnectorCategories = "connectorCategories",
  StoredSecretKmsRead = "storedSecretKmsRead",
  StoredSecretKmsWrite = "storedSecretKmsWrite",
  PersistentSecretKmsRead = "persistentSecretKmsRead",
  PersistentSecretKmsWrite = "persistentSecretKmsWrite",

  Trinity = "trinity",
  ZapierConnector = "zapierConnector",
  VoiceChatRealtimeBilling = "voiceChatRealtimeBilling",
  HostedSites = "hostedSites",
  SandboxIoLimiters = "sandboxIoLimiters",
  ZeroMaps = "zeroMaps",
  UnifiedSettings = "unifiedSettings",
}
