/**
 * Feature switch keys
 *
 * Defines all available feature switch identifiers.
 */
export enum FeatureSwitchKey {
  Dummy = "dummy",
  ExternalConnectorCatalog = "externalConnectorCatalog",
  AhrefsConnector = "ahrefsConnector",
  BillConnector = "billConnector",
  BentomlConnector = "bentomlConnector",
  BoxConnector = "boxConnector",
  CanvaConnector = "canvaConnector",
  CalComConnector = "calComConnector",
  CopperConnector = "copperConnector",
  DatadogConnector = "datadogConnector",
  DeelConnector = "deelConnector",
  DocuSignConnector = "docusignConnector",
  DropboxConnector = "dropboxConnector",
  FigmaConnector = "figmaConnector",
  ExpensifyConnector = "expensifyConnector",
  GoogleContactsConnector = "googleContactsConnector",
  GoogleFormsConnector = "googleFormsConnector",
  MercuryConnector = "mercuryConnector",
  NeonConnector = "neonConnector",
  NetSuiteConnector = "netSuiteConnector",
  GarminConnectConnector = "garminConnectConnector",
  QuickBooksConnector = "quickbooksConnector",
  RedditConnector = "redditConnector",
  SupabaseConnector = "supabaseConnector",
  WebflowConnector = "webflowConnector",
  CloseConnector = "closeConnector",
  MetaAdsConnector = "metaAdsConnector",
  TikTokAdsConnector = "tiktokAdsConnector",
  AwsConnector = "awsConnector",
  PosthogConnector = "posthogConnector",
  PayPalConnector = "payPalConnector",
  RampConnector = "rampConnector",
  MailchimpConnector = "mailchimpConnector",
  ResendConnector = "resendConnector",
  PexelsConnector = "pexelsConnector",
  SpotifyConnector = "spotifyConnector",
  ZeroDebug = "zeroDebug",
  CanonicalSlackIngress = "canonicalSlackIngress",
  CanonicalSlackWebVisibility = "canonicalSlackWebVisibility",
  CanonicalSlackAssets = "canonicalSlackAssets",
  ZeroWeather = "zeroWeather",
  ZeroFinance = "zeroFinance",
  ZeroPeopleSearch = "zeroPeopleSearch",
  Banking = "banking",
  Lab = "lab",
  NotionWorkflowAutomations = "notionWorkflowAutomations",
  GithubWebhookAutomations = "githubWebhookAutomations",
  GithubWorkflowRunAutomations = "githubWorkflowRunAutomations",
  MorningBrief = "morningBrief",
  ManualMorningBrief = "manualMorningBrief",
  TestOauthConnector = "testOauthConnector",
  FreshdeskConnector = "freshdeskConnector",
  StabilityAiConnector = "stabilityAiConnector",
  ZoomConnector = "zoomConnector",
  WorkdayConnector = "workdayConnector",
  CodexFastMode = "codexFastMode",
  RealAgentInPreview = "realAgentInPreview",
  ComposerUploadPopover = "composerUploadPopover",
  StructuredPrompt = "structuredPrompt",

  ZapierConnector = "zapierConnector",
  HtmlArtifactCommentEditing = "htmlArtifactCommentEditing",
  ComputerUseDesktopPlugins = "computerUseDesktopPlugins",
  AgentUnreadIndicators = "agentUnreadIndicators",
  ChatThreadUnifiedSearch = "chatThreadUnifiedSearch",
  ComposerChatThreadSuggestions = "composerChatThreadSuggestions",
  SidebarSubscriptionUsage = "sidebarSubscriptionUsage",
  TeamsIntegration = "teamsIntegration",
  FeishuIntegration = "feishuIntegration",
  PresentationExport = "presentationExport",
  Artifacts = "artifacts",
  HostedArtifactVersions = "hostedArtifactVersions",
  VideoArtifactPosters = "videoArtifactPosters",
  WebsiteTemplateV2 = "websiteTemplateV2",
  PlanUpgradeGuidance = "planUpgradeGuidance",
  OrgPlanEntitlementReads = "orgPlanEntitlementReads",
  WorkflowConnectorReadiness = "workflowConnectorReadiness",
  ZeroMail = "zeroMail",
  ComposerConnectorPermissions = "composerConnectorPermissions",
  ThreeColumnNav = "threeColumnNav",
  ChatHistoryBackfillProgress = "chatHistoryBackfillProgress",
}
