/**
 * Feature switch keys
 *
 * Defines all available feature switch identifiers.
 */
export enum FeatureSwitchKey {
  Dummy = "dummy",
  AhrefsConnector = "ahrefsConnector",
  BentomlConnector = "bentomlConnector",
  BoxConnector = "boxConnector",
  CanvaConnector = "canvaConnector",
  DeelConnector = "deelConnector",
  DocuSignConnector = "docusignConnector",
  DropboxConnector = "dropboxConnector",
  FigmaConnector = "figmaConnector",
  MercuryConnector = "mercuryConnector",
  Microsoft365Connector = "microsoft365Connector",
  NeonConnector = "neonConnector",
  GarminConnectConnector = "garminConnectConnector",
  QuickBooksConnector = "quickbooksConnector",
  RedditConnector = "redditConnector",
  SupabaseConnector = "supabaseConnector",
  WebflowConnector = "webflowConnector",
  CloseConnector = "closeConnector",
  OutlookMailConnector = "outlookMailConnector",
  OutlookCalendarConnector = "outlookCalendarConnector",
  TikTokAdsConnector = "tiktokAdsConnector",
  AwsConnector = "awsConnector",
  PosthogConnector = "posthogConnector",
  MailchimpConnector = "mailchimpConnector",
  ResendConnector = "resendConnector",
  DataExport = "dataExport",
  SpotifyConnector = "spotifyConnector",
  GitHubIntegration = "githubIntegration",
  ZeroDebug = "zeroDebug",
  Banking = "banking",
  Lab = "lab",
  WorkflowsViewer = "workflowsViewer",
  TestOauthConnector = "testOauthConnector",
  FreshdeskConnector = "freshdeskConnector",
  StabilityAiConnector = "stabilityAiConnector",
  ZoomConnector = "zoomConnector",
  ApiKeys = "apiKeys",

  ZapierConnector = "zapierConnector",
  SandboxIoLimiters = "sandboxIoLimiters",
  ChatGithubPrTracking = "chatGithubPrTracking",
  ChatRunGroupFolding = "chatRunGroupFolding",
  ChatTemplatePicker = "chatTemplatePicker",
  VideoTemplatePicker = "videoTemplatePicker",
  MemoryViewer = "memoryViewer",
  MemoryDevRefresh = "memoryDevRefresh",
  PresentationHtmlPptxDownload = "presentationHtmlPptxDownload",
  ChatSlashWorkflowCommands = "chatSlashWorkflowCommands",
  WorkflowGmailEventTriggers = "workflowGmailEventTriggers",
  GoalWorkflows = "goalWorkflows",
  MobileSingleLineComposer = "mobileSingleLineComposer",
  CustomConnectorProposals = "customConnectorProposals",
  ComputerUseDelegatedAuthorization = "computerUseDelegatedAuthorization",
}
