export const TEST_OAUTH_CLIENT_ID = "test-oauth-client";
export const TEST_OAUTH_CLIENT_SECRET = "test-oauth-secret";
export const TEST_OAUTH_ACCESS_SECRET_NAME = "TEST_OAUTH_ACCESS_TOKEN";
export const TEST_OAUTH_REFRESH_SECRET_NAME = "TEST_OAUTH_REFRESH_TOKEN";
export const TEST_OAUTH_API_ACCESS_SECRET_NAME = "TEST_OAUTH_API_ACCESS_TOKEN";
export const TEST_OAUTH_API_REFRESH_SECRET_NAME =
  "TEST_OAUTH_API_REFRESH_TOKEN";
