[package]
name = "guest-contracts"
version = "0.13.8"
edition.workspace = true
description = "Shared contracts between runner and guest binaries"

[dependencies]
api-contracts.workspace = true
base64 = { workspace = true, features = ["simd-unsafe", "std"] }
chrono = { workspace = true, features = ["alloc"] }
libc = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
uuid = { workspace = true, features = ["std", "v4"] }

[dev-dependencies]
process-control-ipc.workspace = true
tempfile = { workspace = true, features = ["getrandom"] }

[lints]
workspace = true
