export const PLATFORM_CLIENT_VERSION_HEADER = "X-Client-Version";
export const PLATFORM_CLIENT_TYPE_HEADER = "X-Client-Type";
export const PLATFORM_CLIENT_SESSION_ID_HEADER = "X-Client-Session-Id";
export const PLATFORM_CLIENT_REQUEST_ID_HEADER = "X-Client-Request-Id";

export const PLATFORM_CLIENT_HEADER_NAMES = [
  PLATFORM_CLIENT_VERSION_HEADER,
  PLATFORM_CLIENT_TYPE_HEADER,
  PLATFORM_CLIENT_SESSION_ID_HEADER,
  PLATFORM_CLIENT_REQUEST_ID_HEADER,
] as const;
