export const SSH_ERROR_CODES = {
  UNAVAILABLE: "SSH_UNAVAILABLE",
  AGENT_UNAVAILABLE: "SSH_AGENT_UNAVAILABLE",
  INVALID_INPUT: "SSH_INVALID_INPUT",
  INVALID_HOST: "SSH_INVALID_HOST",
  CONNECTION_NOT_FOUND: "SSH_CONNECTION_NOT_FOUND",
  GENERATION_CONFLICT: "SSH_GENERATION_CONFLICT",
} as const;

export type SshErrorCode =
  (typeof SSH_ERROR_CODES)[keyof typeof SSH_ERROR_CODES];
