"""Shared invalid hostname identity test cases."""

import pytest

ONLY_DOTS_HOSTNAME = "..."

INVALID_IDNA_HOSTNAME_CASES = (
    pytest.param("\uff21.example", id="fullwidth-latin"),
    pytest.param(ONLY_DOTS_HOSTNAME, id="dots"),
    pytest.param("api.github.com..", id="multiple-trailing-dots"),
    pytest.param("api%2egithub.com", id="percent-encoded-dot"),
    pytest.param("b%C3%BCcher.example", id="percent-encoded-unicode"),
    pytest.param("xn--.com", id="empty-punycode-label"),
    pytest.param("xn--a.com", id="short-punycode"),
    pytest.param("xn--zzzz.example", id="invalid-punycode"),
    pytest.param("xn--ph7c.example", id="disallowed-punycode"),
    pytest.param("\u4f8b\uff1a\u5b50.example", id="fullwidth-colon"),
    pytest.param("\u4f8b\uff0c\u5b50.example", id="fullwidth-comma"),
    pytest.param("\u212a.example", id="kelvin-sign"),
    pytest.param("\u1e9e.de", id="capital-eszett"),
    pytest.param("\u03f2.example", id="lunate-sigma"),
    pytest.param("\u034f.example", id="combining-grapheme-joiner"),
    pytest.param("\u0301.example", id="leading-combining-mark"),
    pytest.param("\ufe0f.example", id="variation-selector"),
    pytest.param("xn--rld.example", id="invalid-rld"),
    pytest.param("xn--f09a.example", id="invalid-f09a"),
    pytest.param("xn--hsg.example", id="invalid-hsg"),
    pytest.param("xn--43f.example", id="invalid-43f"),
    pytest.param("\u00a8.example", id="diaeresis"),
    pytest.param("\u10a0.example", id="georgian-asomtavruli"),
    pytest.param("\u04c0.example", id="cyrillic-palochka"),
    pytest.param("\ufe12.example", id="presentation-comma"),
    pytest.param("\ufffc.example", id="object-replacement"),
    pytest.param("\u05d0a\u05d0.example", id="rtl-ltr-rtl"),
    pytest.param("\u05d01\u0662.example", id="rtl-european-arabic-number-mixing"),
    pytest.param("\u05d0-.example", id="rtl-invalid-terminal-class"),
    pytest.param("\u0754\u3d20.example", id="invalid-arabic-context"),
    pytest.param("a\u0754b.example", id="arabic-between-latin"),
    pytest.param("\u25a5\u33d5\u067a.example", id="invalid-script-context"),
    pytest.param("\u28a8\u17b5.example", id="invalid-khmer-context"),
    pytest.param("\u0663a.example", id="arabic-digit-before-latin"),
    pytest.param("\u0663!.example", id="arabic-digit-symbol"),
    pytest.param("\u0663\u067aa.example", id="arabic-digit-arabic-latin"),
    pytest.param("a\u0663b.example", id="latin-arabic-digit-latin"),
    pytest.param("a\u0663\u0664.example", id="latin-arabic-digits"),
    pytest.param("1\u0663.example", id="ascii-and-arabic-digits"),
    pytest.param("!\u0663!.example", id="punctuation-arabic-digit"),
    pytest.param("0177.0.0.1", id="octal-ipv4"),
    pytest.param("127\u30020\u30020\u30021", id="ideographic-dot-ipv4"),
    pytest.param("127.0.0.1\u3002", id="trailing-ideographic-dot-ipv4"),
    pytest.param("\uff11\uff12\uff17.\uff10.\uff10.\uff11", id="fullwidth-ipv4"),
)
