// Auto-generated from Black Forest Labs API docs.
// Source: https://docs.bfl.ai/quick_start/generating_images
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:bfl
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../firewall-types";

export const bflFirewall = {
  name: "bfl",
  description: "Black Forest Labs API",
  placeholders: {
    BFL_API_KEY: "bfl_CoffeeSafeLocalCoffeeSafeLocalCoffeeSafe",
  },
  apis: [
    {
      base: "https://api.bfl.ai",
      auth: {
        headers: {
          "x-key": "${{ secrets.BFL_API_KEY }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://api.eu.bfl.ai",
      auth: {
        headers: {
          "x-key": "${{ secrets.BFL_API_KEY }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://api.us.bfl.ai",
      auth: {
        headers: {
          "x-key": "${{ secrets.BFL_API_KEY }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
