// Auto-generated from Porkbun API docs.
// Source: https://porkbun.com/api/json/v3/spec
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:porkbun
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../firewall-types";

export const porkbunFirewall = {
  name: "porkbun",
  description: "Porkbun",
  placeholders: {
    PORKBUN_API_KEY: "pk1_Coffee5afe10ca1Coffee5afe10ca1Coffee5afe10ca1Coffee5afe10ca",
    PORKBUN_SECRET_API_KEY: "sk1_Coffee5afe10ca1Coffee5afe10ca1Coffee5afe10ca1Coffee5afe10ca",
  },
  apis: [
    {
      base: "https://api.porkbun.com/api/json/v3",
      auth: {
        headers: {
          "X-API-Key": "${{ secrets.PORKBUN_API_KEY }}",
          "X-Secret-API-Key": "${{ secrets.PORKBUN_SECRET_API_KEY }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://api-ipv4.porkbun.com/api/json/v3",
      auth: {
        headers: {
          "X-API-Key": "${{ secrets.PORKBUN_API_KEY }}",
          "X-Secret-API-Key": "${{ secrets.PORKBUN_SECRET_API_KEY }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
