//! Mitmdump process supervision.

use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use tokio::io::AsyncBufReadExt;
use tokio::sync::{Mutex as AsyncMutex, mpsc};
use tracing::{error, info, warn};

use super::flush::{
    MitmJsonlFlushHandle, UsageFlushTarget, new_usage_state_id, usage_flush_state_guard,
};
use super::registry::{ProxyRegistryHandle, VmRegistration, write_empty_registry};
use super::stderr::log_mitmdump_stderr_line;
use crate::error::{RunnerError, RunnerResult};

// Embedded mitmproxy addon files (auto-generated by build.rs from mitm-addon/src/*.py).
include!(concat!(env!("OUT_DIR"), "/addon_files.rs"));

/// Timeout for waiting for mitmdump to become ready after spawn.
const READY_TIMEOUT: Duration = Duration::from_secs(10);
/// Short bounded retry for Linux `execve` returning ETXTBSY while a freshly
/// installed/replaced mitmdump binary is still observed as writable.
const TEXT_BUSY_SPAWN_RETRY_DELAY: Duration = Duration::from_millis(20);
const TEXT_BUSY_SPAWN_MAX_RETRIES: usize = 5;

/// Timeout for graceful shutdown before SIGKILL.
///
/// Usage upload drain is handled before SIGTERM; this only bounds mitmproxy's
/// own graceful process exit.
const STOP_TIMEOUT: Duration = Duration::from_secs(10);

/// Configuration for starting the proxy.
#[derive(Clone)]
pub struct ProxyConfig {
    /// Path to the mitmdump binary.
    pub mitmdump_bin: PathBuf,
    /// Directory containing mitmproxy CA files (mitmproxy-ca.pem).
    pub ca_dir: PathBuf,
    /// Directory where addon scripts will be written.
    pub addon_dir: PathBuf,
    /// Path where the proxy registry JSON will be written.
    pub registry_path: PathBuf,
    /// Lock file path for coordinating concurrent registry access.
    pub registry_lock_path: PathBuf,
    /// VM0 API URL passed to the addon (optional).
    pub api_url: Option<String>,
}

/// Manages the mitmdump process lifecycle and proxy registry.
pub struct MitmProxy {
    port: u16,
    config: ProxyConfig,
    child: Option<tokio::process::Child>,
    /// Sender used by the stdout monitor task to signal unexpected exit.
    crash_tx: mpsc::Sender<()>,
    /// Set to `true` during graceful `stop()` / `Drop` to suppress crash notifications.
    stopping: Arc<AtomicBool>,
    /// Per-mitmdump-process token written by the addon to `usage-pending`.
    usage_state_id: String,
    /// Host timestamp from when `usage_state_id` was minted.
    usage_state_started_at_ms: u64,
    usage_flush_state: Arc<Mutex<UsageFlushTarget>>,
    jsonl_flush_request_lock: Arc<AsyncMutex<()>>,
}

impl MitmProxy {
    /// Prepare the proxy: allocate a port, write addon script and empty registry.
    ///
    /// Returns `(proxy, crash_rx)`. The caller should select on `crash_rx` to
    /// detect unexpected mitmdump exits and trigger a restart.
    pub async fn new(config: ProxyConfig) -> RunnerResult<(Self, mpsc::Receiver<()>)> {
        let port = find_available_port()?;

        // Write addon scripts to directory.
        // Remove-and-recreate to purge stale files from previous binary versions
        // (e.g. a renamed module would leave an orphan .py that Python could import).
        match tokio::fs::remove_dir_all(&config.addon_dir).await {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => {
                return Err(RunnerError::Internal(format!(
                    "remove stale addon dir {}: {e}",
                    config.addon_dir.display()
                )));
            }
        }
        tokio::fs::create_dir_all(&config.addon_dir)
            .await
            .map_err(|e| RunnerError::Internal(format!("create addon dir: {e}")))?;
        for (name, content) in ADDON_FILES {
            // Addon file names may include subdirectories (e.g.
            // "usage/providers/connectors/x.py") after the usage/ package split.
            // Ensure the parent directory exists before writing.
            let path = config.addon_dir.join(name);
            if let Some(parent) = path.parent() {
                tokio::fs::create_dir_all(parent).await.map_err(|e| {
                    RunnerError::Internal(format!(
                        "create addon parent dir {}: {e}",
                        parent.display()
                    ))
                })?;
            }
            tokio::fs::write(&path, content)
                .await
                .map_err(|e| RunnerError::Internal(format!("write addon {name}: {e}")))?;
        }

        // Write empty registry file.
        write_empty_registry(&config.registry_path).await?;

        let (crash_tx, crash_rx) = mpsc::channel(1);
        let (usage_state_id, usage_state_started_at_ms) = new_usage_state_id();
        let usage_flush_state = Arc::new(Mutex::new(UsageFlushTarget {
            expected_usage_state_id: usage_state_id.clone(),
            usage_state_started_at_ms,
        }));
        let jsonl_flush_request_lock = Arc::new(AsyncMutex::new(()));

        Ok((
            Self {
                port,
                config,
                child: None,
                crash_tx,
                stopping: Arc::new(AtomicBool::new(false)),
                usage_state_id,
                usage_state_started_at_ms,
                usage_flush_state,
                jsonl_flush_request_lock,
            },
            crash_rx,
        ))
    }

    /// Spawn the mitmdump process.
    pub async fn start(&mut self) -> RunnerResult<()> {
        let child = spawn_mitmdump(
            &self.config,
            self.port,
            &self.crash_tx,
            &self.stopping,
            &self.usage_state_id,
        )
        .await?;
        self.child = Some(child);
        info!(port = self.port, "mitmdump started");
        Ok(())
    }

    /// The port mitmdump is listening on.
    pub fn port(&self) -> u16 {
        self.port
    }

    /// Create a cloneable handle for registry operations (register/unregister VMs).
    ///
    /// The handle is `Clone + Send + Sync` and uses file locking for concurrent
    /// access, making it safe to share across executor tasks.
    pub fn registry_handle(&self) -> ProxyRegistryHandle {
        ProxyRegistryHandle {
            registry_path: self.config.registry_path.clone(),
            lock_path: self.config.registry_lock_path.clone(),
        }
    }

    /// Create a cloneable handle for asking the addon to flush accepted JSONL writes.
    pub fn jsonl_flush_handle(&self, request_flush_tx: mpsc::Sender<()>) -> MitmJsonlFlushHandle {
        MitmJsonlFlushHandle {
            addon_dir: self.config.addon_dir.clone(),
            usage_state: Arc::clone(&self.usage_flush_state),
            request_lock: Arc::clone(&self.jsonl_flush_request_lock),
            request_flush_tx,
        }
    }

    /// Register a VM in the proxy registry so the addon can identify its traffic.
    pub async fn register_vm(
        &self,
        source_ip: &str,
        registration: &VmRegistration<'_>,
    ) -> RunnerResult<()> {
        self.registry_handle()
            .register_vm(source_ip, registration)
            .await
    }

    /// Unregister a VM from the proxy registry.
    pub async fn unregister_vm(&self, source_ip: &str) -> RunnerResult<()> {
        self.registry_handle().unregister_vm(source_ip).await
    }

    /// Current mitmdump usage state expected in the usage-pending state file.
    pub fn usage_flush_target(&mut self) -> Option<UsageFlushTarget> {
        let child_exited = match self.child.as_mut()?.try_wait() {
            Ok(Some(status)) => {
                error!(
                    r#type = "usage_underbilling",
                    reason = "mitm_exited_before_usage_flush",
                    underbilling_class = "risk",
                    component = "runner",
                    code = status.code(),
                    "mitmdump exited before usage flush"
                );
                true
            }
            Ok(None) => false,
            Err(e) => {
                warn!(error = %e, "failed to query mitmdump status before usage flush");
                false
            }
        };
        if child_exited {
            self.child = None;
            return None;
        }

        let _child_pid = self.child.as_ref().and_then(|child| child.id())?;
        Some(UsageFlushTarget {
            expected_usage_state_id: self.usage_state_id.clone(),
            usage_state_started_at_ms: self.usage_state_started_at_ms,
        })
    }

    /// Ask the running addon to flush buffered usage before shutdown.
    pub fn request_usage_flush(&mut self) -> bool {
        let Some(child) = self.child.as_mut() else {
            return false;
        };
        match child.try_wait() {
            Ok(Some(status)) => {
                error!(
                    r#type = "usage_underbilling",
                    reason = "mitm_exited_before_usage_flush",
                    underbilling_class = "risk",
                    component = "runner",
                    code = status.code(),
                    "mitmdump exited before usage flush request"
                );
                self.child = None;
                return false;
            }
            Ok(None) => {}
            Err(e) => {
                warn!(error = %e, "failed to query mitmdump status before usage flush request");
            }
        }

        let signaled = send_usage_flush_signal(child);
        if !signaled {
            error!(
                r#type = "usage_underbilling",
                reason = "usage_flush_request_failed",
                underbilling_class = "risk",
                component = "runner",
                "failed to request mitmdump usage flush"
            );
            return false;
        }

        match child.try_wait() {
            Ok(Some(status)) => {
                error!(
                    r#type = "usage_underbilling",
                    reason = "usage_flush_request_failed",
                    underbilling_class = "risk",
                    component = "runner",
                    code = status.code(),
                    "mitmdump exited after usage flush request"
                );
                self.child = None;
                false
            }
            Ok(None) => true,
            Err(e) => {
                warn!(error = %e, "failed to query mitmdump status after usage flush request");
                true
            }
        }
    }

    /// Prepare for restart: kill any lingering child, permanently silence
    /// its stdout monitor, and return fresh parameters for
    /// [`spawn_mitmdump`].
    ///
    /// `stopping` is scoped to a single child. The old flag is set to
    /// `true` (so the old monitor task, which may observe the stdout
    /// pipe close at some arbitrary point after this call returns,
    /// reads "graceful shutdown" and never emits a spurious crash
    /// notification) and the field is replaced with a fresh `Arc` for
    /// the incoming process. The new child's monitor starts from a
    /// clean slate and will detect real crashes.
    ///
    /// The caller should spawn the mitmdump process (potentially in a
    /// background task) and then call `complete_restart` with the result.
    pub async fn begin_restart(&mut self) -> MitmRestartParams {
        // Silence the old monitor permanently: after this call, no one
        // else holds a handle that could reset its `Arc<AtomicBool>`
        // back to `false`, so the monitor is guaranteed to read `true`
        // regardless of scheduling order between `kill().await` and
        // the stdout-pipe drain.
        self.stopping.store(true, Ordering::Release);
        if let Some(child) = self.child.as_mut() {
            match child.try_wait() {
                Ok(Some(_status)) => {}
                Ok(None) => error!(
                    r#type = "usage_underbilling",
                    reason = "mitm_restart_in_memory_usage_risk",
                    underbilling_class = "risk",
                    component = "runner",
                    "restarting mitmdump by killing live child; in-memory usage may be lost"
                ),
                Err(e) => error!(
                    r#type = "usage_underbilling",
                    reason = "mitm_restart_in_memory_usage_risk",
                    underbilling_class = "risk",
                    component = "runner",
                    error = %e,
                    "failed to query mitmdump status before restart kill; in-memory usage may be lost"
                ),
            }
            let _ = child.kill().await;
            self.child = None;
        }
        // Fresh flag for the incoming process's monitor.
        let new_stopping = Arc::new(AtomicBool::new(false));
        self.stopping = Arc::clone(&new_stopping);
        let (usage_state_id, usage_state_started_at_ms) = new_usage_state_id();
        self.usage_state_id = usage_state_id.clone();
        self.usage_state_started_at_ms = usage_state_started_at_ms;
        *usage_flush_state_guard(&self.usage_flush_state) = UsageFlushTarget {
            expected_usage_state_id: usage_state_id.clone(),
            usage_state_started_at_ms,
        };
        MitmRestartParams {
            config: self.config.clone(),
            port: self.port,
            crash_tx: self.crash_tx.clone(),
            stopping: new_stopping,
            usage_state_id,
        }
    }

    /// Finish a restart by storing the newly spawned child process.
    pub fn complete_restart(&mut self, child: tokio::process::Child) {
        self.child = Some(child);
    }

    /// Gracefully stop mitmdump (SIGTERM → timeout → SIGKILL).
    pub async fn stop(&mut self) -> RunnerResult<()> {
        self.stopping.store(true, Ordering::Release);
        let Some(ref mut child) = self.child else {
            return Ok(());
        };
        info!("stopping mitmdump");
        send_sigterm(child);

        match tokio::time::timeout(STOP_TIMEOUT, child.wait()).await {
            Ok(Ok(status)) => {
                info!(code = status.code(), "mitmdump stopped");
            }
            Ok(Err(e)) => {
                warn!(error = %e, "mitmdump wait failed");
            }
            Err(_) => {
                warn!("mitmdump did not exit in time, sending SIGKILL");
                let _ = child.kill().await;
            }
        }
        self.child = None;
        Ok(())
    }

    /// Immediately kill and reap mitmdump without the graceful SIGTERM window.
    pub async fn kill_now(&mut self) -> RunnerResult<()> {
        self.stopping.store(true, Ordering::Release);
        let Some(ref mut child) = self.child else {
            return Ok(());
        };
        if child
            .try_wait()
            .map_err(|e| RunnerError::Internal(format!("check mitmdump process: {e}")))?
            .is_some()
        {
            self.child = None;
            return Ok(());
        }
        if let Err(kill_error) = child.start_kill() {
            if child
                .try_wait()
                .map_err(|e| RunnerError::Internal(format!("recheck mitmdump process: {e}")))?
                .is_some()
            {
                self.child = None;
                return Ok(());
            }
            return Err(RunnerError::Internal(format!(
                "kill mitmdump process after startup failure: {kill_error}"
            )));
        }
        child
            .wait()
            .await
            .map_err(|e| RunnerError::Internal(format!("wait for killed mitmdump process: {e}")))?;
        self.child = None;
        Ok(())
    }
}

#[cfg(test)]
impl MitmProxy {
    /// Create a noop proxy for testing. No real process is spawned.
    ///
    /// `stop()` already handles `child: None` (returns immediately),
    /// and `begin_restart()` is never triggered because the test holds
    /// the crash channel sender and never sends on it.
    pub fn noop() -> (Self, mpsc::Receiver<()>) {
        let (crash_tx, crash_rx) = mpsc::channel(1);
        (
            Self {
                port: 0,
                config: ProxyConfig {
                    mitmdump_bin: std::path::PathBuf::new(),
                    ca_dir: std::path::PathBuf::new(),
                    addon_dir: std::path::PathBuf::new(),
                    registry_path: std::path::PathBuf::new(),
                    registry_lock_path: std::path::PathBuf::new(),
                    api_url: None,
                },
                child: None,
                crash_tx,
                stopping: Arc::new(AtomicBool::new(false)),
                usage_state_id: "test-usage-state-id".to_string(),
                usage_state_started_at_ms: super::flush::now_millis(),
                usage_flush_state: Arc::new(Mutex::new(UsageFlushTarget {
                    expected_usage_state_id: "test-usage-state-id".to_string(),
                    usage_state_started_at_ms: super::flush::now_millis(),
                })),
                jsonl_flush_request_lock: Arc::new(AsyncMutex::new(())),
            },
            crash_rx,
        )
    }

    pub fn usage_state_id_for_test(&self) -> &str {
        &self.usage_state_id
    }

    pub fn set_child_for_test(&mut self, child: tokio::process::Child) {
        self.child = Some(child);
    }

    pub fn set_addon_dir_for_test(&mut self, addon_dir: PathBuf) {
        self.config.addon_dir = addon_dir;
    }
}

impl Drop for MitmProxy {
    fn drop(&mut self) {
        self.stopping.store(true, Ordering::Release);
        crate::child_cleanup::kill_and_reap_child_on_drop("mitmdump", &mut self.child);
    }
}

/// Parameters needed to spawn a mitmdump process, returned by
/// [`MitmProxy::begin_restart`]. All fields are owned/cloned so the spawn
/// can happen in a background task without borrowing `MitmProxy`.
pub(crate) struct MitmRestartParams {
    config: ProxyConfig,
    port: u16,
    crash_tx: mpsc::Sender<()>,
    stopping: Arc<AtomicBool>,
    usage_state_id: String,
}

impl MitmRestartParams {
    /// Spawn mitmdump using these parameters. Suitable for `tokio::spawn`.
    pub(crate) async fn spawn(self) -> RunnerResult<tokio::process::Child> {
        spawn_mitmdump(
            &self.config,
            self.port,
            &self.crash_tx,
            &self.stopping,
            &self.usage_state_id,
        )
        .await
    }
}

/// Spawn a mitmdump process, wire up stdout/stderr monitors, and wait for
/// it to become ready. This is a free function so it can run in a
/// `tokio::spawn` without borrowing `MitmProxy`.
pub(crate) async fn spawn_mitmdump(
    config: &ProxyConfig,
    port: u16,
    crash_tx: &mpsc::Sender<()>,
    stopping: &Arc<AtomicBool>,
    usage_state_id: &str,
) -> RunnerResult<tokio::process::Child> {
    let mut cmd = tokio::process::Command::new(&config.mitmdump_bin);
    cmd.arg("--mode")
        .arg("transparent")
        .arg("--listen-port")
        .arg(port.to_string())
        .arg("--set")
        .arg(format!("confdir={}", config.ca_dir.display()))
        .arg("--set")
        .arg(format!(
            "vm0_proxy_registry_path={}",
            config.registry_path.display()
        ))
        .arg("--set")
        .arg(format!("vm0_usage_state_id={usage_state_id}"))
        .arg("--scripts")
        .arg(config.addon_dir.join("mitm_addon.py"))
        .arg("--set")
        .arg("flow_detail=0")
        .arg("--set")
        .arg("termlog_verbosity=warn")
        .arg("--set")
        .arg(format!(
            "ssl_verify_upstream_trusted_ca={}",
            crate::deps::SYSTEM_CA_BUNDLE
        ));
    if let Some(url) = &config.api_url {
        cmd.arg("--set").arg(format!("vm0_api_url={url}"));
    }
    cmd.stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped());
    cmd.kill_on_drop(true);

    // SAFETY: `set_pdeathsig` calls `prctl(PR_SET_PDEATHSIG)` which is
    // async-signal-safe. This ensures the kernel sends SIGKILL to the
    // mitmdump child when the parent runner process dies, preventing
    // orphaned processes after runner crashes or restarts.
    unsafe {
        cmd.pre_exec(|| {
            nix::sys::prctl::set_pdeathsig(nix::sys::signal::Signal::SIGKILL)
                .map_err(std::io::Error::from)
        });
    }

    info!(port, bin = %config.mitmdump_bin.display(), "starting mitmdump");

    let mut child = spawn_mitmdump_child(&mut cmd, &config.mitmdump_bin).await?;

    // Stream stdout to tracing; when the pipe closes (process exited),
    // send a crash notification unless we're in a graceful stop.
    if let Some(stdout) = child.stdout.take() {
        let crash_tx = crash_tx.clone();
        let stopping = Arc::clone(stopping);
        tokio::spawn(async move {
            let mut lines = tokio::io::BufReader::new(stdout).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                if !line.is_empty() {
                    info!(target: "mitmdump", "{line}");
                }
            }
            // Pipe closed — process exited.
            if !stopping.load(Ordering::Acquire) {
                let _ = crash_tx.send(()).await;
            }
        });
    }
    if let Some(stderr) = child.stderr.take() {
        tokio::spawn(async move {
            let mut lines = tokio::io::BufReader::new(stderr).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                if !line.is_empty() {
                    log_mitmdump_stderr_line(&line);
                }
            }
        });
    }

    // Wait for process to be alive (poll liveness).
    if let Err(e) = wait_for_ready(&mut child, port, READY_TIMEOUT).await {
        stopping.store(true, Ordering::Release);
        let _ = child.kill().await;
        return Err(e);
    }

    Ok(child)
}

fn is_text_file_busy(error: &std::io::Error) -> bool {
    error.raw_os_error() == Some(nix::libc::ETXTBSY)
}

async fn spawn_mitmdump_child(
    cmd: &mut tokio::process::Command,
    bin: &Path,
) -> RunnerResult<tokio::process::Child> {
    spawn_mitmdump_child_with_retry(cmd, bin, TEXT_BUSY_SPAWN_RETRY_DELAY, |attempt, error| {
        warn!(
            attempt,
            bin = %bin.display(),
            error = %error,
            "mitmdump binary is text-busy, retrying spawn"
        );
    })
    .await
}

async fn spawn_mitmdump_child_with_retry(
    cmd: &mut tokio::process::Command,
    bin: &Path,
    retry_delay: Duration,
    on_text_busy: impl FnMut(usize, &std::io::Error),
) -> RunnerResult<tokio::process::Child> {
    retry_text_busy_spawn(bin, retry_delay, || cmd.spawn(), on_text_busy).await
}

async fn retry_text_busy_spawn<T>(
    bin: &Path,
    retry_delay: Duration,
    mut spawn: impl FnMut() -> std::io::Result<T>,
    mut on_text_busy: impl FnMut(usize, &std::io::Error),
) -> RunnerResult<T> {
    let mut attempt = 0usize;
    loop {
        match spawn() {
            Ok(child) => return Ok(child),
            Err(error) if is_text_file_busy(&error) && attempt < TEXT_BUSY_SPAWN_MAX_RETRIES => {
                attempt += 1;
                on_text_busy(attempt, &error);
                tokio::time::sleep(retry_delay).await;
            }
            Err(error) => {
                return Err(RunnerError::Internal(format!(
                    "spawn mitmdump {}: {error}",
                    bin.display()
                )));
            }
        }
    }
}

/// Wait for mitmdump to start listening on `port` (TCP connect probe).
async fn wait_for_ready(
    child: &mut tokio::process::Child,
    port: u16,
    timeout: Duration,
) -> RunnerResult<()> {
    let poll_interval = Duration::from_millis(200);
    let start = std::time::Instant::now();
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));

    while start.elapsed() < timeout {
        // Check if process died.
        match child.try_wait() {
            Ok(Some(status)) => {
                return Err(RunnerError::Internal(format!(
                    "mitmdump exited immediately with {}",
                    status
                        .code()
                        .map_or("unknown".to_string(), |c| c.to_string()),
                )));
            }
            Ok(None) => {}
            Err(e) => {
                return Err(RunnerError::Internal(format!(
                    "mitmdump process check: {e}"
                )));
            }
        }
        // Probe TCP port.
        if tokio::net::TcpStream::connect(addr).await.is_ok() {
            return Ok(());
        }
        tokio::time::sleep(poll_interval).await;
    }

    Err(RunnerError::Internal(format!(
        "mitmdump did not start listening on port {port} within {}s",
        timeout.as_secs()
    )))
}

/// Find an available TCP port by binding to port 0.
fn find_available_port() -> RunnerResult<u16> {
    let listener = std::net::TcpListener::bind("0.0.0.0:0")
        .map_err(|e| RunnerError::Internal(format!("bind port 0: {e}")))?;
    let port = listener
        .local_addr()
        .map_err(|e| RunnerError::Internal(format!("local_addr: {e}")))?
        .port();
    Ok(port)
}

fn send_sigterm(child: &tokio::process::Child) {
    if let Some(pid) = child.id() {
        let _ = nix::sys::signal::kill(
            nix::unistd::Pid::from_raw(pid as i32),
            nix::sys::signal::Signal::SIGTERM,
        );
    }
}

fn send_usage_flush_signal(child: &tokio::process::Child) -> bool {
    let Some(pid) = child.id() else {
        return false;
    };
    nix::sys::signal::kill(
        nix::unistd::Pid::from_raw(pid as i32),
        nix::sys::signal::Signal::SIGUSR1,
    )
    .is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::PermissionsExt;

    fn write_fake_listening_mitmdump(path: &Path) {
        std::fs::write(
            path,
            r#"#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$@" > "$0.args"
port=""
prev=""
for arg in "$@"; do
  if [ "$prev" = "--listen-port" ]; then
    port="$arg"
    break
  fi
  prev="$arg"
done
exec python3 - "$port" <<'PY'
import socket
import sys

port = int(sys.argv[1])
sock = socket.socket()
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind(("127.0.0.1", port))
sock.listen(1)
while True:
    conn, _ = sock.accept()
    conn.close()
PY
"#,
        )
        .unwrap();
        let mut perms = std::fs::metadata(path).unwrap().permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(path, perms).unwrap();
    }

    #[tokio::test]
    async fn retry_text_busy_spawn_retries_text_busy_errors() {
        let spawn_calls = std::cell::Cell::new(0usize);
        let retry_count = std::cell::Cell::new(0usize);
        let spawned = retry_text_busy_spawn(
            Path::new("fake-mitmdump"),
            Duration::ZERO,
            || {
                let calls = spawn_calls.get() + 1;
                spawn_calls.set(calls);
                if calls == 1 {
                    Err(std::io::Error::from_raw_os_error(nix::libc::ETXTBSY))
                } else {
                    Ok("spawned")
                }
            },
            |attempt, error| {
                assert!(is_text_file_busy(error), "unexpected retry error: {error}");
                retry_count.set(attempt);
            },
        )
        .await
        .unwrap();

        assert_eq!(spawned, "spawned");
        assert_eq!(spawn_calls.get(), 2);
        assert_eq!(retry_count.get(), 1);
    }

    #[cfg(target_os = "linux")]
    #[tokio::test]
    async fn retry_text_busy_spawn_does_not_retry_other_errors() {
        let spawn_calls = std::cell::Cell::new(0usize);
        let retry_count = std::cell::Cell::new(0usize);
        let error = retry_text_busy_spawn::<()>(
            Path::new("fake-mitmdump"),
            Duration::ZERO,
            || {
                spawn_calls.set(spawn_calls.get() + 1);
                Err(std::io::Error::from_raw_os_error(nix::libc::ENOENT))
            },
            |_attempt, _error| retry_count.set(retry_count.get() + 1),
        )
        .await
        .unwrap_err();

        assert_eq!(spawn_calls.get(), 1);
        assert_eq!(retry_count.get(), 0);
        assert!(
            error.to_string().contains("spawn mitmdump fake-mitmdump"),
            "unexpected error: {error}",
        );
    }

    #[cfg(target_os = "linux")]
    #[tokio::test]
    async fn retry_text_busy_spawn_stops_after_retry_limit() {
        let spawn_calls = std::cell::Cell::new(0usize);
        let last_retry_attempt = std::cell::Cell::new(0usize);
        let error = retry_text_busy_spawn::<()>(
            Path::new("fake-mitmdump"),
            Duration::ZERO,
            || {
                spawn_calls.set(spawn_calls.get() + 1);
                Err(std::io::Error::from_raw_os_error(nix::libc::ETXTBSY))
            },
            |attempt, error| {
                assert!(is_text_file_busy(error), "unexpected retry error: {error}");
                last_retry_attempt.set(attempt);
            },
        )
        .await
        .unwrap_err();

        assert_eq!(spawn_calls.get(), TEXT_BUSY_SPAWN_MAX_RETRIES + 1);
        assert_eq!(last_retry_attempt.get(), TEXT_BUSY_SPAWN_MAX_RETRIES);
        assert!(
            error.to_string().contains("spawn mitmdump fake-mitmdump"),
            "unexpected error: {error}",
        );
    }

    async fn wait_for_reaped_pid(pid: nix::unistd::Pid) -> bool {
        let deadline = tokio::time::Instant::now() + Duration::from_secs(2);
        loop {
            match nix::sys::wait::waitpid(pid, Some(nix::sys::wait::WaitPidFlag::WNOHANG)) {
                Ok(nix::sys::wait::WaitStatus::StillAlive) => {}
                Ok(_) => return true,
                Err(nix::errno::Errno::ECHILD) => {
                    return nix::sys::signal::kill(pid, None).is_err();
                }
                Err(_) => {}
            }
            if tokio::time::Instant::now() >= deadline {
                return false;
            }
            tokio::time::sleep(Duration::from_millis(50)).await;
        }
    }

    #[test]
    fn find_port_returns_nonzero() {
        let port = find_available_port().unwrap();
        assert!(port > 0, "expected non-zero port, got {port}");
    }

    #[test]
    fn addon_scripts_are_embedded() {
        let files: Vec<&str> = ADDON_FILES.iter().map(|(name, _)| *name).collect();

        // All expected modules must be present.  `usage/` is a package after
        // #10381; each submodule must embed under its relative path so the
        // runtime extractor rebuilds the directory tree before mitmdump loads
        // the addon.
        for expected in [
            "mitm_addon.py",
            "auth.py",
            "billing_body.py",
            "body_capture.py",
            "body_decoding.py",
            "body_limits.py",
            "flow_metadata_keys.py",
            "generated/__init__.py",
            "generated/builtin_firewalls/__init__.py",
            "generated/builtin_firewalls/cloudflare_0.py",
            "generated/builtin_firewalls/github_0.py",
            "generated/builtin_firewalls/loader.py",
            "generated/builtin_firewalls/manifest.py",
            "matching.py",
            "registry.py",
            "response_streaming.py",
            "url_utils.py",
            "logging_utils.py",
            "usage/__init__.py",
            "usage/anthropic_messages.py",
            "usage/counters.py",
            "usage/idempotency.py",
            "usage/model_tokens.py",
            "usage/openai_responses.py",
            "usage/sse.py",
            "usage/webhook.py",
            "usage/providers/__init__.py",
            "usage/providers/model_provider.py",
            "usage/providers/connectors/__init__.py",
            "usage/providers/connectors/x.py",
        ] {
            assert!(
                files.contains(&expected),
                "addon files should include {expected}, got: {files:?}"
            );
        }

        let generated_builtin_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("mitm-addon/src/generated/builtin_firewalls");
        let mut expected_generated_builtin_files: Vec<String> =
            std::fs::read_dir(&generated_builtin_dir)
                .unwrap_or_else(|error| panic!("read {}: {error}", generated_builtin_dir.display()))
                .map(|entry| entry.unwrap())
                .filter(|entry| entry.path().extension().and_then(|ext| ext.to_str()) == Some("py"))
                .map(|entry| {
                    format!(
                        "generated/builtin_firewalls/{}",
                        entry.file_name().to_string_lossy()
                    )
                })
                .collect();
        expected_generated_builtin_files.sort();
        assert!(
            !expected_generated_builtin_files.is_empty(),
            "expected generated builtin firewall files under {}",
            generated_builtin_dir.display()
        );
        for expected in expected_generated_builtin_files {
            assert!(
                files.contains(&expected.as_str()),
                "addon files should include generated builtin firewall file {expected}, got: {files:?}"
            );
        }

        let (_, content) = ADDON_FILES
            .iter()
            .find(|(name, _)| *name == "mitm_addon.py")
            .unwrap();
        assert!(
            content.contains("mitmproxy addon"),
            "mitm_addon.py should contain expected header"
        );
    }

    #[tokio::test]
    async fn mitm_proxy_new_fails_when_stale_addon_dir_cleanup_fails() {
        let dir = tempfile::tempdir().unwrap();
        let addon_dir = dir.path().join("addon");
        tokio::fs::write(&addon_dir, b"not a directory")
            .await
            .unwrap();
        let config = ProxyConfig {
            mitmdump_bin: dir.path().join("mitmdump"),
            ca_dir: dir.path().join("ca"),
            addon_dir: addon_dir.clone(),
            registry_path: dir.path().join("proxy-registry.json"),
            registry_lock_path: dir.path().join("proxy-registry.json.lock"),
            api_url: None,
        };

        let result = MitmProxy::new(config).await;

        let error = result.err().expect("expected addon cleanup failure");
        assert!(
            error.to_string().contains("remove stale addon dir"),
            "unexpected error: {error}"
        );
        assert_eq!(
            tokio::fs::read(&addon_dir).await.unwrap(),
            b"not a directory"
        );
    }

    #[tokio::test]
    async fn mitm_proxy_new_succeeds_when_addon_dir_is_missing() {
        let dir = tempfile::tempdir().unwrap();
        let addon_dir = dir.path().join("addon");
        let registry_path = dir.path().join("proxy-registry.json");
        let config = ProxyConfig {
            mitmdump_bin: dir.path().join("mitmdump"),
            ca_dir: dir.path().join("ca"),
            addon_dir: addon_dir.clone(),
            registry_path: registry_path.clone(),
            registry_lock_path: dir.path().join("proxy-registry.json.lock"),
            api_url: None,
        };

        let (_proxy, _crash_rx) = MitmProxy::new(config).await.unwrap();

        assert!(addon_dir.join("mitm_addon.py").is_file());
        let raw = tokio::fs::read_to_string(&registry_path).await.unwrap();
        let registry: serde_json::Value = serde_json::from_str(&raw).unwrap();
        assert_eq!(registry["vms"], serde_json::json!({}));
    }

    #[tokio::test]
    async fn wait_for_ready_returns_error_on_timeout() {
        // `sleep` never listens on TCP — guarantees timeout.
        let mut child = tokio::process::Command::new("sleep")
            .arg("60")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();

        let raw_pid = child.id().unwrap() as i32;
        let pid = nix::unistd::Pid::from_raw(raw_pid);
        let port = find_available_port().unwrap();

        let result = wait_for_ready(&mut child, port, Duration::from_millis(500)).await;
        assert!(result.is_err());

        // Process must still be alive — wait_for_ready does NOT kill on error.
        // This is the scenario that caused orphaned processes before the fix:
        // the caller (spawn_mitmdump) is responsible for killing.
        assert!(
            nix::sys::signal::kill(pid, None).is_ok(),
            "process should still be alive after timeout"
        );

        // Simulate spawn_mitmdump error path: kill the child.
        let _ = child.kill().await;

        assert!(
            nix::sys::signal::kill(pid, None).is_err(),
            "process should be dead after kill"
        );
    }

    #[tokio::test]
    async fn wait_for_ready_returns_error_on_early_exit() {
        // `true` exits immediately with status 0.
        let mut child = tokio::process::Command::new("true")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();

        // Wait for `true` to actually exit before calling wait_for_ready,
        // so the first try_wait() inside the function detects it immediately.
        let _ = child.wait().await;

        let port = find_available_port().unwrap();
        let result = wait_for_ready(&mut child, port, Duration::from_secs(5)).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn spawn_mitmdump_passes_usage_state_id_option() {
        let dir = tempfile::tempdir().unwrap();
        let fake_mitmdump = dir.path().join("fake-mitmdump");
        write_fake_listening_mitmdump(&fake_mitmdump);

        let config = ProxyConfig {
            mitmdump_bin: fake_mitmdump.clone(),
            ca_dir: dir.path().join("ca"),
            addon_dir: dir.path().join("addon"),
            registry_path: dir.path().join("proxy-registry.json"),
            registry_lock_path: dir.path().join("proxy-registry.json.lock"),
            api_url: None,
        };
        let (crash_tx, _crash_rx) = mpsc::channel(1);
        let stopping = Arc::new(AtomicBool::new(false));
        let port = find_available_port().unwrap();

        let mut child = spawn_mitmdump(&config, port, &crash_tx, &stopping, "usage-state-test")
            .await
            .unwrap();
        stopping.store(true, Ordering::Release);
        let _ = child.kill().await;

        let args = std::fs::read_to_string(fake_mitmdump.with_extension("args")).unwrap();
        assert!(
            args.lines()
                .any(|arg| arg == "vm0_usage_state_id=usage-state-test"),
            "mitmdump args should include vm0_usage_state_id option; got:\n{args}",
        );
    }

    #[tokio::test]
    async fn spawn_mitmdump_kills_child_when_handle_is_dropped() {
        let dir = tempfile::tempdir().unwrap();
        let fake_mitmdump = dir.path().join("fake-mitmdump");
        write_fake_listening_mitmdump(&fake_mitmdump);

        let config = ProxyConfig {
            mitmdump_bin: fake_mitmdump,
            ca_dir: dir.path().join("ca"),
            addon_dir: dir.path().join("addon"),
            registry_path: dir.path().join("proxy-registry.json"),
            registry_lock_path: dir.path().join("proxy-registry.json.lock"),
            api_url: None,
        };
        let (crash_tx, _crash_rx) = mpsc::channel(1);
        let stopping = Arc::new(AtomicBool::new(false));
        let port = find_available_port().unwrap();

        let child = spawn_mitmdump(&config, port, &crash_tx, &stopping, "usage-state-test")
            .await
            .unwrap();
        let pid = nix::unistd::Pid::from_raw(child.id().unwrap() as i32);
        stopping.store(true, Ordering::Release);
        drop(child);

        assert!(
            wait_for_reaped_pid(pid).await,
            "dropping mitmdump Child should kill and reap the process"
        );
    }

    #[tokio::test]
    async fn usage_flush_target_returns_target_for_running_child() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let child = tokio::process::Command::new("sleep")
            .arg("60")
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();
        proxy.child = Some(child);

        assert!(proxy.usage_flush_target().is_some());

        proxy.stop().await.unwrap();
    }

    #[tokio::test]
    async fn usage_flush_target_skips_exited_child() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let mut child = tokio::process::Command::new("true")
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();
        child.wait().await.unwrap();
        proxy.child = Some(child);

        assert!(proxy.usage_flush_target().is_none());
        assert!(proxy.child.is_none());
    }

    #[tokio::test]
    async fn kill_now_reaps_exited_child() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let mut child = tokio::process::Command::new("true")
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();
        child.wait().await.unwrap();
        proxy.child = Some(child);

        proxy.kill_now().await.unwrap();

        assert!(proxy.child.is_none());
    }

    #[tokio::test]
    async fn request_usage_flush_signals_child() {
        let dir = tempfile::tempdir().unwrap();
        let signal_file = dir.path().join("usage-flush-requested");

        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let mut command = tokio::process::Command::new("python3");
        command
            .arg("-c")
            .arg(
                r#"
import os
import signal

import sys

signal_file = sys.argv[1]
usage_signal = signal.SIGUSR1
signal.pthread_sigmask(signal.SIG_BLOCK, {usage_signal})
os.write(1, b"ready\n")
while True:
    received_signal = signal.sigwait({usage_signal})
    if received_signal == usage_signal:
        fd = os.open(signal_file, os.O_CREAT | os.O_TRUNC | os.O_WRONLY, 0o644)
        os.close(fd)
        os.write(1, b"signaled\n")
"#,
            )
            .arg(&signal_file)
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::null())
            .kill_on_drop(true);
        let mut child = command.spawn().unwrap();
        let stdout = child.stdout.take().unwrap();
        let mut ready_lines = tokio::io::BufReader::new(stdout).lines();
        proxy.child = Some(child);

        let ready = tokio::time::timeout(Duration::from_secs(2), ready_lines.next_line())
            .await
            .expect("child did not become ready for SIGUSR1")
            .unwrap();
        assert_eq!(ready.as_deref(), Some("ready"));

        assert!(proxy.request_usage_flush());

        let signaled = tokio::time::timeout(Duration::from_secs(2), ready_lines.next_line())
            .await
            .expect("child did not observe SIGUSR1")
            .unwrap();
        assert_eq!(signaled.as_deref(), Some("signaled"));
        assert!(signal_file.exists(), "child did not observe SIGUSR1");
        let _ = proxy.child.as_mut().unwrap().kill().await;
        proxy.child = None;
    }

    #[test]
    fn request_usage_flush_returns_false_without_child() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();

        assert!(!proxy.request_usage_flush());
    }

    #[tokio::test]
    async fn request_usage_flush_returns_false_for_exited_child() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let mut child = tokio::process::Command::new("bash")
            .arg("-c")
            .arg("echo ready")
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();
        let stdout = child.stdout.take().unwrap();
        let mut ready_lines = tokio::io::BufReader::new(stdout).lines();
        assert_eq!(
            ready_lines.next_line().await.unwrap().as_deref(),
            Some("ready")
        );
        assert!(ready_lines.next_line().await.unwrap().is_none());
        let status = child.wait().await.unwrap();
        assert!(status.success(), "child exited with {status}");
        proxy.child = Some(child);

        assert!(!proxy.request_usage_flush());
        assert!(proxy.child.is_none());
    }

    /// Regression for #10624: `begin_restart` must lock the old
    /// monitor's `stopping` at `true` and hand the caller a fresh
    /// `Arc<AtomicBool>` for the next child. If the old flag were
    /// shared across the restart boundary, the old stdout monitor
    /// could race in after `kill().await` returned, read `stopping ==
    /// false`, and emit a spurious crash notification.
    #[tokio::test]
    async fn begin_restart_isolates_stopping_flag_per_child() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let old_stopping = Arc::clone(&proxy.stopping);

        let params = proxy.begin_restart().await;

        // Old flag is now permanently `true`; any task still holding
        // `old_stopping` (the old monitor) will observe graceful
        // shutdown semantics regardless of when it wakes up.
        assert!(old_stopping.load(Ordering::Acquire));

        // The next child's monitor starts from a clean slate.
        assert!(!params.stopping.load(Ordering::Acquire));

        // And the proxy holds that same fresh `Arc` — so subsequent
        // `stop()` / `Drop` calls operate on the new child, not the
        // already-silenced old one.
        assert!(Arc::ptr_eq(&proxy.stopping, &params.stopping));
        assert!(!Arc::ptr_eq(&old_stopping, &params.stopping));
    }

    /// `spawn_mitmdump` can fail (e.g. port still in use), leaving the
    /// caller to retry without ever calling `complete_restart`. Each
    /// `begin_restart` in that retry chain must still hand out a fresh
    /// `Arc` and lock every previous one — otherwise a stale flag
    /// could be reset on the next round, resurrecting the race.
    #[tokio::test]
    async fn repeated_begin_restart_produces_independent_flags() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();

        let first = proxy.begin_restart().await;
        let second = proxy.begin_restart().await;
        let third = proxy.begin_restart().await;

        // Every handed-out Arc is distinct.
        assert!(!Arc::ptr_eq(&first.stopping, &second.stopping));
        assert!(!Arc::ptr_eq(&second.stopping, &third.stopping));
        assert!(!Arc::ptr_eq(&first.stopping, &third.stopping));

        // Superseded flags are permanently locked; only the most
        // recent one remains mutable.
        assert!(first.stopping.load(Ordering::Acquire));
        assert!(second.stopping.load(Ordering::Acquire));
        assert!(!third.stopping.load(Ordering::Acquire));
        assert!(Arc::ptr_eq(&proxy.stopping, &third.stopping));
    }

    /// `stop()` must set the *current* child's flag, not the one just
    /// superseded by `begin_restart`. A regression here would make
    /// `stop()` a silent no-op (the old Arc is already `true`), while
    /// the new child's monitor — which is what `stop()` exists to
    /// silence — would keep reading `false`.
    #[tokio::test]
    async fn stop_after_begin_restart_targets_current_flag() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let params = proxy.begin_restart().await;
        let current = Arc::clone(&params.stopping);
        assert!(!current.load(Ordering::Acquire));

        proxy.stop().await.unwrap();

        assert!(current.load(Ordering::Acquire));
    }
}
