import { describe, expect, it } from "vitest";
import {
  compileGoogleManifestFirewall,
  renderGoogleManifestFirewall,
  validateGoogleManifestPermissionManifest,
  type GoogleManifestPermission,
} from "../google-manifest";

type TestRouteKind = "base" | "upload";

interface TestPermission extends GoogleManifestPermission {
  readonly category?: string;
}

const ROUTE_KINDS = [
  "base",
  "upload",
] as const satisfies readonly TestRouteKind[];

const APIS = [
  {
    base: "https://example.test/api",
    kind: "base",
  },
  {
    base: "https://example.test/upload",
    kind: "upload",
  },
] as const satisfies ReadonlyArray<{
  readonly base: string;
  readonly kind: TestRouteKind;
}>;

const OFFICIAL_ROUTE_KEYS = new Set([
  "base:GET /v1/files/{fileId}",
  "base:POST /v1/files",
  "upload:POST /v1/files",
]);

const MANIFEST = [
  {
    name: "files.read",
    category: "Files",
    description: "Read files.",
    routeKeys: ["base:GET /v1/files/{fileId}"],
  },
  {
    name: "files.write",
    category: "Files",
    description: "Create files.",
    routeKeys: ["base:POST /v1/files", "upload:POST /v1/files"],
  },
] as const satisfies readonly TestPermission[];

function validate(manifest: readonly TestPermission[]): void {
  validateGoogleManifestPermissionManifest({
    serviceLabel: "Test Google",
    routeKinds: ROUTE_KINDS,
    officialRouteKeys: OFFICIAL_ROUTE_KEYS,
    manifest,
    categoryOrder: ["Files"],
  });
}

describe("Google manifest compiler", () => {
  it("validates and compiles permissions by route kind", () => {
    const compiled = compileGoogleManifestFirewall({
      serviceLabel: "Test Google",
      routeKinds: ROUTE_KINDS,
      officialRouteKeys: OFFICIAL_ROUTE_KEYS,
      manifest: MANIFEST,
      apis: APIS,
      categoryOrder: ["Files"],
    });

    expect(compiled.apis).toEqual([
      {
        base: "https://example.test/api",
        kind: "base",
        permissions: [
          {
            name: "files.read",
            description: "Read files.",
            rules: ["GET /v1/files/{fileId}"],
          },
          {
            name: "files.write",
            description: "Create files.",
            rules: ["POST /v1/files"],
          },
        ],
      },
      {
        base: "https://example.test/upload",
        kind: "upload",
        permissions: [
          {
            name: "files.write",
            description: "Create files.",
            rules: ["POST /v1/files"],
          },
        ],
      },
    ]);
    expect(compiled.categories).toEqual({
      categories: {
        "files.read": "Files",
        "files.write": "Files",
      },
      displayOrder: ["Files"],
    });
  });

  it("supports category-less manifests", () => {
    const compiled = compileGoogleManifestFirewall({
      serviceLabel: "Test Google",
      routeKinds: ["base"],
      officialRouteKeys: new Set(["base:GET /v1/documents/{documentId}"]),
      manifest: [
        {
          name: "documents.read",
          description: "Read documents.",
          routeKeys: ["base:GET /v1/documents/{documentId}"],
        },
      ],
      apis: [
        {
          base: "https://docs.example.test",
          kind: "base",
        },
      ],
    });

    expect(compiled.categories).toBeUndefined();
    expect(compiled.apis[0]?.permissions).toEqual([
      {
        name: "documents.read",
        description: "Read documents.",
        rules: ["GET /v1/documents/{documentId}"],
      },
    ]);
  });

  it("renders defaults, unknown policy, and categories", () => {
    const compiled = compileGoogleManifestFirewall({
      serviceLabel: "Test Google",
      routeKinds: ROUTE_KINDS,
      officialRouteKeys: OFFICIAL_ROUTE_KEYS,
      manifest: MANIFEST,
      apis: APIS,
      categoryOrder: ["Files"],
    });

    if (!compiled.categories) {
      throw new Error("Expected compiled categories");
    }

    const ts = renderGoogleManifestFirewall({
      headerLines: [
        "// Auto-generated from Test Google Discovery and manifest.",
        "// Source: https://example.test/discovery",
        "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:test-google",
        "//",
        "// DO NOT EDIT THIS FILE MANUALLY.",
      ],
      firewallVarName: "testGoogleFirewall",
      firewallName: "test-google",
      firewallDescription: "Test Google API",
      tokenPlaceholderName: "TEST_GOOGLE_TOKEN",
      tokenPlaceholderValue: "ya29.test",
      apis: compiled.apis,
      defaultAllowed: {
        varName: "testGoogleDefaultAllowed",
        permissions: ["files.read"],
      },
      defaultUnknownPolicy: {
        varName: "testGoogleDefaultUnknownPolicy",
        policy: "deny",
      },
      categories: {
        varName: "testGoogleCategories",
        config: compiled.categories,
      },
    });

    expect(ts).toContain("export const testGoogleFirewall = {");
    expect(ts).toContain(
      'Authorization: "Bearer ${{ secrets.TEST_GOOGLE_TOKEN }}",',
    );
    expect(ts).toContain(
      "export const testGoogleDefaultAllowed: ReadonlyArray<",
    );
    expect(ts).toContain('  "files.read",');
    expect(ts).toContain(
      'export const testGoogleDefaultUnknownPolicy = "deny" satisfies FirewallPolicyValue;',
    );
    expect(ts).toContain("export const testGoogleCategories: Record<");
  });

  it("fails malformed route keys", () => {
    expect(() => {
      validate([
        {
          ...MANIFEST[0],
          routeKeys: ["GET /v1/files/{fileId}"],
        },
        MANIFEST[1],
      ]);
    }).toThrow("Malformed Test Google route key");
  });

  it("fails unknown route key kinds", () => {
    expect(() => {
      validate([
        {
          ...MANIFEST[0],
          routeKeys: ["admin:GET /v1/files/{fileId}"],
        },
        MANIFEST[1],
      ]);
    }).toThrow("Unknown Test Google route key kind");
  });

  it("fails malformed route rules", () => {
    expect(() => {
      validate([
        {
          ...MANIFEST[0],
          routeKeys: ["base:GET v1/files/{fileId}"],
        },
        MANIFEST[1],
      ]);
    }).toThrow("Malformed Test Google route rule");
  });

  it("fails duplicate permission names", () => {
    expect(() => {
      validate([
        MANIFEST[0],
        {
          ...MANIFEST[1],
          name: "files.read",
        },
      ]);
    }).toThrow(
      "Test Google permission manifest has duplicate permission names",
    );
  });

  it("fails duplicate route assignments", () => {
    expect(() => {
      validate([
        {
          ...MANIFEST[0],
          routeKeys: ["base:GET /v1/files/{fileId}", "base:POST /v1/files"],
        },
        MANIFEST[1],
      ]);
    }).toThrow("Duplicate Test Google manifest route assignments");
  });

  it("fails unknown manifest routes", () => {
    expect(() => {
      validate([
        {
          ...MANIFEST[0],
          routeKeys: [
            "base:GET /v1/files/{fileId}",
            "base:GET /v1/files/{fileId}/bogus",
          ],
        },
        MANIFEST[1],
      ]);
    }).toThrow("Unknown Test Google manifest route keys");
  });

  it("fails missing official routes", () => {
    expect(() => {
      validateGoogleManifestPermissionManifest({
        serviceLabel: "Test Google",
        routeKinds: ROUTE_KINDS,
        officialRouteKeys: new Set([
          ...OFFICIAL_ROUTE_KEYS,
          "base:DELETE /v1/files/{fileId}",
        ]),
        manifest: MANIFEST,
        categoryOrder: ["Files"],
      });
    }).toThrow("Missing Test Google manifest route keys");
  });

  it("fails invalid category references", () => {
    expect(() => {
      validateGoogleManifestPermissionManifest({
        serviceLabel: "Test Google",
        routeKinds: ROUTE_KINDS,
        officialRouteKeys: OFFICIAL_ROUTE_KEYS,
        manifest: [
          MANIFEST[0],
          {
            ...MANIFEST[1],
            category: "Admin",
          },
        ],
        categoryOrder: ["Files"],
      });
    }).toThrow(
      "Test Google permissions reference categories outside display order",
    );
  });

  it("fails missing categories when category order is configured", () => {
    expect(() => {
      validateGoogleManifestPermissionManifest({
        serviceLabel: "Test Google",
        routeKinds: ROUTE_KINDS,
        officialRouteKeys: OFFICIAL_ROUTE_KEYS,
        manifest: [
          MANIFEST[0],
          {
            name: "files.write",
            description: "Create files.",
            routeKeys: ["base:POST /v1/files", "upload:POST /v1/files"],
          },
        ],
        categoryOrder: ["Files"],
      });
    }).toThrow("Test Google permissions missing categories");
  });

  it("fails duplicate category display order entries", () => {
    expect(() => {
      validateGoogleManifestPermissionManifest({
        serviceLabel: "Test Google",
        routeKinds: ROUTE_KINDS,
        officialRouteKeys: OFFICIAL_ROUTE_KEYS,
        manifest: MANIFEST,
        categoryOrder: ["Files", "Files"],
      });
    }).toThrow("Test Google category order has duplicate categories");
  });

  it("fails duplicate configured route kinds", () => {
    expect(() => {
      validateGoogleManifestPermissionManifest({
        serviceLabel: "Test Google",
        routeKinds: ["base", "base"],
        officialRouteKeys: new Set(["base:GET /v1/files/{fileId}"]),
        manifest: [
          {
            name: "files.read",
            description: "Read files.",
            routeKeys: ["base:GET /v1/files/{fileId}"],
          },
        ],
      });
    }).toThrow("Duplicate Test Google route kinds");
  });

  it("fails configured route kinds with no official routes", () => {
    expect(() => {
      compileGoogleManifestFirewall({
        serviceLabel: "Test Google",
        routeKinds: ROUTE_KINDS,
        officialRouteKeys: new Set(["base:GET /v1/files/{fileId}"]),
        manifest: [
          {
            name: "files.read",
            description: "Read files.",
            routeKeys: ["base:GET /v1/files/{fileId}"],
          },
        ],
        apis: APIS,
      });
    }).toThrow("Missing Test Google official route kinds");
  });

  it("fails API route kinds outside the configured route kinds", () => {
    expect(() => {
      compileGoogleManifestFirewall({
        serviceLabel: "Test Google",
        routeKinds: ["base"],
        officialRouteKeys: new Set(["base:GET /v1/files/{fileId}"]),
        manifest: [
          {
            name: "files.read",
            description: "Read files.",
            routeKeys: ["base:GET /v1/files/{fileId}"],
          },
        ],
        apis: [
          {
            base: "https://example.test/upload",
            kind: "upload",
          },
        ],
      });
    }).toThrow("Unknown Test Google API route kinds");
  });

  it("fails missing API route kinds", () => {
    expect(() => {
      compileGoogleManifestFirewall({
        serviceLabel: "Test Google",
        routeKinds: ROUTE_KINDS,
        officialRouteKeys: OFFICIAL_ROUTE_KEYS,
        manifest: MANIFEST,
        apis: [
          {
            base: "https://example.test/api",
            kind: "base",
          },
        ],
      });
    }).toThrow("Missing Test Google API route kinds");
  });

  it("fails duplicate API route kinds", () => {
    expect(() => {
      compileGoogleManifestFirewall({
        serviceLabel: "Test Google",
        routeKinds: ["base"],
        officialRouteKeys: new Set(["base:GET /v1/files/{fileId}"]),
        manifest: [
          {
            name: "files.read",
            description: "Read files.",
            routeKeys: ["base:GET /v1/files/{fileId}"],
          },
        ],
        apis: [
          {
            base: "https://example.test/api",
            kind: "base",
          },
          {
            base: "https://example.test/api-duplicate",
            kind: "base",
          },
        ],
      });
    }).toThrow("Duplicate Test Google API route kinds");
  });
});
