import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import {
  type BuiltinFirewallRuntimeFirewall,
  type PythonBuiltinFirewallCatalogEntry,
  type PythonBuiltinFirewallCatalogFile,
  renderPythonBuiltinFirewallCatalogFiles,
} from "../python-builtin-firewall-catalog";

const MAX_GENERATED_PYTHON_LINE_LENGTH = 512;
const TEST_GENERATED_HEADER = [
  "# @generated by test.",
  "# Do not edit by hand.",
  "# ruff: noqa",
] as const;

function testFirewall(
  name: string,
  rules: readonly string[] = [],
): BuiltinFirewallRuntimeFirewall {
  return {
    name,
    apis: [
      {
        base: `https://${name}.example.com`,
        auth: {},
        ...(rules.length > 0
          ? {
              permissions: [
                {
                  name: "test",
                  rules: [...rules],
                },
              ],
            }
          : {}),
      },
    ],
  };
}

function connectorEntry(
  firewall: BuiltinFirewallRuntimeFirewall,
): PythonBuiltinFirewallCatalogEntry {
  return {
    firewall,
    diagnosticKind: "connector",
  };
}

function modelProviderEntry(
  firewall: BuiltinFirewallRuntimeFirewall,
): PythonBuiltinFirewallCatalogEntry {
  return {
    firewall,
    diagnosticKind: "modelProvider",
  };
}

function renderEntries(
  entries: readonly PythonBuiltinFirewallCatalogEntry[],
  options: { readonly maxJsonChunkLength?: number } = {},
): readonly PythonBuiltinFirewallCatalogFile[] {
  return renderPythonBuiltinFirewallCatalogFiles({
    entries,
    generatedHeader: TEST_GENERATED_HEADER,
    maxJsonChunkLength: options.maxJsonChunkLength,
  });
}

function findGeneratedFile(
  files: readonly PythonBuiltinFirewallCatalogFile[],
  path: string,
): PythonBuiltinFirewallCatalogFile {
  const file = files.find((candidate) => {
    return candidate.path === path;
  });
  if (file === undefined) {
    throw new Error(`missing generated file: ${path}`);
  }
  return file;
}

function assertPythonCatalogLoadsNames(
  files: readonly PythonBuiltinFirewallCatalogFile[],
  names: readonly string[],
): void {
  const packageRoot = mkdtempSync(join(tmpdir(), "builtin-firewalls-"));
  const packageDir = join(packageRoot, "builtin_firewalls");
  try {
    mkdirSync(packageDir, { recursive: true });
    for (const file of files) {
      writeFileSync(join(packageDir, file.path), file.content);
    }

    execFileSync(
      "python3",
      [
        "-c",
        [
          "import json",
          "import os",
          "from builtin_firewalls import BUILTIN_FIREWALLS",
          'names = json.loads(os.environ["EXPECTED_FIREWALL_NAMES"])',
          "for name in names:",
          '    assert BUILTIN_FIREWALLS[name]["name"] == name',
        ].join("\n"),
      ],
      {
        env: {
          ...process.env,
          EXPECTED_FIREWALL_NAMES: JSON.stringify(names),
          PYTHONPATH: packageRoot,
        },
      },
    );
  } finally {
    rmSync(packageRoot, { recursive: true, force: true });
  }
}

function jsonPartFromModule(file: PythonBuiltinFirewallCatalogFile): string {
  const prefix = "JSON_PART = ";
  const start = file.content.indexOf(prefix);
  if (start === -1) {
    throw new Error(`missing JSON_PART assignment in ${file.path}`);
  }

  const literal = file.content.slice(start + prefix.length).trim();
  if (literal.startsWith('r"""') && literal.endsWith('"""')) {
    return literal.slice(4, -3);
  }

  const value: unknown = JSON.parse(literal);
  if (typeof value !== "string") {
    throw new Error(`JSON_PART assignment in ${file.path} is not a string`);
  }
  return value;
}

function jsonAssignmentFromModule(
  file: PythonBuiltinFirewallCatalogFile,
  name: string,
): unknown {
  const prefix = `${name} = `;
  const start = file.content.indexOf(prefix);
  if (start === -1) {
    throw new Error(`missing ${name} assignment in ${file.path}`);
  }

  const valueStart = start + prefix.length;
  const nextAssignment = file.content.indexOf("\n\n", valueStart);
  const literal = file.content
    .slice(
      valueStart,
      nextAssignment === -1 ? file.content.length : nextAssignment,
    )
    .trim();
  if (!literal.startsWith("json.loads(")) {
    return JSON.parse(literal);
  }

  const chunks: string[] = [];
  const stringLiteralPattern = /r"""([\s\S]*?)"""|"(?:\\.|[^"\\])*"/g;
  for (
    let match = stringLiteralPattern.exec(literal);
    match !== null;
    match = stringLiteralPattern.exec(literal)
  ) {
    const rawLiteral = match[1];
    if (rawLiteral !== undefined) {
      chunks.push(rawLiteral);
      continue;
    }
    const parsedLiteral: unknown = JSON.parse(match[0]);
    if (typeof parsedLiteral !== "string") {
      throw new Error(`invalid Python JSON string literal in ${file.path}`);
    }
    chunks.push(parsedLiteral);
  }

  return JSON.parse(chunks.join(""));
}

describe("Python builtin firewall catalog renderer", () => {
  it("renders a deterministic Python package from synthetic entries", () => {
    const entries = [
      connectorEntry(testFirewall("github")),
      modelProviderEntry(testFirewall("model-provider:openai-api-key")),
    ];
    const firstRender = renderEntries(entries);
    const secondRender = renderEntries(entries);
    const paths = firstRender.map((file) => {
      return file.path;
    });

    expect(secondRender).toStrictEqual(firstRender);
    expect(paths).toStrictEqual([
      "__init__.py",
      "manifest.py",
      "loader.py",
      "diagnostics.py",
      "github_0.py",
      "model_provider_openai_api_key_0.py",
    ]);
    expect(findGeneratedFile(firstRender, "__init__.py").content).toContain(
      "BUILTIN_FIREWALLS = _BuiltinFirewallCatalog()",
    );
    expect(findGeneratedFile(firstRender, "__init__.py").content).not.toContain(
      "importlib",
    );
    expect(findGeneratedFile(firstRender, "loader.py").content).toContain(
      "from . import github_0",
    );
    expect(findGeneratedFile(firstRender, "manifest.py").content).toContain(
      '"github": ("github_0",),',
    );
    expect(findGeneratedFile(firstRender, "github_0.py").content).toContain(
      "JSON_PART = ",
    );
    for (const file of firstRender) {
      expect(file.content).toContain("# @generated by test.");
      for (const line of file.content.split("\n")) {
        expect(line.length).toBeLessThanOrEqual(
          MAX_GENERATED_PYTHON_LINE_LENGTH,
        );
      }
    }
  });

  it("uses explicit diagnostic classification instead of name prefixes", () => {
    const files = renderEntries([
      connectorEntry({
        name: "model-provider:connector-prefix",
        apis: [
          {
            base: "https://connector-prefix.example.com",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.CONNECTOR_TOKEN }}",
              },
            },
          },
        ],
      }),
      connectorEntry({
        name: "serpapi",
        apis: [
          {
            base: "https://serpapi.com/search",
            auth: {
              query: {
                api_key: "${{ secrets.SERPAPI_TOKEN }}",
              },
            },
          },
        ],
      }),
      connectorEntry({
        name: "dynamic",
        apis: [
          {
            base: "https://{workspace}.example.com",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.DYNAMIC_TOKEN }}",
              },
            },
          },
        ],
      }),
      modelProviderEntry({
        name: "plain-provider",
        apis: [
          {
            base: "https://api.example.com/v1/responses",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.PROVIDER_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "responses",
                description: "Provider Responses API",
                rules: ["POST /"],
              },
            ],
          },
        ],
      }),
    ]);
    const diagnostics = findGeneratedFile(files, "diagnostics.py");

    expect(
      jsonAssignmentFromModule(diagnostics, "CONNECTOR_DIAGNOSTIC_FIREWALLS"),
    ).toStrictEqual([
      {
        name: "model-provider:connector-prefix",
        apis: [
          {
            base: "https://connector-prefix.example.com",
            envNames: ["CONNECTOR_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
      {
        name: "serpapi",
        apis: [
          {
            base: "https://serpapi.com/search",
            envNames: ["SERPAPI_TOKEN"],
            authHeaderNames: [],
            authQueryParamNames: ["api_key"],
          },
        ],
      },
    ]);
    expect(
      jsonAssignmentFromModule(
        diagnostics,
        "MODEL_PROVIDER_DIAGNOSTIC_EXCLUSIONS",
      ),
    ).toStrictEqual([
      {
        name: "plain-provider",
        apis: [
          {
            base: "https://api.example.com/v1/responses",
            permissions: [
              {
                name: "responses",
                rules: ["POST /"],
              },
            ],
          },
        ],
      },
    ]);
    expect(diagnostics.content).not.toContain("DYNAMIC_TOKEN");
    expect(diagnostics.content).not.toContain("JSON_PART");
    expect(diagnostics.content).not.toContain("Provider Responses API");
  });

  it("renders diagnostic JSON through json.loads so escaped unicode round-trips", () => {
    const emoji = "\u{1f600}";
    const files = renderEntries([
      modelProviderEntry({
        name: `model-provider:${emoji}`,
        apis: [
          {
            base: "https://api.example.com/v1/responses",
            auth: {},
            permissions: [
              {
                name: `responses-${emoji}`,
                rules: [`POST /emoji-${emoji}`],
              },
            ],
          },
        ],
      }),
    ]);
    const diagnostics = findGeneratedFile(files, "diagnostics.py");

    expect(diagnostics.content).toContain("import json");
    expect(diagnostics.content).toContain(
      "MODEL_PROVIDER_DIAGNOSTIC_EXCLUSIONS = json.loads(",
    );
    expect(diagnostics.content).toContain("\\ud83d\\ude00");
    expect(diagnostics.content).not.toContain(emoji);
    expect(
      jsonAssignmentFromModule(
        diagnostics,
        "MODEL_PROVIDER_DIAGNOSTIC_EXCLUSIONS",
      ),
    ).toStrictEqual([
      {
        name: `model-provider:${emoji}`,
        apis: [
          {
            base: "https://api.example.com/v1/responses",
            permissions: [
              {
                name: `responses-${emoji}`,
                rules: [`POST /emoji-${emoji}`],
              },
            ],
          },
        ],
      },
    ]);
  });

  it("renders manifest entries in sorted firewall-name order", () => {
    const files = renderEntries([
      connectorEntry(testFirewall("zeta")),
      connectorEntry(testFirewall("alpha")),
    ]);
    const manifest = findGeneratedFile(files, "manifest.py").content;

    expect(manifest.indexOf('"alpha"')).toBeLessThan(
      manifest.indexOf('"zeta"'),
    );
  });

  it("uses safe deterministic module names for non-module firewall names", () => {
    const files = renderEntries([
      modelProviderEntry(testFirewall("model-provider:openai-api-key")),
      connectorEntry(testFirewall("123-special")),
    ]);
    const manifest = findGeneratedFile(files, "manifest.py").content;
    const paths = files.map((file) => {
      return file.path;
    });

    expect(manifest).toContain(
      '"model-provider:openai-api-key": ("model_provider_openai_api_key_0",),',
    );
    expect(manifest).toContain('"123-special": ("firewall_123_special_0",),');
    expect(paths).toContain("model_provider_openai_api_key_0.py");
    expect(paths).toContain("firewall_123_special_0.py");
  });

  it("bounds generated module names for very long firewall names", () => {
    const longPrefix = `very-long-${"connector-".repeat(80)}`;
    const firstName = `${longPrefix}alpha`;
    const secondName = `${longPrefix}beta`;
    const files = renderEntries([
      connectorEntry(testFirewall(firstName)),
      connectorEntry(testFirewall(secondName)),
    ]);
    const manifest = findGeneratedFile(files, "manifest.py").content;
    const loader = findGeneratedFile(files, "loader.py").content;
    const partPaths = files
      .map((file) => {
        return file.path;
      })
      .filter((path) => {
        return path.endsWith("_0.py");
      });

    expect(partPaths).toHaveLength(2);
    expect(new Set(partPaths).size).toBe(2);
    for (const path of partPaths) {
      expect(path.length).toBeLessThanOrEqual(120);
    }
    for (const file of files) {
      for (const line of file.content.split("\n")) {
        expect(line.length).toBeLessThanOrEqual(
          MAX_GENERATED_PYTHON_LINE_LENGTH,
        );
      }
    }
    expect(loader).toContain("    if name == (\n");
    expect(manifest).toContain("    (\n");
    assertPythonCatalogLoadsNames(files, [firstName, secondName]);
  });

  it("deduplicates sanitized module-name collisions", () => {
    const files = renderEntries([
      connectorEntry(testFirewall("a-b")),
      connectorEntry(testFirewall("a:b")),
    ]);
    const manifest = findGeneratedFile(files, "manifest.py").content;
    const paths = files.map((file) => {
      return file.path;
    });

    expect(manifest).toContain('"a-b": ("a_b_0",),');
    expect(manifest).toContain('"a:b": ("a_b_2_0",),');
    expect(paths).toContain("a_b_0.py");
    expect(paths).toContain("a_b_2_0.py");
  });

  it("splits large firewall JSON into multiple generated modules", () => {
    const files = renderEntries(
      [
        connectorEntry(
          testFirewall("chunky", [
            "GET /alpha-alpha-alpha-alpha-alpha",
            "POST /beta-beta-beta-beta-beta",
          ]),
        ),
      ],
      {
        maxJsonChunkLength: 25,
      },
    );
    const manifest = findGeneratedFile(files, "manifest.py").content;
    const partFiles = files.filter((file) => {
      return file.path.startsWith("chunky_");
    });

    expect(partFiles.length).toBeGreaterThan(1);
    expect(manifest).toContain('"chunky": (');
    expect(
      JSON.parse(partFiles.map(jsonPartFromModule).join("")),
    ).toStrictEqual(
      testFirewall("chunky", [
        "GET /alpha-alpha-alpha-alpha-alpha",
        "POST /beta-beta-beta-beta-beta",
      ]),
    );
    for (const file of partFiles) {
      expect(file.content).toContain("JSON_PART = ");
    }
  });

  it("bounds source lines when a single JSON line is long", () => {
    const longRule = `GET /${"x".repeat(MAX_GENERATED_PYTHON_LINE_LENGTH * 2)}`;
    const escapedLongRule = `POST /${'\\"'.repeat(
      MAX_GENERATED_PYTHON_LINE_LENGTH,
    )}`;
    const firewall = testFirewall("long-line", [longRule, escapedLongRule]);
    const files = renderEntries([connectorEntry(firewall)]);
    const partFiles = files.filter((file) => {
      return file.path.startsWith("long_line_");
    });

    for (const file of files) {
      for (const line of file.content.split("\n")) {
        expect(line.length).toBeLessThanOrEqual(
          MAX_GENERATED_PYTHON_LINE_LENGTH,
        );
      }
    }
    expect(partFiles.length).toBeGreaterThan(1);
    expect(
      JSON.parse(partFiles.map(jsonPartFromModule).join("")),
    ).toStrictEqual(firewall);
  });

  it("renders chunk literals that preserve quote, backslash, and unicode boundaries", () => {
    const emoji = "\u{1f600}";
    const firewall = testFirewall("chunky", [
      `GET /emoji-${emoji}`,
      'POST /quote-"""',
      "PATCH /trailing-backslash\\",
    ]);
    const files = renderEntries([connectorEntry(firewall)], {
      maxJsonChunkLength: 1,
    });
    const partFiles = files.filter((file) => {
      return file.path.startsWith("chunky_");
    });
    const renderedJson = partFiles.map(jsonPartFromModule).join("");

    expect(partFiles.length).toBeGreaterThan(1);
    expect(renderedJson).toContain("\\ud83d\\ude00");
    expect(renderedJson).not.toContain(emoji);
    expect(JSON.parse(renderedJson)).toStrictEqual(firewall);
  });

  it("rejects duplicate firewall names", () => {
    expect(() => {
      renderEntries([
        connectorEntry(testFirewall("duplicate")),
        modelProviderEntry(testFirewall("duplicate")),
      ]);
    }).toThrow("duplicate built-in firewall catalog name: duplicate");
  });

  it("rejects unsupported JSON catalog values instead of silently rewriting them", () => {
    expect(() => {
      renderEntries([
        connectorEntry({
          ...testFirewall("nan"),
          observedAt: Number.NaN,
        }),
      ]);
    }).toThrow("unsupported JSON catalog number: NaN");

    expect(() => {
      renderEntries([
        connectorEntry({
          ...testFirewall("date"),
          observedAt: new Date("2026-06-24T00:00:00.000Z"),
        }),
      ]);
    }).toThrow("unsupported JSON catalog object: Date");
  });

  it("rejects circular JSON catalog values without rejecting shared objects", () => {
    const sharedAuth = {
      headers: {
        Authorization: "Bearer token",
      },
    };
    expect(() => {
      renderEntries([
        connectorEntry({
          name: "shared",
          apis: [
            {
              base: "https://shared-a.example.com",
              auth: sharedAuth,
            },
            {
              base: "https://shared-b.example.com",
              auth: sharedAuth,
            },
          ],
        }),
      ]);
    }).not.toThrow();

    const circular: Record<string, unknown> = {};
    circular.self = circular;

    expect(() => {
      renderEntries([
        connectorEntry({
          ...testFirewall("circular"),
          circular,
        }),
      ]);
    }).toThrow("unsupported circular JSON catalog value");

    const circularAuth: Record<string, unknown> = {};
    circularAuth.self = circularAuth;

    expect(() => {
      renderEntries([
        connectorEntry({
          name: "circular-auth",
          apis: [
            {
              base: "https://circular-auth.example.com",
              auth: circularAuth,
            },
          ],
        }),
      ]);
    }).toThrow("unsupported circular JSON catalog value");
  });
});
