import * as fs from "node:fs";
import * as path from "node:path";
import { describe, expect, it } from "vitest";

import {
  buildPythonBuiltinFirewallCatalog,
  renderComposedPythonBuiltinFirewallCatalogFiles,
  type PythonBuiltinFirewallSourceFirewall,
} from "../python-builtin-firewall-catalog-composition";
import type { PythonBuiltinFirewallCatalogFile } from "../python-builtin-firewall-catalog";

const TEST_GENERATED_HEADER = [
  "# @generated by test.",
  "# Do not edit by hand.",
  "# ruff: noqa",
] as const;
const FULL_FIREWALL_SOURCE_TEST_TIMEOUT_MS = 60_000;

function modelProviderFirewall(
  name = "model-provider:test",
): PythonBuiltinFirewallSourceFirewall {
  const firewall = {
    name,
    apis: [
      {
        base: "https://model-provider.example.com/v1/responses",
        auth: {
          headers: {
            Authorization: "Bearer ${{ secrets.MODEL_PROVIDER_TOKEN }}",
          },
        },
        permissions: [
          {
            name: "model:api",
            rules: ["POST /responses"],
            description: "Model API access",
          },
        ],
      },
    ],
    defaultPolicies: {
      unknownPolicy: "deny",
    },
    placeholders: {
      MODEL_PROVIDER_TOKEN: "placeholder",
    },
  };
  return firewall;
}

function findGeneratedContent(
  files: readonly PythonBuiltinFirewallCatalogFile[],
  generatedPath: string,
): string {
  const file = files.find((candidate) => {
    return candidate.path === generatedPath;
  });
  if (file === undefined) {
    throw new Error(`missing generated file: ${generatedPath}`);
  }
  return file.content;
}

function jsonAssignmentFromContent(content: string, name: string): unknown {
  const prefix = `${name} = `;
  const start = content.indexOf(prefix);
  if (start === -1) {
    throw new Error(`missing ${name} assignment`);
  }

  const valueStart = start + prefix.length;
  const nextAssignment = content.indexOf("\n\n", valueStart);
  const literal = content
    .slice(valueStart, nextAssignment === -1 ? content.length : nextAssignment)
    .trim();
  if (!literal.startsWith("json.loads(")) {
    return JSON.parse(literal);
  }

  const chunks: string[] = [];
  const stringLiteralPattern = /r"""([\s\S]*?)"""|"(?:\\.|[^"\\])*"/g;
  for (
    let match = stringLiteralPattern.exec(literal);
    match !== null;
    match = stringLiteralPattern.exec(literal)
  ) {
    const rawLiteral = match[1];
    if (rawLiteral !== undefined) {
      chunks.push(rawLiteral);
      continue;
    }
    const parsedLiteral: unknown = JSON.parse(match[0]);
    if (typeof parsedLiteral !== "string") {
      throw new Error("invalid Python JSON string literal");
    }
    chunks.push(parsedLiteral);
  }

  return JSON.parse(chunks.join(""));
}

describe("Python builtin firewall catalog composition", () => {
  it(
    "composes connector and caller-provided model-provider firewalls",
    async () => {
      const catalog = await buildPythonBuiltinFirewallCatalog({
        modelProviderFirewalls: [modelProviderFirewall()],
      });

      expect(catalog.firewalls.github?.apis[0]?.base).toBe(
        "https://api.github.com",
      );
      expect(catalog.firewalls["model-provider:test"]?.apis[0]?.base).toBe(
        "https://model-provider.example.com/v1/responses",
      );
      expect(catalog.firewalls.github).not.toHaveProperty("label");
      expect(catalog.firewalls.github).not.toHaveProperty("categories");
      expect(catalog.firewalls.github).not.toHaveProperty("defaultPolicies");
      expect(catalog.firewalls["model-provider:test"]).not.toHaveProperty(
        "placeholders",
      );
      expect(catalog.firewalls["model-provider:test"]).not.toHaveProperty(
        "defaultPolicies",
      );
      expect(
        catalog.firewalls["model-provider:test"]?.apis[0]?.permissions,
      ).toStrictEqual([
        {
          name: "model:api",
          rules: ["POST /responses"],
        },
      ]);
    },
    FULL_FIREWALL_SOURCE_TEST_TIMEOUT_MS,
  );

  it(
    "strips connector permission descriptions from the builtin runtime catalog",
    async () => {
      const catalog = await buildPythonBuiltinFirewallCatalog({
        modelProviderFirewalls: [],
      });
      const permission = catalog.firewalls.clerk?.apis
        .flatMap((api) => {
          return api.permissions ?? [];
        })
        .find((candidate) => {
          return candidate.name === "users:read";
        });

      expect(permission).toBeDefined();
      expect(permission).toMatchObject({
        name: "users:read",
        rules: expect.any(Array),
      });
      expect(permission).not.toHaveProperty("description");
    },
    FULL_FIREWALL_SOURCE_TEST_TIMEOUT_MS,
  );

  it(
    "preserves representative connector auth templates",
    async () => {
      const catalog = await buildPythonBuiltinFirewallCatalog({
        modelProviderFirewalls: [modelProviderFirewall()],
      });

      expect(catalog.firewalls.cloudflare?.apis[0]?.auth).toStrictEqual({
        headers: {
          Authorization: "Bearer ${{ secrets.CLOUDFLARE_TOKEN }}",
        },
      });
      expect(catalog.firewalls.serpapi?.apis[0]?.auth).toStrictEqual({
        query: {
          api_key: "${{ secrets.SERPAPI_TOKEN }}",
        },
      });
      expect(catalog.firewalls.aws?.apis[0]?.auth).toStrictEqual({
        awsSigv4: {
          accessKeyId: "${{ secrets.AWS_ACCESS_KEY_ID }}",
          secretAccessKey: "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
          sessionToken: "${{ secrets.AWS_SESSION_TOKEN }}",
        },
      });
    },
    FULL_FIREWALL_SOURCE_TEST_TIMEOUT_MS,
  );

  it(
    "keeps ScrapeNinja RapidAPI auth headers in the builtin catalog and diagnostics",
    async () => {
      const catalog = await buildPythonBuiltinFirewallCatalog({
        modelProviderFirewalls: [],
      });

      expect(catalog.firewalls.scrapeninja?.apis[0]).toMatchObject({
        base: "https://scrapeninja.p.rapidapi.com",
        auth: {
          headers: {
            "X-RapidAPI-Host": "scrapeninja.p.rapidapi.com",
            "X-RapidAPI-Key": "${{ secrets.SCRAPENINJA_TOKEN }}",
          },
        },
      });

      const files = await renderComposedPythonBuiltinFirewallCatalogFiles({
        modelProviderFirewalls: [],
        generatedHeader: TEST_GENERATED_HEADER,
      });
      const diagnostics = findGeneratedContent(files, "diagnostics.py");

      expect(
        jsonAssignmentFromContent(
          diagnostics,
          "CONNECTOR_DIAGNOSTIC_FIREWALLS",
        ),
      ).toEqual(
        expect.arrayContaining([
          {
            apis: [
              {
                authHeaderNames: ["X-RapidAPI-Host", "X-RapidAPI-Key"],
                authQueryParamNames: [],
                base: "https://scrapeninja.p.rapidapi.com",
                envNames: ["SCRAPENINJA_TOKEN"],
              },
            ],
            name: "scrapeninja",
          },
        ]),
      );
    },
    FULL_FIREWALL_SOURCE_TEST_TIMEOUT_MS,
  );

  it("renders explicit model-provider diagnostics without relying on name prefix", async () => {
    const files = await renderComposedPythonBuiltinFirewallCatalogFiles({
      modelProviderFirewalls: [modelProviderFirewall("plain-provider")],
      generatedHeader: TEST_GENERATED_HEADER,
    });

    expect(findGeneratedContent(files, "manifest.py")).toContain(
      '"plain-provider": ("plain_provider_0",),',
    );
    expect(findGeneratedContent(files, "diagnostics.py")).toContain(
      '"name": "plain-provider"',
    );
  });

  it(
    "rejects duplicate names across connector and model-provider sources",
    async () => {
      await expect(
        buildPythonBuiltinFirewallCatalog({
          modelProviderFirewalls: [modelProviderFirewall("github")],
        }),
      ).rejects.toThrow("duplicate built-in firewall catalog name: github");
    },
    FULL_FIREWALL_SOURCE_TEST_TIMEOUT_MS,
  );

  it("does not import eager connector catalogs or API contracts", () => {
    const source = fs.readFileSync(
      path.resolve(
        import.meta.dirname,
        "../python-builtin-firewall-catalog-composition.ts",
      ),
      "utf-8",
    );

    expect(source).not.toContain("@vm0/connectors/firewalls/all");
    expect(source).not.toContain("@vm0/api-contracts");
  });
});
