import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import {
  type BuiltinFirewallRuntimeApi,
  type BuiltinFirewallRuntimeFirewall,
  type PythonBuiltinFirewallCatalogEntry,
  type PythonBuiltinFirewallCatalogFile,
  renderPythonBuiltinFirewallCatalogFiles,
} from "../python-builtin-firewall-catalog";

const MAX_GENERATED_PYTHON_LINE_LENGTH = 512;
const TEST_GENERATED_HEADER = [
  "# @generated by test.",
  "# Do not edit by hand.",
  "# ruff: noqa",
] as const;

function testFirewall(
  name: string,
  rules: readonly string[] = [],
): BuiltinFirewallRuntimeFirewall {
  return {
    name,
    apis: [
      {
        base: `https://${name}.example.com`,
        auth: {},
        ...(rules.length > 0
          ? {
              permissions: [
                {
                  name: "test",
                  rules: [...rules],
                },
              ],
            }
          : {}),
      },
    ],
  };
}

function connectorEntry(
  firewall: BuiltinFirewallRuntimeFirewall,
): PythonBuiltinFirewallCatalogEntry {
  return {
    firewall,
    diagnosticKind: "connector",
  };
}

function modelProviderEntry(
  firewall: BuiltinFirewallRuntimeFirewall,
): PythonBuiltinFirewallCatalogEntry {
  return {
    firewall,
    diagnosticKind: "modelProvider",
  };
}

function renderEntries(
  entries: readonly PythonBuiltinFirewallCatalogEntry[],
  options: { readonly maxJsonChunkLength?: number } = {},
): readonly PythonBuiltinFirewallCatalogFile[] {
  return renderPythonBuiltinFirewallCatalogFiles({
    entries,
    generatedHeader: TEST_GENERATED_HEADER,
    maxJsonChunkLength: options.maxJsonChunkLength,
  });
}

function findGeneratedFile(
  files: readonly PythonBuiltinFirewallCatalogFile[],
  path: string,
): PythonBuiltinFirewallCatalogFile {
  const file = files.find((candidate) => {
    return candidate.path === path;
  });
  if (file === undefined) {
    throw new Error(`missing generated file: ${path}`);
  }
  return file;
}

function assertPythonCatalogLoadsNames(
  files: readonly PythonBuiltinFirewallCatalogFile[],
  names: readonly string[],
): void {
  const packageRoot = mkdtempSync(join(tmpdir(), "builtin-firewalls-"));
  const packageDir = join(packageRoot, "builtin_firewalls");
  try {
    mkdirSync(packageDir, { recursive: true });
    for (const file of files) {
      writeFileSync(join(packageDir, file.path), file.content);
    }

    execFileSync(
      "python3",
      [
        "-c",
        [
          "import json",
          "import os",
          "from builtin_firewalls import BUILTIN_FIREWALLS",
          'names = json.loads(os.environ["EXPECTED_FIREWALL_NAMES"])',
          "for name in names:",
          '    assert BUILTIN_FIREWALLS[name]["name"] == name',
        ].join("\n"),
      ],
      {
        env: {
          ...process.env,
          EXPECTED_FIREWALL_NAMES: JSON.stringify(names),
          PYTHONPATH: packageRoot,
        },
      },
    );
  } finally {
    rmSync(packageRoot, { recursive: true, force: true });
  }
}

function jsonPartFromModule(file: PythonBuiltinFirewallCatalogFile): string {
  const prefix = "JSON_PART = ";
  const start = file.content.indexOf(prefix);
  if (start === -1) {
    throw new Error(`missing JSON_PART assignment in ${file.path}`);
  }

  const literal = file.content.slice(start + prefix.length).trim();
  if (literal.startsWith('r"""') && literal.endsWith('"""')) {
    return literal.slice(4, -3);
  }

  const value: unknown = JSON.parse(literal);
  if (typeof value !== "string") {
    throw new Error(`JSON_PART assignment in ${file.path} is not a string`);
  }
  return value;
}

function jsonAssignmentFromModule(
  file: PythonBuiltinFirewallCatalogFile,
  name: string,
): unknown {
  const prefix = `${name} = `;
  const start = file.content.indexOf(prefix);
  if (start === -1) {
    throw new Error(`missing ${name} assignment in ${file.path}`);
  }

  const valueStart = start + prefix.length;
  const nextAssignment = file.content.indexOf("\n\n", valueStart);
  const literal = file.content
    .slice(
      valueStart,
      nextAssignment === -1 ? file.content.length : nextAssignment,
    )
    .trim();
  if (!literal.startsWith("json.loads(")) {
    return JSON.parse(literal);
  }

  const chunks: string[] = [];
  const stringLiteralPattern = /r"""([\s\S]*?)"""|"(?:\\.|[^"\\])*"/g;
  for (
    let match = stringLiteralPattern.exec(literal);
    match !== null;
    match = stringLiteralPattern.exec(literal)
  ) {
    const rawLiteral = match[1];
    if (rawLiteral !== undefined) {
      chunks.push(rawLiteral);
      continue;
    }
    const parsedLiteral: unknown = JSON.parse(match[0]);
    if (typeof parsedLiteral !== "string") {
      throw new Error(`invalid Python JSON string literal in ${file.path}`);
    }
    chunks.push(parsedLiteral);
  }

  return JSON.parse(chunks.join(""));
}

describe("Python builtin firewall catalog renderer", () => {
  it("renders a deterministic Python package from synthetic entries", () => {
    const entries = [
      connectorEntry(testFirewall("github")),
      modelProviderEntry(testFirewall("model-provider:openai-api-key")),
    ];
    const firstRender = renderEntries(entries);
    const secondRender = renderEntries(entries);
    const paths = firstRender.map((file) => {
      return file.path;
    });

    expect(secondRender).toStrictEqual(firstRender);
    expect(paths).toStrictEqual([
      "__init__.py",
      "manifest.py",
      "loader.py",
      "diagnostics.py",
      "github_0.py",
      "model_provider_openai_api_key_0.py",
    ]);
    expect(findGeneratedFile(firstRender, "__init__.py").content).toContain(
      "BUILTIN_FIREWALLS = _BuiltinFirewallCatalog()",
    );
    expect(findGeneratedFile(firstRender, "__init__.py").content).not.toContain(
      "importlib",
    );
    expect(findGeneratedFile(firstRender, "loader.py").content).toContain(
      "from . import github_0",
    );
    expect(findGeneratedFile(firstRender, "manifest.py").content).toContain(
      '"github": ("github_0",),',
    );
    expect(findGeneratedFile(firstRender, "github_0.py").content).toContain(
      "JSON_PART = ",
    );
    for (const file of firstRender) {
      expect(file.content).toContain("# @generated by test.");
      for (const line of file.content.split("\n")) {
        expect(line.length).toBeLessThanOrEqual(
          MAX_GENERATED_PYTHON_LINE_LENGTH,
        );
      }
    }
  });

  it("uses explicit diagnostic classification instead of name prefixes", () => {
    const files = renderEntries([
      connectorEntry({
        name: "model-provider:connector-prefix",
        apis: [
          {
            base: "https://connector-prefix.example.com",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.CONNECTOR_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "connector-read",
                rules: ["GET /items/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "serpapi",
        apis: [
          {
            base: "https://serpapi.com/search",
            auth: {
              query: {
                api_key: "${{ secrets.SERPAPI_TOKEN }}",
              },
            },
          },
        ],
      }),
      connectorEntry({
        name: "dynamic",
        apis: [
          {
            base: "https://{workspace}.example.com",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.DYNAMIC_TOKEN }}",
              },
            },
          },
        ],
      }),
      modelProviderEntry({
        name: "plain-provider",
        apis: [
          {
            base: "https://api.example.com/v1/responses",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.PROVIDER_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "responses",
                rules: ["POST /"],
              },
            ],
          },
        ],
      }),
    ]);
    const diagnostics = findGeneratedFile(files, "diagnostics.py");

    expect(
      jsonAssignmentFromModule(diagnostics, "CONNECTOR_DIAGNOSTIC_FIREWALLS"),
    ).toStrictEqual([
      {
        name: "model-provider:connector-prefix",
        apis: [
          {
            base: "https://connector-prefix.example.com",
            envNames: ["CONNECTOR_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
      {
        name: "serpapi",
        apis: [
          {
            base: "https://serpapi.com/search",
            envNames: ["SERPAPI_TOKEN"],
            authHeaderNames: [],
            authQueryParamNames: ["api_key"],
          },
        ],
      },
    ]);
    expect(
      jsonAssignmentFromModule(
        diagnostics,
        "MODEL_PROVIDER_DIAGNOSTIC_EXCLUSIONS",
      ),
    ).toStrictEqual([
      {
        name: "plain-provider",
        apis: [
          {
            base: "https://api.example.com/v1/responses",
            permissions: [
              {
                name: "responses",
                rules: ["POST /"],
              },
            ],
          },
        ],
      },
    ]);
    expect(diagnostics.content).not.toContain("DYNAMIC_TOKEN");
    expect(diagnostics.content).not.toContain("JSON_PART");
  });

  it("keeps connector diagnostic permissions only for shared static bases", () => {
    const files = renderEntries([
      connectorEntry({
        name: "shared-one",
        apis: [
          {
            base: "https://Shared.Example.com.:443/api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.SHARED_ONE_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "items:read",
                rules: ["GET /items/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "shared-two",
        apis: [
          {
            base: "https://shared.example.com/api/",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.SHARED_TWO_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "messages:read",
                rules: ["GET /messages/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "unique",
        apis: [
          {
            base: "https://unique.example.com",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.UNIQUE_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "unique:read",
                rules: ["GET /unique/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "duplicate-only",
        apis: [
          {
            base: "https://duplicate.example.com/api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.DUPLICATE_ONE_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "duplicate-one:read",
                rules: ["GET /one/{id}"],
              },
            ],
          },
          {
            base: "https://duplicate.example.com/api/",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.DUPLICATE_TWO_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "duplicate-two:read",
                rules: ["GET /two/{id}"],
              },
            ],
          },
        ],
      }),
    ]);
    const diagnostics = findGeneratedFile(files, "diagnostics.py");

    expect(
      jsonAssignmentFromModule(diagnostics, "CONNECTOR_DIAGNOSTIC_FIREWALLS"),
    ).toStrictEqual([
      {
        name: "duplicate-only",
        apis: [
          {
            base: "https://duplicate.example.com/api",
            envNames: ["DUPLICATE_ONE_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
          {
            base: "https://duplicate.example.com/api/",
            envNames: ["DUPLICATE_TWO_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
      {
        name: "shared-one",
        apis: [
          {
            base: "https://Shared.Example.com.:443/api",
            envNames: ["SHARED_ONE_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
            permissions: [
              {
                name: "items:read",
                rules: ["GET /items/{id}"],
              },
            ],
          },
        ],
      },
      {
        name: "shared-two",
        apis: [
          {
            base: "https://shared.example.com/api/",
            envNames: ["SHARED_TWO_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
            permissions: [
              {
                name: "messages:read",
                rules: ["GET /messages/{id}"],
              },
            ],
          },
        ],
      },
      {
        name: "unique",
        apis: [
          {
            base: "https://unique.example.com",
            envNames: ["UNIQUE_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
    ]);
  });

  it("uses runtime path semantics for diagnostic shared static bases", () => {
    const files = renderEntries([
      connectorEntry({
        name: "dot-segment",
        apis: [
          {
            base: "https://path.example.com/a/../b",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.DOT_SEGMENT_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "dot-segment:read",
                rules: ["GET /dot-segment/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "encoded-dot-segment",
        apis: [
          {
            base: "https://encoded-path.example.com/a/%2e%2e/b",
            auth: {
              headers: {
                Authorization:
                  "Bearer ${{ secrets.ENCODED_DOT_SEGMENT_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "encoded-dot-segment:read",
                rules: ["GET /encoded-dot-segment/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "encoded-target",
        apis: [
          {
            base: "https://encoded-path.example.com/b",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.ENCODED_TARGET_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "encoded-target:read",
                rules: ["GET /encoded-target/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "encoded-unicode-path",
        apis: [
          {
            base: "https://unicode-path.example.com/%E8%B7%AF%E5%BE%84",
            auth: {
              headers: {
                Authorization:
                  "Bearer ${{ secrets.ENCODED_UNICODE_PATH_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "encoded-unicode-path:read",
                rules: ["GET /encoded-unicode-path/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "normalized-target",
        apis: [
          {
            base: "https://path.example.com/b",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.NORMALIZED_TARGET_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "normalized-target:read",
                rules: ["GET /normalized-target/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "shared-path-one",
        apis: [
          {
            base: "https://shared-path.example.com/api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.SHARED_PATH_ONE_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "shared-path-one:read",
                rules: ["GET /one/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "shared-path-two",
        apis: [
          {
            base: "https://shared-path.example.com/api/",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.SHARED_PATH_TWO_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "shared-path-two:read",
                rules: ["GET /two/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "unicode-path",
        apis: [
          {
            base: "https://unicode-path.example.com/路径",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.UNICODE_PATH_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "unicode-path:read",
                rules: ["GET /unicode-path/{id}"],
              },
            ],
          },
        ],
      }),
    ]);
    const diagnostics = findGeneratedFile(files, "diagnostics.py");

    expect(
      jsonAssignmentFromModule(diagnostics, "CONNECTOR_DIAGNOSTIC_FIREWALLS"),
    ).toStrictEqual([
      {
        name: "dot-segment",
        apis: [
          {
            base: "https://path.example.com/a/../b",
            envNames: ["DOT_SEGMENT_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
      {
        name: "encoded-dot-segment",
        apis: [
          {
            base: "https://encoded-path.example.com/a/%2e%2e/b",
            envNames: ["ENCODED_DOT_SEGMENT_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
      {
        name: "encoded-target",
        apis: [
          {
            base: "https://encoded-path.example.com/b",
            envNames: ["ENCODED_TARGET_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
      {
        name: "encoded-unicode-path",
        apis: [
          {
            base: "https://unicode-path.example.com/%E8%B7%AF%E5%BE%84",
            envNames: ["ENCODED_UNICODE_PATH_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
      {
        name: "normalized-target",
        apis: [
          {
            base: "https://path.example.com/b",
            envNames: ["NORMALIZED_TARGET_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
      {
        name: "shared-path-one",
        apis: [
          {
            base: "https://shared-path.example.com/api",
            envNames: ["SHARED_PATH_ONE_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
            permissions: [
              {
                name: "shared-path-one:read",
                rules: ["GET /one/{id}"],
              },
            ],
          },
        ],
      },
      {
        name: "shared-path-two",
        apis: [
          {
            base: "https://shared-path.example.com/api/",
            envNames: ["SHARED_PATH_TWO_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
            permissions: [
              {
                name: "shared-path-two:read",
                rules: ["GET /two/{id}"],
              },
            ],
          },
        ],
      },
      {
        name: "unicode-path",
        apis: [
          {
            base: "https://unicode-path.example.com/路径",
            envNames: ["UNICODE_PATH_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
    ]);
  });

  it("omits connector diagnostic APIs whose static bases are invalid at runtime", () => {
    const files = renderEntries([
      connectorEntry({
        name: "malformed-dot",
        apis: [
          {
            base: "https://shared-dot.example.com../api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.MALFORMED_DOT_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "malformed:read",
                rules: ["GET /malformed/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "empty-port",
        apis: [
          {
            base: "https://shared-dot.example.com:/api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.EMPTY_PORT_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "empty-port:read",
                rules: ["GET /empty-port/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "userinfo",
        apis: [
          {
            base: "https://user@shared-dot.example.com/api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.USERINFO_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "userinfo:read",
                rules: ["GET /userinfo/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "query-base",
        apis: [
          {
            base: "https://shared-dot.example.com/api?version=1",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.QUERY_BASE_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "query-base:read",
                rules: ["GET /query-base/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "encoded-dot",
        apis: [
          {
            base: "https://shared-dot.example%2ecom/api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.ENCODED_DOT_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "encoded-dot:read",
                rules: ["GET /encoded-dot/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "backslash-base",
        apis: [
          {
            base: "https://shared-dot.example.com\\api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.BACKSLASH_BASE_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "backslash-base:read",
                rules: ["GET /backslash-base/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "raw-space-base",
        apis: [
          {
            base: "https://shared-dot.example.com/ raw-space",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.RAW_SPACE_BASE_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "raw-space-base:read",
                rules: ["GET /raw-space-base/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "valid-dot",
        apis: [
          {
            base: "https://shared-dot.example.com/api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.VALID_DOT_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "valid:read",
                rules: ["GET /valid/{id}"],
              },
            ],
          },
        ],
      }),
    ]);
    const diagnostics = findGeneratedFile(files, "diagnostics.py");

    expect(
      jsonAssignmentFromModule(diagnostics, "CONNECTOR_DIAGNOSTIC_FIREWALLS"),
    ).toStrictEqual([
      {
        name: "valid-dot",
        apis: [
          {
            base: "https://shared-dot.example.com/api",
            envNames: ["VALID_DOT_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
          },
        ],
      },
    ]);
  });

  it("keeps runtime-safe percent-encoded host escapes in shared static base matching", () => {
    const files = renderEntries([
      connectorEntry({
        name: "encoded-host",
        apis: [
          {
            base: "https://shared%2ddot.example.com/api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.ENCODED_HOST_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "encoded-host:read",
                rules: ["GET /encoded-host/{id}"],
              },
            ],
          },
        ],
      }),
      connectorEntry({
        name: "decoded-host",
        apis: [
          {
            base: "https://shared-dot.example.com/api",
            auth: {
              headers: {
                Authorization: "Bearer ${{ secrets.DECODED_HOST_TOKEN }}",
              },
            },
            permissions: [
              {
                name: "decoded-host:read",
                rules: ["GET /decoded-host/{id}"],
              },
            ],
          },
        ],
      }),
    ]);
    const diagnostics = findGeneratedFile(files, "diagnostics.py");

    expect(
      jsonAssignmentFromModule(diagnostics, "CONNECTOR_DIAGNOSTIC_FIREWALLS"),
    ).toStrictEqual([
      {
        name: "decoded-host",
        apis: [
          {
            base: "https://shared-dot.example.com/api",
            envNames: ["DECODED_HOST_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
            permissions: [
              {
                name: "decoded-host:read",
                rules: ["GET /decoded-host/{id}"],
              },
            ],
          },
        ],
      },
      {
        name: "encoded-host",
        apis: [
          {
            base: "https://shared%2ddot.example.com/api",
            envNames: ["ENCODED_HOST_TOKEN"],
            authHeaderNames: ["Authorization"],
            authQueryParamNames: [],
            permissions: [
              {
                name: "encoded-host:read",
                rules: ["GET /encoded-host/{id}"],
              },
            ],
          },
        ],
      },
    ]);
  });

  it("preserves runtime API host policies in catalog JSON", () => {
    const files = renderEntries([
      connectorEntry({
        name: "jira",
        apis: [
          {
            base: "https://${{ vars.JIRA_DOMAIN }}",
            hostPolicy: {
              kind: "providerOwned",
              suffixes: ["atlassian.net"],
            },
            auth: {
              headers: {
                Authorization:
                  "${{ basic(vars.JIRA_EMAIL, secrets.JIRA_API_TOKEN) }}",
              },
            },
          },
        ],
      }),
    ]);
    const module = findGeneratedFile(files, "jira_0.py");

    expect(JSON.parse(jsonPartFromModule(module))).toStrictEqual({
      name: "jira",
      apis: [
        {
          base: "https://${{ vars.JIRA_DOMAIN }}",
          hostPolicy: {
            kind: "providerOwned",
            suffixes: ["atlassian.net"],
          },
          auth: {
            headers: {
              Authorization:
                "${{ basic(vars.JIRA_EMAIL, secrets.JIRA_API_TOKEN) }}",
            },
          },
        },
      ],
    });
  });

  it("renders diagnostic JSON through json.loads so escaped unicode round-trips", () => {
    const emoji = "\u{1f600}";
    const files = renderEntries([
      modelProviderEntry({
        name: `model-provider:${emoji}`,
        apis: [
          {
            base: "https://api.example.com/v1/responses",
            auth: {},
            permissions: [
              {
                name: `responses-${emoji}`,
                rules: [`POST /emoji-${emoji}`],
              },
            ],
          },
        ],
      }),
    ]);
    const diagnostics = findGeneratedFile(files, "diagnostics.py");

    expect(diagnostics.content).toContain("import json");
    expect(diagnostics.content).toContain(
      "MODEL_PROVIDER_DIAGNOSTIC_EXCLUSIONS = json.loads(",
    );
    expect(diagnostics.content).toContain("\\ud83d\\ude00");
    expect(diagnostics.content).not.toContain(emoji);
    expect(
      jsonAssignmentFromModule(
        diagnostics,
        "MODEL_PROVIDER_DIAGNOSTIC_EXCLUSIONS",
      ),
    ).toStrictEqual([
      {
        name: `model-provider:${emoji}`,
        apis: [
          {
            base: "https://api.example.com/v1/responses",
            permissions: [
              {
                name: `responses-${emoji}`,
                rules: [`POST /emoji-${emoji}`],
              },
            ],
          },
        ],
      },
    ]);
  });

  it("renders Python string keys that load for escaped firewall names", () => {
    const names = [
      'quote"name',
      "backslash\\name",
      "line\nname",
      "tab\tname",
      "unicode-\u{1f600}",
      "separator-\u2028-name",
    ];
    const files = renderEntries(
      names.map((name, index) => {
        return connectorEntry({
          name,
          apis: [
            {
              base: `https://escaped-name-${index}.example.com`,
              auth: {},
            },
          ],
        });
      }),
    );

    assertPythonCatalogLoadsNames(files, names);
  });

  it("renders manifest entries in sorted firewall-name order", () => {
    const files = renderEntries([
      connectorEntry(testFirewall("zeta")),
      connectorEntry(testFirewall("alpha")),
    ]);
    const manifest = findGeneratedFile(files, "manifest.py").content;

    expect(manifest.indexOf('"alpha"')).toBeLessThan(
      manifest.indexOf('"zeta"'),
    );
  });

  it("uses safe deterministic module names for non-module firewall names", () => {
    const files = renderEntries([
      modelProviderEntry(testFirewall("model-provider:openai-api-key")),
      connectorEntry(testFirewall("123-special")),
    ]);
    const manifest = findGeneratedFile(files, "manifest.py").content;
    const paths = files.map((file) => {
      return file.path;
    });

    expect(manifest).toContain(
      '"model-provider:openai-api-key": ("model_provider_openai_api_key_0",),',
    );
    expect(manifest).toContain('"123-special": ("firewall_123_special_0",),');
    expect(paths).toContain("model_provider_openai_api_key_0.py");
    expect(paths).toContain("firewall_123_special_0.py");
  });

  it("bounds generated module names for very long firewall names", () => {
    const longPrefix = `very-long-${"connector-".repeat(80)}`;
    const firstName = `${longPrefix}alpha`;
    const secondName = `${longPrefix}beta`;
    const files = renderEntries([
      connectorEntry(testFirewall(firstName)),
      connectorEntry(testFirewall(secondName)),
    ]);
    const manifest = findGeneratedFile(files, "manifest.py").content;
    const loader = findGeneratedFile(files, "loader.py").content;
    const partPaths = files
      .map((file) => {
        return file.path;
      })
      .filter((path) => {
        return path.endsWith("_0.py");
      });

    expect(partPaths).toHaveLength(2);
    expect(new Set(partPaths).size).toBe(2);
    for (const path of partPaths) {
      expect(path.length).toBeLessThanOrEqual(120);
    }
    for (const file of files) {
      for (const line of file.content.split("\n")) {
        expect(line.length).toBeLessThanOrEqual(
          MAX_GENERATED_PYTHON_LINE_LENGTH,
        );
      }
    }
    expect(loader).toContain("    if name == (\n");
    expect(manifest).toContain("    (\n");
    assertPythonCatalogLoadsNames(files, [firstName, secondName]);
  });

  it("deduplicates sanitized module-name collisions", () => {
    const files = renderEntries([
      connectorEntry(testFirewall("a-b")),
      connectorEntry(testFirewall("a:b")),
    ]);
    const manifest = findGeneratedFile(files, "manifest.py").content;
    const paths = files.map((file) => {
      return file.path;
    });

    expect(manifest).toContain('"a-b": ("a_b_0",),');
    expect(manifest).toContain('"a:b": ("a_b_2_0",),');
    expect(paths).toContain("a_b_0.py");
    expect(paths).toContain("a_b_2_0.py");
  });

  it("splits large firewall JSON into multiple generated modules", () => {
    const files = renderEntries(
      [
        connectorEntry(
          testFirewall("chunky", [
            "GET /alpha-alpha-alpha-alpha-alpha",
            "POST /beta-beta-beta-beta-beta",
          ]),
        ),
      ],
      {
        maxJsonChunkLength: 25,
      },
    );
    const manifest = findGeneratedFile(files, "manifest.py").content;
    const partFiles = files.filter((file) => {
      return file.path.startsWith("chunky_");
    });

    expect(partFiles.length).toBeGreaterThan(1);
    expect(manifest).toContain('"chunky": (');
    expect(
      JSON.parse(partFiles.map(jsonPartFromModule).join("")),
    ).toStrictEqual(
      testFirewall("chunky", [
        "GET /alpha-alpha-alpha-alpha-alpha",
        "POST /beta-beta-beta-beta-beta",
      ]),
    );
    for (const file of partFiles) {
      expect(file.content).toContain("JSON_PART = ");
    }
  });

  it("bounds source lines when a single JSON line is long", () => {
    const longRule = `GET /${"x".repeat(MAX_GENERATED_PYTHON_LINE_LENGTH * 2)}`;
    const escapedLongRule = `POST /${'\\"'.repeat(
      MAX_GENERATED_PYTHON_LINE_LENGTH,
    )}`;
    const firewall = testFirewall("long-line", [longRule, escapedLongRule]);
    const files = renderEntries([connectorEntry(firewall)]);
    const partFiles = files.filter((file) => {
      return file.path.startsWith("long_line_");
    });

    for (const file of files) {
      for (const line of file.content.split("\n")) {
        expect(line.length).toBeLessThanOrEqual(
          MAX_GENERATED_PYTHON_LINE_LENGTH,
        );
      }
    }
    expect(partFiles.length).toBeGreaterThan(1);
    expect(
      JSON.parse(partFiles.map(jsonPartFromModule).join("")),
    ).toStrictEqual(firewall);
  });

  it("renders chunk literals that preserve quote, backslash, and unicode boundaries", () => {
    const emoji = "\u{1f600}";
    const firewall = testFirewall("chunky", [
      `GET /emoji-${emoji}`,
      'POST /quote-"""',
      "PATCH /trailing-backslash\\",
    ]);
    const files = renderEntries([connectorEntry(firewall)], {
      maxJsonChunkLength: 1,
    });
    const partFiles = files.filter((file) => {
      return file.path.startsWith("chunky_");
    });
    const renderedJson = partFiles.map(jsonPartFromModule).join("");

    expect(partFiles.length).toBeGreaterThan(1);
    expect(renderedJson).toContain("\\ud83d\\ude00");
    expect(renderedJson).not.toContain(emoji);
    expect(JSON.parse(renderedJson)).toStrictEqual(firewall);
  });

  it("rejects duplicate firewall names", () => {
    expect(() => {
      renderEntries([
        connectorEntry(testFirewall("duplicate")),
        modelProviderEntry(testFirewall("duplicate")),
      ]);
    }).toThrow("duplicate built-in firewall catalog name: duplicate");
  });

  it("rejects unsupported JSON catalog values instead of silently rewriting them", () => {
    expect(() => {
      renderEntries([
        connectorEntry({
          ...testFirewall("nan"),
          observedAt: Number.NaN,
        }),
      ]);
    }).toThrow("unsupported JSON catalog number: NaN");

    expect(() => {
      renderEntries([
        connectorEntry({
          ...testFirewall("date"),
          observedAt: new Date("2026-06-24T00:00:00.000Z"),
        }),
      ]);
    }).toThrow("unsupported JSON catalog object: Date");

    let constructorAccessorInvoked = false;
    const constructorAccessorPrototype = {};
    Object.defineProperty(constructorAccessorPrototype, "constructor", {
      get() {
        constructorAccessorInvoked = true;
        return Date;
      },
    });
    const objectWithConstructorAccessor = {
      name: "constructor-accessor",
      apis: [
        {
          base: "https://constructor-accessor.example.com",
          auth: {},
        },
      ],
    };
    Object.setPrototypeOf(
      objectWithConstructorAccessor,
      constructorAccessorPrototype,
    );
    expect(() => {
      renderEntries([connectorEntry(objectWithConstructorAccessor)]);
    }).toThrow("unsupported JSON catalog object: unknown");
    expect(constructorAccessorInvoked).toBe(false);

    expect(() => {
      renderEntries([
        connectorEntry({
          ...testFirewall("undefined"),
          observedAt: undefined,
        }),
      ]);
    }).toThrow("unsupported JSON catalog value: undefined");

    expect(() => {
      renderEntries([
        connectorEntry({
          ...testFirewall("symbol-key"),
          [Symbol("internal")]: "hidden",
        }),
      ]);
    }).toThrow("unsupported JSON catalog object symbol key");

    const objectWithHiddenProperty = {
      ...testFirewall("hidden-object-property"),
    };
    Object.defineProperty(objectWithHiddenProperty, "hidden", {
      value: "secret",
    });
    expect(() => {
      renderEntries([connectorEntry(objectWithHiddenProperty)]);
    }).toThrow(
      "unsupported JSON catalog object non-enumerable property: hidden",
    );

    let objectAccessorInvoked = false;
    const objectWithAccessor = {
      ...testFirewall("object-accessor"),
    };
    Object.defineProperty(objectWithAccessor, "dynamic", {
      enumerable: true,
      get() {
        objectAccessorInvoked = true;
        return "secret";
      },
    });
    expect(() => {
      renderEntries([connectorEntry(objectWithAccessor)]);
    }).toThrow("unsupported JSON catalog object accessor property: dynamic");
    expect(objectAccessorInvoked).toBe(false);

    let nameAccessorInvoked = false;
    const firewallWithNameAccessor = testFirewall("name-accessor");
    Object.defineProperty(firewallWithNameAccessor, "name", {
      enumerable: true,
      get() {
        nameAccessorInvoked = true;
        return "name-accessor";
      },
    });
    expect(() => {
      renderEntries([connectorEntry(firewallWithNameAccessor)]);
    }).toThrow("unsupported JSON catalog object accessor property: name");
    expect(nameAccessorInvoked).toBe(false);

    let authAccessorInvoked = false;
    const authWithAccessor: Record<string, unknown> = {};
    Object.defineProperty(authWithAccessor, "headers", {
      enumerable: true,
      get() {
        authAccessorInvoked = true;
        return {
          Authorization: "Bearer ${{ secrets.ACCESSOR_TOKEN }}",
        };
      },
    });
    expect(() => {
      renderEntries([
        connectorEntry({
          name: "auth-accessor",
          apis: [
            {
              base: "https://auth-accessor.example.com",
              auth: authWithAccessor,
            },
          ],
        }),
      ]);
    }).toThrow("unsupported JSON catalog object accessor property: headers");
    expect(authAccessorInvoked).toBe(false);

    const sparseApis: BuiltinFirewallRuntimeApi[] = [];
    sparseApis[1] = {
      base: "https://sparse-array.example.com",
      auth: {},
    };
    expect(() => {
      renderEntries([
        connectorEntry({
          name: "sparse-array",
          apis: sparseApis,
        }),
      ]);
    }).toThrow("unsupported sparse JSON catalog array");

    const apisWithProperty: BuiltinFirewallRuntimeApi[] & {
      extra?: string;
    } = [
      {
        base: "https://array-property.example.com",
        auth: {},
      },
    ];
    apisWithProperty.extra = "hidden";
    expect(() => {
      renderEntries([
        connectorEntry({
          name: "array-property",
          apis: apisWithProperty,
        }),
      ]);
    }).toThrow("unsupported JSON catalog array property: extra");

    const apisWithHiddenProperty: BuiltinFirewallRuntimeApi[] = [
      {
        base: "https://hidden-array-property.example.com",
        auth: {},
      },
    ];
    Object.defineProperty(apisWithHiddenProperty, "hidden", {
      value: "secret",
    });
    expect(() => {
      renderEntries([
        connectorEntry({
          name: "hidden-array-property",
          apis: apisWithHiddenProperty,
        }),
      ]);
    }).toThrow("unsupported JSON catalog array property: hidden");

    let arrayAccessorInvoked = false;
    const apisWithAccessor: BuiltinFirewallRuntimeApi[] = [
      {
        base: "https://array-accessor.example.com",
        auth: {},
      },
    ];
    Object.defineProperty(apisWithAccessor, "0", {
      enumerable: true,
      get() {
        arrayAccessorInvoked = true;
        return {
          base: "https://array-accessor.example.com",
          auth: {},
        };
      },
    });
    expect(() => {
      renderEntries([
        connectorEntry({
          name: "array-accessor",
          apis: apisWithAccessor,
        }),
      ]);
    }).toThrow("unsupported JSON catalog array accessor property: 0");
    expect(arrayAccessorInvoked).toBe(false);

    const apisWithSymbol: BuiltinFirewallRuntimeApi[] = [
      {
        base: "https://array-symbol.example.com",
        auth: {},
      },
    ];
    Object.defineProperty(apisWithSymbol, Symbol("internal"), {
      value: "hidden",
    });
    expect(() => {
      renderEntries([
        connectorEntry({
          name: "array-symbol",
          apis: apisWithSymbol,
        }),
      ]);
    }).toThrow("unsupported JSON catalog array symbol key");
  });

  it("rejects circular JSON catalog values without rejecting shared objects", () => {
    const sharedAuth = {
      headers: {
        Authorization: "Bearer token",
      },
    };
    expect(() => {
      renderEntries([
        connectorEntry({
          name: "shared",
          apis: [
            {
              base: "https://shared-a.example.com",
              auth: sharedAuth,
            },
            {
              base: "https://shared-b.example.com",
              auth: sharedAuth,
            },
          ],
        }),
      ]);
    }).not.toThrow();

    const circular: Record<string, unknown> = {};
    circular.self = circular;

    expect(() => {
      renderEntries([
        connectorEntry({
          ...testFirewall("circular"),
          circular,
        }),
      ]);
    }).toThrow("unsupported circular JSON catalog value");

    const circularAuth: Record<string, unknown> = {};
    circularAuth.self = circularAuth;

    expect(() => {
      renderEntries([
        connectorEntry({
          name: "circular-auth",
          apis: [
            {
              base: "https://circular-auth.example.com",
              auth: circularAuth,
            },
          ],
        }),
      ]);
    }).toThrow("unsupported circular JSON catalog value");
  });
});
