import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, describe, expect, it } from "vitest";

import {
  generatePythonBuiltinFirewallCatalogPackage,
  renderProjectPythonBuiltinFirewallCatalogFiles,
} from "../python-builtin-firewall-catalog-package";

const FULL_FIREWALL_SOURCE_TEST_TIMEOUT_MS = 60_000;
const tempDirs: string[] = [];

async function makeTempDir(): Promise<string> {
  const tempDir = await mkdtemp(
    join(tmpdir(), "python-builtin-firewall-catalog-"),
  );
  tempDirs.push(tempDir);
  return tempDir;
}

function findGeneratedContent(
  files: readonly { readonly path: string; readonly content: string }[],
  generatedPath: string,
): string {
  const file = files.find((candidate) => {
    return candidate.path === generatedPath;
  });
  if (file === undefined) {
    throw new Error(`missing generated file: ${generatedPath}`);
  }
  return file.content;
}

async function readGeneratedFile(
  packageDir: string,
  generatedPath: string,
): Promise<string> {
  return await readFile(join(packageDir, generatedPath), "utf-8");
}

afterEach(async () => {
  await Promise.all(
    tempDirs.splice(0).map(async (tempDir) => {
      await rm(tempDir, { recursive: true, force: true });
    }),
  );
});

describe("Python builtin firewall catalog package generation", () => {
  it(
    "renders project connector and model-provider firewalls with generator headers",
    async () => {
      const files = await renderProjectPythonBuiltinFirewallCatalogFiles();
      const paths = files.map((file) => {
        return file.path;
      });

      expect(paths).toContain("__init__.py");
      expect(paths).toContain("loader.py");
      expect(paths).toContain("manifest.py");
      expect(paths).toContain("diagnostics.py");
      expect(paths).toContain("github_0.py");
      expect(paths).toContain("model_provider_openai_api_key_0.py");
      expect(findGeneratedContent(files, "__init__.py")).toContain(
        "# @generated by @vm0/firewalls-generator.",
      );
      expect(findGeneratedContent(files, "__init__.py")).toContain(
        "BUILTIN_FIREWALLS = _BuiltinFirewallCatalog()",
      );
      expect(findGeneratedContent(files, "loader.py")).toContain(
        "from . import github_0",
      );
      expect(findGeneratedContent(files, "manifest.py")).toContain(
        '"github": ("github_0",),',
      );
      expect(findGeneratedContent(files, "manifest.py")).toContain(
        '"model-provider:openai-api-key": ("model_provider_openai_api_key_0",),',
      );
    },
    FULL_FIREWALL_SOURCE_TEST_TIMEOUT_MS,
  );

  it(
    "writes the package to disk and removes the legacy single-file catalog",
    async () => {
      const tempDir = await makeTempDir();
      const packageDir = join(tempDir, "builtin_firewalls");
      const legacyPath = join(tempDir, "builtin_firewalls.py");
      await writeFile(legacyPath, "legacy");

      await generatePythonBuiltinFirewallCatalogPackage({
        outputPath: packageDir,
        legacyOutputPath: legacyPath,
      });

      await expect(readFile(legacyPath, "utf-8")).rejects.toMatchObject({
        code: "ENOENT",
      });
      await expect(
        readGeneratedFile(packageDir, "__init__.py"),
      ).resolves.toContain("# @generated by @vm0/firewalls-generator.");
      await expect(
        readGeneratedFile(packageDir, "loader.py"),
      ).resolves.toContain("from . import model_provider_openai_api_key_0");
      await expect(
        readGeneratedFile(packageDir, "manifest.py"),
      ).resolves.toContain(
        '"model-provider:openai-api-key": ("model_provider_openai_api_key_0",),',
      );
    },
    FULL_FIREWALL_SOURCE_TEST_TIMEOUT_MS,
  );

  it("keeps the project writer on a narrow model-provider contracts import", async () => {
    const source = await readFile(
      resolve(
        import.meta.dirname,
        "../python-builtin-firewall-catalog-package.ts",
      ),
      "utf-8",
    );

    expect(source).toContain(
      "@vm0/api-contracts/contracts/model-provider-firewalls",
    );
    expect(source).not.toContain(
      "@vm0/api-contracts/contracts/model-providers",
    );
    expect(source).not.toContain('from "@vm0/api-contracts"');
    expect(source).not.toContain("@vm0/connectors/firewalls/all");
  });
});
