import * as fs from "node:fs";
import * as path from "node:path";
import { describe, expect, it } from "vitest";

import {
  buildPythonBuiltinFirewallCatalog,
  renderComposedPythonBuiltinFirewallCatalogFiles,
} from "../python-builtin-firewall-catalog-composition";
import type {
  BuiltinFirewallRuntimeFirewall,
  PythonBuiltinFirewallCatalogFile,
} from "../python-builtin-firewall-catalog";

const TEST_GENERATED_HEADER = [
  "# @generated by test.",
  "# Do not edit by hand.",
  "# ruff: noqa",
] as const;

function modelProviderFirewall(
  name = "model-provider:test",
): BuiltinFirewallRuntimeFirewall {
  return {
    name,
    apis: [
      {
        base: "https://model-provider.example.com/v1/responses",
        auth: {
          headers: {
            Authorization: "Bearer ${{ secrets.MODEL_PROVIDER_TOKEN }}",
          },
        },
        permissions: [
          {
            name: "model:api",
            rules: ["POST /responses"],
            description: "Model API access",
          },
        ],
      },
    ],
    defaultPolicies: {
      unknownPolicy: "deny",
    },
    placeholders: {
      MODEL_PROVIDER_TOKEN: "placeholder",
    },
  };
}

function findGeneratedContent(
  files: readonly PythonBuiltinFirewallCatalogFile[],
  generatedPath: string,
): string {
  const file = files.find((candidate) => {
    return candidate.path === generatedPath;
  });
  if (file === undefined) {
    throw new Error(`missing generated file: ${generatedPath}`);
  }
  return file.content;
}

describe("Python builtin firewall catalog composition", () => {
  it("composes connector and caller-provided model-provider firewalls", async () => {
    const catalog = await buildPythonBuiltinFirewallCatalog({
      modelProviderFirewalls: [modelProviderFirewall()],
    });

    expect(catalog.firewalls.github?.apis[0]?.base).toBe(
      "https://api.github.com",
    );
    expect(catalog.firewalls["model-provider:test"]?.apis[0]?.base).toBe(
      "https://model-provider.example.com/v1/responses",
    );
    expect(catalog.firewalls.github).not.toHaveProperty("label");
    expect(catalog.firewalls.github).not.toHaveProperty("categories");
    expect(catalog.firewalls.github).not.toHaveProperty("defaultPolicies");
    expect(catalog.firewalls["model-provider:test"]).not.toHaveProperty(
      "placeholders",
    );
    expect(catalog.firewalls["model-provider:test"]).not.toHaveProperty(
      "defaultPolicies",
    );
  });

  it("preserves representative connector auth templates", async () => {
    const catalog = await buildPythonBuiltinFirewallCatalog({
      modelProviderFirewalls: [modelProviderFirewall()],
    });

    expect(catalog.firewalls.cloudflare?.apis[0]?.auth).toStrictEqual({
      headers: {
        Authorization: "Bearer ${{ secrets.CLOUDFLARE_TOKEN }}",
      },
    });
    expect(catalog.firewalls.serpapi?.apis[0]?.auth).toStrictEqual({
      query: {
        api_key: "${{ secrets.SERPAPI_TOKEN }}",
      },
    });
    expect(catalog.firewalls.aws?.apis[0]?.auth).toStrictEqual({
      awsSigv4: {
        accessKeyId: "${{ secrets.AWS_ACCESS_KEY_ID }}",
        secretAccessKey: "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
        sessionToken: "${{ secrets.AWS_SESSION_TOKEN }}",
      },
    });
  });

  it("renders explicit model-provider diagnostics without relying on name prefix", async () => {
    const files = await renderComposedPythonBuiltinFirewallCatalogFiles({
      modelProviderFirewalls: [modelProviderFirewall("plain-provider")],
      generatedHeader: TEST_GENERATED_HEADER,
    });

    expect(findGeneratedContent(files, "manifest.py")).toContain(
      '"plain-provider": ("plain_provider_0",),',
    );
    expect(findGeneratedContent(files, "diagnostics.py")).toContain(
      '"name": "plain-provider"',
    );
  });

  it("rejects duplicate names across connector and model-provider sources", async () => {
    await expect(
      buildPythonBuiltinFirewallCatalog({
        modelProviderFirewalls: [modelProviderFirewall("github")],
      }),
    ).rejects.toThrow("duplicate built-in firewall catalog name: github");
  });

  it("does not import eager connector catalogs or API contracts", () => {
    const source = fs.readFileSync(
      path.resolve(
        import.meta.dirname,
        "../python-builtin-firewall-catalog-composition.ts",
      ),
      "utf-8",
    );

    expect(source).not.toContain("@vm0/connectors/firewalls/all");
    expect(source).not.toContain("@vm0/api-contracts");
  });
});
