// Auto-generated from Apollo.io API docs.
// Source: https://docs.apollo.io/docs/api-overview
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:apollo
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const apolloFirewall = {
  name: "apollo",
  description: "Apollo",
  placeholders: {
    APOLLO_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffee00",
  },
  apis: [
    {
      base: "https://api.apollo.io",
      auth: {
        headers: {
          "X-Api-Key": "${{ secrets.APOLLO_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
