// Auto-generated from Browserbase API docs.
// Source: https://docs.browserbase.com/reference/api/overview
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:browserbase
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const browserbaseFirewall = {
  name: "browserbase",
  description: "Browserbase API",
  placeholders: {
    BROWSERBASE_TOKEN: "bb_CoffeeSafeLocal_CoffeeSafeLocalCoffeeSafeLocal",
  },
  apis: [
    {
      base: "https://api.browserbase.com",
      auth: {
        headers: {
          "X-BB-API-Key": "${{ secrets.BROWSERBASE_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
