// Auto-generated from drive9 API docs.
// Source: https://drive9.ai/SKILL.md
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:drive9
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const drive9Firewall = {
  name: "drive9",
  description: "drive9 API",
  placeholders: {
    DRIVE9_TOKEN: "drive9_sk_CoffeeSafeLocalCoffeeSafeLocalCoffeeSa",
  },
  apis: [
    {
      base: "https://api.drive9.ai",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.DRIVE9_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
