// Auto-generated — GitHub firewall config.
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:github
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const githubFirewall = {
  name: "github",
  description: "GitHub",
  placeholders: {
    GITHUB_TOKEN: "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",
    GH_TOKEN: "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",
  },
  apis: [
    {
      // REST + GraphQL API.
      base: "https://api.github.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.GITHUB_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      // Release asset uploads.
      base: "https://uploads.github.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.GITHUB_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      // Git smart-HTTP (clone/push/pull, includes LFS under /info/lfs).
      base: "https://github.com/{owner}/{repo}.git",
      auth: {
        headers: {
          Authorization: '${{ basic("x-access-token", secrets.GITHUB_TOKEN) }}',
        },
      },
      permissions: [],
    },
    {
      // Gist git protocol — canonical form returned by the API's
      // git_pull_url / git_push_url fields (no username segment).
      base: "https://gist.github.com/{gist_id}.git",
      auth: {
        headers: {
          Authorization: '${{ basic("x-access-token", secrets.GITHUB_TOKEN) }}',
        },
      },
      permissions: [],
    },
    {
      // Gist git protocol — browser-URL form with username segment,
      // also served by GitHub's gist git server. Users often copy
      // this URL out of the gist page and append ".git".
      base: "https://gist.github.com/{user}/{gist_id}.git",
      auth: {
        headers: {
          Authorization: '${{ basic("x-access-token", secrets.GITHUB_TOKEN) }}',
        },
      },
      permissions: [],
    },
    {
      // Raw file content — used by curl/wget/requests for private repos.
      base: "https://raw.githubusercontent.com/{owner}/{repo}",
      auth: {
        headers: {
          Authorization: '${{ basic("x-access-token", secrets.GITHUB_TOKEN) }}',
        },
      },
      permissions: [],
    },
    {
      // Archive downloads — used by go get / pip install git+ / npm github:.
      base: "https://codeload.github.com/{owner}/{repo}",
      auth: {
        headers: {
          Authorization: '${{ basic("x-access-token", secrets.GITHUB_TOKEN) }}',
        },
      },
      permissions: [],
    },
    {
      // GitHub Packages — npm registry (npm install @scope/pkg).
      base: "https://npm.pkg.github.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.GITHUB_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
