// Auto-generated from Hume AI API docs.
// Source: https://dev.hume.ai/docs/introduction/api-key
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:hume
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const humeFirewall = {
  name: "hume",
  description: "Hume AI API",
  placeholders: {
    HUME_TOKEN:
      "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeL",
  },
  apis: [
    {
      base: "https://api.hume.ai",
      auth: {
        headers: {
          "X-Hume-Api-Key": "${{ secrets.HUME_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
