// Auto-generated from Jira REST API v3 docs.
// Source: https://developer.atlassian.com/cloud/jira/platform/rest/v3/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:jira
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const jiraFirewall = {
  name: "jira",
  description: "Jira REST API (API token auth)",
  placeholders: {
    JIRA_API_TOKEN: "Coffee5afe10ca1Coffee5af",
  },
  apis: [
    {
      base: "https://${{ vars.JIRA_DOMAIN }}",
      auth: {
        headers: {
          Authorization:
            "${{ basic(vars.JIRA_EMAIL, secrets.JIRA_API_TOKEN) }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
