// Auto-generated from LangSmith API docs.
// Source: https://docs.smith.langchain.com/reference/api
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:langsmith
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const langsmithFirewall = {
  name: "langsmith",
  description: "LangSmith",
  placeholders: {
    LANGSMITH_TOKEN: "lsv2_pt_c0ffeesafe10ca1c0ffeesafe10ca1c0_ffee5afe",
  },
  apis: [
    {
      base: "https://api.smith.langchain.com",
      auth: {
        headers: {
          "X-Api-Key": "${{ secrets.LANGSMITH_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
