// Auto-generated from Miro REST API docs.
// Source: https://developers.miro.com/reference/overview
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:miro
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const miroFirewall = {
  name: "miro",
  description: "Miro",
  placeholders: {
    MIRO_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal",
  },
  apis: [
    {
      base: "https://api.miro.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.MIRO_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
