// Auto-generated from PDF.co API docs.
// Source: https://docs.pdf.co/api-reference/introduction
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:pdfco
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const pdfcoFirewall = {
  name: "pdfco",
  description: "PDF.co API",
  placeholders: {
    PDFCO_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSa",
  },
  apis: [
    {
      base: "https://api.pdf.co",
      auth: {
        headers: {
          "x-api-key": "${{ secrets.PDFCO_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
