// Auto-generated from PDForge API docs.
// Source: https://docs.pdforge.com/getting-started/authentication
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:pdforge
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const pdforgeFirewall = {
  name: "pdforge",
  description: "PDForge PDF Generation API",
  placeholders: {
    PDFORGE_API_KEY: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSaf",
  },
  apis: [
    {
      base: "https://api.pdforge.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.PDFORGE_API_KEY }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
