// Auto-generated from Reportei API docs.
// Source: https://developers.reportei.com/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:reportei
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const reporteiFirewall = {
  name: "reportei",
  description: "Reportei API",
  placeholders: {
    REPORTEI_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSaf",
  },
  apis: [
    {
      base: "https://app.reportei.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.REPORTEI_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
