// Auto-generated from Shopify Admin API docs.
// Source: https://shopify.dev/docs/api/admin-rest
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:shopify
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const shopifyFirewall = {
  name: "shopify",
  description: "Shopify Admin API",
  placeholders: {
    SHOPIFY_TOKEN: "shpat_CoffeeSafeLocalCoffeeSafeLocalCo",
  },
  apis: [
    {
      base: "https://${{ vars.SHOPIFY_SHOP }}.myshopify.com",
      auth: {
        headers: {
          "X-Shopify-Access-Token": "${{ secrets.SHOPIFY_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
