// Auto-generated from Stability AI API docs.
// Source: https://platform.stability.ai/docs/api-reference
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:stability-ai
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const stabilityAiFirewall = {
  name: "stability-ai",
  description: "Stability AI",
  placeholders: {
    STABILITY_TOKEN: "sk-CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal",
  },
  apis: [
    {
      base: "https://api.stability.ai",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.STABILITY_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
