// Auto-generated from Supabase Management API docs.
// Source: https://supabase.com/docs/reference/api/introduction
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:supabase
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const supabaseFirewall = {
  name: "supabase",
  description: "Supabase Management API",
  placeholders: {
    SUPABASE_TOKEN: "sbp_oauth_c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe",
  },
  apis: [
    {
      base: "https://api.supabase.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.SUPABASE_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
