// Auto-generated from Typeform API docs.
// Source: https://www.typeform.com/developers/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:typeform
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const typeformFirewall = {
  name: "typeform",
  description: "Typeform API",
  placeholders: {
    TYPEFORM_TOKEN: "tfp_c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe",
  },
  apis: [
    {
      base: "https://api.typeform.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.TYPEFORM_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
