// Auto-generated from Weights & Biases API docs.
// Source: https://docs.wandb.ai/ref/rest
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:wandb
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const wandbFirewall = {
  name: "wandb",
  description: "Weights & Biases",
  placeholders: {
    WANDB_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafe",
  },
  apis: [
    {
      base: "https://api.wandb.ai",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.WANDB_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
