// Auto-generated from Wrike API docs.
// Source: https://developers.wrike.com/overview/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:wrike
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const wrikeFirewall = {
  name: "wrike",
  description: "Wrike Project Management API",
  placeholders: {
    WRIKE_TOKEN: "wrkTkn_CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLoca",
  },
  apis: [
    {
      base: "https://www.wrike.com",
      auth: {
        headers: {
          Authorization: "bearer ${{ secrets.WRIKE_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://app-us2.wrike.com",
      auth: {
        headers: {
          Authorization: "bearer ${{ secrets.WRIKE_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://app-eu.wrike.com",
      auth: {
        headers: {
          Authorization: "bearer ${{ secrets.WRIKE_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
