// Auto-generated from ZapSign API docs.
// Source: https://docs.zapsign.com.br/english/authentication/autenticacao
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:zapsign
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const zapsignFirewall = {
  name: "zapsign",
  description: "ZapSign API",
  placeholders: {
    ZAPSIGN_TOKEN: "c0ffee5a-fe10-ca1c-0ffe-e5afe10c",
  },
  apis: [
    {
      base: "https://api.zapsign.com.br",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.ZAPSIGN_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
