import type { Firewall, FirewallApi } from "@vm0/connectors/firewall-types";
import { getAllConnectorFirewalls } from "@vm0/connectors/firewalls";
import { MODEL_PROVIDER_FIREWALL_CONFIGS } from "../contracts/model-providers";

type JsonValue =
  | string
  | number
  | boolean
  | null
  | readonly JsonValue[]
  | { readonly [key: string]: JsonValue };

interface BuiltinFirewallCatalog {
  readonly firewalls: Record<string, Firewall>;
}

function runtimeApi(api: FirewallApi): FirewallApi {
  return {
    base: api.base,
    auth: api.auth,
    ...(api.permissions !== undefined ? { permissions: api.permissions } : {}),
  };
}

function runtimeFirewall(firewall: Firewall): Firewall {
  return {
    name: firewall.name,
    apis: firewall.apis.map(runtimeApi),
  };
}

export function buildBuiltinFirewallCatalog(): BuiltinFirewallCatalog {
  const connectorFirewalls = Object.entries(getAllConnectorFirewalls()).map(
    ([, firewall]) => {
      return runtimeFirewall(firewall);
    },
  );
  const modelProviderFirewalls = Object.values(
    MODEL_PROVIDER_FIREWALL_CONFIGS,
  ).map((firewall) => {
    return runtimeFirewall(firewall);
  });

  const firewalls: Record<string, Firewall> = {};
  for (const firewall of [...connectorFirewalls, ...modelProviderFirewalls]) {
    if (firewall.name in firewalls) {
      throw new Error(
        `duplicate built-in firewall catalog name: ${firewall.name}`,
      );
    }
    firewalls[firewall.name] = firewall;
  }

  return {
    firewalls,
  };
}

function sortJson(value: unknown): JsonValue {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(sortJson);
  }
  if (typeof value !== "object") {
    throw new Error(`unsupported JSON catalog value: ${typeof value}`);
  }

  const sorted: Record<string, JsonValue> = {};
  for (const key of Object.keys(value).sort()) {
    const nested = (value as Record<string, unknown>)[key];
    if (nested !== undefined) {
      sorted[key] = sortJson(nested);
    }
  }
  return sorted;
}

function stableJson(value: unknown): string {
  return JSON.stringify(sortJson(value), null, 2);
}

function pythonMultilineStringLiteral(value: string): string {
  if (!value.includes('"""')) {
    return `r"""\n${value}\n"""`;
  }
  if (!value.includes("'''")) {
    return `r'''\n${value}\n'''`;
  }
  throw new Error(
    "generated firewall catalog contains both Python triple quotes",
  );
}

function indentPythonExpression(value: string): string {
  const [firstLine, ...remainingLines] = value.split("\n");
  return [`    ${firstLine ?? ""}`, ...remainingLines].join("\n");
}

export function renderPythonBuiltinFirewallCatalog(): string {
  const catalog = buildBuiltinFirewallCatalog();
  const firewallsJson = stableJson(catalog.firewalls);

  return [
    "# @generated by @vm0/api-contracts.",
    "# Do not edit by hand.",
    "# Regenerate with: cd turbo && pnpm -F @vm0/api-contracts generate:rust",
    "# ruff: noqa",
    "",
    "import json",
    "",
    "BUILTIN_FIREWALLS = json.loads(",
    indentPythonExpression(pythonMultilineStringLiteral(firewallsJson)),
    ")",
    "",
  ].join("\n");
}
