import type { Firewall, FirewallApi } from "@vm0/connectors/firewall-types";
import { getAllConnectorFirewalls } from "@vm0/connectors/firewalls/all";
import { MODEL_PROVIDER_FIREWALL_CONFIGS } from "../contracts/model-providers";

type JsonValue =
  | string
  | number
  | boolean
  | null
  | readonly JsonValue[]
  | { readonly [key: string]: JsonValue };

export interface BuiltinFirewallCatalog {
  readonly firewalls: Record<string, Firewall>;
}

export interface PythonBuiltinFirewallCatalogFile {
  readonly path: string;
  readonly content: string;
}

interface RenderPythonBuiltinFirewallCatalogOptions {
  readonly catalog?: BuiltinFirewallCatalog;
  readonly maxJsonChunkLength?: number;
}

interface DiagnosticConnectorApi {
  readonly base: string;
  readonly envNames: readonly string[];
  readonly authHeaderNames: readonly string[];
  readonly authQueryParamNames: readonly string[];
}

interface DiagnosticConnectorFirewall {
  readonly name: string;
  readonly apis: readonly DiagnosticConnectorApi[];
}

interface DiagnosticPermission {
  readonly name: string;
  readonly rules: readonly string[];
}

interface DiagnosticModelProviderApi {
  readonly base: string;
  readonly permissions: readonly DiagnosticPermission[];
}

interface DiagnosticModelProviderFirewall {
  readonly name: string;
  readonly apis: readonly DiagnosticModelProviderApi[];
}

interface BuiltinFirewallDiagnosticManifest {
  readonly connectorFirewalls: readonly DiagnosticConnectorFirewall[];
  readonly modelProviderExclusions: readonly DiagnosticModelProviderFirewall[];
}

const DEFAULT_FIREWALL_JSON_CHUNK_LENGTH = 200_000;
const MAX_GENERATED_PYTHON_LINE_LENGTH = 512;
const PYTHON_JSON_PART_ASSIGNMENT_PREFIX = "JSON_PART = ";
// Fallback JSON string literals can double quotes and backslashes.
const MAX_JSON_PART_SOURCE_CHARS = Math.floor(
  (MAX_GENERATED_PYTHON_LINE_LENGTH -
    PYTHON_JSON_PART_ASSIGNMENT_PREFIX.length -
    2) /
    2,
);
const pythonGeneratedHeader = [
  "# @generated by @vm0/api-contracts.",
  "# Do not edit by hand.",
  "# Regenerate with: cd turbo && pnpm -F @vm0/api-contracts generate:rust",
  "# ruff: noqa",
] as const;
const MODEL_PROVIDER_FIREWALL_PREFIX = "model-provider:";
const DIAGNOSTIC_REFERENCE_NAME_PATTERN =
  /\b(?:secrets|vars)\.([a-zA-Z_][a-zA-Z0-9_]*)/g;

function runtimeApi(api: FirewallApi): FirewallApi {
  return {
    base: api.base,
    auth: api.auth,
    ...(api.permissions !== undefined ? { permissions: api.permissions } : {}),
  };
}

function runtimeFirewall(firewall: Firewall): Firewall {
  return {
    name: firewall.name,
    apis: firewall.apis.map(runtimeApi),
  };
}

export function buildBuiltinFirewallCatalog(): BuiltinFirewallCatalog {
  const connectorFirewalls = Object.values(getAllConnectorFirewalls()).map(
    (firewall) => {
      return runtimeFirewall(firewall);
    },
  );
  const modelProviderFirewalls = Object.values(
    MODEL_PROVIDER_FIREWALL_CONFIGS,
  ).map((firewall) => {
    return runtimeFirewall(firewall);
  });

  const firewalls: Record<string, Firewall> = {};
  for (const firewall of [...connectorFirewalls, ...modelProviderFirewalls]) {
    if (firewall.name in firewalls) {
      throw new Error(
        `duplicate built-in firewall catalog name: ${firewall.name}`,
      );
    }
    firewalls[firewall.name] = firewall;
  }

  return {
    firewalls,
  };
}

function hasDynamicBaseMarker(base: string): boolean {
  return base.includes("{") || base.includes("}");
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function extractDiagnosticReferenceNames(value: unknown): readonly string[] {
  const result: string[] = [];
  const seen = new Set<string>();

  function add(name: string): void {
    if (seen.has(name)) {
      return;
    }
    seen.add(name);
    result.push(name);
  }

  function visit(nested: unknown): void {
    if (typeof nested === "string") {
      DIAGNOSTIC_REFERENCE_NAME_PATTERN.lastIndex = 0;
      for (
        let match = DIAGNOSTIC_REFERENCE_NAME_PATTERN.exec(nested);
        match !== null;
        match = DIAGNOSTIC_REFERENCE_NAME_PATTERN.exec(nested)
      ) {
        const name = match[1];
        if (name !== undefined) {
          add(name);
        }
      }
      return;
    }
    if (Array.isArray(nested)) {
      for (const item of nested) {
        visit(item);
      }
      return;
    }
    if (!isRecord(nested)) {
      return;
    }
    for (const key of Object.keys(nested).sort()) {
      visit(nested[key]);
    }
  }

  visit(value);
  return result;
}

function diagnosticAuthHeaderNames(
  auth: FirewallApi["auth"],
): readonly string[] {
  return Object.keys(auth.headers ?? {})
    .filter((name) => {
      return name.length > 0;
    })
    .sort();
}

function diagnosticAuthQueryParamNames(
  auth: FirewallApi["auth"],
): readonly string[] {
  return Object.keys(auth.query ?? {})
    .filter((name) => {
      return name.length > 0;
    })
    .sort();
}

function diagnosticConnectorApi(
  api: FirewallApi,
): DiagnosticConnectorApi | null {
  if (hasDynamicBaseMarker(api.base)) {
    return null;
  }

  const envNames = extractDiagnosticReferenceNames(api.auth);
  if (envNames.length === 0) {
    return null;
  }

  return {
    base: api.base,
    envNames,
    authHeaderNames: diagnosticAuthHeaderNames(api.auth),
    authQueryParamNames: diagnosticAuthQueryParamNames(api.auth),
  };
}

function diagnosticPermissions(
  permissions: FirewallApi["permissions"],
): readonly DiagnosticPermission[] {
  if (permissions === undefined) {
    return [];
  }
  return permissions.map((permission) => {
    return {
      name: permission.name,
      rules: [...permission.rules],
    };
  });
}

function diagnosticModelProviderApi(
  api: FirewallApi,
): DiagnosticModelProviderApi | null {
  if (hasDynamicBaseMarker(api.base)) {
    return null;
  }

  return {
    base: api.base,
    permissions: diagnosticPermissions(api.permissions),
  };
}

function buildBuiltinFirewallDiagnosticManifest(
  catalog: BuiltinFirewallCatalog,
): BuiltinFirewallDiagnosticManifest {
  const connectorFirewalls: DiagnosticConnectorFirewall[] = [];
  const modelProviderExclusions: DiagnosticModelProviderFirewall[] = [];

  for (const name of Object.keys(catalog.firewalls).sort()) {
    const firewall = catalog.firewalls[name];
    if (firewall === undefined) {
      throw new Error(`missing built-in firewall catalog entry: ${name}`);
    }

    if (name.startsWith(MODEL_PROVIDER_FIREWALL_PREFIX)) {
      const apis = firewall.apis
        .map(diagnosticModelProviderApi)
        .filter((api): api is DiagnosticModelProviderApi => {
          return api !== null;
        });
      if (apis.length > 0) {
        modelProviderExclusions.push({
          name,
          apis,
        });
      }
      continue;
    }

    const apis = firewall.apis
      .map(diagnosticConnectorApi)
      .filter((api): api is DiagnosticConnectorApi => {
        return api !== null;
      });
    if (apis.length > 0) {
      connectorFirewalls.push({
        name,
        apis,
      });
    }
  }

  return {
    connectorFirewalls,
    modelProviderExclusions,
  };
}

function sortJson(value: unknown): JsonValue {
  if (
    value === null ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return value;
  }
  if (Array.isArray(value)) {
    return value.map(sortJson);
  }
  if (typeof value !== "object") {
    throw new Error(`unsupported JSON catalog value: ${typeof value}`);
  }

  const sorted: Record<string, JsonValue> = {};
  for (const key of Object.keys(value).sort()) {
    const nested = (value as Record<string, unknown>)[key];
    if (nested !== undefined) {
      sorted[key] = sortJson(nested);
    }
  }
  return sorted;
}

function unicodeEscape(codePoint: number): string {
  return `\\u${codePoint.toString(16).padStart(4, "0")}`;
}

function escapeNonAsciiJson(value: string): string {
  let escaped = "";
  for (const char of value) {
    const codePoint = char.codePointAt(0);
    if (codePoint === undefined) {
      throw new Error("failed to read JSON code point");
    }
    if (codePoint <= 0x7f) {
      escaped += char;
      continue;
    }
    if (codePoint <= 0xffff) {
      escaped += unicodeEscape(codePoint);
      continue;
    }

    const shifted = codePoint - 0x10000;
    escaped += unicodeEscape(0xd800 + (shifted >> 10));
    escaped += unicodeEscape(0xdc00 + (shifted & 0x3ff));
  }
  return escaped;
}

function stablePrettyJson(value: unknown): string {
  const json = JSON.stringify(sortJson(value), null, 2);
  if (json === undefined) {
    throw new Error("failed to encode firewall catalog JSON");
  }
  return escapeNonAsciiJson(json);
}

function pythonEscapedStringLiteral(value: string): string {
  const literal = JSON.stringify(value);
  if (literal === undefined) {
    throw new Error("failed to encode Python string literal");
  }
  return literal;
}

function hasOddTrailingBackslashes(value: string): boolean {
  let count = 0;
  for (let index = value.length - 1; index >= 0; index -= 1) {
    if (value[index] !== "\\") {
      break;
    }
    count += 1;
  }
  return count % 2 === 1;
}

function pythonJsonChunkLiteral(value: string): string {
  if (
    !value.includes('"""') &&
    !value.endsWith('"') &&
    !hasOddTrailingBackslashes(value)
  ) {
    return `r"""${value}"""`;
  }
  return pythonEscapedStringLiteral(value);
}

function sanitizePythonModuleBase(name: string): string {
  const sanitized = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_");
  if (sanitized.length === 0) {
    return "firewall";
  }
  if (/^[a-z_]/.test(sanitized)) {
    return sanitized;
  }
  return `firewall_${sanitized}`;
}

function uniqueModuleBaseNames(
  names: readonly string[],
): ReadonlyMap<string, string> {
  const used = new Set<string>();
  const bases = new Map<string, string>();

  for (const name of names) {
    const base = sanitizePythonModuleBase(name);
    let candidate = base;
    let suffix = 2;
    while (used.has(candidate)) {
      candidate = `${base}_${suffix}`;
      suffix += 1;
    }
    used.add(candidate);
    bases.set(name, candidate);
  }

  return bases;
}

function splitJsonLines(value: string, maxLength: number): readonly string[] {
  if (!Number.isInteger(maxLength) || maxLength < 1) {
    throw new Error(`invalid firewall JSON chunk length: ${maxLength}`);
  }

  const maxSegmentLength = Math.min(maxLength, MAX_JSON_PART_SOURCE_CHARS);
  const chunks: string[] = [];
  let current = "";
  const lines = value.split("\n");
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    if (line === undefined) {
      throw new Error("failed to read firewall JSON line");
    }
    const segment = index < lines.length - 1 ? `${line}\n` : line;
    if (segment.length > maxSegmentLength) {
      if (current.length > 0) {
        chunks.push(current);
        current = "";
      }
      for (
        let offset = 0;
        offset < segment.length;
        offset += maxSegmentLength
      ) {
        const piece = segment.slice(offset, offset + maxSegmentLength);
        if (offset + maxSegmentLength < segment.length) {
          chunks.push(piece);
        } else {
          current = piece;
        }
      }
      continue;
    }
    if (current.length > 0 && current.length + segment.length > maxLength) {
      chunks.push(current);
      current = "";
    }
    current += segment;
  }
  if (current.length > 0) {
    chunks.push(current);
  }
  return chunks.length > 0 ? chunks : [""];
}

function renderPythonPackageInit(): string {
  return [
    ...pythonGeneratedHeader,
    "",
    "import json",
    "from collections.abc import Iterator, Mapping",
    "from typing import Any",
    "",
    "from .loader import load_json_parts",
    "from .manifest import FIREWALL_MODULES",
    "",
    "",
    "class _BuiltinFirewallCatalog(Mapping[str, dict[str, Any]]):",
    "    def __init__(self) -> None:",
    "        self._cache: dict[str, dict[str, Any]] = {}",
    "",
    "    def __getitem__(self, name: str) -> dict[str, Any]:",
    "        if name not in FIREWALL_MODULES:",
    "            raise KeyError(name)",
    "        if name not in self._cache:",
    "            self._cache[name] = self._load(name)",
    "        return self._cache[name]",
    "",
    "    def __iter__(self) -> Iterator[str]:",
    "        return iter(FIREWALL_MODULES)",
    "",
    "    def __len__(self) -> int:",
    "        return len(FIREWALL_MODULES)",
    "",
    "    def __contains__(self, name: object) -> bool:",
    "        return name in FIREWALL_MODULES",
    "",
    "    def _load(self, name: str) -> dict[str, Any]:",
    "        parts = load_json_parts(name)",
    '        value = json.loads("".join(parts))',
    "        if not isinstance(value, dict):",
    '            raise TypeError(f"builtin firewall {name} is not a JSON object")',
    "        return value",
    "",
    "",
    "BUILTIN_FIREWALLS = _BuiltinFirewallCatalog()",
    "",
  ].join("\n");
}

function renderPythonLoader(
  modulesByFirewall: ReadonlyMap<string, readonly string[]>,
): string {
  const lines = [
    ...pythonGeneratedHeader,
    "",
    "",
    "def load_json_parts(name: str) -> tuple[str, ...]:",
  ];

  for (const [name, modules] of modulesByFirewall) {
    lines.push(`    if name == ${pythonEscapedStringLiteral(name)}:`);
    for (const moduleName of modules) {
      lines.push(`        from . import ${moduleName}`);
    }
    lines.push("");
    if (modules.length > 1) {
      lines.push("        return (");
      for (const moduleName of modules) {
        lines.push(`            ${moduleName}.JSON_PART,`);
      }
      lines.push("        )");
      continue;
    }

    const renderedParts = modules
      .map((moduleName) => {
        return `${moduleName}.JSON_PART`;
      })
      .join(", ");
    const tupleSuffix = modules.length === 1 ? "," : "";
    lines.push(`        return (${renderedParts}${tupleSuffix})`);
  }

  lines.push("    raise KeyError(name)", "");
  return lines.join("\n");
}

function renderPythonManifest(
  modulesByFirewall: ReadonlyMap<string, readonly string[]>,
): string {
  const lines = [...pythonGeneratedHeader, "", "FIREWALL_MODULES = {"];

  for (const [name, modules] of modulesByFirewall) {
    const renderedModules = modules
      .map((moduleName) => {
        return pythonEscapedStringLiteral(moduleName);
      })
      .join(", ");
    const tupleSuffix = modules.length === 1 ? "," : "";
    if (modules.length > 1) {
      lines.push(`    ${pythonEscapedStringLiteral(name)}: (`);
      for (const moduleName of modules) {
        lines.push(`        ${pythonEscapedStringLiteral(moduleName)},`);
      }
      lines.push("    ),");
      continue;
    }

    lines.push(
      `    ${pythonEscapedStringLiteral(name)}: (${renderedModules}${tupleSuffix}),`,
    );
  }

  lines.push("}", "");
  return lines.join("\n");
}

function renderPythonDiagnosticManifest(
  manifest: BuiltinFirewallDiagnosticManifest,
): string {
  return [
    ...pythonGeneratedHeader,
    "",
    `CONNECTOR_DIAGNOSTIC_FIREWALLS = ${stablePrettyJson(
      manifest.connectorFirewalls,
    )}`,
    "",
    `MODEL_PROVIDER_DIAGNOSTIC_EXCLUSIONS = ${stablePrettyJson(
      manifest.modelProviderExclusions,
    )}`,
    "",
  ].join("\n");
}

function renderPythonJsonPartModule(jsonPart: string): string {
  return [
    ...pythonGeneratedHeader,
    "",
    `${PYTHON_JSON_PART_ASSIGNMENT_PREFIX}${pythonJsonChunkLiteral(jsonPart)}`,
    "",
  ].join("\n");
}

export function renderPythonBuiltinFirewallCatalogFiles(
  options: RenderPythonBuiltinFirewallCatalogOptions = {},
): readonly PythonBuiltinFirewallCatalogFile[] {
  const catalog = options.catalog ?? buildBuiltinFirewallCatalog();
  const diagnosticManifest = buildBuiltinFirewallDiagnosticManifest(catalog);
  const maxJsonChunkLength =
    options.maxJsonChunkLength ?? DEFAULT_FIREWALL_JSON_CHUNK_LENGTH;
  const names = Object.keys(catalog.firewalls).sort();
  const moduleBaseNames = uniqueModuleBaseNames(names);
  const modulesByFirewall = new Map<string, readonly string[]>();
  const partFiles: PythonBuiltinFirewallCatalogFile[] = [];

  for (const name of names) {
    const firewall = catalog.firewalls[name];
    if (firewall === undefined) {
      throw new Error(`missing built-in firewall catalog entry: ${name}`);
    }

    const baseName = moduleBaseNames.get(name);
    if (baseName === undefined) {
      throw new Error(`missing Python module name for firewall: ${name}`);
    }

    const chunks = splitJsonLines(
      stablePrettyJson(firewall),
      maxJsonChunkLength,
    );
    const moduleNames = chunks.map((_, index) => {
      return `${baseName}_${index}`;
    });
    modulesByFirewall.set(name, moduleNames);

    for (let index = 0; index < chunks.length; index += 1) {
      const moduleName = moduleNames[index];
      const chunk = chunks[index];
      if (moduleName === undefined || chunk === undefined) {
        throw new Error(`missing generated Python chunk for firewall: ${name}`);
      }
      partFiles.push({
        path: `${moduleName}.py`,
        content: renderPythonJsonPartModule(chunk),
      });
    }
  }

  return [
    {
      path: "__init__.py",
      content: renderPythonPackageInit(),
    },
    {
      path: "manifest.py",
      content: renderPythonManifest(modulesByFirewall),
    },
    {
      path: "loader.py",
      content: renderPythonLoader(modulesByFirewall),
    },
    {
      path: "diagnostics.py",
      content: renderPythonDiagnosticManifest(diagnosticManifest),
    },
    ...partFiles,
  ];
}
