import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { type RustRouteBinding, rustRouteBindings } from "./routes";

const generatedRoutesPath = fileURLToPath(
  new URL(
    "../../../../../crates/api-contracts/src/generated/routes.rs",
    import.meta.url,
  ),
);

const httpMethods = [
  "GET",
  "POST",
  "PUT",
  "PATCH",
  "DELETE",
  "HEAD",
  "OPTIONS",
] as const;

export type HttpMethod = (typeof httpMethods)[number];
export type RustMethodVariant =
  | "Get"
  | "Post"
  | "Put"
  | "Patch"
  | "Delete"
  | "Head"
  | "Options";

export interface NormalizedRouteBinding {
  readonly method: HttpMethod;
  readonly path: string;
  readonly pathParams: readonly PathParamBinding[];
  readonly rustMethodVariant: RustMethodVariant;
  readonly rustModulePath: readonly string[];
  readonly rustConstName: string;
}

interface PathParamBinding {
  readonly routeName: string;
  readonly rustName: string;
}

interface ModuleNode {
  readonly routes: NormalizedRouteBinding[];
  readonly children: Map<string, ModuleNode>;
}

const rustModuleSegmentPattern = /^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$/;
const rustConstNamePattern = /^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$/;
const routePathParamPattern = /^[A-Za-z][A-Za-z0-9_]*$/;
const rustKeywords = new Set([
  "abstract",
  "as",
  "async",
  "await",
  "become",
  "box",
  "break",
  "const",
  "continue",
  "crate",
  "do",
  "dyn",
  "else",
  "enum",
  "extern",
  "false",
  "final",
  "fn",
  "for",
  "gen",
  "if",
  "impl",
  "in",
  "let",
  "loop",
  "macro",
  "macro_rules",
  "match",
  "mod",
  "move",
  "mut",
  "override",
  "priv",
  "pub",
  "ref",
  "return",
  "self",
  "Self",
  "static",
  "struct",
  "super",
  "trait",
  "true",
  "try",
  "type",
  "typeof",
  "union",
  "unsized",
  "unsafe",
  "use",
  "virtual",
  "where",
  "while",
  "yield",
]);

export function normalizeRouteBindings(
  bindings: readonly RustRouteBinding[],
): readonly NormalizedRouteBinding[] {
  const seenRustNames = new Set<string>();
  const seenRoutes = new Set<string>();
  const normalized: NormalizedRouteBinding[] = [];

  for (const binding of bindings) {
    const label = routeLabel(binding);
    const method = validateHttpMethod(binding.route.method, label);
    const path = validateRoutePath(binding.route.path, label);
    const pathParams = extractPathParams(path, label);
    const rustModulePath = validateRustModulePath(
      binding.rustModulePath,
      label,
    );
    const rustConstName = validateRustConstName(binding.rustConstName, label);
    const rustName = [...rustModulePath, rustConstName].join("::");
    const routeKey = `${method} ${path}`;

    if (seenRustNames.has(rustName)) {
      throw new Error(`duplicate Rust route binding: ${rustName}`);
    }
    seenRustNames.add(rustName);

    if (seenRoutes.has(routeKey)) {
      throw new Error(`duplicate route binding: ${routeKey}`);
    }
    seenRoutes.add(routeKey);

    normalized.push({
      method,
      path,
      pathParams,
      rustMethodVariant: toRustMethodVariant(method),
      rustModulePath,
      rustConstName,
    });
  }

  return [...normalized].sort(compareRouteBindings);
}

export function renderRustRoutes(
  bindings: readonly RustRouteBinding[],
): string {
  const routes = normalizeRouteBindings(bindings);
  const root = buildRouteTree(routes);
  const lines = [
    "// @generated by @vm0/api-contracts.",
    "// Do not edit by hand.",
    "// Regenerate with: cd turbo && pnpm -F @vm0/api-contracts generate:rust",
    "",
    ...renderModuleNode(root, ""),
  ];

  return `${lines.join("\n")}\n`;
}

export async function generateRustRoutesFile(
  outputPath = generatedRoutesPath,
): Promise<void> {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderRustRoutes(rustRouteBindings));
}

function routeLabel(binding: RustRouteBinding): string {
  const rustName = [...binding.rustModulePath, binding.rustConstName].join(
    "::",
  );
  return rustName.length > 0 ? rustName : "<unnamed route binding>";
}

function validateHttpMethod(value: unknown, label: string): HttpMethod {
  if (typeof value !== "string") {
    throw new Error(`${label} is missing a string HTTP method`);
  }

  if (!isHttpMethod(value)) {
    throw new Error(`${label} uses unsupported HTTP method: ${value}`);
  }

  return value;
}

function validateRoutePath(value: unknown, label: string): string {
  if (typeof value !== "string") {
    throw new Error(`${label} is missing a string route path`);
  }

  if (!value.startsWith("/")) {
    throw new Error(`${label} route path must start with '/': ${value}`);
  }

  return value;
}

function extractPathParams(
  path: string,
  label: string,
): readonly PathParamBinding[] {
  const seenRouteNames = new Set<string>();
  const seenRustNames = new Set<string>();
  const params: PathParamBinding[] = [];

  for (const segment of path.split("/")) {
    if (!segment.includes(":")) {
      continue;
    }

    if (!segment.startsWith(":")) {
      throw new Error(`${label} uses unsupported route param segment: ${path}`);
    }

    const routeName = segment.slice(1);
    if (!routePathParamPattern.test(routeName)) {
      throw new Error(`${label} has invalid route param name: ${routeName}`);
    }

    const rustName = toRustParamName(routeName);
    if (seenRouteNames.has(routeName)) {
      throw new Error(`${label} has duplicate route param: ${routeName}`);
    }
    if (seenRustNames.has(rustName)) {
      throw new Error(`${label} has duplicate Rust route param: ${rustName}`);
    }

    seenRouteNames.add(routeName);
    seenRustNames.add(rustName);
    params.push({ routeName, rustName });
  }

  return params;
}

function toRustParamName(routeName: string): string {
  const snake = routeName
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase();

  return rustKeywords.has(snake) ? `${snake}_` : snake;
}

function validateRustModulePath(
  segments: readonly string[],
  label: string,
): readonly string[] {
  if (segments.length === 0) {
    throw new Error(`${label} must declare at least one Rust module segment`);
  }

  return segments.map((segment) => {
    if (!rustModuleSegmentPattern.test(segment)) {
      throw new Error(`${label} has invalid Rust module segment: ${segment}`);
    }

    return segment;
  });
}

function validateRustConstName(value: string, label: string): string {
  if (!rustConstNamePattern.test(value)) {
    throw new Error(`${label} has invalid Rust const name: ${value}`);
  }

  return value;
}

function isHttpMethod(value: string): value is HttpMethod {
  return httpMethods.some((method) => {
    return method === value;
  });
}

function toRustMethodVariant(method: HttpMethod): RustMethodVariant {
  switch (method) {
    case "GET":
      return "Get";
    case "POST":
      return "Post";
    case "PUT":
      return "Put";
    case "PATCH":
      return "Patch";
    case "DELETE":
      return "Delete";
    case "HEAD":
      return "Head";
    case "OPTIONS":
      return "Options";
  }
}

function compareRouteBindings(
  left: NormalizedRouteBinding,
  right: NormalizedRouteBinding,
): number {
  return compareAscii(rustRouteName(left), rustRouteName(right));
}

function rustRouteName(binding: NormalizedRouteBinding): string {
  return [...binding.rustModulePath, binding.rustConstName].join("::");
}

function buildRouteTree(routes: readonly NormalizedRouteBinding[]): ModuleNode {
  const root = createModuleNode();

  for (const route of routes) {
    let node = root;

    for (const segment of route.rustModulePath) {
      let child = node.children.get(segment);
      if (child === undefined) {
        child = createModuleNode();
        node.children.set(segment, child);
      }
      node = child;
    }

    node.routes.push(route);
  }

  return root;
}

function createModuleNode(): ModuleNode {
  return {
    routes: [],
    children: new Map(),
  };
}

function renderModuleNode(node: ModuleNode, indent: string): string[] {
  const lines: string[] = [];
  const routes = [...node.routes].sort(compareRouteBindings);
  const children = [...node.children.entries()].sort(
    ([leftName], [rightName]) => {
      return compareAscii(leftName, rightName);
    },
  );

  for (const route of routes) {
    const routeType = route.pathParams.length > 0 ? "RouteTemplate" : "Route";
    appendBlankLineIfNeeded(lines);
    lines.push(
      `${indent}pub const ${route.rustConstName}: crate::${routeType} = crate::${routeType} {`,
    );
    lines.push(
      `${indent}    method: crate::Method::${route.rustMethodVariant},`,
    );
    lines.push(`${indent}    path: ${rustStringLiteral(route.path)},`);
    lines.push(`${indent}};`);

    if (route.pathParams.length > 0) {
      lines.push("");
      lines.push(`${indent}#[derive(Debug, Clone, Copy)]`);
      lines.push(`${indent}pub struct Params<'a> {`);
      for (const param of route.pathParams) {
        lines.push(`${indent}    pub ${param.rustName}: &'a str,`);
      }
      lines.push(`${indent}}`);
      lines.push("");
      lines.push(`${indent}#[must_use]`);
      lines.push(`${indent}pub fn path(params: Params<'_>) -> String {`);
      lines.push(...renderParameterizedPath(route, `${indent}    `));
      lines.push(`${indent}}`);
      lines.push("");
      lines.push(`${indent}#[must_use]`);
      lines.push(
        `${indent}pub fn route(params: Params<'_>) -> crate::ResolvedRoute {`,
      );
      lines.push(
        `${indent}    crate::ResolvedRoute::new(${route.rustConstName}.method, path(params))`,
      );
      lines.push(`${indent}}`);
    }
  }

  for (const [moduleName, child] of children) {
    appendBlankLineIfNeeded(lines);
    lines.push(`${indent}pub mod ${moduleName} {`);
    lines.push(...renderModuleNode(child, `${indent}    `));
    lines.push(`${indent}}`);
  }

  return lines;
}

function renderParameterizedPath(
  route: NormalizedRouteBinding,
  indent: string,
): string[] {
  const formatPath = route.path
    .split("/")
    .map((segment) => {
      return segment.startsWith(":") ? "{}" : escapeRustFormatString(segment);
    })
    .join("/");
  const args = route.pathParams.map((param) => {
    return `crate::route::encode_path_segment(params.${param.rustName})`;
  });

  const lines = [
    `${indent}format!(`,
    `${indent}    ${rustStringLiteral(formatPath)},`,
  ];
  for (const arg of args) {
    lines.push(`${indent}    ${arg},`);
  }
  lines.push(`${indent})`);
  return lines;
}

function escapeRustFormatString(value: string): string {
  return value.replace(/\{/g, "{{").replace(/\}/g, "}}");
}

function compareAscii(left: string, right: string): number {
  if (left < right) {
    return -1;
  }
  if (left > right) {
    return 1;
  }
  return 0;
}

function appendBlankLineIfNeeded(lines: string[]): void {
  if (lines.length > 0) {
    lines.push("");
  }
}

function rustStringLiteral(value: string): string {
  let literal = '"';

  for (const char of value) {
    if (char === "\\") {
      literal += "\\\\";
    } else if (char === '"') {
      literal += '\\"';
    } else if (char === "\n") {
      literal += "\\n";
    } else if (char === "\r") {
      literal += "\\r";
    } else if (char === "\t") {
      literal += "\\t";
    } else {
      const codePoint = char.codePointAt(0);
      if (codePoint !== undefined && codePoint < 0x20) {
        literal += `\\u{${codePoint.toString(16)}}`;
      } else {
        literal += char;
      }
    }
  }

  return `${literal}"`;
}

function isMainModule(): boolean {
  const entrypoint = process.argv[1];
  return (
    entrypoint !== undefined &&
    import.meta.url === pathToFileURL(entrypoint).href
  );
}

if (isMainModule()) {
  void generateRustRoutesFile().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
