import { createHmac, timingSafeEqual } from "node:crypto";
import { env } from "../../../env";

const MAX_CONNECT_AGE_SECONDS = 600; // 10 minutes

function getSigningKey(): string {
  return env().SECRETS_ENCRYPTION_KEY;
}

/**
 * Generate an HMAC signature for iMessage connect parameters.
 * Used to verify that the connect URL was generated by our server.
 */
function signConnectParams(
  imessageHandle: string,
  orgId: string,
  timestamp: number,
): string {
  const data = `imessage:${imessageHandle}:${orgId}:${timestamp}`;
  return createHmac("sha256", getSigningKey()).update(data).digest("hex");
}

/**
 * Build a full iMessage connect URL for the user to bind their account.
 */
export function buildConnectUrl(imessageHandle: string, orgId: string): string {
  const timestamp = Math.floor(Date.now() / 1000);
  const signature = signConnectParams(imessageHandle, orgId, timestamp);

  const params = new URLSearchParams({
    handle: imessageHandle,
    org: orgId,
    ts: String(timestamp),
    sig: signature,
  });

  const baseUrl = env().NEXT_PUBLIC_APP_URL;
  return `${baseUrl}/imessage/connect?${params.toString()}`;
}

/**
 * Verify a connect signature and check expiry.
 */
export function verifyConnectSignature(
  imessageHandle: string,
  orgId: string,
  timestamp: number,
  signature: string,
): boolean {
  const now = Math.floor(Date.now() / 1000);
  if (now - timestamp > MAX_CONNECT_AGE_SECONDS) return false;

  const expected = signConnectParams(imessageHandle, orgId, timestamp);
  const expectedBuf = Buffer.from(expected, "hex");
  const signatureBuf = Buffer.from(signature, "hex");
  if (expectedBuf.length !== signatureBuf.length) return false;
  return timingSafeEqual(expectedBuf, signatureBuf);
}
