[package]
name = "tracing-test-support"
version = "0.1.2"
edition.workspace = true
description = "Tracing capture helpers for Rust tests"

[dependencies]
tracing = { workspace = true, features = ["attributes", "std"] }
tracing-subscriber = { workspace = true, features = ["ansi", "fmt", "smallvec", "std", "tracing-log"] }

[lints]
workspace = true
