[package]
name = "runner-rpc-client"
version = "0.2.1"
edition.workspace = true

[dependencies]
libc = { workspace = true, features = ["std"] }
runner-rpc-proto.workspace = true
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["io-std", "io-util", "net", "rt", "time"] }

[dev-dependencies]
tempfile = { workspace = true, features = ["getrandom"] }
tokio = { workspace = true, features = ["macros", "test-util"] }

[lints]
workspace = true
