use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};
use tokio::io::AsyncBufReadExt;
use tokio::sync::mpsc;
use tracing::{info, warn};
use uuid::Uuid;

use crate::error::{RunnerError, RunnerResult};
use crate::lock;
use crate::types::{Firewall, NetworkPolicy, SecretConnectorMetadata};

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ProxyRegistry {
    vms: HashMap<String, VmEntry>,
    updated_at: i64,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct VmEntry {
    run_id: String,
    cli_agent_type: String,
    sandbox_token: String,
    registered_at: i64,
    network_log_path: String,
    proxy_log_path: String,
    firewalls: Option<Vec<Firewall>>,
    network_policies: Option<HashMap<String, NetworkPolicy>>,
    encrypted_secrets: Option<String>,
    secret_connector_map: Option<HashMap<String, String>>,
    secret_connector_metadata_map: Option<HashMap<String, SecretConnectorMetadata>>,
    vars: Option<HashMap<String, String>>,
    #[serde(default)]
    capture_network_bodies: bool,
    billable_firewalls: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    model_usage_provider: Option<String>,
}

/// Parameters for registering a VM in the proxy registry.
#[derive(Debug)]
pub struct VmRegistration<'a> {
    pub run_id: &'a str,
    pub cli_agent_type: &'a str,
    pub sandbox_token: &'a str,
    pub network_log_path: &'a std::path::Path,
    pub proxy_log_path: &'a std::path::Path,
    pub firewalls: Option<&'a [Firewall]>,
    pub network_policies: Option<&'a HashMap<String, NetworkPolicy>>,
    pub encrypted_secrets: Option<&'a str>,
    pub secret_connector_map: Option<&'a HashMap<String, String>>,
    pub secret_connector_metadata_map: Option<&'a HashMap<String, SecretConnectorMetadata>>,
    pub vars: Option<&'a HashMap<String, String>>,
    pub capture_network_bodies: bool,
    pub billable_firewalls: &'a [String],
    pub model_usage_provider: Option<&'a str>,
}

// Embedded mitmproxy addon files (auto-generated by build.rs from mitm-addon/src/*.py).
include!(concat!(env!("OUT_DIR"), "/addon_files.rs"));

/// Timeout for waiting for mitmdump to become ready after spawn.
const READY_TIMEOUT: Duration = Duration::from_secs(10);

/// Timeout for graceful shutdown before SIGKILL.
///
/// Must be long enough for `done()` in the mitmproxy addon to flush
/// all in-flight usage reports (each POST has a 10 s HTTP timeout).
const STOP_TIMEOUT: Duration = Duration::from_secs(15);

/// Maximum time to wait for pending usage reports to flush before stopping.
///
/// The runner polls `{addon_dir}/usage-pending` (written by the Python
/// addon) and waits until both counters reach zero or this timeout expires.
/// 30 s is generous for worst-case webhook delivery (10 s timeout × 2
/// retries = 20.5 s) with headroom for mitmproxy event-loop drain.
pub const USAGE_FLUSH_TIMEOUT: Duration = Duration::from_secs(30);

/// Poll interval when waiting for usage flush.
const USAGE_FLUSH_POLL: Duration = Duration::from_millis(200);

/// Current JSON schema version for `{addon_dir}/usage-pending`.
const USAGE_PENDING_VERSION: u32 = 1;

/// Tolerated wall-clock skew when validating addon timestamps.
const USAGE_PENDING_CLOCK_SKEW: Duration = Duration::from_secs(300);

#[derive(Debug, Clone)]
pub struct UsageFlushTarget {
    expected_usage_state_id: String,
    usage_state_started_at_ms: u64,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct UsagePendingState {
    version: u32,
    pid: u32,
    usage_state_id: String,
    updated_at_ms: u64,
    flows: u32,
    reports: u32,
}

#[derive(Debug, Clone)]
struct UsagePendingSnapshot {
    pid: u32,
    usage_state_id: String,
    updated_at_ms: u64,
    flows: u32,
    reports: u32,
}

impl From<&UsagePendingState> for UsagePendingSnapshot {
    fn from(state: &UsagePendingState) -> Self {
        Self {
            pid: state.pid,
            usage_state_id: state.usage_state_id.clone(),
            updated_at_ms: state.updated_at_ms,
            flows: state.flows,
            reports: state.reports,
        }
    }
}

/// Configuration for starting the proxy.
#[derive(Clone)]
pub struct ProxyConfig {
    /// Path to the mitmdump binary.
    pub mitmdump_bin: PathBuf,
    /// Directory containing mitmproxy CA files (mitmproxy-ca.pem).
    pub ca_dir: PathBuf,
    /// Directory where addon scripts will be written.
    pub addon_dir: PathBuf,
    /// Path where the proxy registry JSON will be written.
    pub registry_path: PathBuf,
    /// Lock file path for coordinating concurrent registry access.
    pub registry_lock_path: PathBuf,
    /// VM0 API URL passed to the addon (optional).
    pub api_url: Option<String>,
}

/// Manages the mitmdump process lifecycle and proxy registry.
pub struct MitmProxy {
    port: u16,
    config: ProxyConfig,
    child: Option<tokio::process::Child>,
    /// Sender used by the stdout monitor task to signal unexpected exit.
    crash_tx: mpsc::Sender<()>,
    /// Set to `true` during graceful `stop()` / `Drop` to suppress crash notifications.
    stopping: Arc<AtomicBool>,
    /// Per-mitmdump-process token written by the addon to `usage-pending`.
    usage_state_id: String,
    /// Host timestamp from when `usage_state_id` was minted.
    usage_state_started_at_ms: u64,
}

impl MitmProxy {
    /// Prepare the proxy: allocate a port, write addon script and empty registry.
    ///
    /// Returns `(proxy, crash_rx)`. The caller should select on `crash_rx` to
    /// detect unexpected mitmdump exits and trigger a restart.
    pub async fn new(config: ProxyConfig) -> RunnerResult<(Self, mpsc::Receiver<()>)> {
        let port = find_available_port()?;

        // Write addon scripts to directory.
        // Remove-and-recreate to purge stale files from previous binary versions
        // (e.g. a renamed module would leave an orphan .py that Python could import).
        let _ = tokio::fs::remove_dir_all(&config.addon_dir).await;
        tokio::fs::create_dir_all(&config.addon_dir)
            .await
            .map_err(|e| RunnerError::Internal(format!("create addon dir: {e}")))?;
        for (name, content) in ADDON_FILES {
            // Addon file names may include subdirectories (e.g.
            // "usage/providers/connectors/x.py") after the usage/ package split.
            // Ensure the parent directory exists before writing.
            let path = config.addon_dir.join(name);
            if let Some(parent) = path.parent() {
                tokio::fs::create_dir_all(parent).await.map_err(|e| {
                    RunnerError::Internal(format!(
                        "create addon parent dir {}: {e}",
                        parent.display()
                    ))
                })?;
            }
            tokio::fs::write(&path, content)
                .await
                .map_err(|e| RunnerError::Internal(format!("write addon {name}: {e}")))?;
        }

        // Write empty registry file.
        let empty_registry = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&config.registry_path, &empty_registry).await?;

        let (crash_tx, crash_rx) = mpsc::channel(1);
        let (usage_state_id, usage_state_started_at_ms) = new_usage_state_id();

        Ok((
            Self {
                port,
                config,
                child: None,
                crash_tx,
                stopping: Arc::new(AtomicBool::new(false)),
                usage_state_id,
                usage_state_started_at_ms,
            },
            crash_rx,
        ))
    }

    /// Spawn the mitmdump process.
    pub async fn start(&mut self) -> RunnerResult<()> {
        let child = spawn_mitmdump(
            &self.config,
            self.port,
            &self.crash_tx,
            &self.stopping,
            &self.usage_state_id,
        )
        .await?;
        self.child = Some(child);
        info!(port = self.port, "mitmdump started");
        Ok(())
    }

    /// The port mitmdump is listening on.
    pub fn port(&self) -> u16 {
        self.port
    }

    /// Create a cloneable handle for registry operations (register/unregister VMs).
    ///
    /// The handle is `Clone + Send + Sync` and uses file locking for concurrent
    /// access, making it safe to share across executor tasks.
    pub fn registry_handle(&self) -> ProxyRegistryHandle {
        ProxyRegistryHandle {
            registry_path: self.config.registry_path.clone(),
            lock_path: self.config.registry_lock_path.clone(),
        }
    }

    /// Register a VM in the proxy registry so the addon can identify its traffic.
    pub async fn register_vm(
        &self,
        source_ip: &str,
        registration: &VmRegistration<'_>,
    ) -> RunnerResult<()> {
        self.registry_handle()
            .register_vm(source_ip, registration)
            .await
    }

    /// Unregister a VM from the proxy registry.
    pub async fn unregister_vm(&self, source_ip: &str) -> RunnerResult<()> {
        self.registry_handle().unregister_vm(source_ip).await
    }

    /// Current mitmdump usage state expected in the usage-pending state file.
    pub fn usage_flush_target(&mut self) -> Option<UsageFlushTarget> {
        let child_exited = match self.child.as_mut()?.try_wait() {
            Ok(Some(status)) => {
                warn!(code = status.code(), "mitmdump exited before usage flush");
                true
            }
            Ok(None) => false,
            Err(e) => {
                warn!(error = %e, "failed to query mitmdump status before usage flush");
                false
            }
        };
        if child_exited {
            self.child = None;
            return None;
        }

        let _child_pid = self.child.as_ref().and_then(|child| child.id())?;
        Some(UsageFlushTarget {
            expected_usage_state_id: self.usage_state_id.clone(),
            usage_state_started_at_ms: self.usage_state_started_at_ms,
        })
    }

    /// Prepare for restart: kill any lingering child, permanently silence
    /// its stdout monitor, and return fresh parameters for
    /// [`spawn_mitmdump`].
    ///
    /// `stopping` is scoped to a single child. The old flag is set to
    /// `true` (so the old monitor task, which may observe the stdout
    /// pipe close at some arbitrary point after this call returns,
    /// reads "graceful shutdown" and never emits a spurious crash
    /// notification) and the field is replaced with a fresh `Arc` for
    /// the incoming process. The new child's monitor starts from a
    /// clean slate and will detect real crashes.
    ///
    /// The caller should spawn the mitmdump process (potentially in a
    /// background task) and then call `complete_restart` with the result.
    pub async fn begin_restart(&mut self) -> MitmRestartParams {
        // Silence the old monitor permanently: after this call, no one
        // else holds a handle that could reset its `Arc<AtomicBool>`
        // back to `false`, so the monitor is guaranteed to read `true`
        // regardless of scheduling order between `kill().await` and
        // the stdout-pipe drain.
        self.stopping.store(true, Ordering::Release);
        if let Some(ref mut child) = self.child {
            let _ = child.kill().await;
            self.child = None;
        }
        // Fresh flag for the incoming process's monitor.
        let new_stopping = Arc::new(AtomicBool::new(false));
        self.stopping = Arc::clone(&new_stopping);
        let (usage_state_id, usage_state_started_at_ms) = new_usage_state_id();
        self.usage_state_id = usage_state_id.clone();
        self.usage_state_started_at_ms = usage_state_started_at_ms;
        MitmRestartParams {
            config: self.config.clone(),
            port: self.port,
            crash_tx: self.crash_tx.clone(),
            stopping: new_stopping,
            usage_state_id,
        }
    }

    /// Finish a restart by storing the newly spawned child process.
    pub fn complete_restart(&mut self, child: tokio::process::Child) {
        self.child = Some(child);
    }

    /// Gracefully stop mitmdump (SIGTERM → timeout → SIGKILL).
    pub async fn stop(&mut self) -> RunnerResult<()> {
        self.stopping.store(true, Ordering::Release);
        let Some(ref mut child) = self.child else {
            return Ok(());
        };
        info!("stopping mitmdump");
        send_sigterm(child);

        match tokio::time::timeout(STOP_TIMEOUT, child.wait()).await {
            Ok(Ok(status)) => {
                info!(code = status.code(), "mitmdump stopped");
            }
            Ok(Err(e)) => {
                warn!(error = %e, "mitmdump wait failed");
            }
            Err(_) => {
                warn!("mitmdump did not exit in time, sending SIGKILL");
                let _ = child.kill().await;
            }
        }
        self.child = None;
        Ok(())
    }
}

fn now_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis().min(u128::from(u64::MAX)) as u64)
        .unwrap_or(0)
}

fn new_usage_state_id() -> (String, u64) {
    (Uuid::new_v4().to_string(), now_millis())
}

fn parse_usage_pending_state(content: &str) -> Result<UsagePendingState, String> {
    let trimmed = content.trim();
    if trimmed.is_empty() {
        return Err("state file is empty".to_string());
    }
    serde_json::from_str::<UsagePendingState>(trimmed)
        .map_err(|e| format!("state file is not valid usage-pending JSON: {e}"))
}

fn validate_usage_pending_state(
    state: &UsagePendingState,
    target: &UsageFlushTarget,
    now_ms: u64,
) -> Result<(), String> {
    if state.version != USAGE_PENDING_VERSION {
        return Err(format!(
            "unsupported version {}, expected {}",
            state.version, USAGE_PENDING_VERSION
        ));
    }
    if state.usage_state_id != target.expected_usage_state_id {
        return Err("usage state id does not match current mitmdump process".to_string());
    }

    let skew_ms = USAGE_PENDING_CLOCK_SKEW.as_millis() as u64;
    let min_updated_at = target.usage_state_started_at_ms.saturating_sub(skew_ms);
    if state.updated_at_ms < min_updated_at {
        return Err(format!(
            "updatedAtMs {} predates current usage state id start {}",
            state.updated_at_ms, target.usage_state_started_at_ms
        ));
    }
    if state.updated_at_ms > now_ms.saturating_add(skew_ms) {
        return Err(format!(
            "updatedAtMs {} is too far in the future",
            state.updated_at_ms
        ));
    }

    Ok(())
}

/// Wait for all pending proxy usage reports to be delivered.
///
/// The Python addon writes JSON to `{addon_dir}/usage-pending` with the
/// mitmdump usage-state identity plus in-flight flow and report counters.
/// A successful drain requires current valid state with `flows == 0` and
/// `reports == 0`. Missing, unreadable, stale, wrong state id, or invalid
/// state is treated as not ready and waits until timeout. The JSON `pid`
/// is diagnostic only: mitmdump launchers can keep the runner's direct
/// child as a wrapper while the Python addon runs in a child process.
pub async fn wait_usage_flush(
    addon_dir: &Path,
    timeout: Duration,
    target: &UsageFlushTarget,
) -> bool {
    let path = addon_dir.join("usage-pending");
    let deadline = tokio::time::Instant::now() + timeout;
    loop {
        let (not_ready, snapshot) = match tokio::fs::read_to_string(&path).await {
            Ok(content) => match parse_usage_pending_state(&content) {
                Ok(state) => {
                    let snapshot = Some(UsagePendingSnapshot::from(&state));
                    match validate_usage_pending_state(&state, target, now_millis()) {
                        Ok(()) => {
                            if state.flows == 0 && state.reports == 0 {
                                return true;
                            }
                            (
                                format!("pending flows={} reports={}", state.flows, state.reports),
                                snapshot,
                            )
                        }
                        Err(reason) => (reason, snapshot),
                    }
                }
                Err(reason) => (reason, None),
            },
            Err(e) => (format!("cannot read {}: {e}", path.display()), None),
        };
        let now = tokio::time::Instant::now();
        if now >= deadline {
            match snapshot {
                Some(snapshot) => warn!(
                    timeout_secs = timeout.as_secs(),
                    reason = %not_ready,
                    pid = snapshot.pid,
                    usage_state_id = %snapshot.usage_state_id,
                    updated_at_ms = snapshot.updated_at_ms,
                    flows = snapshot.flows,
                    reports = snapshot.reports,
                    "usage flush timed out, proceeding with proxy stop"
                ),
                None => warn!(
                    timeout_secs = timeout.as_secs(),
                    reason = %not_ready,
                    "usage flush timed out, proceeding with proxy stop"
                ),
            }
            return false;
        }
        tokio::time::sleep(std::cmp::min(USAGE_FLUSH_POLL, deadline - now)).await;
    }
}

#[cfg(test)]
impl MitmProxy {
    /// Create a noop proxy for testing. No real process is spawned.
    ///
    /// `stop()` already handles `child: None` (returns immediately),
    /// and `begin_restart()` is never triggered because the test holds
    /// the crash channel sender and never sends on it.
    pub fn noop() -> (Self, mpsc::Receiver<()>) {
        let (crash_tx, crash_rx) = mpsc::channel(1);
        (
            Self {
                port: 0,
                config: ProxyConfig {
                    mitmdump_bin: std::path::PathBuf::new(),
                    ca_dir: std::path::PathBuf::new(),
                    addon_dir: std::path::PathBuf::new(),
                    registry_path: std::path::PathBuf::new(),
                    registry_lock_path: std::path::PathBuf::new(),
                    api_url: None,
                },
                child: None,
                crash_tx,
                stopping: Arc::new(AtomicBool::new(false)),
                usage_state_id: "test-usage-state-id".to_string(),
                usage_state_started_at_ms: now_millis(),
            },
            crash_rx,
        )
    }
}

impl Drop for MitmProxy {
    fn drop(&mut self) {
        self.stopping.store(true, Ordering::Release);
        // Best-effort kill if still running.
        if let Some(ref mut child) = self.child {
            let _ = child.start_kill();
        }
    }
}

/// Parameters needed to spawn a mitmdump process, returned by
/// [`MitmProxy::begin_restart`]. All fields are owned/cloned so the spawn
/// can happen in a background task without borrowing `MitmProxy`.
pub(crate) struct MitmRestartParams {
    config: ProxyConfig,
    port: u16,
    crash_tx: mpsc::Sender<()>,
    stopping: Arc<AtomicBool>,
    usage_state_id: String,
}

impl MitmRestartParams {
    /// Spawn mitmdump using these parameters. Suitable for `tokio::spawn`.
    pub(crate) async fn spawn(self) -> RunnerResult<tokio::process::Child> {
        spawn_mitmdump(
            &self.config,
            self.port,
            &self.crash_tx,
            &self.stopping,
            &self.usage_state_id,
        )
        .await
    }
}

/// Spawn a mitmdump process, wire up stdout/stderr monitors, and wait for
/// it to become ready. This is a free function so it can run in a
/// `tokio::spawn` without borrowing `MitmProxy`.
pub(crate) async fn spawn_mitmdump(
    config: &ProxyConfig,
    port: u16,
    crash_tx: &mpsc::Sender<()>,
    stopping: &Arc<AtomicBool>,
    usage_state_id: &str,
) -> RunnerResult<tokio::process::Child> {
    let mut cmd = tokio::process::Command::new(&config.mitmdump_bin);
    cmd.arg("--mode")
        .arg("transparent")
        .arg("--listen-port")
        .arg(port.to_string())
        .arg("--set")
        .arg(format!("confdir={}", config.ca_dir.display()))
        .arg("--set")
        .arg(format!(
            "vm0_proxy_registry_path={}",
            config.registry_path.display()
        ))
        .arg("--set")
        .arg(format!("vm0_usage_state_id={usage_state_id}"))
        .arg("--scripts")
        .arg(config.addon_dir.join("mitm_addon.py"))
        .arg("--set")
        .arg("flow_detail=0")
        .arg("--set")
        .arg("termlog_verbosity=warn")
        .arg("--set")
        .arg(format!(
            "ssl_verify_upstream_trusted_ca={}",
            crate::deps::SYSTEM_CA_BUNDLE
        ));
    if let Some(url) = &config.api_url {
        cmd.arg("--set").arg(format!("vm0_api_url={url}"));
    }
    cmd.stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped());
    cmd.kill_on_drop(true);

    // SAFETY: `set_pdeathsig` calls `prctl(PR_SET_PDEATHSIG)` which is
    // async-signal-safe. This ensures the kernel sends SIGKILL to the
    // mitmdump child when the parent runner process dies, preventing
    // orphaned processes after runner crashes or restarts.
    unsafe {
        cmd.pre_exec(|| {
            nix::sys::prctl::set_pdeathsig(nix::sys::signal::Signal::SIGKILL)
                .map_err(std::io::Error::from)
        });
    }

    info!(port, bin = %config.mitmdump_bin.display(), "starting mitmdump");

    let mut child = cmd
        .spawn()
        .map_err(|e| RunnerError::Internal(format!("spawn mitmdump: {e}")))?;

    // Stream stdout to tracing; when the pipe closes (process exited),
    // send a crash notification unless we're in a graceful stop.
    if let Some(stdout) = child.stdout.take() {
        let crash_tx = crash_tx.clone();
        let stopping = Arc::clone(stopping);
        tokio::spawn(async move {
            let mut lines = tokio::io::BufReader::new(stdout).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                if !line.is_empty() {
                    info!(target: "mitmdump", "{line}");
                }
            }
            // Pipe closed — process exited.
            if !stopping.load(Ordering::Acquire) {
                let _ = crash_tx.send(()).await;
            }
        });
    }
    if let Some(stderr) = child.stderr.take() {
        tokio::spawn(async move {
            let mut lines = tokio::io::BufReader::new(stderr).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                if !line.is_empty() {
                    warn!(target: "mitmdump", "stderr: {line}");
                }
            }
        });
    }

    // Wait for process to be alive (poll liveness).
    if let Err(e) = wait_for_ready(&mut child, port, READY_TIMEOUT).await {
        stopping.store(true, Ordering::Release);
        let _ = child.kill().await;
        return Err(e);
    }

    Ok(child)
}

/// Wait for mitmdump to start listening on `port` (TCP connect probe).
async fn wait_for_ready(
    child: &mut tokio::process::Child,
    port: u16,
    timeout: Duration,
) -> RunnerResult<()> {
    let poll_interval = Duration::from_millis(200);
    let start = std::time::Instant::now();
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));

    while start.elapsed() < timeout {
        // Check if process died.
        match child.try_wait() {
            Ok(Some(status)) => {
                return Err(RunnerError::Internal(format!(
                    "mitmdump exited immediately with {}",
                    status
                        .code()
                        .map_or("unknown".to_string(), |c| c.to_string()),
                )));
            }
            Ok(None) => {}
            Err(e) => {
                return Err(RunnerError::Internal(format!(
                    "mitmdump process check: {e}"
                )));
            }
        }
        // Probe TCP port.
        if tokio::net::TcpStream::connect(addr).await.is_ok() {
            return Ok(());
        }
        tokio::time::sleep(poll_interval).await;
    }

    Err(RunnerError::Internal(format!(
        "mitmdump did not start listening on port {port} within {}s",
        timeout.as_secs()
    )))
}

/// Find an available TCP port by binding to port 0.
fn find_available_port() -> RunnerResult<u16> {
    let listener = std::net::TcpListener::bind("0.0.0.0:0")
        .map_err(|e| RunnerError::Internal(format!("bind port 0: {e}")))?;
    let port = listener
        .local_addr()
        .map_err(|e| RunnerError::Internal(format!("local_addr: {e}")))?
        .port();
    Ok(port)
}

/// Read the proxy registry JSON file.
async fn read_registry(path: &std::path::Path) -> RunnerResult<ProxyRegistry> {
    let content = tokio::fs::read_to_string(path)
        .await
        .map_err(|e| RunnerError::Internal(format!("read registry: {e}")))?;
    serde_json::from_str(&content)
        .map_err(|e| RunnerError::Internal(format!("parse registry: {e}")))
}

/// Write the proxy registry JSON file atomically (write tmp + rename).
///
/// This ensures the Python mitm-addon never reads a partially-written file.
async fn write_registry(path: &std::path::Path, value: &ProxyRegistry) -> RunnerResult<()> {
    let content = serde_json::to_string(value)
        .map_err(|e| RunnerError::Internal(format!("serialize registry: {e}")))?;
    let tmp = path.with_extension("json.tmp");
    tokio::fs::write(&tmp, content)
        .await
        .map_err(|e| RunnerError::Internal(format!("write registry tmp: {e}")))?;
    tokio::fs::rename(&tmp, path)
        .await
        .map_err(|e| RunnerError::Internal(format!("rename registry: {e}")))
}

/// Lightweight, cloneable handle for proxy registry operations.
///
/// Uses file locking (`flock`) to ensure concurrent register/unregister calls
/// from multiple executor tasks don't corrupt the registry JSON.
#[derive(Clone)]
pub struct ProxyRegistryHandle {
    registry_path: PathBuf,
    lock_path: PathBuf,
}

impl ProxyRegistryHandle {
    /// Create a handle from explicit paths (for testing).
    #[cfg(test)]
    pub fn new(registry_path: PathBuf, lock_path: PathBuf) -> Self {
        Self {
            registry_path,
            lock_path,
        }
    }

    /// Register a VM in the proxy registry.
    pub async fn register_vm(
        &self,
        source_ip: &str,
        registration: &VmRegistration<'_>,
    ) -> RunnerResult<()> {
        let _guard = lock::acquire(self.lock_path.clone()).await?;

        let mut registry = read_registry(&self.registry_path).await?;
        let now = chrono::Utc::now().timestamp_millis();
        let firewalls = registration.firewalls.map(|s| {
            let mut s = s.to_vec();
            let mut idx = 0usize;
            for entry in &mut s {
                for api in &mut entry.apis {
                    if api.id.is_empty() {
                        api.id = format!("{}:{}", registration.run_id, idx);
                    }
                    idx += 1;
                }
            }
            s
        });
        registry.vms.insert(
            source_ip.to_string(),
            VmEntry {
                run_id: registration.run_id.to_string(),
                cli_agent_type: registration.cli_agent_type.to_string(),
                sandbox_token: registration.sandbox_token.to_string(),
                registered_at: now,
                network_log_path: registration.network_log_path.to_string_lossy().into_owned(),
                proxy_log_path: registration.proxy_log_path.to_string_lossy().into_owned(),
                firewalls,
                network_policies: registration.network_policies.cloned(),
                encrypted_secrets: registration.encrypted_secrets.map(String::from),
                secret_connector_map: registration.secret_connector_map.cloned(),
                secret_connector_metadata_map: registration.secret_connector_metadata_map.cloned(),
                vars: registration.vars.cloned(),
                capture_network_bodies: registration.capture_network_bodies,
                billable_firewalls: registration.billable_firewalls.to_vec(),
                model_usage_provider: registration.model_usage_provider.map(String::from),
            },
        );
        registry.updated_at = now;
        write_registry(&self.registry_path, &registry).await?;
        info!(
            source_ip,
            run_id = registration.run_id,
            "registered VM in proxy registry"
        );
        Ok(())
    }

    /// Unregister a VM from the proxy registry.
    pub async fn unregister_vm(&self, source_ip: &str) -> RunnerResult<()> {
        let _guard = lock::acquire(self.lock_path.clone()).await?;

        let mut registry = read_registry(&self.registry_path).await?;
        registry.vms.remove(source_ip);
        registry.updated_at = chrono::Utc::now().timestamp_millis();
        write_registry(&self.registry_path, &registry).await?;
        info!(source_ip, "unregistered VM from proxy registry");
        Ok(())
    }
}

/// Send SIGTERM to a child process.
fn send_sigterm(child: &tokio::process::Child) {
    if let Some(pid) = child.id() {
        let _ = nix::sys::signal::kill(
            nix::unistd::Pid::from_raw(pid as i32),
            nix::sys::signal::Signal::SIGTERM,
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{FirewallApi, FirewallAuth, FirewallPermission};
    use std::os::unix::fs::PermissionsExt;

    fn write_fake_listening_mitmdump(path: &Path) {
        std::fs::write(
            path,
            r#"#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$@" > "$0.args"
port=""
prev=""
for arg in "$@"; do
  if [ "$prev" = "--listen-port" ]; then
    port="$arg"
    break
  fi
  prev="$arg"
done
exec python3 - "$port" <<'PY'
import socket
import sys

port = int(sys.argv[1])
sock = socket.socket()
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind(("127.0.0.1", port))
sock.listen(1)
while True:
    conn, _ = sock.accept()
    conn.close()
PY
"#,
        )
        .unwrap();
        let mut perms = std::fs::metadata(path).unwrap().permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(path, perms).unwrap();
    }

    async fn wait_for_reaped_pid(pid: nix::unistd::Pid) -> bool {
        let deadline = tokio::time::Instant::now() + Duration::from_secs(2);
        loop {
            match nix::sys::wait::waitpid(pid, Some(nix::sys::wait::WaitPidFlag::WNOHANG)) {
                Ok(nix::sys::wait::WaitStatus::StillAlive) => {}
                Ok(_) => return true,
                Err(nix::errno::Errno::ECHILD) => {
                    return nix::sys::signal::kill(pid, None).is_err();
                }
                Err(_) => {}
            }
            if tokio::time::Instant::now() >= deadline {
                return false;
            }
            tokio::time::sleep(Duration::from_millis(50)).await;
        }
    }

    #[test]
    fn find_port_returns_nonzero() {
        let port = find_available_port().unwrap();
        assert!(port > 0, "expected non-zero port, got {port}");
    }

    #[test]
    fn addon_scripts_are_embedded() {
        let files: Vec<&str> = ADDON_FILES.iter().map(|(name, _)| *name).collect();

        // All expected modules must be present.  `usage/` is a package after
        // #10381; each submodule must embed under its relative path so the
        // runtime extractor rebuilds the directory tree before mitmdump loads
        // the addon.
        for expected in [
            "mitm_addon.py",
            "auth.py",
            "body_utils.py",
            "matching.py",
            "registry.py",
            "response_streaming.py",
            "url_utils.py",
            "logging_utils.py",
            "usage/__init__.py",
            "usage/anthropic_messages.py",
            "usage/counters.py",
            "usage/model_tokens.py",
            "usage/namespaces.py",
            "usage/openai_responses.py",
            "usage/sse.py",
            "usage/webhook.py",
            "usage/providers/__init__.py",
            "usage/providers/model_provider.py",
            "usage/providers/connectors/__init__.py",
            "usage/providers/connectors/x.py",
        ] {
            assert!(
                files.contains(&expected),
                "addon files should include {expected}, got: {files:?}"
            );
        }

        let (_, content) = ADDON_FILES
            .iter()
            .find(|(name, _)| *name == "mitm_addon.py")
            .unwrap();
        assert!(
            content.contains("mitmproxy addon"),
            "mitm_addon.py should contain expected header"
        );
    }

    #[tokio::test]
    async fn registry_register_and_unregister() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        // Register a VM.
        let mut registry = read_registry(&registry_path).await.unwrap();
        registry.vms.insert(
            "10.200.0.2".to_string(),
            VmEntry {
                run_id: "test-run".to_string(),
                cli_agent_type: "claude-code".to_string(),
                sandbox_token: String::new(),
                registered_at: 1000,
                network_log_path: "/tmp/network-test-run.jsonl".to_string(),
                proxy_log_path: "/tmp/proxy-test-run.jsonl".to_string(),
                firewalls: None,
                network_policies: None,
                encrypted_secrets: None,
                secret_connector_map: None,
                secret_connector_metadata_map: None,
                vars: None,
                capture_network_bodies: false,
                billable_firewalls: vec![],
                model_usage_provider: None,
            },
        );
        write_registry(&registry_path, &registry).await.unwrap();

        // Verify registration.
        let loaded = read_registry(&registry_path).await.unwrap();
        let vm = loaded.vms.get("10.200.0.2").unwrap();
        assert_eq!(vm.run_id, "test-run");

        // Unregister the VM.
        let mut registry = read_registry(&registry_path).await.unwrap();
        registry.vms.remove("10.200.0.2");
        write_registry(&registry_path, &registry).await.unwrap();

        // Verify unregistration.
        let loaded = read_registry(&registry_path).await.unwrap();
        assert!(
            !loaded.vms.contains_key("10.200.0.2"),
            "VM should be removed from registry"
        );
    }

    #[tokio::test]
    async fn registry_handle_register_and_unregister() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.json.lock");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        // Register via handle.
        let registration = VmRegistration {
            run_id: "run-1",
            cli_agent_type: "claude-code",
            sandbox_token: "tok-1",
            network_log_path: std::path::Path::new("/tmp/network-run-1.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-1.jsonl"),
            firewalls: None,
            network_policies: None,
            encrypted_secrets: None,
            secret_connector_map: None,
            secret_connector_metadata_map: None,
            vars: None,
            capture_network_bodies: false,
            billable_firewalls: &[],
            model_usage_provider: None,
        };
        handle
            .register_vm("10.200.0.2", &registration)
            .await
            .unwrap();

        let loaded = read_registry(&registry_path).await.unwrap();
        let vm = loaded.vms.get("10.200.0.2").unwrap();
        assert_eq!(vm.run_id, "run-1");

        // Re-register same IP overwrites the entry.
        let registration2 = VmRegistration {
            run_id: "run-2",
            cli_agent_type: "codex",
            sandbox_token: "tok-2",
            network_log_path: std::path::Path::new("/tmp/network-run-2.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-2.jsonl"),
            firewalls: None,
            network_policies: None,
            encrypted_secrets: None,
            secret_connector_map: None,
            secret_connector_metadata_map: None,
            vars: None,
            capture_network_bodies: false,
            billable_firewalls: &[],
            model_usage_provider: None,
        };
        handle
            .register_vm("10.200.0.2", &registration2)
            .await
            .unwrap();
        let loaded = read_registry(&registry_path).await.unwrap();
        let vm = loaded.vms.get("10.200.0.2").unwrap();
        assert_eq!(vm.run_id, "run-2");
        assert_eq!(vm.cli_agent_type, "codex");

        // Unregister via handle.
        handle.unregister_vm("10.200.0.2").await.unwrap();

        let loaded = read_registry(&registry_path).await.unwrap();
        assert!(!loaded.vms.contains_key("10.200.0.2"));

        // Unregister non-existent IP is a no-op.
        handle.unregister_vm("10.200.0.99").await.unwrap();
    }

    #[tokio::test]
    async fn registry_handle_concurrent_access() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.json.lock");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        // Spawn 10 concurrent register tasks.
        let mut tasks = tokio::task::JoinSet::new();
        for i in 0..10 {
            let h = handle.clone();
            let ip = format!("10.200.0.{}", i + 2);
            let run_id_owned = format!("run-{i}");
            tasks.spawn(async move {
                let log_path =
                    std::path::PathBuf::from(format!("/tmp/network-{run_id_owned}.jsonl"));
                let proxy_path =
                    std::path::PathBuf::from(format!("/tmp/proxy-{run_id_owned}.jsonl"));
                let registration = VmRegistration {
                    run_id: &run_id_owned,
                    cli_agent_type: "claude-code",
                    sandbox_token: "",
                    network_log_path: &log_path,
                    proxy_log_path: &proxy_path,
                    firewalls: None,
                    network_policies: None,
                    encrypted_secrets: None,
                    secret_connector_map: None,
                    secret_connector_metadata_map: None,
                    vars: None,
                    capture_network_bodies: false,
                    billable_firewalls: &[],
                    model_usage_provider: None,
                };
                h.register_vm(&ip, &registration).await.unwrap();
            });
        }
        while let Some(result) = tasks.join_next().await {
            result.unwrap();
        }

        // All 10 VMs should be registered (no lost updates).
        let loaded = read_registry(&registry_path).await.unwrap();
        assert_eq!(loaded.vms.len(), 10);
    }

    #[tokio::test]
    async fn registry_with_firewalls() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.json.lock");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        let firewall_entries = vec![Firewall {
            name: "gmail".to_string(),
            apis: vec![FirewallApi {
                id: String::new(),
                base: "https://gmail.googleapis.com/gmail/v1/users/me".to_string(),
                auth: FirewallAuth {
                    headers: std::collections::HashMap::from([(
                        "Authorization".to_string(),
                        "Bearer ${{ secrets.GMAIL_TOKEN }}".to_string(),
                    )]),
                    base: None,
                    query: None,
                },
                permissions: Some(vec![FirewallPermission {
                    name: "mail-read".to_string(),
                    description: None,
                    rules: vec![
                        "GET /messages".to_string(),
                        "GET /messages/{id}".to_string(),
                    ],
                }]),
            }],
        }];

        let registration = VmRegistration {
            run_id: "run-fw",
            cli_agent_type: "claude-code",
            sandbox_token: "tok",
            network_log_path: std::path::Path::new("/tmp/network-run-fw.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-fw.jsonl"),
            firewalls: Some(&firewall_entries),
            network_policies: None,
            encrypted_secrets: None,
            secret_connector_map: None,
            secret_connector_metadata_map: None,
            vars: None,
            capture_network_bodies: false,
            billable_firewalls: &[],
            model_usage_provider: None,
        };
        handle
            .register_vm("10.200.0.5", &registration)
            .await
            .unwrap();

        // Verify firewall entries are stored in registry.
        let loaded = read_registry(&registry_path).await.unwrap();
        let vm = loaded.vms.get("10.200.0.5").unwrap();
        let stored = vm.firewalls.as_ref().unwrap();
        assert_eq!(stored.len(), 1);
        assert_eq!(stored[0].apis.len(), 1);
        assert_eq!(
            stored[0].apis[0].base,
            "https://gmail.googleapis.com/gmail/v1/users/me"
        );

        // Verify id was assigned by register_vm: "{run_id}:{global_index}".
        assert_eq!(stored[0].apis[0].id, "run-fw:0");

        // Verify JSON shape matches what the Python addon expects.
        let raw = tokio::fs::read_to_string(&registry_path).await.unwrap();
        let value: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let vm_json = &value["vms"]["10.200.0.5"];
        let fw = &vm_json["firewalls"][0];
        assert_eq!(fw["name"], "gmail");
        assert_eq!(
            fw["apis"][0]["base"],
            "https://gmail.googleapis.com/gmail/v1/users/me"
        );
        assert_eq!(fw["apis"][0]["id"], "run-fw:0");

        // Verify permissions are preserved in JSON for the Python addon.
        let perms = &fw["apis"][0]["permissions"];
        assert_eq!(perms[0]["name"], "mail-read");
        assert_eq!(perms[0]["rules"][0], "GET /messages");
        assert_eq!(perms[0]["rules"][1], "GET /messages/{id}");

        // Empty billableFirewalls round-trips as [] (Python reads vm_info["billableFirewalls"]).
        assert_eq!(vm_json["billableFirewalls"], serde_json::json!([]));
    }

    #[tokio::test]
    async fn registry_serializes_billable_firewalls() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.json.lock");
        write_registry(
            &registry_path,
            &ProxyRegistry {
                vms: HashMap::new(),
                updated_at: 0,
            },
        )
        .await
        .unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };
        let billable = ["model-provider:vm0".to_string()];
        let registration = VmRegistration {
            run_id: "run-billing",
            cli_agent_type: "codex",
            sandbox_token: "tok",
            network_log_path: std::path::Path::new("/tmp/network-run-billing.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-billing.jsonl"),
            firewalls: None,
            network_policies: None,
            encrypted_secrets: None,
            secret_connector_map: None,
            secret_connector_metadata_map: None,
            vars: None,
            capture_network_bodies: false,
            billable_firewalls: &billable,
            model_usage_provider: Some("claude-sonnet-4-6"),
        };
        handle
            .register_vm("10.200.0.9", &registration)
            .await
            .unwrap();

        // Guard the TS↔Rust↔Python wire contract: the camelCase key is what
        // mitm-addon reads via `vm_info["billableFirewalls"]`.
        let raw = tokio::fs::read_to_string(&registry_path).await.unwrap();
        let value: serde_json::Value = serde_json::from_str(&raw).unwrap();
        assert_eq!(
            value["vms"]["10.200.0.9"]["billableFirewalls"],
            serde_json::json!(["model-provider:vm0"])
        );
        assert_eq!(
            value["vms"]["10.200.0.9"]["cliAgentType"],
            serde_json::json!("codex")
        );
        assert_eq!(
            value["vms"]["10.200.0.9"]["modelUsageProvider"],
            serde_json::json!("claude-sonnet-4-6")
        );
    }

    #[tokio::test]
    async fn register_vm_stores_encrypted_secrets() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.lock");

        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        let metadata = HashMap::from([(
            "CHATGPT_ACCESS_TOKEN".to_string(),
            SecretConnectorMetadata {
                source_type: "model-provider".to_string(),
                source_user_id: Some("user-123".to_string()),
                metadata_key: Some("codex-oauth-token".to_string()),
            },
        )]);
        let registration = VmRegistration {
            run_id: "run-enc",
            cli_agent_type: "claude-code",
            sandbox_token: "tok",
            network_log_path: std::path::Path::new("/tmp/network-run-enc.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-enc.jsonl"),
            firewalls: None,
            network_policies: None,
            encrypted_secrets: Some("iv_b64:tag_b64:data_b64"),
            secret_connector_map: None,
            secret_connector_metadata_map: Some(&metadata),
            vars: None,
            capture_network_bodies: false,
            billable_firewalls: &[],
            model_usage_provider: None,
        };
        handle
            .register_vm("10.200.0.6", &registration)
            .await
            .unwrap();

        let loaded = read_registry(&registry_path).await.unwrap();
        let vm = loaded.vms.get("10.200.0.6").unwrap();
        assert_eq!(
            vm.encrypted_secrets.as_deref(),
            Some("iv_b64:tag_b64:data_b64")
        );

        // Verify JSON key name matches what the Python addon expects.
        let raw = tokio::fs::read_to_string(&registry_path).await.unwrap();
        let value: serde_json::Value = serde_json::from_str(&raw).unwrap();
        assert_eq!(
            value["vms"]["10.200.0.6"]["encryptedSecrets"],
            "iv_b64:tag_b64:data_b64"
        );
        assert_eq!(
            value["vms"]["10.200.0.6"]["secretConnectorMetadataMap"]["CHATGPT_ACCESS_TOKEN"]["sourceUserId"],
            "user-123"
        );
    }

    #[tokio::test]
    async fn registry_firewall_auth_base_serialized() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.lock");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        let firewall_entries = vec![Firewall {
            name: "discord-webhook".to_string(),
            apis: vec![FirewallApi {
                id: String::new(),
                base: "https://firewall-placeholder.vm3.ai/discord-webhook/hook".to_string(),
                auth: FirewallAuth {
                    headers: std::collections::HashMap::new(),
                    base: Some("${{ secrets.DISCORD_WEBHOOK_URL }}".to_string()),
                    query: None,
                },
                permissions: None,
            }],
        }];

        let registration = VmRegistration {
            run_id: "run-webhook",
            cli_agent_type: "claude-code",
            sandbox_token: "tok",
            network_log_path: std::path::Path::new("/tmp/network-run-webhook.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-webhook.jsonl"),
            firewalls: Some(&firewall_entries),
            network_policies: None,
            encrypted_secrets: Some("enc_data"),
            secret_connector_map: None,
            secret_connector_metadata_map: None,
            vars: None,
            capture_network_bodies: false,
            billable_firewalls: &[],
            model_usage_provider: None,
        };
        handle
            .register_vm("10.200.0.7", &registration)
            .await
            .unwrap();

        // Verify auth.base is preserved in the registry JSON.
        let raw = tokio::fs::read_to_string(&registry_path).await.unwrap();
        let value: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let api = &value["vms"]["10.200.0.7"]["firewalls"][0]["apis"][0];
        assert_eq!(api["auth"]["base"], "${{ secrets.DISCORD_WEBHOOK_URL }}");
        // headers should be empty object
        assert_eq!(api["auth"]["headers"], serde_json::json!({}));
    }

    #[tokio::test]
    async fn registry_firewall_auth_query_serialized() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.lock");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        let firewall_entries = vec![Firewall {
            name: "serpapi".to_string(),
            apis: vec![FirewallApi {
                id: String::new(),
                base: "https://serpapi.com".to_string(),
                auth: FirewallAuth {
                    headers: std::collections::HashMap::new(),
                    base: None,
                    query: Some(
                        [(
                            "api_key".to_string(),
                            "${{ secrets.SERPAPI_TOKEN }}".to_string(),
                        )]
                        .into_iter()
                        .collect(),
                    ),
                },
                permissions: None,
            }],
        }];

        let registration = VmRegistration {
            run_id: "run-query-auth",
            cli_agent_type: "claude-code",
            sandbox_token: "tok",
            network_log_path: std::path::Path::new("/tmp/network-run-query.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-query.jsonl"),
            firewalls: Some(&firewall_entries),
            network_policies: None,
            encrypted_secrets: Some("enc_data"),
            secret_connector_map: None,
            secret_connector_metadata_map: None,
            vars: None,
            capture_network_bodies: false,
            billable_firewalls: &[],
            model_usage_provider: None,
        };
        handle
            .register_vm("10.200.0.8", &registration)
            .await
            .unwrap();

        // Verify auth.query is preserved in the registry JSON.
        let raw = tokio::fs::read_to_string(&registry_path).await.unwrap();
        let value: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let api = &value["vms"]["10.200.0.8"]["firewalls"][0]["apis"][0];
        assert_eq!(
            api["auth"]["query"],
            serde_json::json!({"api_key": "${{ secrets.SERPAPI_TOKEN }}"})
        );
        // headers should be empty object, base should be absent
        assert_eq!(api["auth"]["headers"], serde_json::json!({}));
        assert_eq!(api["auth"]["base"], serde_json::Value::Null);
    }

    #[tokio::test]
    async fn wait_for_ready_returns_error_on_timeout() {
        // `sleep` never listens on TCP — guarantees timeout.
        let mut child = tokio::process::Command::new("sleep")
            .arg("60")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();

        let raw_pid = child.id().unwrap() as i32;
        let pid = nix::unistd::Pid::from_raw(raw_pid);
        let port = find_available_port().unwrap();

        let result = wait_for_ready(&mut child, port, Duration::from_millis(500)).await;
        assert!(result.is_err());

        // Process must still be alive — wait_for_ready does NOT kill on error.
        // This is the scenario that caused orphaned processes before the fix:
        // the caller (spawn_mitmdump) is responsible for killing.
        assert!(
            nix::sys::signal::kill(pid, None).is_ok(),
            "process should still be alive after timeout"
        );

        // Simulate spawn_mitmdump error path: kill the child.
        let _ = child.kill().await;

        assert!(
            nix::sys::signal::kill(pid, None).is_err(),
            "process should be dead after kill"
        );
    }

    #[tokio::test]
    async fn wait_for_ready_returns_error_on_early_exit() {
        // `true` exits immediately with status 0.
        let mut child = tokio::process::Command::new("true")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();

        // Wait for `true` to actually exit before calling wait_for_ready,
        // so the first try_wait() inside the function detects it immediately.
        let _ = child.wait().await;

        let port = find_available_port().unwrap();
        let result = wait_for_ready(&mut child, port, Duration::from_secs(5)).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn spawn_mitmdump_passes_usage_state_id_option() {
        let dir = tempfile::tempdir().unwrap();
        let fake_mitmdump = dir.path().join("fake-mitmdump");
        write_fake_listening_mitmdump(&fake_mitmdump);

        let config = ProxyConfig {
            mitmdump_bin: fake_mitmdump.clone(),
            ca_dir: dir.path().join("ca"),
            addon_dir: dir.path().join("addon"),
            registry_path: dir.path().join("proxy-registry.json"),
            registry_lock_path: dir.path().join("proxy-registry.json.lock"),
            api_url: None,
        };
        let (crash_tx, _crash_rx) = mpsc::channel(1);
        let stopping = Arc::new(AtomicBool::new(false));
        let port = find_available_port().unwrap();

        let mut child = spawn_mitmdump(&config, port, &crash_tx, &stopping, "usage-state-test")
            .await
            .unwrap();
        stopping.store(true, Ordering::Release);
        let _ = child.kill().await;

        let args = std::fs::read_to_string(fake_mitmdump.with_extension("args")).unwrap();
        assert!(
            args.lines()
                .any(|arg| arg == "vm0_usage_state_id=usage-state-test"),
            "mitmdump args should include vm0_usage_state_id option; got:\n{args}",
        );
    }

    #[tokio::test]
    async fn spawn_mitmdump_kills_child_when_handle_is_dropped() {
        let dir = tempfile::tempdir().unwrap();
        let fake_mitmdump = dir.path().join("fake-mitmdump");
        write_fake_listening_mitmdump(&fake_mitmdump);

        let config = ProxyConfig {
            mitmdump_bin: fake_mitmdump,
            ca_dir: dir.path().join("ca"),
            addon_dir: dir.path().join("addon"),
            registry_path: dir.path().join("proxy-registry.json"),
            registry_lock_path: dir.path().join("proxy-registry.json.lock"),
            api_url: None,
        };
        let (crash_tx, _crash_rx) = mpsc::channel(1);
        let stopping = Arc::new(AtomicBool::new(false));
        let port = find_available_port().unwrap();

        let child = spawn_mitmdump(&config, port, &crash_tx, &stopping, "usage-state-test")
            .await
            .unwrap();
        let pid = nix::unistd::Pid::from_raw(child.id().unwrap() as i32);
        stopping.store(true, Ordering::Release);
        drop(child);

        assert!(
            wait_for_reaped_pid(pid).await,
            "dropping mitmdump Child should kill and reap the process"
        );
    }

    #[tokio::test]
    async fn usage_flush_target_returns_target_for_running_child() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let child = tokio::process::Command::new("sleep")
            .arg("60")
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();
        proxy.child = Some(child);

        assert!(proxy.usage_flush_target().is_some());

        proxy.stop().await.unwrap();
    }

    #[tokio::test]
    async fn usage_flush_target_skips_exited_child() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let mut child = tokio::process::Command::new("true")
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();
        child.wait().await.unwrap();
        proxy.child = Some(child);

        assert!(proxy.usage_flush_target().is_none());
        assert!(proxy.child.is_none());
    }

    fn usage_target() -> UsageFlushTarget {
        UsageFlushTarget {
            expected_usage_state_id: "state-test".to_string(),
            usage_state_started_at_ms: 1_770_000_000_000,
        }
    }

    fn usage_state(flows: u32, reports: u32) -> String {
        serde_json::json!({
            "version": 1,
            "pid": 1234,
            "usageStateId": "state-test",
            "updatedAtMs": 1_770_000_000_001u64,
            "flows": flows,
            "reports": reports,
        })
        .to_string()
    }

    #[tokio::test]
    async fn wait_usage_flush_returns_true_when_zero() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        std::fs::write(dir.path().join("usage-pending"), usage_state(0, 0)).unwrap();
        assert!(wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_times_out_when_file_missing() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_waits_for_state_file_to_appear() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        let path = dir.path().join("usage-pending");

        let p = path.clone();
        let handle = tokio::spawn(async move {
            tokio::time::sleep(Duration::from_millis(500)).await;
            std::fs::write(&p, usage_state(0, 0)).unwrap();
        });

        let d = dir.path().to_path_buf();
        assert!(wait_usage_flush(&d, Duration::from_secs(5), &target).await);
        handle.await.unwrap();
    }

    #[tokio::test]
    async fn wait_usage_flush_waits_until_zero() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        let path = dir.path().join("usage-pending");
        std::fs::write(&path, usage_state(2, 1)).unwrap();

        let p = path.clone();
        let handle = tokio::spawn(async move {
            tokio::time::sleep(Duration::from_millis(500)).await;
            std::fs::write(&p, usage_state(0, 0)).unwrap();
        });

        let d = dir.path().to_path_buf();
        assert!(wait_usage_flush(&d, Duration::from_secs(5), &target).await);
        handle.await.unwrap();
    }

    #[tokio::test]
    async fn wait_usage_flush_timeout() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        std::fs::write(dir.path().join("usage-pending"), usage_state(1, 3)).unwrap();
        // Very short timeout — should return false.
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_times_out_on_corrupt_file() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        std::fs::write(dir.path().join("usage-pending"), "garbage").unwrap();
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_times_out_on_empty_file() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        std::fs::write(dir.path().join("usage-pending"), "").unwrap();
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_rejects_unknown_field() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        let state = serde_json::json!({
            "version": 1,
            "pid": 1234,
            "usageStateId": "state-test",
            "updatedAtMs": 1_770_000_000_001u64,
            "flows": 0,
            "reports": 0,
            "extraField": "unexpected",
        });
        std::fs::write(dir.path().join("usage-pending"), state.to_string()).unwrap();
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_rejects_unsupported_version() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        let state = serde_json::json!({
            "version": 2,
            "pid": 1234,
            "usageStateId": "state-test",
            "updatedAtMs": 1_770_000_000_001u64,
            "flows": 0,
            "reports": 0,
        });
        std::fs::write(dir.path().join("usage-pending"), state.to_string()).unwrap();
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_rejects_missing_required_field() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        let state = serde_json::json!({
            "version": 1,
            "pid": 1234,
            "usageStateId": "state-test",
            "updatedAtMs": 1_770_000_000_001u64,
            "flows": 0,
        });
        std::fs::write(dir.path().join("usage-pending"), state.to_string()).unwrap();
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_rejects_wrong_usage_state_id() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        let state = serde_json::json!({
            "version": 1,
            "pid": 1234,
            "usageStateId": "old-state",
            "updatedAtMs": 1_770_000_000_001u64,
            "flows": 0,
            "reports": 0,
        });
        std::fs::write(dir.path().join("usage-pending"), state.to_string()).unwrap();
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_allows_wrapper_pid_mismatch() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        let state = serde_json::json!({
            "version": 1,
            "pid": 5678,
            "usageStateId": "state-test",
            "updatedAtMs": 1_770_000_000_001u64,
            "flows": 0,
            "reports": 0,
        });
        std::fs::write(dir.path().join("usage-pending"), state.to_string()).unwrap();
        assert!(wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_rejects_stale_state() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        let state = serde_json::json!({
            "version": 1,
            "pid": 1234,
            "usageStateId": "state-test",
            "updatedAtMs": 1_769_000_000_000u64,
            "flows": 0,
            "reports": 0,
        });
        std::fs::write(dir.path().join("usage-pending"), state.to_string()).unwrap();
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_rejects_future_state() {
        let dir = tempfile::tempdir().unwrap();
        let target = usage_target();
        let state = serde_json::json!({
            "version": 1,
            "pid": 1234,
            "usageStateId": "state-test",
            "updatedAtMs": now_millis() + USAGE_PENDING_CLOCK_SKEW.as_millis() as u64 + 60_000,
            "flows": 0,
            "reports": 0,
        });
        std::fs::write(dir.path().join("usage-pending"), state.to_string()).unwrap();
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(50), &target).await);
    }

    /// Regression for #10624: `begin_restart` must lock the old
    /// monitor's `stopping` at `true` and hand the caller a fresh
    /// `Arc<AtomicBool>` for the next child. If the old flag were
    /// shared across the restart boundary, the old stdout monitor
    /// could race in after `kill().await` returned, read `stopping ==
    /// false`, and emit a spurious crash notification.
    #[tokio::test]
    async fn begin_restart_isolates_stopping_flag_per_child() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let old_stopping = Arc::clone(&proxy.stopping);

        let params = proxy.begin_restart().await;

        // Old flag is now permanently `true`; any task still holding
        // `old_stopping` (the old monitor) will observe graceful
        // shutdown semantics regardless of when it wakes up.
        assert!(old_stopping.load(Ordering::Acquire));

        // The next child's monitor starts from a clean slate.
        assert!(!params.stopping.load(Ordering::Acquire));

        // And the proxy holds that same fresh `Arc` — so subsequent
        // `stop()` / `Drop` calls operate on the new child, not the
        // already-silenced old one.
        assert!(Arc::ptr_eq(&proxy.stopping, &params.stopping));
        assert!(!Arc::ptr_eq(&old_stopping, &params.stopping));
    }

    /// `spawn_mitmdump` can fail (e.g. port still in use), leaving the
    /// caller to retry without ever calling `complete_restart`. Each
    /// `begin_restart` in that retry chain must still hand out a fresh
    /// `Arc` and lock every previous one — otherwise a stale flag
    /// could be reset on the next round, resurrecting the race.
    #[tokio::test]
    async fn repeated_begin_restart_produces_independent_flags() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();

        let first = proxy.begin_restart().await;
        let second = proxy.begin_restart().await;
        let third = proxy.begin_restart().await;

        // Every handed-out Arc is distinct.
        assert!(!Arc::ptr_eq(&first.stopping, &second.stopping));
        assert!(!Arc::ptr_eq(&second.stopping, &third.stopping));
        assert!(!Arc::ptr_eq(&first.stopping, &third.stopping));

        // Superseded flags are permanently locked; only the most
        // recent one remains mutable.
        assert!(first.stopping.load(Ordering::Acquire));
        assert!(second.stopping.load(Ordering::Acquire));
        assert!(!third.stopping.load(Ordering::Acquire));
        assert!(Arc::ptr_eq(&proxy.stopping, &third.stopping));
    }

    /// `stop()` must set the *current* child's flag, not the one just
    /// superseded by `begin_restart`. A regression here would make
    /// `stop()` a silent no-op (the old Arc is already `true`), while
    /// the new child's monitor — which is what `stop()` exists to
    /// silence — would keep reading `false`.
    #[tokio::test]
    async fn stop_after_begin_restart_targets_current_flag() {
        let (mut proxy, _crash_rx) = MitmProxy::noop();
        let params = proxy.begin_restart().await;
        let current = Arc::clone(&params.stopping);
        assert!(!current.load(Ordering::Acquire));

        proxy.stop().await.unwrap();

        assert!(current.load(Ordering::Acquire));
    }
}
