use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

use serde::{Deserialize, Serialize};
use tokio::io::AsyncBufReadExt;
use tokio::sync::mpsc;
use tracing::{info, warn};

use crate::error::{RunnerError, RunnerResult};
use crate::lock;
use crate::types::{Firewall, NetworkPolicy};

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ProxyRegistry {
    vms: HashMap<String, VmEntry>,
    updated_at: i64,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct VmEntry {
    run_id: String,
    sandbox_token: String,
    registered_at: i64,
    network_log_path: String,
    proxy_log_path: String,
    firewalls: Option<Vec<Firewall>>,
    network_policies: Option<HashMap<String, NetworkPolicy>>,
    encrypted_secrets: Option<String>,
    secret_connector_map: Option<HashMap<String, String>>,
    vars: Option<HashMap<String, String>>,
    #[serde(default)]
    capture_network_bodies: bool,
}

/// Parameters for registering a VM in the proxy registry.
#[derive(Debug)]
pub struct VmRegistration<'a> {
    pub run_id: &'a str,
    pub sandbox_token: &'a str,
    pub network_log_path: &'a std::path::Path,
    pub proxy_log_path: &'a std::path::Path,
    pub firewalls: Option<&'a [Firewall]>,
    pub network_policies: Option<&'a HashMap<String, NetworkPolicy>>,
    pub encrypted_secrets: Option<&'a str>,
    pub secret_connector_map: Option<&'a HashMap<String, String>>,
    pub vars: Option<&'a HashMap<String, String>>,
    pub capture_network_bodies: bool,
}

// Embedded mitmproxy addon files (auto-generated by build.rs from mitm-addon/src/*.py).
include!(concat!(env!("OUT_DIR"), "/addon_files.rs"));

/// Timeout for waiting for mitmdump to become ready after spawn.
const READY_TIMEOUT: Duration = Duration::from_secs(10);

/// Timeout for graceful shutdown before SIGKILL.
///
/// Must be long enough for `done()` in the mitmproxy addon to flush
/// all in-flight usage reports (each POST has a 10 s HTTP timeout).
const STOP_TIMEOUT: Duration = Duration::from_secs(15);

/// Maximum time to wait for pending usage reports to flush before stopping.
///
/// The runner polls `{addon_dir}/usage-pending` (written by the Python
/// addon) and waits until both counters reach zero or this timeout expires.
/// 30 s is generous for worst-case webhook delivery (10 s timeout × 2
/// retries = 20.5 s) with headroom for mitmproxy event-loop drain.
pub const USAGE_FLUSH_TIMEOUT: Duration = Duration::from_secs(30);

/// Poll interval when waiting for usage flush.
const USAGE_FLUSH_POLL: Duration = Duration::from_millis(200);

/// Configuration for starting the proxy.
#[derive(Clone)]
pub struct ProxyConfig {
    /// Path to the mitmdump binary.
    pub mitmdump_bin: PathBuf,
    /// Directory containing mitmproxy CA files (mitmproxy-ca.pem).
    pub ca_dir: PathBuf,
    /// Directory where addon scripts will be written.
    pub addon_dir: PathBuf,
    /// Path where the proxy registry JSON will be written.
    pub registry_path: PathBuf,
    /// Lock file path for coordinating concurrent registry access.
    pub registry_lock_path: PathBuf,
    /// VM0 API URL passed to the addon (optional).
    pub api_url: Option<String>,
}

/// Manages the mitmdump process lifecycle and proxy registry.
pub struct MitmProxy {
    port: u16,
    config: ProxyConfig,
    child: Option<tokio::process::Child>,
    /// Sender used by the stdout monitor task to signal unexpected exit.
    crash_tx: mpsc::Sender<()>,
    /// Set to `true` during graceful `stop()` / `Drop` to suppress crash notifications.
    stopping: Arc<AtomicBool>,
}

impl MitmProxy {
    /// Prepare the proxy: allocate a port, write addon script and empty registry.
    ///
    /// Returns `(proxy, crash_rx)`. The caller should select on `crash_rx` to
    /// detect unexpected mitmdump exits and trigger a restart.
    pub async fn new(config: ProxyConfig) -> RunnerResult<(Self, mpsc::Receiver<()>)> {
        let port = find_available_port()?;

        // Write addon scripts to directory.
        // Remove-and-recreate to purge stale files from previous binary versions
        // (e.g. a renamed module would leave an orphan .py that Python could import).
        let _ = tokio::fs::remove_dir_all(&config.addon_dir).await;
        tokio::fs::create_dir_all(&config.addon_dir)
            .await
            .map_err(|e| RunnerError::Internal(format!("create addon dir: {e}")))?;
        for (name, content) in ADDON_FILES {
            tokio::fs::write(config.addon_dir.join(name), content)
                .await
                .map_err(|e| RunnerError::Internal(format!("write addon {name}: {e}")))?;
        }

        // Write empty registry file.
        let empty_registry = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&config.registry_path, &empty_registry).await?;

        let (crash_tx, crash_rx) = mpsc::channel(1);

        Ok((
            Self {
                port,
                config,
                child: None,
                crash_tx,
                stopping: Arc::new(AtomicBool::new(false)),
            },
            crash_rx,
        ))
    }

    /// Spawn the mitmdump process.
    pub async fn start(&mut self) -> RunnerResult<()> {
        let child = spawn_mitmdump(&self.config, self.port, &self.crash_tx, &self.stopping).await?;
        self.child = Some(child);
        info!(port = self.port, "mitmdump started");
        Ok(())
    }

    /// The port mitmdump is listening on.
    pub fn port(&self) -> u16 {
        self.port
    }

    /// Create a cloneable handle for registry operations (register/unregister VMs).
    ///
    /// The handle is `Clone + Send + Sync` and uses file locking for concurrent
    /// access, making it safe to share across executor tasks.
    pub fn registry_handle(&self) -> ProxyRegistryHandle {
        ProxyRegistryHandle {
            registry_path: self.config.registry_path.clone(),
            lock_path: self.config.registry_lock_path.clone(),
        }
    }

    /// Register a VM in the proxy registry so the addon can identify its traffic.
    pub async fn register_vm(
        &self,
        source_ip: &str,
        registration: &VmRegistration<'_>,
    ) -> RunnerResult<()> {
        self.registry_handle()
            .register_vm(source_ip, registration)
            .await
    }

    /// Unregister a VM from the proxy registry.
    pub async fn unregister_vm(&self, source_ip: &str) -> RunnerResult<()> {
        self.registry_handle().unregister_vm(source_ip).await
    }

    /// Prepare for restart: reset `stopping`, kill any lingering child, and
    /// return the parameters needed for [`spawn_mitmdump`].
    ///
    /// The caller should spawn the mitmdump process (potentially in a
    /// background task) and then call [`complete_restart`] with the result.
    pub async fn begin_restart(&mut self) -> MitmRestartParams {
        self.stopping.store(false, Ordering::Release);
        // Kill old child if somehow still running.
        if let Some(ref mut child) = self.child {
            let _ = child.kill().await;
            self.child = None;
        }
        MitmRestartParams {
            config: self.config.clone(),
            port: self.port,
            crash_tx: self.crash_tx.clone(),
            stopping: Arc::clone(&self.stopping),
        }
    }

    /// Finish a restart by storing the newly spawned child process.
    pub fn complete_restart(&mut self, child: tokio::process::Child) {
        self.child = Some(child);
    }

    /// Gracefully stop mitmdump (SIGTERM → timeout → SIGKILL).
    pub async fn stop(&mut self) -> RunnerResult<()> {
        self.stopping.store(true, Ordering::Release);
        let Some(ref mut child) = self.child else {
            return Ok(());
        };
        info!("stopping mitmdump");
        send_sigterm(child);

        match tokio::time::timeout(STOP_TIMEOUT, child.wait()).await {
            Ok(Ok(status)) => {
                info!(code = status.code(), "mitmdump stopped");
            }
            Ok(Err(e)) => {
                warn!(error = %e, "mitmdump wait failed");
            }
            Err(_) => {
                warn!("mitmdump did not exit in time, sending SIGKILL");
                let _ = child.kill().await;
            }
        }
        self.child = None;
        Ok(())
    }
}

/// Wait for all pending proxy usage reports to be delivered.
///
/// The Python addon writes `<flows>:<reports>` to `{addon_dir}/usage-pending`
/// where `flows` is the number of in-flight model-provider HTTP flows and
/// `reports` is the number of usage webhook POSTs in the thread pool.
///
/// Returns `true` if both counters reached zero, `false` on timeout.
/// Missing or unreadable file is treated as zero (old addon version or
/// no reports were ever submitted).
pub async fn wait_usage_flush(addon_dir: &Path, timeout: Duration) -> bool {
    let path = addon_dir.join("usage-pending");
    let deadline = tokio::time::Instant::now() + timeout;
    loop {
        match tokio::fs::read_to_string(&path).await {
            Ok(s) => {
                let trimmed = s.trim();
                if trimmed == "0:0" || trimmed == "0" {
                    return true;
                }
                // Verify the file contains a valid "<flows>:<reports>" pair.
                // If unparseable (corrupt file, future format change), treat
                // as zero to avoid blocking shutdown for 30 s on stale data.
                let parseable = if let Some((flows, reports)) = trimmed.split_once(':') {
                    flows.parse::<u32>().is_ok() && reports.parse::<u32>().is_ok()
                } else {
                    trimmed.parse::<u32>().is_ok()
                };
                if !parseable {
                    warn!(
                        content = trimmed,
                        "usage-pending file has unparseable content, treating as flushed"
                    );
                    return true;
                }
            }
            // File missing = no reports were ever submitted (or old addon).
            Err(_) => return true,
        }
        if tokio::time::Instant::now() >= deadline {
            warn!(
                timeout_secs = timeout.as_secs(),
                "usage flush timed out, proceeding with proxy stop"
            );
            return false;
        }
        tokio::time::sleep(USAGE_FLUSH_POLL).await;
    }
}

#[cfg(test)]
impl MitmProxy {
    /// Create a noop proxy for testing. No real process is spawned.
    ///
    /// `stop()` already handles `child: None` (returns immediately),
    /// and `begin_restart()` is never triggered because the test holds
    /// the crash channel sender and never sends on it.
    pub fn noop() -> (Self, mpsc::Receiver<()>) {
        let (crash_tx, crash_rx) = mpsc::channel(1);
        (
            Self {
                port: 0,
                config: ProxyConfig {
                    mitmdump_bin: std::path::PathBuf::new(),
                    ca_dir: std::path::PathBuf::new(),
                    addon_dir: std::path::PathBuf::new(),
                    registry_path: std::path::PathBuf::new(),
                    registry_lock_path: std::path::PathBuf::new(),
                    api_url: None,
                },
                child: None,
                crash_tx,
                stopping: Arc::new(AtomicBool::new(false)),
            },
            crash_rx,
        )
    }
}

impl Drop for MitmProxy {
    fn drop(&mut self) {
        self.stopping.store(true, Ordering::Release);
        // Best-effort kill if still running.
        if let Some(ref mut child) = self.child {
            let _ = child.start_kill();
        }
    }
}

/// Parameters needed to spawn a mitmdump process, returned by
/// [`MitmProxy::begin_restart`]. All fields are owned/cloned so the spawn
/// can happen in a background task without borrowing `MitmProxy`.
pub(crate) struct MitmRestartParams {
    config: ProxyConfig,
    port: u16,
    crash_tx: mpsc::Sender<()>,
    stopping: Arc<AtomicBool>,
}

impl MitmRestartParams {
    /// Spawn mitmdump using these parameters. Suitable for `tokio::spawn`.
    pub(crate) async fn spawn(self) -> RunnerResult<tokio::process::Child> {
        spawn_mitmdump(&self.config, self.port, &self.crash_tx, &self.stopping).await
    }
}

/// Spawn a mitmdump process, wire up stdout/stderr monitors, and wait for
/// it to become ready. This is a free function so it can run in a
/// `tokio::spawn` without borrowing `MitmProxy`.
pub(crate) async fn spawn_mitmdump(
    config: &ProxyConfig,
    port: u16,
    crash_tx: &mpsc::Sender<()>,
    stopping: &Arc<AtomicBool>,
) -> RunnerResult<tokio::process::Child> {
    let mut cmd = tokio::process::Command::new(&config.mitmdump_bin);
    cmd.arg("--mode")
        .arg("transparent")
        .arg("--listen-port")
        .arg(port.to_string())
        .arg("--set")
        .arg(format!("confdir={}", config.ca_dir.display()))
        .arg("--set")
        .arg(format!(
            "vm0_proxy_registry_path={}",
            config.registry_path.display()
        ))
        .arg("--scripts")
        .arg(config.addon_dir.join("mitm_addon.py"))
        .arg("--set")
        .arg("flow_detail=0")
        .arg("--set")
        .arg("termlog_verbosity=warn")
        .arg("--set")
        .arg(format!(
            "ssl_verify_upstream_trusted_ca={}",
            crate::deps::SYSTEM_CA_BUNDLE
        ));
    if let Some(url) = &config.api_url {
        cmd.arg("--set").arg(format!("vm0_api_url={url}"));
    }
    cmd.stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped());

    // SAFETY: `set_pdeathsig` calls `prctl(PR_SET_PDEATHSIG)` which is
    // async-signal-safe. This ensures the kernel sends SIGKILL to the
    // mitmdump child when the parent runner process dies, preventing
    // orphaned processes after runner crashes or restarts.
    unsafe {
        cmd.pre_exec(|| {
            nix::sys::prctl::set_pdeathsig(nix::sys::signal::Signal::SIGKILL)
                .map_err(std::io::Error::from)
        });
    }

    info!(port, bin = %config.mitmdump_bin.display(), "starting mitmdump");

    let mut child = cmd
        .spawn()
        .map_err(|e| RunnerError::Internal(format!("spawn mitmdump: {e}")))?;

    // Stream stdout to tracing; when the pipe closes (process exited),
    // send a crash notification unless we're in a graceful stop.
    if let Some(stdout) = child.stdout.take() {
        let crash_tx = crash_tx.clone();
        let stopping = Arc::clone(stopping);
        tokio::spawn(async move {
            let mut lines = tokio::io::BufReader::new(stdout).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                if !line.is_empty() {
                    info!(target: "mitmdump", "{line}");
                }
            }
            // Pipe closed — process exited.
            if !stopping.load(Ordering::Acquire) {
                let _ = crash_tx.send(()).await;
            }
        });
    }
    if let Some(stderr) = child.stderr.take() {
        tokio::spawn(async move {
            let mut lines = tokio::io::BufReader::new(stderr).lines();
            while let Ok(Some(line)) = lines.next_line().await {
                if !line.is_empty() {
                    warn!(target: "mitmdump", "stderr: {line}");
                }
            }
        });
    }

    // Wait for process to be alive (poll liveness).
    if let Err(e) = wait_for_ready(&mut child, port, READY_TIMEOUT).await {
        stopping.store(true, Ordering::Release);
        let _ = child.kill().await;
        return Err(e);
    }

    Ok(child)
}

/// Wait for mitmdump to start listening on `port` (TCP connect probe).
async fn wait_for_ready(
    child: &mut tokio::process::Child,
    port: u16,
    timeout: Duration,
) -> RunnerResult<()> {
    let poll_interval = Duration::from_millis(200);
    let start = std::time::Instant::now();
    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));

    while start.elapsed() < timeout {
        // Check if process died.
        match child.try_wait() {
            Ok(Some(status)) => {
                return Err(RunnerError::Internal(format!(
                    "mitmdump exited immediately with {}",
                    status
                        .code()
                        .map_or("unknown".to_string(), |c| c.to_string()),
                )));
            }
            Ok(None) => {}
            Err(e) => {
                return Err(RunnerError::Internal(format!(
                    "mitmdump process check: {e}"
                )));
            }
        }
        // Probe TCP port.
        if tokio::net::TcpStream::connect(addr).await.is_ok() {
            return Ok(());
        }
        tokio::time::sleep(poll_interval).await;
    }

    Err(RunnerError::Internal(format!(
        "mitmdump did not start listening on port {port} within {}s",
        timeout.as_secs()
    )))
}

/// Find an available TCP port by binding to port 0.
fn find_available_port() -> RunnerResult<u16> {
    let listener = std::net::TcpListener::bind("0.0.0.0:0")
        .map_err(|e| RunnerError::Internal(format!("bind port 0: {e}")))?;
    let port = listener
        .local_addr()
        .map_err(|e| RunnerError::Internal(format!("local_addr: {e}")))?
        .port();
    Ok(port)
}

/// Read the proxy registry JSON file.
async fn read_registry(path: &std::path::Path) -> RunnerResult<ProxyRegistry> {
    let content = tokio::fs::read_to_string(path)
        .await
        .map_err(|e| RunnerError::Internal(format!("read registry: {e}")))?;
    serde_json::from_str(&content)
        .map_err(|e| RunnerError::Internal(format!("parse registry: {e}")))
}

/// Write the proxy registry JSON file atomically (write tmp + rename).
///
/// This ensures the Python mitm-addon never reads a partially-written file.
async fn write_registry(path: &std::path::Path, value: &ProxyRegistry) -> RunnerResult<()> {
    let content = serde_json::to_string(value)
        .map_err(|e| RunnerError::Internal(format!("serialize registry: {e}")))?;
    let tmp = path.with_extension("json.tmp");
    tokio::fs::write(&tmp, content)
        .await
        .map_err(|e| RunnerError::Internal(format!("write registry tmp: {e}")))?;
    tokio::fs::rename(&tmp, path)
        .await
        .map_err(|e| RunnerError::Internal(format!("rename registry: {e}")))
}

/// Lightweight, cloneable handle for proxy registry operations.
///
/// Uses file locking (`flock`) to ensure concurrent register/unregister calls
/// from multiple executor tasks don't corrupt the registry JSON.
#[derive(Clone)]
pub struct ProxyRegistryHandle {
    registry_path: PathBuf,
    lock_path: PathBuf,
}

impl ProxyRegistryHandle {
    /// Create a handle from explicit paths (for testing).
    #[cfg(test)]
    pub fn new(registry_path: PathBuf, lock_path: PathBuf) -> Self {
        Self {
            registry_path,
            lock_path,
        }
    }

    /// Register a VM in the proxy registry.
    pub async fn register_vm(
        &self,
        source_ip: &str,
        registration: &VmRegistration<'_>,
    ) -> RunnerResult<()> {
        let _guard = lock::acquire(self.lock_path.clone()).await?;

        let mut registry = read_registry(&self.registry_path).await?;
        let now = chrono::Utc::now().timestamp_millis();
        let firewalls = registration.firewalls.map(|s| {
            let mut s = s.to_vec();
            let mut idx = 0usize;
            for entry in &mut s {
                for api in &mut entry.apis {
                    if api.id.is_empty() {
                        api.id = format!("{}:{}", registration.run_id, idx);
                    }
                    idx += 1;
                }
            }
            s
        });
        registry.vms.insert(
            source_ip.to_string(),
            VmEntry {
                run_id: registration.run_id.to_string(),
                sandbox_token: registration.sandbox_token.to_string(),
                registered_at: now,
                network_log_path: registration.network_log_path.to_string_lossy().into_owned(),
                proxy_log_path: registration.proxy_log_path.to_string_lossy().into_owned(),
                firewalls,
                network_policies: registration.network_policies.cloned(),
                encrypted_secrets: registration.encrypted_secrets.map(String::from),
                secret_connector_map: registration.secret_connector_map.cloned(),
                vars: registration.vars.cloned(),
                capture_network_bodies: registration.capture_network_bodies,
            },
        );
        registry.updated_at = now;
        write_registry(&self.registry_path, &registry).await?;
        info!(
            source_ip,
            run_id = registration.run_id,
            "registered VM in proxy registry"
        );
        Ok(())
    }

    /// Unregister a VM from the proxy registry.
    pub async fn unregister_vm(&self, source_ip: &str) -> RunnerResult<()> {
        let _guard = lock::acquire(self.lock_path.clone()).await?;

        let mut registry = read_registry(&self.registry_path).await?;
        registry.vms.remove(source_ip);
        registry.updated_at = chrono::Utc::now().timestamp_millis();
        write_registry(&self.registry_path, &registry).await?;
        info!(source_ip, "unregistered VM from proxy registry");
        Ok(())
    }
}

/// Send SIGTERM to a child process.
fn send_sigterm(child: &tokio::process::Child) {
    if let Some(pid) = child.id() {
        let _ = nix::sys::signal::kill(
            nix::unistd::Pid::from_raw(pid as i32),
            nix::sys::signal::Signal::SIGTERM,
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{FirewallApi, FirewallAuth, FirewallPermission};

    #[test]
    fn find_port_returns_nonzero() {
        let port = find_available_port().unwrap();
        assert!(port > 0, "expected non-zero port, got {port}");
    }

    #[test]
    fn addon_scripts_are_embedded() {
        let files: Vec<&str> = ADDON_FILES.iter().map(|(name, _)| *name).collect();

        // All expected modules must be present.
        for expected in [
            "mitm_addon.py",
            "auth.py",
            "body_utils.py",
            "matching.py",
            "url_utils.py",
            "logging_utils.py",
            "usage.py",
        ] {
            assert!(
                files.contains(&expected),
                "addon files should include {expected}, got: {files:?}"
            );
        }

        let (_, content) = ADDON_FILES
            .iter()
            .find(|(name, _)| *name == "mitm_addon.py")
            .unwrap();
        assert!(
            content.contains("mitmproxy addon"),
            "mitm_addon.py should contain expected header"
        );
    }

    #[tokio::test]
    async fn registry_register_and_unregister() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        // Register a VM.
        let mut registry = read_registry(&registry_path).await.unwrap();
        registry.vms.insert(
            "10.200.0.2".to_string(),
            VmEntry {
                run_id: "test-run".to_string(),
                sandbox_token: String::new(),
                registered_at: 1000,
                network_log_path: "/tmp/network-test-run.jsonl".to_string(),
                proxy_log_path: "/tmp/proxy-test-run.jsonl".to_string(),
                firewalls: None,
                network_policies: None,
                encrypted_secrets: None,
                secret_connector_map: None,
                vars: None,
                capture_network_bodies: false,
            },
        );
        write_registry(&registry_path, &registry).await.unwrap();

        // Verify registration.
        let loaded = read_registry(&registry_path).await.unwrap();
        let vm = loaded.vms.get("10.200.0.2").unwrap();
        assert_eq!(vm.run_id, "test-run");

        // Unregister the VM.
        let mut registry = read_registry(&registry_path).await.unwrap();
        registry.vms.remove("10.200.0.2");
        write_registry(&registry_path, &registry).await.unwrap();

        // Verify unregistration.
        let loaded = read_registry(&registry_path).await.unwrap();
        assert!(
            !loaded.vms.contains_key("10.200.0.2"),
            "VM should be removed from registry"
        );
    }

    #[tokio::test]
    async fn registry_handle_register_and_unregister() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.json.lock");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        // Register via handle.
        let registration = VmRegistration {
            run_id: "run-1",
            sandbox_token: "tok-1",
            network_log_path: std::path::Path::new("/tmp/network-run-1.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-1.jsonl"),
            firewalls: None,
            network_policies: None,
            encrypted_secrets: None,
            secret_connector_map: None,
            vars: None,
            capture_network_bodies: false,
        };
        handle
            .register_vm("10.200.0.2", &registration)
            .await
            .unwrap();

        let loaded = read_registry(&registry_path).await.unwrap();
        let vm = loaded.vms.get("10.200.0.2").unwrap();
        assert_eq!(vm.run_id, "run-1");

        // Re-register same IP overwrites the entry.
        let registration2 = VmRegistration {
            run_id: "run-2",
            sandbox_token: "tok-2",
            network_log_path: std::path::Path::new("/tmp/network-run-2.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-2.jsonl"),
            firewalls: None,
            network_policies: None,
            encrypted_secrets: None,
            secret_connector_map: None,
            vars: None,
            capture_network_bodies: false,
        };
        handle
            .register_vm("10.200.0.2", &registration2)
            .await
            .unwrap();
        let loaded = read_registry(&registry_path).await.unwrap();
        let vm = loaded.vms.get("10.200.0.2").unwrap();
        assert_eq!(vm.run_id, "run-2");

        // Unregister via handle.
        handle.unregister_vm("10.200.0.2").await.unwrap();

        let loaded = read_registry(&registry_path).await.unwrap();
        assert!(!loaded.vms.contains_key("10.200.0.2"));

        // Unregister non-existent IP is a no-op.
        handle.unregister_vm("10.200.0.99").await.unwrap();
    }

    #[tokio::test]
    async fn registry_handle_concurrent_access() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.json.lock");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        // Spawn 10 concurrent register tasks.
        let mut tasks = tokio::task::JoinSet::new();
        for i in 0..10 {
            let h = handle.clone();
            let ip = format!("10.200.0.{}", i + 2);
            let run_id_owned = format!("run-{i}");
            tasks.spawn(async move {
                let log_path =
                    std::path::PathBuf::from(format!("/tmp/network-{run_id_owned}.jsonl"));
                let proxy_path =
                    std::path::PathBuf::from(format!("/tmp/proxy-{run_id_owned}.jsonl"));
                let registration = VmRegistration {
                    run_id: &run_id_owned,
                    sandbox_token: "",
                    network_log_path: &log_path,
                    proxy_log_path: &proxy_path,
                    firewalls: None,
                    network_policies: None,
                    encrypted_secrets: None,
                    secret_connector_map: None,
                    vars: None,
                    capture_network_bodies: false,
                };
                h.register_vm(&ip, &registration).await.unwrap();
            });
        }
        while let Some(result) = tasks.join_next().await {
            result.unwrap();
        }

        // All 10 VMs should be registered (no lost updates).
        let loaded = read_registry(&registry_path).await.unwrap();
        assert_eq!(loaded.vms.len(), 10);
    }

    #[tokio::test]
    async fn registry_with_firewalls() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.json.lock");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        let firewall_entries = vec![Firewall {
            name: "gmail".to_string(),
            ref_key: "gmail".to_string(),
            apis: vec![FirewallApi {
                id: String::new(),
                base: "https://gmail.googleapis.com/gmail/v1/users/me".to_string(),
                auth: FirewallAuth {
                    headers: std::collections::HashMap::from([(
                        "Authorization".to_string(),
                        "Bearer ${{ secrets.GMAIL_TOKEN }}".to_string(),
                    )]),
                    base: None,
                    query: None,
                },
                permissions: Some(vec![FirewallPermission {
                    name: "mail-read".to_string(),
                    description: None,
                    rules: vec![
                        "GET /messages".to_string(),
                        "GET /messages/{id}".to_string(),
                    ],
                }]),
            }],
        }];

        let registration = VmRegistration {
            run_id: "run-fw",
            sandbox_token: "tok",
            network_log_path: std::path::Path::new("/tmp/network-run-fw.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-fw.jsonl"),
            firewalls: Some(&firewall_entries),
            network_policies: None,
            encrypted_secrets: None,
            secret_connector_map: None,
            vars: None,
            capture_network_bodies: false,
        };
        handle
            .register_vm("10.200.0.5", &registration)
            .await
            .unwrap();

        // Verify firewall entries are stored in registry.
        let loaded = read_registry(&registry_path).await.unwrap();
        let vm = loaded.vms.get("10.200.0.5").unwrap();
        let stored = vm.firewalls.as_ref().unwrap();
        assert_eq!(stored.len(), 1);
        assert_eq!(stored[0].apis.len(), 1);
        assert_eq!(
            stored[0].apis[0].base,
            "https://gmail.googleapis.com/gmail/v1/users/me"
        );

        // Verify id was assigned by register_vm: "{run_id}:{global_index}".
        assert_eq!(stored[0].apis[0].id, "run-fw:0");

        // Verify JSON shape matches what the Python addon expects.
        let raw = tokio::fs::read_to_string(&registry_path).await.unwrap();
        let value: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let vm_json = &value["vms"]["10.200.0.5"];
        let fw = &vm_json["firewalls"][0];
        assert_eq!(fw["name"], "gmail");
        assert_eq!(fw["ref"], "gmail");
        assert_eq!(
            fw["apis"][0]["base"],
            "https://gmail.googleapis.com/gmail/v1/users/me"
        );
        assert_eq!(fw["apis"][0]["id"], "run-fw:0");

        // Verify permissions are preserved in JSON for the Python addon.
        let perms = &fw["apis"][0]["permissions"];
        assert_eq!(perms[0]["name"], "mail-read");
        assert_eq!(perms[0]["rules"][0], "GET /messages");
        assert_eq!(perms[0]["rules"][1], "GET /messages/{id}");
    }

    #[tokio::test]
    async fn register_vm_stores_encrypted_secrets() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.lock");

        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        let registration = VmRegistration {
            run_id: "run-enc",
            sandbox_token: "tok",
            network_log_path: std::path::Path::new("/tmp/network-run-enc.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-enc.jsonl"),
            firewalls: None,
            network_policies: None,
            encrypted_secrets: Some("iv_b64:tag_b64:data_b64"),
            secret_connector_map: None,
            vars: None,
            capture_network_bodies: false,
        };
        handle
            .register_vm("10.200.0.6", &registration)
            .await
            .unwrap();

        let loaded = read_registry(&registry_path).await.unwrap();
        let vm = loaded.vms.get("10.200.0.6").unwrap();
        assert_eq!(
            vm.encrypted_secrets.as_deref(),
            Some("iv_b64:tag_b64:data_b64")
        );

        // Verify JSON key name matches what the Python addon expects.
        let raw = tokio::fs::read_to_string(&registry_path).await.unwrap();
        let value: serde_json::Value = serde_json::from_str(&raw).unwrap();
        assert_eq!(
            value["vms"]["10.200.0.6"]["encryptedSecrets"],
            "iv_b64:tag_b64:data_b64"
        );
    }

    #[tokio::test]
    async fn registry_firewall_auth_base_serialized() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.lock");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        let firewall_entries = vec![Firewall {
            name: "discord-webhook".to_string(),
            ref_key: "discord-webhook".to_string(),
            apis: vec![FirewallApi {
                id: String::new(),
                base: "https://firewall-placeholder.vm3.ai/discord-webhook/hook".to_string(),
                auth: FirewallAuth {
                    headers: std::collections::HashMap::new(),
                    base: Some("${{ secrets.DISCORD_WEBHOOK_URL }}".to_string()),
                    query: None,
                },
                permissions: None,
            }],
        }];

        let registration = VmRegistration {
            run_id: "run-webhook",
            sandbox_token: "tok",
            network_log_path: std::path::Path::new("/tmp/network-run-webhook.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-webhook.jsonl"),
            firewalls: Some(&firewall_entries),
            network_policies: None,
            encrypted_secrets: Some("enc_data"),
            secret_connector_map: None,
            vars: None,
            capture_network_bodies: false,
        };
        handle
            .register_vm("10.200.0.7", &registration)
            .await
            .unwrap();

        // Verify auth.base is preserved in the registry JSON.
        let raw = tokio::fs::read_to_string(&registry_path).await.unwrap();
        let value: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let api = &value["vms"]["10.200.0.7"]["firewalls"][0]["apis"][0];
        assert_eq!(api["auth"]["base"], "${{ secrets.DISCORD_WEBHOOK_URL }}");
        // headers should be empty object
        assert_eq!(api["auth"]["headers"], serde_json::json!({}));
    }

    #[tokio::test]
    async fn registry_firewall_auth_query_serialized() {
        let dir = tempfile::tempdir().unwrap();
        let registry_path = dir.path().join("proxy-registry.json");
        let lock_path = dir.path().join("proxy-registry.lock");
        let empty = ProxyRegistry {
            vms: HashMap::new(),
            updated_at: 0,
        };
        write_registry(&registry_path, &empty).await.unwrap();

        let handle = ProxyRegistryHandle {
            registry_path: registry_path.clone(),
            lock_path,
        };

        let firewall_entries = vec![Firewall {
            name: "serpapi".to_string(),
            ref_key: "serpapi".to_string(),
            apis: vec![FirewallApi {
                id: String::new(),
                base: "https://serpapi.com".to_string(),
                auth: FirewallAuth {
                    headers: std::collections::HashMap::new(),
                    base: None,
                    query: Some(
                        [(
                            "api_key".to_string(),
                            "${{ secrets.SERPAPI_TOKEN }}".to_string(),
                        )]
                        .into_iter()
                        .collect(),
                    ),
                },
                permissions: None,
            }],
        }];

        let registration = VmRegistration {
            run_id: "run-query-auth",
            sandbox_token: "tok",
            network_log_path: std::path::Path::new("/tmp/network-run-query.jsonl"),
            proxy_log_path: std::path::Path::new("/tmp/proxy-run-query.jsonl"),
            firewalls: Some(&firewall_entries),
            network_policies: None,
            encrypted_secrets: Some("enc_data"),
            secret_connector_map: None,
            vars: None,
            capture_network_bodies: false,
        };
        handle
            .register_vm("10.200.0.8", &registration)
            .await
            .unwrap();

        // Verify auth.query is preserved in the registry JSON.
        let raw = tokio::fs::read_to_string(&registry_path).await.unwrap();
        let value: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let api = &value["vms"]["10.200.0.8"]["firewalls"][0]["apis"][0];
        assert_eq!(
            api["auth"]["query"],
            serde_json::json!({"api_key": "${{ secrets.SERPAPI_TOKEN }}"})
        );
        // headers should be empty object, base should be absent
        assert_eq!(api["auth"]["headers"], serde_json::json!({}));
        assert_eq!(api["auth"]["base"], serde_json::Value::Null);
    }

    #[tokio::test]
    async fn wait_for_ready_returns_error_on_timeout() {
        // `sleep` never listens on TCP — guarantees timeout.
        let mut child = tokio::process::Command::new("sleep")
            .arg("60")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();

        let raw_pid = child.id().unwrap() as i32;
        let pid = nix::unistd::Pid::from_raw(raw_pid);
        let port = find_available_port().unwrap();

        let result = wait_for_ready(&mut child, port, Duration::from_millis(500)).await;
        assert!(result.is_err());

        // Process must still be alive — wait_for_ready does NOT kill on error.
        // This is the scenario that caused orphaned processes before the fix:
        // the caller (spawn_mitmdump) is responsible for killing.
        assert!(
            nix::sys::signal::kill(pid, None).is_ok(),
            "process should still be alive after timeout"
        );

        // Simulate spawn_mitmdump error path: kill the child.
        let _ = child.kill().await;

        assert!(
            nix::sys::signal::kill(pid, None).is_err(),
            "process should be dead after kill"
        );
    }

    #[tokio::test]
    async fn wait_for_ready_returns_error_on_early_exit() {
        // `true` exits immediately with status 0.
        let mut child = tokio::process::Command::new("true")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .unwrap();

        // Wait for `true` to actually exit before calling wait_for_ready,
        // so the first try_wait() inside the function detects it immediately.
        let _ = child.wait().await;

        let port = find_available_port().unwrap();
        let result = wait_for_ready(&mut child, port, Duration::from_secs(5)).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn wait_usage_flush_returns_true_when_zero() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("usage-pending"), "0:0").unwrap();
        assert!(wait_usage_flush(dir.path(), Duration::from_secs(1)).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_returns_true_when_file_missing() {
        let dir = tempfile::tempdir().unwrap();
        // No file written — should return true immediately.
        assert!(wait_usage_flush(dir.path(), Duration::from_secs(1)).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_waits_until_zero() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("usage-pending");
        std::fs::write(&path, "2:1").unwrap();

        let p = path.clone();
        let handle = tokio::spawn(async move {
            tokio::time::sleep(Duration::from_millis(500)).await;
            std::fs::write(&p, "0:0").unwrap();
        });

        let d = dir.path().to_path_buf();
        assert!(wait_usage_flush(&d, Duration::from_secs(5)).await);
        handle.await.unwrap();
    }

    #[tokio::test]
    async fn wait_usage_flush_timeout() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("usage-pending"), "1:3").unwrap();
        // Very short timeout — should return false.
        assert!(!wait_usage_flush(dir.path(), Duration::from_millis(300)).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_returns_true_on_corrupt_file() {
        let dir = tempfile::tempdir().unwrap();
        // Corrupt / unparseable content should not block shutdown.
        std::fs::write(dir.path().join("usage-pending"), "garbage").unwrap();
        assert!(wait_usage_flush(dir.path(), Duration::from_secs(1)).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_returns_true_on_empty_file() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("usage-pending"), "").unwrap();
        assert!(wait_usage_flush(dir.path(), Duration::from_secs(1)).await);
    }

    #[tokio::test]
    async fn wait_usage_flush_accepts_plain_zero() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("usage-pending"), "0").unwrap();
        assert!(wait_usage_flush(dir.path(), Duration::from_secs(1)).await);
    }
}
