use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Poll
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PollResponse {
    pub job: Option<Job>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Job {
    pub run_id: Uuid,
    #[serde(default)]
    pub experimental_profile: Option<String>,
}

// ---------------------------------------------------------------------------
// Claim (execution context)
// Keep in sync with TS: packages/core/src/contracts/runners.ts → executionContextSchema
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExecutionContext {
    pub run_id: Uuid,
    pub prompt: String,
    #[serde(default)]
    pub append_system_prompt: Option<String>,
    // Agent compose version ID (full SHA-256 content hash).
    // Deserialized for forward compatibility but not consumed by runner.
    #[serde(default, rename = "agentComposeVersionId")]
    pub _agent_compose_version_id: Option<String>,
    // Vars are passed to the proxy registry for auth header template resolution.
    #[serde(default)]
    pub vars: Option<HashMap<String, String>>,
    // Checkpoint resume not yet implemented
    #[allow(dead_code)]
    #[serde(default)]
    pub checkpoint_id: Option<Uuid>,
    pub sandbox_token: String,
    pub working_dir: String,
    #[serde(default)]
    pub storage_manifest: Option<StorageManifest>,
    #[serde(default)]
    pub environment: Option<HashMap<String, String>>,
    #[serde(default)]
    pub resume_session: Option<ResumeSession>,
    #[serde(default)]
    pub secret_values: Option<Vec<String>>,
    // Forwarded to mitm-addon via proxy registry for auth resolution
    #[serde(default)]
    pub encrypted_secrets: Option<String>,
    // Maps secret names to OAuth connector types for runtime token refresh
    #[serde(default)]
    pub secret_connector_map: Option<HashMap<String, String>>,
    pub cli_agent_type: String,
    #[serde(default)]
    pub debug_no_mock_claude: Option<bool>,
    #[serde(default)]
    pub api_start_time: Option<f64>,
    #[serde(default)]
    pub user_timezone: Option<String>,
    // Memory storage name for first-run init — not yet consumed by runner
    #[allow(dead_code)]
    #[serde(default)]
    pub memory_name: Option<String>,
    #[serde(default)]
    pub capture_network_bodies: Option<bool>,
    #[serde(default)]
    pub firewalls: Option<Vec<Firewall>>,
    #[serde(default)]
    pub network_policies: Option<std::collections::HashMap<String, NetworkPolicy>>,
    #[serde(default)]
    pub disallowed_tools: Option<Vec<String>>,
    #[serde(default)]
    pub tools: Option<Vec<String>>,
    #[serde(default)]
    pub settings: Option<String>,
    // Profile selection — handled by api provider at discover time, not read on ExecutionContext
    #[allow(dead_code)]
    #[serde(default)]
    pub experimental_profile: Option<String>,
    // Feature flags evaluated at job creation time (all switch states for user/org)
    #[serde(default)]
    pub feature_flags: Option<HashMap<String, bool>>,
}

/// A single firewall config with its name, ref key, and API entries.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Firewall {
    pub name: String,
    /// The ref key from vm0.yaml (e.g., "github", "slack").
    /// `ref` is a Rust keyword, so we rename via serde.
    #[serde(rename = "ref")]
    pub ref_key: String,
    pub apis: Vec<FirewallApi>,
}

/// A single firewall API entry with base URL and auth headers for proxy-side matching.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct FirewallApi {
    /// Unique identifier for cache keying in mitm-addon. Generated by the
    /// runner at registry-write time (not supplied by the web API).
    #[serde(default)]
    pub id: String,
    pub base: String,
    pub auth: FirewallAuth,
    #[serde(default)]
    pub permissions: Option<Vec<FirewallPermission>>,
}

/// A named permission group with matching rules for request authorization.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct FirewallPermission {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    pub rules: Vec<String>,
}

/// Auth configuration for a firewall API entry.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct FirewallAuth {
    pub headers: std::collections::HashMap<String, String>,
    /// Optional base URL template for URL rewriting (e.g. webhook-url connectors).
    /// When set, the proxy rewrites the request URL instead of injecting headers.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
}

/// Per-firewall grant configuration: which permissions are authorized and
/// what policy applies to unknown endpoints (not matching any rule).
/// Refs absent from the map are fully permissive (all granted + allow unknown).
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct NetworkPolicy {
    /// Permission names granted by the user.
    pub allow: Vec<String>,
    /// Permission names explicitly denied by the admin.
    pub deny: Vec<String>,
    /// Permission names requiring user approval before use.
    pub ask: Vec<String>,
    /// Policy for requests not matching any known permission rule.
    /// Values: "allow", "deny", "ask"
    pub unknown_policy: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StorageManifest {
    pub storages: Vec<StorageEntry>,
    #[serde(default)]
    pub artifact: Option<ArtifactEntry>,
    #[serde(default)]
    pub memory: Option<ArtifactEntry>,
    /// Paths to clean before downloading (computed from previous fingerprints).
    /// Used on VM reuse to remove stale files from changed/removed storages.
    #[serde(default)]
    pub cleanup_paths: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StorageEntry {
    pub mount_path: String,
    #[serde(default)]
    pub archive_url: Option<String>,
    #[serde(default)]
    pub vas_storage_name: Option<String>,
    #[serde(default)]
    pub vas_version_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ArtifactEntry {
    pub mount_path: String,
    #[serde(default)]
    pub archive_url: Option<String>,
    pub vas_storage_name: String,
    pub vas_version_id: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResumeSession {
    pub session_id: String,
    pub session_history: String,
}

impl ExecutionContext {
    /// Extract the session ID from `resume_session` for keep-alive VM reuse.
    ///
    /// Returns `Some` for continued sessions. For first runs this returns
    /// `None`; the executor reads the CLI-generated session ID from the
    /// guest filesystem post-execution (see `read_guest_session_id`).
    pub fn session_id(&self) -> Option<&str> {
        self.resume_session.as_ref().map(|r| r.session_id.as_str())
    }
}

// ---------------------------------------------------------------------------
// Heartbeat
// ---------------------------------------------------------------------------

/// Runner state snapshot sent to the server via heartbeat.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct HeartbeatState {
    pub runner_id: String,
    pub runner_name: String,
    pub group: String,
    pub profiles: Vec<String>,
    pub total_vcpu: u32,
    pub total_memory_mb: u32,
    pub max_concurrent: usize,
    pub allocated_vcpu: u32,
    pub allocated_memory_mb: u32,
    pub running_count: usize,
    pub held_sessions: Vec<String>,
    pub mode: String,
}

// ---------------------------------------------------------------------------
// Complete
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CompleteRequest {
    pub run_id: Uuid,
    pub exit_code: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn poll_response_with_job() {
        let json = json!({
            "job": {
                "runId": "550e8400-e29b-41d4-a716-446655440000",
                "experimentalProfile": "browser"
            }
        });
        let resp: PollResponse = serde_json::from_value(json).unwrap();
        let job = resp.job.unwrap();
        assert_eq!(
            job.run_id,
            "550e8400-e29b-41d4-a716-446655440000"
                .parse::<Uuid>()
                .unwrap()
        );
        assert_eq!(job.experimental_profile.as_deref(), Some("browser"));
    }

    #[test]
    fn poll_response_no_job() {
        let json = json!({ "job": null });
        let resp: PollResponse = serde_json::from_value(json).unwrap();
        assert!(resp.job.is_none());
    }

    #[test]
    fn job_optional_profile_defaults_to_none() {
        let json = json!({
            "runId": "550e8400-e29b-41d4-a716-446655440000"
        });
        let job: Job = serde_json::from_value(json).unwrap();
        assert!(job.experimental_profile.is_none());
    }

    #[test]
    fn execution_context_minimal() {
        let json = json!({
            "runId": "550e8400-e29b-41d4-a716-446655440000",
            "prompt": "hello",
            "sandboxToken": "tok-123",
            "workingDir": "/home/user",
            "cliAgentType": "claude_code"
        });
        let ctx: ExecutionContext = serde_json::from_value(json).unwrap();
        assert_eq!(ctx.prompt, "hello");
        assert_eq!(ctx.sandbox_token, "tok-123");
        assert_eq!(ctx.working_dir, "/home/user");
        assert_eq!(ctx.cli_agent_type, "claude_code");
        assert!(ctx.append_system_prompt.is_none());
        assert!(ctx.vars.is_none());
        assert!(ctx.firewalls.is_none());
        assert!(ctx.secret_values.is_none());
    }

    #[test]
    fn execution_context_all_optional_fields() {
        let json = json!({
            "runId": "550e8400-e29b-41d4-a716-446655440000",
            "prompt": "analyze code",
            "sandboxToken": "tok-456",
            "workingDir": "/workspace",
            "cliAgentType": "claude_code",
            "appendSystemPrompt": "be concise",
            "agentComposeVersionId": "sha256-abc",
            "vars": {"API_KEY": "secret"},
            "checkpointId": "660e8400-e29b-41d4-a716-446655440000",
            "storageManifest": {
                "storages": [{"mountPath": "/data", "archiveUrl": "https://s3/archive.tar.gz"}],
                "artifact": {
                    "mountPath": "/artifacts",
                    "vasStorageName": "art-1",
                    "vasVersionId": "v1"
                },
                "memory": {
                    "mountPath": "/memory",
                    "vasStorageName": "mem-1",
                    "vasVersionId": "v2"
                }
            },
            "environment": {"NODE_ENV": "production"},
            "resumeSession": {"sessionId": "sess-1", "sessionHistory": "/tmp/history"},
            "secretValues": ["s1", "s2"],
            "encryptedSecrets": "enc-blob",
            "secretConnectorMap": {"github": "oauth"},
            "debugNoMockClaude": true,
            "apiStartTime": 1700000000000.0,
            "userTimezone": "America/New_York",
            "memoryName": "project-mem",
            "firewalls": [{
                "name": "github",
                "ref": "github",
                "apis": [{"base": "https://api.github.com", "auth": {"headers": {}}}]
            }],
            "disallowedTools": ["CronCreate"],
            "tools": ["Bash", "Read"],
            "settings": "{\"hooks\":{}}",
            "experimentalProfile": "browser",
            "featureFlags": {"computerUse": true, "voiceChat": false}
        });
        let ctx: ExecutionContext = serde_json::from_value(json).unwrap();
        assert_eq!(ctx.append_system_prompt.as_deref(), Some("be concise"));
        assert_eq!(ctx.vars.as_ref().unwrap()["API_KEY"], "secret");
        assert_eq!(ctx.environment.as_ref().unwrap()["NODE_ENV"], "production");
        assert_eq!(ctx.resume_session.as_ref().unwrap().session_id, "sess-1");
        assert_eq!(ctx.secret_values.as_ref().unwrap().len(), 2);
        assert_eq!(ctx.encrypted_secrets.as_deref(), Some("enc-blob"));
        assert!(ctx.debug_no_mock_claude.unwrap());
        assert_eq!(ctx.firewalls.as_ref().unwrap()[0].name, "github");
        assert_eq!(ctx.disallowed_tools.as_ref().unwrap(), &["CronCreate"]);
        assert_eq!(ctx.tools.as_ref().unwrap(), &["Bash", "Read"]);
        assert_eq!(ctx.settings.as_deref(), Some("{\"hooks\":{}}"));
        assert!(ctx.storage_manifest.is_some());
        let flags = ctx.feature_flags.as_ref().unwrap();
        assert_eq!(flags.get("computerUse"), Some(&true));
        assert_eq!(flags.get("voiceChat"), Some(&false));
    }

    #[test]
    fn firewall_round_trip() {
        let fw = Firewall {
            name: "github".into(),
            ref_key: "github".into(),
            apis: vec![FirewallApi {
                id: "api-1".into(),
                base: "https://api.github.com".into(),
                auth: FirewallAuth {
                    headers: [("Authorization".into(), "Bearer tok".into())]
                        .into_iter()
                        .collect(),
                    base: None,
                },
                permissions: Some(vec![FirewallPermission {
                    name: "metadata:read".into(),
                    description: Some("read repo metadata".into()),
                    rules: vec!["GET /repos/{owner}/{repo}".into()],
                }]),
            }],
        };
        let json = serde_json::to_value(&fw).unwrap();
        // `ref_key` serializes as "ref"
        assert_eq!(json["ref"], "github");
        assert!(json.get("ref_key").is_none());
        // round-trip
        let deserialized: Firewall = serde_json::from_value(json).unwrap();
        assert_eq!(deserialized.ref_key, "github");
        assert_eq!(
            deserialized.apis[0].permissions.as_ref().unwrap()[0].name,
            "metadata:read"
        );
    }

    #[test]
    fn firewall_auth_base_omitted_when_none() {
        let auth = FirewallAuth {
            headers: HashMap::new(),
            base: None,
        };
        let json = serde_json::to_value(&auth).unwrap();
        assert!(json.get("base").is_none());
    }

    #[test]
    fn complete_request_camel_case() {
        let req = CompleteRequest {
            run_id: "550e8400-e29b-41d4-a716-446655440000".parse().unwrap(),
            exit_code: 0,
            error: None,
        };
        let json = serde_json::to_value(&req).unwrap();
        assert!(json.get("runId").is_some());
        assert!(json.get("exitCode").is_some());
        // error omitted when None
        assert!(json.get("error").is_none());
    }

    #[test]
    fn complete_request_with_error() {
        let req = CompleteRequest {
            run_id: "550e8400-e29b-41d4-a716-446655440000".parse().unwrap(),
            exit_code: 1,
            error: Some("timeout".into()),
        };
        let json = serde_json::to_value(&req).unwrap();
        assert_eq!(json["error"], "timeout");
    }

    #[test]
    fn session_id_returns_none_without_resume() {
        let json = json!({
            "runId": "550e8400-e29b-41d4-a716-446655440000",
            "prompt": "hello",
            "sandboxToken": "tok",
            "workingDir": "/home/user",
            "cliAgentType": "claude_code"
        });
        let ctx: ExecutionContext = serde_json::from_value(json).unwrap();
        assert!(ctx.session_id().is_none());
    }

    #[test]
    fn session_id_returns_id_from_resume_session() {
        let json = json!({
            "runId": "550e8400-e29b-41d4-a716-446655440000",
            "prompt": "hello",
            "sandboxToken": "tok",
            "workingDir": "/home/user",
            "cliAgentType": "claude_code",
            "resumeSession": {
                "sessionId": "sess-abc-123",
                "sessionHistory": "{}"
            }
        });
        let ctx: ExecutionContext = serde_json::from_value(json).unwrap();
        assert_eq!(ctx.session_id(), Some("sess-abc-123"));
    }

    #[test]
    fn storage_manifest_camel_case() {
        let json = json!({
            "storages": [{"mountPath": "/workspace"}],
            "artifact": {
                "mountPath": "/artifacts",
                "vasStorageName": "my-artifact",
                "vasVersionId": "v1"
            }
        });
        let manifest: StorageManifest = serde_json::from_value(json).unwrap();
        assert_eq!(manifest.storages[0].mount_path, "/workspace");
        assert_eq!(
            manifest.artifact.as_ref().unwrap().vas_storage_name,
            "my-artifact"
        );
        assert!(manifest.memory.is_none());
    }

    #[test]
    fn heartbeat_state_serializes_camel_case() {
        let state = HeartbeatState {
            runner_id: "550e8400-e29b-41d4-a716-446655440000".into(),
            runner_name: "runner-1".into(),
            group: "vm0/production".into(),
            profiles: vec!["vm0/default".into()],
            total_vcpu: 16,
            total_memory_mb: 32768,
            max_concurrent: 8,
            allocated_vcpu: 6,
            allocated_memory_mb: 6144,
            running_count: 2,
            held_sessions: vec!["session-abc".into()],
            mode: "running".into(),
        };
        let json: serde_json::Value = serde_json::to_value(&state).unwrap();
        assert_eq!(json["runnerId"], "550e8400-e29b-41d4-a716-446655440000");
        assert_eq!(json["runnerName"], "runner-1");
        assert_eq!(json["totalVcpu"], 16);
        assert_eq!(json["totalMemoryMb"], 32768);
        assert_eq!(json["maxConcurrent"], 8);
        assert_eq!(json["allocatedVcpu"], 6);
        assert_eq!(json["allocatedMemoryMb"], 6144);
        assert_eq!(json["runningCount"], 2);
        assert_eq!(json["heldSessions"], json!(["session-abc"]));
        assert_eq!(json["mode"], "running");
    }
}
