use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Poll
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PollResponse {
    pub job: Option<Job>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Job {
    pub run_id: Uuid,
}

// ---------------------------------------------------------------------------
// Claim (execution context)
// Keep in sync with TS: packages/core/src/contracts/runners.ts → executionContextSchema
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExecutionContext {
    pub run_id: Uuid,
    pub prompt: String,
    // Not yet used by runner — compose version for traceability
    #[allow(dead_code)]
    #[serde(default)]
    pub agent_compose_version_id: Option<String>,
    // Not yet used by runner — vars are expanded into environment at compose time
    #[allow(dead_code)]
    #[serde(default)]
    pub vars: Option<HashMap<String, String>>,
    // Not yet used by runner — checkpoint resume not yet implemented
    #[allow(dead_code)]
    #[serde(default)]
    pub checkpoint_id: Option<Uuid>,
    pub sandbox_token: String,
    pub working_dir: String,
    #[serde(default)]
    pub storage_manifest: Option<StorageManifest>,
    #[serde(default)]
    pub environment: Option<HashMap<String, String>>,
    #[serde(default)]
    pub resume_session: Option<ResumeSession>,
    #[serde(default)]
    pub secret_values: Option<Vec<String>>,
    // Forwarded to mitm-addon via proxy registry for auth resolution
    #[serde(default)]
    pub encrypted_secrets: Option<String>,
    // Maps secret names to OAuth connector types for runtime token refresh
    #[serde(default)]
    pub secret_connector_map: Option<HashMap<String, String>>,
    pub cli_agent_type: String,
    #[serde(default)]
    pub experimental_firewall: Option<ExperimentalFirewall>,
    #[serde(default)]
    pub debug_no_mock_claude: Option<bool>,
    #[serde(default)]
    pub api_start_time: Option<f64>,
    #[serde(default)]
    pub user_timezone: Option<String>,
    // Not yet used by runner — agent display name for logging/UI
    #[allow(dead_code)]
    #[serde(default)]
    pub agent_name: Option<String>,
    // Not yet used by runner — org slug for agent
    #[allow(dead_code)]
    #[serde(default)]
    pub agent_org_slug: Option<String>,
    // Not yet used by runner — memory storage name for first-run init
    #[allow(dead_code)]
    #[serde(default)]
    pub memory_name: Option<String>,
    #[serde(default)]
    pub experimental_services: Option<Vec<ServiceEntry>>,
}

/// Firewall and proxy configuration attached to each execution.
///
/// Field names use snake_case in JSON (matching the TS zod schema).
#[derive(Debug, Deserialize)]
pub struct ExperimentalFirewall {
    pub enabled: bool,
    #[serde(default)]
    pub rules: Option<Vec<crate::proxy::FirewallRule>>,
}

/// A single service with its name, ref key, and API entries.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ServiceEntry {
    pub name: String,
    /// The ref key from vm0.yaml (e.g., "github", "slack").
    /// `ref` is a Rust keyword, so we rename via serde.
    #[serde(rename = "ref")]
    pub ref_key: String,
    pub apis: Vec<ServiceApiEntry>,
}

/// A single service API entry with base URL and auth headers for proxy-side matching.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ServiceApiEntry {
    /// Unique identifier for cache keying in mitm-addon. Generated by the
    /// runner at registry-write time (not supplied by the web API).
    #[serde(default)]
    pub id: String,
    pub base: String,
    pub auth: ServiceApiAuth,
    #[serde(default)]
    pub permissions: Option<Vec<ServiceApiPermission>>,
}

/// A named permission group with matching rules for request authorization.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ServiceApiPermission {
    pub name: String,
    #[serde(default)]
    pub description: Option<String>,
    pub rules: Vec<String>,
}

/// Auth configuration for a service API entry.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ServiceApiAuth {
    pub headers: std::collections::HashMap<String, String>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StorageManifest {
    pub storages: Vec<StorageEntry>,
    #[serde(default)]
    pub artifact: Option<ArtifactEntry>,
    #[serde(default)]
    pub memory: Option<ArtifactEntry>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StorageEntry {
    pub mount_path: String,
    #[serde(default)]
    pub archive_url: Option<String>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ArtifactEntry {
    pub mount_path: String,
    #[serde(default)]
    pub archive_url: Option<String>,
    pub vas_storage_name: String,
    pub vas_version_id: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResumeSession {
    pub session_id: String,
    pub session_history: String,
}

// ---------------------------------------------------------------------------
// Complete
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CompleteRequest {
    pub run_id: Uuid,
    pub exit_code: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}
