/**
 * Existing Next.js API routes in apps/web at the point web route growth was
 * frozen. New API routes should be implemented in apps/api instead.
 *
 * When a route is migrated out of apps/web, remove its entry here as part of
 * the same change. Do not add new entries; the no-new-api-routes rule checks
 * that this baseline only shrinks relative to the branch's git base.
 */
export const WEB_API_ROUTE_BASELINE = [
  "app/api/integrations/telegram/[botId]/avatar/route.ts",
  "app/api/integrations/telegram/[botId]/route.ts",
  "app/api/integrations/telegram/auth-callback/route.ts",
  "app/api/integrations/telegram/link/route.ts",
  "app/api/integrations/telegram/route.ts",
  "app/api/runners/heartbeat/route.ts",
  "app/api/runners/jobs/[id]/claim/route.ts",
  "app/api/runners/poll/route.ts",
  "app/api/runners/realtime/token/route.ts",
  "app/api/telegram/register/route.ts",
  "app/api/telegram/setup-status/route.ts",
  "app/api/telegram/webhook/[telegramBotId]/route.ts",
  "app/api/webhooks/agent/checkpoints/prepare-history/route.ts",
  "app/api/webhooks/agent/checkpoints/route.ts",
  "app/api/webhooks/agent/complete/route.ts",
  "app/api/webhooks/agent/events/route.ts",
  "app/api/webhooks/agent/firewall/auth/route.ts",
  "app/api/webhooks/agent/heartbeat/route.ts",
  "app/api/webhooks/agent/storages/commit/route.ts",
  "app/api/webhooks/agent/storages/prepare/route.ts",
  "app/api/webhooks/agent/telemetry/route.ts",
  "app/api/webhooks/agent/usage-event/route.ts",
  "app/api/webhooks/clerk/route.ts",
  "app/api/webhooks/github/route.ts",
  "app/api/webhooks/stripe/route.ts",
  "app/api/zero/billing/auto-recharge/route.ts",
  "app/api/zero/billing/checkout/route.ts",
  "app/api/zero/billing/downgrade/route.ts",
  "app/api/zero/billing/invoices/route.ts",
  "app/api/zero/billing/portal/route.ts",
  "app/api/zero/billing/redeem/[campaign]/route.ts",
  "app/api/zero/billing/status/route.ts",
  "app/api/zero/connectors/[type]/route.ts",
  "app/api/zero/connectors/[type]/scope-diff/route.ts",
  "app/api/zero/connectors/[type]/sessions/[sessionId]/route.ts",
  "app/api/zero/connectors/[type]/sessions/route.ts",
  "app/api/zero/connectors/computer/route.ts",
  "app/api/zero/connectors/route.ts",
  "app/api/zero/connectors/search/route.ts",
  "app/api/zero/custom-connectors/[id]/route.ts",
  "app/api/zero/custom-connectors/[id]/secret/route.ts",
  "app/api/zero/custom-connectors/route.ts",
  "app/api/zero/default-agent/route.ts",
  "app/api/zero/developer-support/route.ts",
  "app/api/zero/email/callbacks/reply/route.ts",
  "app/api/zero/email/callbacks/trigger/route.ts",
  "app/api/zero/email/inbound/route.ts",
  "app/api/zero/feature-switches/route.ts",
  "app/api/zero/integrations/chat/message/route.ts",
  "app/api/zero/integrations/slack/connect/route.ts",
  "app/api/zero/integrations/slack/download-file/route.ts",
  "app/api/zero/integrations/slack/message/route.ts",
  "app/api/zero/integrations/slack/route.ts",
  "app/api/zero/integrations/slack/upload-file/complete/route.ts",
  "app/api/zero/integrations/slack/upload-file/init/route.ts",
  "app/api/zero/integrations/telegram/bots/route.ts",
  "app/api/zero/integrations/telegram/download-file/route.ts",
  "app/api/zero/integrations/telegram/message/route.ts",
  "app/api/zero/integrations/telegram/upload-file/complete/route.ts",
  "app/api/zero/integrations/telegram/upload-file/init/route.ts",
  "app/api/zero/image-io/generate/route.ts",
  "app/api/zero/logs/[id]/route.ts",
  "app/api/zero/logs/route.ts",
  "app/api/zero/logs/search/route.ts",
  "app/api/zero/slack/channels/route.ts",
  "app/api/zero/slack/commands/route.ts",
  "app/api/zero/slack/connect/route.ts",
  "app/api/zero/slack/events/route.ts",
  "app/api/zero/slack/interactive/route.ts",
  "app/api/zero/slack/oauth/callback/route.ts",
  "app/api/zero/slack/oauth/connect/route.ts",
  "app/api/zero/slack/oauth/install/route.ts",
] as const;

export const WEB_API_ROUTE_BASELINE_SET = new Set<string>(
  WEB_API_ROUTE_BASELINE,
);
