/**
 * ts-rest API Contracts
 *
 * This module provides type-safe API contracts using ts-rest.
 *
 * IMPORTANT: We use @ts-rest/core@3.53.0-rc.1 (RC version) because:
 * - The stable version (3.52.x) requires Zod v3
 * - This project uses Zod v4 which has breaking type changes
 * - The RC version adds Zod v4 compatibility
 *
 * TODO: Upgrade to stable @ts-rest/core@3.53.0 when released.
 * Track: https://github.com/ts-rest/ts-rest/releases
 */
export { initContract } from "./base";
export {
  apiErrorSchema,
  ApiError,
  createErrorResponse,
  RUN_ERROR_GUIDANCE,
  type ApiErrorKey,
  type ApiErrorResponse,
} from "./errors";
export {
  composesMainContract,
  composesByIdContract,
  composesVersionsContract,
  composesListContract,
  composesMetadataContract,
  composesInstructionsContract,
  type ComposesMainContract,
  type ComposesByIdContract,
  type ComposesVersionsContract,
  type ComposesListContract,
  type ComposesMetadataContract,
  type ComposesInstructionsContract,
  AGENT_NAME_REGEX,
  agentNameSchema,
  volumeConfigSchema,
  agentDefinitionSchema,
  agentComposeContentSchema,
  agentComposeApiContentSchema,
  composeResponseSchema,
  composeListItemSchema,
  metadataUpdateSchema,
  composeInstructionsResponseSchema,
  ZERO_CAPABILITIES,
  ZERO_CAPABILITY_META,
  type ZeroCapability,
  type ZeroCapabilityMeta,
  // Inferred types
  type ComposeResponse,
  type ComposeListItem,
} from "./composes";
export {
  runsMainContract,
  runsByIdContract,
  runsCancelContract,
  runEventsContract,
  runTelemetryContract,
  runSystemLogContract,
  runMetricsContract,
  runAgentEventsContract,
  runNetworkLogsContract,
  logsSearchContract,
  ALL_RUN_STATUSES,
  runStatusSchema,
  unifiedRunRequestSchema,
  createRunResponseSchema,
  getRunResponseSchema,
  runListItemSchema,
  runsListResponseSchema,
  cancelRunResponseSchema,
  runEventSchema,
  runResultSchema,
  runStateSchema,
  eventsResponseSchema,
  telemetryMetricSchema,
  telemetryResponseSchema,
  systemLogResponseSchema,
  metricsResponseSchema,
  agentEventsResponseSchema,
  networkLogEntrySchema,
  networkLogsResponseSchema,
  searchResultSchema,
  logsSearchResponseSchema,
  type RunsMainContract,
  type RunsByIdContract,
  type RunsCancelContract,
  type RunEventsContract,
  type RunTelemetryContract,
  type RunSystemLogContract,
  type RunMetricsContract,
  type RunAgentEventsContract,
  type RunNetworkLogsContract,
  type LogsSearchContract,
  // Inferred types
  type RunStatus,
  type RunResult,
  type RunState,
  type RunEvent,
  type CreateRunResponse,
  type GetRunResponse,
  type RunListItem,
  type RunsListResponse,
  type CancelRunResponse,
  type EventsResponse,
  type TelemetryMetric,
  type TelemetryResponse,
  type SystemLogResponse,
  type MetricsResponse,
  type AgentEventsResponse,
  type NetworkLogEntry,
  type AxiomNetworkEvent,
  type NetworkLogsResponse,
  type SearchResult,
  type LogsSearchResponse,
  runsQueueContract,
  queueEntrySchema,
  runningTaskSchema,
  concurrencyInfoSchema,
  queueResponseSchema,
  type RunsQueueContract,
  type QueueEntry,
  type RunningTask,
  type ConcurrencyInfo,
  type QueueResponse,
} from "./runs";
export {
  storagesContract,
  storageTypeSchema,
  uploadStorageResponseSchema,
  // Direct upload schemas (shared with webhooks)
  MAX_FILE_SIZE_BYTES,
  fileEntryWithHashSchema,
  storageChangesSchema,
  presignedUploadSchema,
  // Direct upload contracts (CLI endpoints)
  storagesPrepareContract,
  storagesCommitContract,
  storagesDownloadContract,
  storagesListContract,
  type StoragesContract,
  type StoragesPrepareContract,
  type StoragesCommitContract,
  type StoragesDownloadContract,
  type StoragesListContract,
} from "./storages";
export {
  webhookEventsContract,
  webhookCompleteContract,
  webhookCheckpointsContract,
  webhookCheckpointsPrepareHistoryContract,
  webhookHeartbeatContract,
  webhookStoragesContract,
  webhookStoragesIncrementalContract,
  webhookTelemetryContract,
  // Direct upload contracts (Webhook endpoints for sandbox)
  webhookStoragesPrepareContract,
  webhookStoragesCommitContract,
  type WebhookEventsContract,
  type WebhookCompleteContract,
  type WebhookCheckpointsContract,
  type WebhookCheckpointsPrepareHistoryContract,
  type WebhookHeartbeatContract,
  type WebhookStoragesContract,
  type WebhookStoragesIncrementalContract,
  type WebhookTelemetryContract,
  type WebhookStoragesPrepareContract,
  type WebhookStoragesCommitContract,
} from "./webhooks";
export {
  cliAuthDeviceContract,
  cliAuthTokenContract,
  cliAuthOrgContract,
  type CliAuthDeviceContract,
  type CliAuthTokenContract,
  type CliAuthOrgContract,
} from "./cli-auth";
export { authContract, type AuthContract } from "./auth";
export {
  cronCleanupSandboxesContract,
  cleanupResultSchema,
  cleanupResponseSchema,
  type CronCleanupSandboxesContract,
} from "./cron";
export {
  orgDefaultAgentContract,
  orgSlugSchema,
  orgResponseSchema,
  updateOrgRequestSchema,
  orgTierSchema,
  type OrgDefaultAgentContract,
  type OrgResponse,
  type UpdateOrgRequest,
  type OrgTier,
} from "./orgs";
export {
  secretNameSchema,
  secretTypeSchema,
  secretResponseSchema,
  secretListResponseSchema,
  setSecretRequestSchema,
  type SecretResponse,
  type SecretListResponse,
  type SetSecretRequest,
  type SecretType,
} from "./secrets";
export {
  variableNameSchema,
  variableResponseSchema,
  variableListResponseSchema,
  setVariableRequestSchema,
  type VariableResponse,
  type VariableListResponse,
  type SetVariableRequest,
} from "./variables";
export {
  modelProviderTypeSchema,
  modelProviderFrameworkSchema,
  modelProviderResponseSchema,
  modelProviderListResponseSchema,
  upsertModelProviderRequestSchema,
  upsertModelProviderResponseSchema,
  updateModelRequestSchema,
  MODEL_PROVIDER_TYPES,
  getFrameworkForType,
  getSecretNameForType,
  getEnvironmentMapping,
  getModels,
  getDefaultModel,
  hasModelSelection,
  allowsCustomModel,
  getCustomModelPlaceholder,
  // Provider compatibility
  getProviderBaseUrl,
  areProvidersCompatible,
  // Selectable provider filtering
  getSelectableProviderTypes,
  // Multi-auth provider support
  hasAuthMethods,
  getAuthMethodsForType,
  getDefaultAuthMethod,
  getSecretsForAuthMethod,
  getSecretNamesForAuthMethod,
  type ModelProviderType,
  type ModelProviderFramework,
  type ModelProviderResponse,
  type ModelProviderListResponse,
  type UpsertModelProviderRequest,
  type UpsertModelProviderResponse,
  type UpdateModelRequest,
  // Multi-auth provider types
  type SecretFieldConfig,
  type AuthMethodConfig,
  // Firewall gateway for model providers
  MODEL_PROVIDER_FIREWALL_CONFIGS,
  getModelProviderFirewall,
  // VM0 managed provider
  VM0_ORG_SLUG,
  VM0_MODEL_TO_PROVIDER,
  getVm0ConcreteProviderType,
  getVm0Vendor,
} from "./model-providers";
export {
  sessionsContract,
  sessionsByIdContract,
  checkpointsByIdContract,
  storedChatMessageSchema,
  sessionResponseSchema,
  sessionListItemSchema,
  checkpointResponseSchema,
  agentComposeSnapshotSchema,
  artifactSnapshotSchema,
  volumeVersionsSnapshotSchema,
  type SessionsContract,
  type SessionsByIdContract,
  type CheckpointsByIdContract,
  // Inferred types
  type StoredChatMessage,
  type SessionResponse,
  type SessionListItem,
  type CheckpointResponse,
  type AgentComposeSnapshot,
  type ArtifactSnapshot,
  type VolumeVersionsSnapshot,
} from "./sessions";
export {
  chatThreadsContract,
  chatThreadByIdContract,
  chatMessagesContract,
  chatThreadListItemSchema,
  chatThreadDetailSchema,
  summaryEntrySchema,
  type SummaryEntry,
  type ChatThreadsContract,
  type ChatThreadByIdContract,
  type ChatMessagesContract,
  type ChatThreadListItem,
  type ChatThreadDetail,
} from "./chat-threads";
export {
  runnersPollContract,
  runnersJobClaimContract,
  runnersHeartbeatContract,
  heartbeatBodySchema,
  runnerGroupSchema,
  jobSchema,
  executionContextSchema,
  storedExecutionContextSchema,
  storageEntrySchema,
  DEFAULT_PROFILE,
  artifactEntrySchema,
  storageManifestSchema,
  resumeSessionSchema,
  type RunnersPollContract,
  type RunnersJobClaimContract,
  type RunnersHeartbeatContract,
  type Job,
  type ExecutionContext,
  type StoredExecutionContext,
  type StorageEntry,
  type ArtifactEntry,
  type StorageManifest,
  type ResumeSession,
} from "./runners";

export {
  runnerRealtimeTokenContract,
  type RunnerRealtimeTokenContract,
} from "./realtime";

export {
  logsListContract,
  logsByIdContract,
  logStatusSchema,
  logEntrySchema,
  paginationSchema,
  logsListResponseSchema,
  artifactSchema,
  logDetailSchema,
  triggerSourceSchema,
  type LogsListContract,
  type LogsByIdContract,
  // Inferred types
  type LogStatus,
  type LogEntry,
  type Pagination,
  type LogsListResponse,
  type Artifact,
  type LogDetail,
  type TriggerSource,
  type LogsFilters,
} from "./logs";

export {
  connectorTypeSchema,
  CONNECTOR_TYPES,
  type ConnectorType,
  type ConnectorConfig,
  type ConnectorSecretConfig,
  type ConnectorAuthMethodConfig,
  type ConnectorAuthMethodType,
  type ConnectorOAuthConfig,
} from "./connectors";
export {
  getConnectorAuthMethods,
  getConnectorDefaultAuthMethod,
  getConnectorSecretsForAuthMethod,
  getConnectorSecretNames,
  getConnectorEnvironmentMapping,
  getEligibleConnectorTypes,
  getConnectorDerivedNames,
  getConnectorProvidedSecretNames,
  getConnectorManagedSecretNames,
  getConnectorTypeForSecretName,
  getConnectorOAuthConfig,
  hasRequiredScopes,
  getScopeDiff,
  type ScopeDiff,
  getApiTokenRequiredSecretNames,
  getApiTokenFieldsByType,
  deriveApiTokenConnectedTypes,
} from "./connector-utils";
export {
  connectorSessionStatusSchema,
  connectorResponseSchema,
  connectorListResponseSchema,
  connectorSessionResponseSchema,
  connectorSessionStatusResponseSchema,
  scopeDiffResponseSchema,
  computerConnectorCreateResponseSchema,
  type ScopeDiffResponse,
  type ConnectorSessionStatus,
  type ConnectorResponse,
  type ConnectorListResponse,
  type ConnectorSessionResponse,
  type ConnectorSessionStatusResponse,
  type ComputerConnectorCreateResponse,
} from "./connector-schemas";

export {
  basicAuthTemplateRe,
  extractSecretNamesFromApis,
  firewallPermissionSchema,
  firewallApiSchema,
  firewallSchema,
  firewallsSchema,
  firewallConfigSchema,
  firewallPolicyValueSchema,
  firewallPoliciesSchema,
  type FirewallConfig,
  type ExpandedFirewallConfig,
  type FirewallApi,
  type Firewall,
  type Firewalls,
  type FirewallPolicyValue,
  type FirewallPolicies,
  hasBaseUrlParams,
  hasBaseUrlVars,
  resolveFirewallBaseUrlVars,
  validateBaseUrl,
} from "./firewalls";

export {
  resolveFirewallSelections,
  collectAndValidatePermissions,
  validateRule,
  type FirewallSelection,
} from "./firewall-expander";

export {
  matchFirewallPath,
  findMatchingPermissions,
  type GraphQLBody,
} from "./firewall-rule-matcher";

export {
  userPreferencesResponseSchema,
  updateUserPreferencesRequestSchema,
  type UserPreferencesResponse,
  type UpdateUserPreferencesRequest,
  sendModeSchema,
  type SendMode,
} from "./zero-user-preferences";
export {
  orgListItemSchema,
  orgListResponseSchema,
  type OrgListItem,
  type OrgListResponse,
} from "./org-list";
export {
  orgRoleSchema,
  orgMemberSchema,
  orgPendingInvitationSchema,
  orgMembershipRequestSchema,
  orgDomainSchema,
  orgMembersResponseSchema,
  orgDomainsResponseSchema,
  inviteOrgMemberRequestSchema,
  removeOrgMemberRequestSchema,
  updateOrgMemberRoleRequestSchema,
  revokeInvitationRequestSchema,
  membershipRequestActionSchema,
  addDomainRequestSchema,
  domainActionRequestSchema,
  orgMessageResponseSchema,
  type OrgRole,
  type OrgMember,
  type OrgPendingInvitation,
  type OrgMembershipRequest,
  type OrgDomain,
  type OrgMembersResponse,
  type OrgDomainsResponse,
  type InviteOrgMemberRequest,
  type RemoveOrgMemberRequest,
  type UpdateOrgMemberRoleRequest,
  type RevokeInvitationRequest,
  type MembershipRequestAction,
  type AddDomainRequest,
  type OrgEnrollmentMode,
  type DomainActionRequest,
  type DomainVerifyRequest,
  type OrgMessageResponse,
} from "./org-members";
export {
  onboardingStatusContract,
  onboardingCompleteContract,
  onboardingSetupContract,
  onboardingStatusResponseSchema,
  type OnboardingStatusContract,
  type OnboardingCompleteContract,
  type OnboardingSetupContract,
  type OnboardingStatusResponse,
} from "./onboarding";
export {
  skillsResolveContract,
  skillFrontmatterSchema,
  type SkillsResolveContract,
} from "./skills";
export {
  zeroAgentsMainContract,
  zeroAgentsByIdContract,
  zeroAgentInstructionsContract,
  zeroAgentFirewallPoliciesContract,
  zeroAgentResponseSchema,
  zeroAgentRequestSchema,
  zeroAgentMetadataRequestSchema,
  zeroAgentInstructionsResponseSchema,
  zeroAgentInstructionsRequestSchema,
  zeroAgentFirewallPoliciesRequestSchema,
  zeroSkillsCollectionContract,
  zeroSkillsDetailContract,
  zeroAgentCustomSkillNameSchema,
  zeroAgentCustomSkillSchema,
  skillFileEntrySchema,
  skillFileMetadataSchema,
  zeroAgentSkillFilesRequestSchema,
  zeroAgentSkillContentResponseSchema,
  zeroAgentSkillListResponseSchema,
  type ZeroAgentsMainContract,
  type ZeroAgentsByIdContract,
  type ZeroAgentInstructionsContract,
  type ZeroAgentFirewallPoliciesContract,
  type ZeroAgentResponse,
  type ZeroAgentRequest,
  type ZeroAgentMetadataRequest,
  type ZeroAgentInstructionsResponse,
  type ZeroAgentInstructionsRequest,
  type ZeroAgentFirewallPoliciesRequest,
  type ZeroAgentCustomSkill,
  type SkillFileEntry,
  type SkillFileMetadata,
  type ZeroAgentSkillFilesRequest,
  type ZeroAgentSkillContentResponse,
  type ZeroSkillsCollectionContract,
  type ZeroSkillsDetailContract,
  firewallAccessRequestStatusSchema,
  firewallAccessRequestResponseSchema,
  createFirewallAccessRequestSchema,
  resolveFirewallAccessRequestSchema,
  firewallAccessRequestsCreateContract,
  firewallAccessRequestsListContract,
  firewallAccessRequestsResolveContract,
  type FirewallAccessRequestResponse,
  type CreateFirewallAccessRequest,
  type ResolveFirewallAccessRequest,
  type FirewallAccessRequestsCreateContract,
  type FirewallAccessRequestsListContract,
  type FirewallAccessRequestsResolveContract,
} from "./zero-agents";
export {
  zeroUserConnectorsContract,
  userConnectorEnabledTypesSchema,
  type UserConnectorEnabledTypes,
  type ZeroUserConnectorsContract,
} from "./user-connectors";
export {
  zeroConnectorsMainContract,
  zeroConnectorsByTypeContract,
  zeroConnectorScopeDiffContract,
  zeroConnectorsSearchContract,
  zeroConnectorSessionsContract,
  zeroConnectorSessionByIdContract,
  zeroComputerConnectorContract,
  type ConnectorSearchAuthMethod,
  type ZeroConnectorsMainContract,
  type ZeroConnectorsByTypeContract,
  type ZeroConnectorScopeDiffContract,
  type ZeroConnectorsSearchContract,
  type ZeroConnectorSessionsContract,
  type ZeroConnectorSessionByIdContract,
  type ZeroComputerConnectorContract,
} from "./zero-connectors";
export {
  zeroOrgContract,
  zeroOrgLeaveContract,
  zeroOrgDeleteContract,
  type ZeroOrgContract,
  type ZeroOrgLeaveContract,
  type ZeroOrgDeleteContract,
} from "./zero-org";
export { zeroOrgListContract, type ZeroOrgListContract } from "./zero-org-list";
export {
  zeroOrgMembersContract,
  zeroOrgInviteContract,
  zeroOrgMembershipRequestsContract,
  type ZeroOrgMembersContract,
  type ZeroOrgInviteContract,
  type ZeroOrgMembershipRequestsContract,
} from "./zero-org-members";
export {
  zeroOrgDomainsContract,
  type ZeroOrgDomainsContract,
} from "./zero-org-domains";
export {
  zeroComposesMainContract,
  zeroComposesByIdContract,
  zeroComposesListContract,
  type ZeroComposesMainContract,
  type ZeroComposesByIdContract,
  type ZeroComposesListContract,
} from "./zero-composes";
export {
  zeroRunsMainContract,
  zeroRunsByIdContract,
  zeroRunsCancelContract,
  zeroRunsQueueContract,
  zeroRunAgentEventsContract,
  zeroRunContextContract,
  zeroRunNetworkLogsContract,
  zeroLogsSearchContract,
  type ZeroRunsMainContract,
  type ZeroRunsByIdContract,
  type ZeroRunsCancelContract,
  type ZeroRunsQueueContract,
  type ZeroRunAgentEventsContract,
  type ZeroRunContextContract,
  type ZeroRunNetworkLogsContract,
  type ZeroLogsSearchContract,
  type RunContextResponse,
} from "./zero-runs";
export {
  zeroSchedulesMainContract,
  zeroSchedulesByNameContract,
  zeroSchedulesEnableContract,
  scheduleResponseSchema,
  scheduleListResponseSchema,
  deployScheduleResponseSchema,
  type ZeroSchedulesMainContract,
  type ZeroSchedulesByNameContract,
  type ZeroSchedulesEnableContract,
  zeroScheduleRunContract,
  type ZeroScheduleRunContract,
  type ScheduleResponse,
  type ScheduleListResponse,
  type DeployScheduleResponse,
} from "./zero-schedules";
export {
  zeroModelProvidersMainContract,
  zeroModelProvidersByTypeContract,
  zeroModelProvidersDefaultContract,
  zeroModelProvidersUpdateModelContract,
  type ZeroModelProvidersMainContract,
  type ZeroModelProvidersByTypeContract,
  type ZeroModelProvidersDefaultContract,
  type ZeroModelProvidersUpdateModelContract,
} from "./zero-model-providers";
export {
  zeroUserPreferencesContract,
  type ZeroUserPreferencesContract,
} from "./zero-user-preferences";
export {
  zeroSecretsContract,
  zeroSecretsByNameContract,
  zeroVariablesContract,
  zeroVariablesByNameContract,
  type ZeroSecretsContract,
  type ZeroSecretsByNameContract,
  type ZeroVariablesContract,
  type ZeroVariablesByNameContract,
} from "./zero-secrets";
export {
  zeroSessionsByIdContract,
  type ZeroSessionsByIdContract,
} from "./zero-sessions";
export {
  integrationsSlackMessageContract,
  type IntegrationsSlackMessageContract,
  type SendSlackMessageBody,
  type SendSlackMessageResponse,
  integrationsSlackUploadInitContract,
  type SlackUploadInitBody,
  type SlackUploadInitResponse,
  integrationsSlackUploadCompleteContract,
  type SlackUploadCompleteBody,
  type SlackUploadCompleteResponse,
} from "./integrations";
export {
  zeroBillingStatusContract,
  zeroBillingCheckoutContract,
  zeroBillingPortalContract,
  zeroBillingAutoRechargeContract,
  zeroBillingInvoicesContract,
  zeroBillingDowngradeContract,
  type ZeroBillingStatusContract,
  type ZeroBillingCheckoutContract,
  type ZeroBillingPortalContract,
  type ZeroBillingAutoRechargeContract,
  type ZeroBillingInvoicesContract,
  type ZeroBillingDowngradeContract,
  // Inferred types
  type BillingStatusResponse,
  type AutoRechargeConfig,
  type CheckoutResponse,
  type PortalResponse,
  type BillingInvoice,
  type BillingInvoicesResponse,
  type DowngradeResponse,
} from "./zero-billing";
export {
  zeroUsageMembersContract,
  type ZeroUsageMembersContract,
  // Inferred types
  type MemberUsage,
  type UsageMembersResponse,
} from "./zero-usage";
export {
  zeroTeamContract,
  teamComposeItemSchema,
  type ZeroTeamContract,
  type TeamComposeItem,
} from "./zero-team";
export {
  zeroIntegrationsSlackContract,
  slackOrgStatusSchema,
  type ZeroIntegrationsSlackContract,
  type SlackOrgStatus,
} from "./zero-integrations-slack";
export {
  zeroSlackConnectContract,
  type ZeroSlackConnectContract,
} from "./zero-slack-connect";
export {
  zeroSlackChannelsContract,
  slackChannelSchema,
  type ZeroSlackChannelsContract,
  type SlackChannel,
} from "./zero-slack-channels";
export {
  zeroQueuePositionContract,
  type ZeroQueuePositionContract,
} from "./zero-queue-position";
export {
  zeroMemberCreditCapContract,
  type ZeroMemberCreditCapContract,
} from "./zero-member-credit-cap";
export {
  zeroAskUserQuestionContract,
  zeroAskUserAnswerContract,
  askUserAnswerStatusSchema,
  type ZeroAskUserQuestionContract,
  type ZeroAskUserAnswerContract,
  type AskUserQuestionItem,
  type AskUserQuestionBody,
  type AskUserQuestionResponse,
  type AskUserAnswerStatus,
  type AskUserAnswerResponse,
} from "./zero-ask-user";
export {
  zeroDeveloperSupportContract,
  developerSupportBodySchema,
  consentCodeResponseSchema,
  submitResponseSchema,
  type ZeroDeveloperSupportContract,
} from "./zero-developer-support";
export {
  zeroComputerUseRegisterContract,
  zeroComputerUseUnregisterContract,
  zeroComputerUseHostContract,
  type ZeroComputerUseRegisterContract,
  type ZeroComputerUseUnregisterContract,
  type ZeroComputerUseHostContract,
} from "./zero-computer-use";
export {
  zeroInsightsContract,
  zeroInsightsRangeContract,
  type ZeroInsightsContract,
  type ZeroInsightsRangeContract,
  type InsightsResponse,
  type InsightsRangeResponse,
  type DayInsight,
} from "./zero-insights";
