/**
 * ts-rest API Contracts
 *
 * This module provides type-safe API contracts using ts-rest.
 *
 * IMPORTANT: We use @ts-rest/core@3.53.0-rc.1 (RC version) because:
 * - The stable version (3.52.x) requires Zod v3
 * - This project uses Zod v4 which has breaking type changes
 * - The RC version adds Zod v4 compatibility
 *
 * TODO: Upgrade to stable @ts-rest/core@3.53.0 when released.
 * Track: https://github.com/ts-rest/ts-rest/releases
 */
export { initContract } from "./base";
export {
  apiErrorSchema,
  ApiError,
  createErrorResponse,
  type ApiErrorKey,
  type ApiErrorResponse,
} from "./errors";
export {
  composesMainContract,
  composesByIdContract,
  composesVersionsContract,
  composesListContract,
  type ComposesMainContract,
  type ComposesByIdContract,
  type ComposesVersionsContract,
  type ComposesListContract,
  agentNameSchema,
  volumeConfigSchema,
  agentDefinitionSchema,
  agentComposeContentSchema,
  composeResponseSchema,
  composeListItemSchema,
  SUPPORTED_APPS,
  SUPPORTED_APP_TAGS,
  type SupportedApp,
  type SupportedAppTag,
  // Inferred types
  type ComposeResponse,
  type ComposeListItem,
} from "./composes";
export {
  runsMainContract,
  runsByIdContract,
  runsCancelContract,
  runEventsContract,
  runTelemetryContract,
  runSystemLogContract,
  runMetricsContract,
  runAgentEventsContract,
  runNetworkLogsContract,
  ALL_RUN_STATUSES,
  runStatusSchema,
  unifiedRunRequestSchema,
  createRunResponseSchema,
  getRunResponseSchema,
  runListItemSchema,
  runsListResponseSchema,
  cancelRunResponseSchema,
  runEventSchema,
  runResultSchema,
  runStateSchema,
  eventsResponseSchema,
  telemetryMetricSchema,
  telemetryResponseSchema,
  systemLogResponseSchema,
  metricsResponseSchema,
  agentEventsResponseSchema,
  networkLogEntrySchema,
  networkLogsResponseSchema,
  type RunsMainContract,
  type RunsByIdContract,
  type RunsCancelContract,
  type RunEventsContract,
  type RunTelemetryContract,
  type RunSystemLogContract,
  type RunMetricsContract,
  type RunAgentEventsContract,
  type RunNetworkLogsContract,
  // Inferred types
  type RunStatus,
  type RunResult,
  type RunState,
  type RunEvent,
  type CreateRunResponse,
  type GetRunResponse,
  type RunListItem,
  type RunsListResponse,
  type CancelRunResponse,
  type EventsResponse,
  type TelemetryMetric,
  type TelemetryResponse,
  type SystemLogResponse,
  type MetricsResponse,
  type AgentEventsResponse,
  type NetworkLogEntry,
  type NetworkLogsResponse,
} from "./runs";
export {
  storagesContract,
  storageTypeSchema,
  uploadStorageResponseSchema,
  // Direct upload schemas (shared with webhooks)
  fileEntryWithHashSchema,
  storageChangesSchema,
  presignedUploadSchema,
  // Direct upload contracts (CLI endpoints)
  storagesPrepareContract,
  storagesCommitContract,
  storagesDownloadContract,
  storagesListContract,
  type StoragesContract,
  type StoragesPrepareContract,
  type StoragesCommitContract,
  type StoragesDownloadContract,
  type StoragesListContract,
} from "./storages";
export {
  webhookEventsContract,
  webhookCompleteContract,
  webhookCheckpointsContract,
  webhookHeartbeatContract,
  webhookStoragesContract,
  webhookStoragesIncrementalContract,
  webhookTelemetryContract,
  // Direct upload contracts (Webhook endpoints for sandbox)
  webhookStoragesPrepareContract,
  webhookStoragesCommitContract,
  type WebhookEventsContract,
  type WebhookCompleteContract,
  type WebhookCheckpointsContract,
  type WebhookHeartbeatContract,
  type WebhookStoragesContract,
  type WebhookStoragesIncrementalContract,
  type WebhookTelemetryContract,
  type WebhookStoragesPrepareContract,
  type WebhookStoragesCommitContract,
} from "./webhooks";
export {
  cliAuthDeviceContract,
  cliAuthTokenContract,
  type CliAuthDeviceContract,
  type CliAuthTokenContract,
} from "./cli-auth";
export { authContract, type AuthContract } from "./auth";
export {
  cronCleanupSandboxesContract,
  cleanupResultSchema,
  cleanupResponseSchema,
  type CronCleanupSandboxesContract,
} from "./cron";
export {
  proxyErrorSchema,
  ProxyErrorCode,
  type ProxyError,
  type ProxyErrorCode as ProxyErrorCodeType,
} from "./proxy";
export {
  scopeContract,
  scopeTypeSchema,
  scopeSlugSchema,
  scopeResponseSchema,
  createScopeRequestSchema,
  updateScopeRequestSchema,
  type ScopeContract,
  type ScopeTypeContract,
  type ScopeResponse,
  type CreateScopeRequest,
  type UpdateScopeRequest,
} from "./scopes";
export {
  credentialsMainContract,
  credentialsByNameContract,
  credentialNameSchema,
  credentialTypeSchema,
  credentialResponseSchema,
  credentialListResponseSchema,
  setCredentialRequestSchema,
  type CredentialsMainContract,
  type CredentialsByNameContract,
  type CredentialResponse,
  type CredentialListResponse,
  type SetCredentialRequest,
  type CredentialType,
} from "./credentials";
export {
  secretsMainContract,
  secretsByNameContract,
  secretNameSchema,
  secretTypeSchema,
  secretResponseSchema,
  secretListResponseSchema,
  setSecretRequestSchema,
  type SecretsMainContract,
  type SecretsByNameContract,
  type SecretResponse,
  type SecretListResponse,
  type SetSecretRequest,
  type SecretType,
} from "./secrets";
export {
  variablesMainContract,
  variablesByNameContract,
  variableNameSchema,
  variableResponseSchema,
  variableListResponseSchema,
  setVariableRequestSchema,
  type VariablesMainContract,
  type VariablesByNameContract,
  type VariableResponse,
  type VariableListResponse,
  type SetVariableRequest,
} from "./variables";
export {
  modelProvidersMainContract,
  modelProvidersCheckContract,
  modelProvidersByTypeContract,
  modelProvidersConvertContract,
  modelProvidersSetDefaultContract,
  modelProvidersUpdateModelContract,
  modelProviderTypeSchema,
  modelProviderFrameworkSchema,
  modelProviderResponseSchema,
  modelProviderListResponseSchema,
  upsertModelProviderRequestSchema,
  upsertModelProviderResponseSchema,
  checkSecretResponseSchema,
  updateModelRequestSchema,
  MODEL_PROVIDER_TYPES,
  getFrameworkForType,
  getSecretNameForType,
  getEnvironmentMapping,
  getModels,
  getDefaultModel,
  hasModelSelection,
  allowsCustomModel,
  getCustomModelPlaceholder,
  // Multi-auth provider support
  hasAuthMethods,
  getAuthMethodsForType,
  getDefaultAuthMethod,
  getSecretsForAuthMethod,
  getSecretNamesForAuthMethod,
  type ModelProvidersMainContract,
  type ModelProvidersCheckContract,
  type ModelProvidersByTypeContract,
  type ModelProvidersConvertContract,
  type ModelProvidersSetDefaultContract,
  type ModelProvidersUpdateModelContract,
  type ModelProviderType,
  type ModelProviderFramework,
  type ModelProviderResponse,
  type ModelProviderListResponse,
  type UpsertModelProviderRequest,
  type UpsertModelProviderResponse,
  type CheckSecretResponse,
  type UpdateModelRequest,
  // Multi-auth provider types
  type SecretFieldConfig,
  type AuthMethodConfig,
} from "./model-providers";
export {
  sessionsByIdContract,
  checkpointsByIdContract,
  sessionResponseSchema,
  checkpointResponseSchema,
  agentComposeSnapshotSchema,
  artifactSnapshotSchema,
  volumeVersionsSnapshotSchema,
  type SessionsByIdContract,
  type CheckpointsByIdContract,
  // Inferred types
  type SessionResponse,
  type CheckpointResponse,
  type AgentComposeSnapshot,
  type ArtifactSnapshot,
  type VolumeVersionsSnapshot,
} from "./sessions";
export {
  runnersPollContract,
  runnersJobClaimContract,
  runnerGroupSchema,
  jobSchema,
  executionContextSchema,
  storedExecutionContextSchema,
  storageEntrySchema,
  artifactEntrySchema,
  storageManifestSchema,
  resumeSessionSchema,
  firewallRuleSchema,
  experimentalFirewallSchema,
  type RunnersPollContract,
  type RunnersJobClaimContract,
  type Job,
  type ExecutionContext,
  type StoredExecutionContext,
  type StorageEntry,
  type ArtifactEntry,
  type StorageManifest,
  type ResumeSession,
  type FirewallRule,
  type ExperimentalFirewall,
} from "./runners";

export {
  schedulesMainContract,
  schedulesByNameContract,
  schedulesEnableContract,
  scheduleRunsContract,
  scheduleYamlSchema,
  scheduleTriggerSchema,
  scheduleRunConfigSchema,
  scheduleDefinitionSchema,
  deployScheduleRequestSchema,
  scheduleResponseSchema,
  scheduleListResponseSchema,
  deployScheduleResponseSchema,
  runSummarySchema,
  scheduleRunsResponseSchema,
  type SchedulesMainContract,
  type SchedulesByNameContract,
  type SchedulesEnableContract,
  type ScheduleRunsContract,
  // Inferred types
  type ScheduleTrigger,
  type ScheduleRunConfig,
  type ScheduleDefinition,
  type DeployScheduleRequest,
  type ScheduleResponse,
  type ScheduleListResponse,
  type DeployScheduleResponse,
  type RunSummary,
  type ScheduleRunsResponse,
} from "./schedules";

export {
  realtimeTokenContract,
  runnerRealtimeTokenContract,
  type RealtimeTokenContract,
  type RunnerRealtimeTokenContract,
  type AblyTokenRequest,
} from "./realtime";

export {
  platformLogsListContract,
  platformLogsByIdContract,
  platformArtifactDownloadContract,
  platformLogStatusSchema,
  platformLogEntrySchema,
  paginationSchema,
  platformLogsListResponseSchema,
  artifactSchema,
  platformLogDetailSchema,
  artifactDownloadResponseSchema,
  type PlatformLogsListContract,
  type PlatformLogsByIdContract,
  type PlatformArtifactDownloadContract,
  // Inferred types
  type PlatformLogStatus,
  type PlatformLogEntry,
  type Pagination,
  type PlatformLogsListResponse,
  type Artifact,
  type PlatformLogDetail,
  type ArtifactDownloadResponse,
} from "./platform";

export {
  composeJobsMainContract,
  composeJobsByIdContract,
  webhookComposeCompleteContract,
  composeJobStatusSchema,
  composeJobResultSchema,
  createComposeJobRequestSchema,
  composeJobResponseSchema,
  type ComposeJobsMainContract,
  type ComposeJobsByIdContract,
  type WebhookComposeCompleteContract,
  type ComposeJobStatus,
  type ComposeJobResult,
  type CreateComposeJobRequest,
  type ComposeJobResponse,
} from "./compose-jobs";

export {
  connectorsMainContract,
  connectorsByTypeContract,
  connectorSessionsContract,
  connectorSessionByIdContract,
  connectorTypeSchema,
  connectorSessionStatusSchema,
  connectorResponseSchema,
  connectorListResponseSchema,
  connectorSessionResponseSchema,
  connectorSessionStatusResponseSchema,
  CONNECTOR_TYPES,
  getConnectorAuthMethods,
  getConnectorDefaultAuthMethod,
  getConnectorSecretsForAuthMethod,
  getConnectorSecretNames,
  getConnectorEnvironmentMapping,
  getConnectorDerivedNames,
  getConnectorProvidedSecretNames,
  getConnectorOAuthConfig,
  type ConnectorsMainContract,
  type ConnectorsByTypeContract,
  type ConnectorSessionsContract,
  type ConnectorSessionByIdContract,
  type ConnectorType,
  type ConnectorSessionStatus,
  type ConnectorResponse,
  type ConnectorListResponse,
  type ConnectorSessionResponse,
  type ConnectorSessionStatusResponse,
  type ConnectorSecretConfig,
  type ConnectorAuthMethodConfig,
  type ConnectorOAuthConfig,
} from "./connectors";

// Public API v1 contracts (developer-friendly external API)
export * from "./public";
