/**
 * ts-rest API Contracts
 *
 * This module provides type-safe API contracts using ts-rest.
 *
 * IMPORTANT: We use @ts-rest/core@3.53.0-rc.1 (RC version) because:
 * - The stable version (3.52.x) requires Zod v3
 * - This project uses Zod v4 which has breaking type changes
 * - The RC version adds Zod v4 compatibility
 *
 * TODO: Upgrade to stable @ts-rest/core@3.53.0 when released.
 * Track: https://github.com/ts-rest/ts-rest/releases
 */
export { initContract } from "./base";
export {
  apiErrorSchema,
  ApiError,
  createErrorResponse,
  RUN_ERROR_GUIDANCE,
  type ApiErrorKey,
  type ApiErrorResponse,
} from "./errors";
export {
  composesMainContract,
  composesByIdContract,
  composesVersionsContract,
  composesListContract,
  composesMetadataContract,
  composesInstructionsContract,
  type ComposesMainContract,
  type ComposesByIdContract,
  type ComposesVersionsContract,
  type ComposesListContract,
  type ComposesMetadataContract,
  type ComposesInstructionsContract,
  AGENT_NAME_REGEX,
  agentNameSchema,
  volumeConfigSchema,
  agentDefinitionSchema,
  agentComposeContentSchema,
  agentComposeApiContentSchema,
  composeResponseSchema,
  composeListItemSchema,
  metadataUpdateSchema,
  composeInstructionsResponseSchema,
  ZERO_CAPABILITIES,
  ZERO_CAPABILITY_META,
  type ZeroCapability,
  type ZeroCapabilityMeta,
  // Inferred types
  type ComposeResponse,
  type ComposeListItem,
} from "./composes";
export {
  runsMainContract,
  runsByIdContract,
  runsCancelContract,
  runEventsContract,
  runTelemetryContract,
  runSystemLogContract,
  runMetricsContract,
  runAgentEventsContract,
  runNetworkLogsContract,
  logsSearchContract,
  ALL_RUN_STATUSES,
  runStatusSchema,
  unifiedRunRequestSchema,
  createRunResponseSchema,
  getRunResponseSchema,
  runListItemSchema,
  runsListResponseSchema,
  cancelRunResponseSchema,
  runEventSchema,
  runResultSchema,
  runStateSchema,
  eventsResponseSchema,
  telemetryMetricSchema,
  telemetryResponseSchema,
  systemLogResponseSchema,
  metricsResponseSchema,
  agentEventsResponseSchema,
  networkLogEntrySchema,
  networkLogsResponseSchema,
  searchResultSchema,
  logsSearchResponseSchema,
  type RunsMainContract,
  type RunsByIdContract,
  type RunsCancelContract,
  type RunEventsContract,
  type RunTelemetryContract,
  type RunSystemLogContract,
  type RunMetricsContract,
  type RunAgentEventsContract,
  type RunNetworkLogsContract,
  type LogsSearchContract,
  // Inferred types
  type RunStatus,
  type RunResult,
  type RunState,
  type RunEvent,
  type CreateRunResponse,
  type GetRunResponse,
  type RunListItem,
  type RunsListResponse,
  type CancelRunResponse,
  type EventsResponse,
  type TelemetryMetric,
  type TelemetryResponse,
  type SystemLogResponse,
  type MetricsResponse,
  type AgentEventsResponse,
  type NetworkLogEntry,
  type NetworkLogsResponse,
  type SearchResult,
  type LogsSearchResponse,
  runsQueueContract,
  queueEntrySchema,
  runningTaskSchema,
  concurrencyInfoSchema,
  queueResponseSchema,
  type RunsQueueContract,
  type QueueEntry,
  type RunningTask,
  type ConcurrencyInfo,
  type QueueResponse,
} from "./runs";
export {
  storagesContract,
  storageTypeSchema,
  uploadStorageResponseSchema,
  // Direct upload schemas (shared with webhooks)
  MAX_FILE_SIZE_BYTES,
  fileEntryWithHashSchema,
  storageChangesSchema,
  presignedUploadSchema,
  // Direct upload contracts (CLI endpoints)
  storagesPrepareContract,
  storagesCommitContract,
  storagesDownloadContract,
  storagesListContract,
  type StoragesContract,
  type StoragesPrepareContract,
  type StoragesCommitContract,
  type StoragesDownloadContract,
  type StoragesListContract,
} from "./storages";
export {
  webhookEventsContract,
  webhookCompleteContract,
  webhookCheckpointsContract,
  webhookHeartbeatContract,
  webhookStoragesContract,
  webhookStoragesIncrementalContract,
  webhookTelemetryContract,
  // Direct upload contracts (Webhook endpoints for sandbox)
  webhookStoragesPrepareContract,
  webhookStoragesCommitContract,
  type WebhookEventsContract,
  type WebhookCompleteContract,
  type WebhookCheckpointsContract,
  type WebhookHeartbeatContract,
  type WebhookStoragesContract,
  type WebhookStoragesIncrementalContract,
  type WebhookTelemetryContract,
  type WebhookStoragesPrepareContract,
  type WebhookStoragesCommitContract,
} from "./webhooks";
export {
  cliAuthDeviceContract,
  cliAuthTokenContract,
  cliAuthOrgContract,
  type CliAuthDeviceContract,
  type CliAuthTokenContract,
  type CliAuthOrgContract,
} from "./cli-auth";
export { authContract, type AuthContract } from "./auth";
export {
  cronCleanupSandboxesContract,
  cleanupResultSchema,
  cleanupResponseSchema,
  type CronCleanupSandboxesContract,
} from "./cron";
export {
  orgDefaultAgentContract,
  orgSlugSchema,
  orgResponseSchema,
  updateOrgRequestSchema,
  orgTierSchema,
  type OrgDefaultAgentContract,
  type OrgResponse,
  type UpdateOrgRequest,
  type OrgTier,
} from "./orgs";
export {
  secretNameSchema,
  secretTypeSchema,
  secretResponseSchema,
  secretListResponseSchema,
  setSecretRequestSchema,
  type SecretResponse,
  type SecretListResponse,
  type SetSecretRequest,
  type SecretType,
} from "./secrets";
export {
  variableNameSchema,
  variableResponseSchema,
  variableListResponseSchema,
  setVariableRequestSchema,
  type VariableResponse,
  type VariableListResponse,
  type SetVariableRequest,
} from "./variables";
export {
  modelProviderTypeSchema,
  modelProviderFrameworkSchema,
  modelProviderResponseSchema,
  modelProviderListResponseSchema,
  upsertModelProviderRequestSchema,
  upsertModelProviderResponseSchema,
  updateModelRequestSchema,
  MODEL_PROVIDER_TYPES,
  getFrameworkForType,
  getSecretNameForType,
  getEnvironmentMapping,
  getModels,
  getDefaultModel,
  hasModelSelection,
  allowsCustomModel,
  getCustomModelPlaceholder,
  // Provider compatibility
  getProviderBaseUrl,
  areProvidersCompatible,
  // Selectable provider filtering
  getSelectableProviderTypes,
  // Multi-auth provider support
  hasAuthMethods,
  getAuthMethodsForType,
  getDefaultAuthMethod,
  getSecretsForAuthMethod,
  getSecretNamesForAuthMethod,
  type ModelProviderType,
  type ModelProviderFramework,
  type ModelProviderResponse,
  type ModelProviderListResponse,
  type UpsertModelProviderRequest,
  type UpsertModelProviderResponse,
  type UpdateModelRequest,
  // Multi-auth provider types
  type SecretFieldConfig,
  type AuthMethodConfig,
  // Firewall gateway for model providers
  MODEL_PROVIDER_FIREWALL_CONFIGS,
  getModelProviderFirewall,
  // VM0 managed provider
  VM0_ORG_SLUG,
  VM0_MODEL_TO_PROVIDER,
  getVm0ConcreteProviderType,
  getVm0Vendor,
} from "./model-providers";
export {
  sessionsContract,
  sessionsByIdContract,
  sessionMessagesContract,
  checkpointsByIdContract,
  storedChatMessageSchema,
  sessionResponseSchema,
  sessionListItemSchema,
  checkpointResponseSchema,
  agentComposeSnapshotSchema,
  artifactSnapshotSchema,
  volumeVersionsSnapshotSchema,
  type SessionsContract,
  type SessionsByIdContract,
  type SessionMessagesContract,
  type CheckpointsByIdContract,
  // Inferred types
  type StoredChatMessage,
  type SessionResponse,
  type SessionListItem,
  type CheckpointResponse,
  type AgentComposeSnapshot,
  type ArtifactSnapshot,
  type VolumeVersionsSnapshot,
} from "./sessions";
export {
  chatThreadsContract,
  chatThreadByIdContract,
  chatThreadRunsContract,
  chatThreadListItemSchema,
  chatThreadDetailSchema,
  summaryEntrySchema,
  type SummaryEntry,
  type ChatThreadsContract,
  type ChatThreadByIdContract,
  type ChatThreadRunsContract,
  type ChatThreadListItem,
  type ChatThreadDetail,
} from "./chat-threads";
export {
  runnersPollContract,
  runnersJobClaimContract,
  runnerGroupSchema,
  jobSchema,
  executionContextSchema,
  storedExecutionContextSchema,
  storageEntrySchema,
  DEFAULT_PROFILE,
  artifactEntrySchema,
  storageManifestSchema,
  resumeSessionSchema,
  type RunnersPollContract,
  type RunnersJobClaimContract,
  type Job,
  type ExecutionContext,
  type StoredExecutionContext,
  type StorageEntry,
  type ArtifactEntry,
  type StorageManifest,
  type ResumeSession,
} from "./runners";

export {
  runnerRealtimeTokenContract,
  type RunnerRealtimeTokenContract,
} from "./realtime";

export {
  logsListContract,
  logsByIdContract,
  logStatusSchema,
  logEntrySchema,
  paginationSchema,
  logsListResponseSchema,
  artifactSchema,
  logDetailSchema,
  triggerSourceSchema,
  type LogsListContract,
  type LogsByIdContract,
  // Inferred types
  type LogStatus,
  type LogEntry,
  type Pagination,
  type LogsListResponse,
  type Artifact,
  type LogDetail,
  type TriggerSource,
  type LogsFilters,
} from "./logs";

export {
  connectorTypeSchema,
  connectorSessionStatusSchema,
  connectorResponseSchema,
  connectorListResponseSchema,
  connectorSessionResponseSchema,
  connectorSessionStatusResponseSchema,
  CONNECTOR_TYPES,
  getConnectorAuthMethods,
  getConnectorDefaultAuthMethod,
  getConnectorSecretsForAuthMethod,
  getConnectorSecretNames,
  getConnectorEnvironmentMapping,
  getConnectorDerivedNames,
  getConnectorProvidedSecretNames,
  getConnectorManagedSecretNames,
  getConnectorTypeForSecretName,
  getConnectorOAuthConfig,
  hasRequiredScopes,
  getScopeDiff,
  scopeDiffResponseSchema,
  type ScopeDiff,
  type ScopeDiffResponse,
  getApiTokenRequiredSecretNames,
  getApiTokenFieldsByType,
  deriveApiTokenConnectedTypes,
  type ConnectorType,
  type ConnectorSessionStatus,
  type ConnectorResponse,
  type ConnectorListResponse,
  type ConnectorSessionResponse,
  type ConnectorSessionStatusResponse,
  type ConnectorConfig,
  type ConnectorSecretConfig,
  type ConnectorAuthMethodConfig,
  type ConnectorOAuthConfig,
  computerConnectorCreateResponseSchema,
  type ComputerConnectorCreateResponse,
} from "./connectors";

export {
  extractSecretNamesFromApis,
  firewallPermissionSchema,
  firewallApiSchema,
  firewallSchema,
  experimentalFirewallsSchema,
  firewallConfigSchema,
  firewallPolicyValueSchema,
  firewallPoliciesSchema,
  type FirewallConfig,
  type ExpandedFirewallConfig,
  type FirewallApi,
  type Firewall,
  type ExperimentalFirewalls,
  type FirewallPolicyValue,
  type FirewallPolicies,
} from "./firewalls";

export {
  expandFirewallConfigs,
  collectAndValidatePermissions,
  validateRule,
  validateBaseUrl,
  type FirewallSelection,
} from "./firewall-expander";

export {
  userPreferencesResponseSchema,
  updateUserPreferencesRequestSchema,
  type UserPreferencesResponse,
  type UpdateUserPreferencesRequest,
  sendModeSchema,
  type SendMode,
} from "./zero-user-preferences";
export {
  orgListItemSchema,
  orgListResponseSchema,
  type OrgListItem,
  type OrgListResponse,
} from "./org-list";
export {
  orgRoleSchema,
  orgMemberSchema,
  orgPendingInvitationSchema,
  orgMembersResponseSchema,
  inviteOrgMemberRequestSchema,
  removeOrgMemberRequestSchema,
  updateOrgMemberRoleRequestSchema,
  orgMessageResponseSchema,
  type OrgRole,
  type OrgMember,
  type OrgPendingInvitation,
  type OrgMembersResponse,
  type InviteOrgMemberRequest,
  type RemoveOrgMemberRequest,
  type UpdateOrgMemberRoleRequest,
  type OrgMessageResponse,
} from "./org-members";
export {
  onboardingStatusContract,
  onboardingCompleteContract,
  onboardingStatusResponseSchema,
  type OnboardingStatusContract,
  type OnboardingCompleteContract,
  type OnboardingStatusResponse,
} from "./onboarding";
export {
  skillsResolveContract,
  skillFrontmatterSchema,
  type SkillsResolveContract,
} from "./skills";
export {
  zeroAgentsMainContract,
  zeroAgentsByIdContract,
  zeroAgentInstructionsContract,
  zeroAgentFirewallPoliciesContract,
  zeroAgentResponseSchema,
  zeroAgentRequestSchema,
  zeroAgentMetadataRequestSchema,
  zeroAgentInstructionsResponseSchema,
  zeroAgentInstructionsRequestSchema,
  zeroAgentFirewallPoliciesRequestSchema,
  type ZeroAgentsMainContract,
  type ZeroAgentsByIdContract,
  type ZeroAgentInstructionsContract,
  type ZeroAgentFirewallPoliciesContract,
  type ZeroAgentResponse,
  type ZeroAgentRequest,
  type ZeroAgentMetadataRequest,
  type ZeroAgentInstructionsResponse,
  type ZeroAgentInstructionsRequest,
  type ZeroAgentFirewallPoliciesRequest,
} from "./zero-agents";
export {
  zeroConnectorsMainContract,
  zeroConnectorsByTypeContract,
  zeroConnectorScopeDiffContract,
  zeroConnectorsSearchContract,
  zeroConnectorSessionsContract,
  zeroConnectorSessionByIdContract,
  zeroComputerConnectorContract,
  type ConnectorSearchAuthMethod,
  type ZeroConnectorsMainContract,
  type ZeroConnectorsByTypeContract,
  type ZeroConnectorScopeDiffContract,
  type ZeroConnectorsSearchContract,
  type ZeroConnectorSessionsContract,
  type ZeroConnectorSessionByIdContract,
  type ZeroComputerConnectorContract,
} from "./zero-connectors";
export {
  zeroOrgContract,
  zeroOrgLeaveContract,
  zeroOrgDeleteContract,
  type ZeroOrgContract,
  type ZeroOrgLeaveContract,
  type ZeroOrgDeleteContract,
} from "./zero-org";
export { zeroOrgListContract, type ZeroOrgListContract } from "./zero-org-list";
export {
  zeroOrgMembersContract,
  zeroOrgInviteContract,
  type ZeroOrgMembersContract,
  type ZeroOrgInviteContract,
} from "./zero-org-members";
export {
  zeroComposesMainContract,
  zeroComposesByIdContract,
  zeroComposesListContract,
  type ZeroComposesMainContract,
  type ZeroComposesByIdContract,
  type ZeroComposesListContract,
} from "./zero-composes";
export {
  zeroRunsMainContract,
  zeroRunsByIdContract,
  zeroRunsCancelContract,
  zeroRunsQueueContract,
  zeroRunAgentEventsContract,
  type ZeroRunsMainContract,
  type ZeroRunsByIdContract,
  type ZeroRunsCancelContract,
  type ZeroRunsQueueContract,
  type ZeroRunAgentEventsContract,
} from "./zero-runs";
export {
  zeroSchedulesMainContract,
  zeroSchedulesByNameContract,
  zeroSchedulesEnableContract,
  scheduleResponseSchema,
  scheduleListResponseSchema,
  deployScheduleResponseSchema,
  type ZeroSchedulesMainContract,
  type ZeroSchedulesByNameContract,
  type ZeroSchedulesEnableContract,
  zeroScheduleRunContract,
  type ZeroScheduleRunContract,
  type ScheduleResponse,
  type ScheduleListResponse,
  type DeployScheduleResponse,
} from "./zero-schedules";
export {
  zeroModelProvidersMainContract,
  zeroModelProvidersByTypeContract,
  zeroModelProvidersDefaultContract,
  zeroModelProvidersUpdateModelContract,
  type ZeroModelProvidersMainContract,
  type ZeroModelProvidersByTypeContract,
  type ZeroModelProvidersDefaultContract,
  type ZeroModelProvidersUpdateModelContract,
} from "./zero-model-providers";
export {
  zeroUserPreferencesContract,
  type ZeroUserPreferencesContract,
} from "./zero-user-preferences";
export {
  zeroSecretsContract,
  zeroSecretsByNameContract,
  zeroVariablesContract,
  zeroVariablesByNameContract,
  type ZeroSecretsContract,
  type ZeroSecretsByNameContract,
  type ZeroVariablesContract,
  type ZeroVariablesByNameContract,
} from "./zero-secrets";
export {
  zeroSessionsByIdContract,
  type ZeroSessionsByIdContract,
} from "./zero-sessions";
export {
  integrationsSlackMessageContract,
  type IntegrationsSlackMessageContract,
  type SendSlackMessageBody,
  type SendSlackMessageResponse,
} from "./integrations";
export {
  zeroBillingStatusContract,
  zeroBillingCheckoutContract,
  zeroBillingPortalContract,
  zeroBillingAutoRechargeContract,
  zeroBillingInvoicesContract,
  zeroBillingDowngradeContract,
  type ZeroBillingStatusContract,
  type ZeroBillingCheckoutContract,
  type ZeroBillingPortalContract,
  type ZeroBillingAutoRechargeContract,
  type ZeroBillingInvoicesContract,
  type ZeroBillingDowngradeContract,
  // Inferred types
  type BillingStatusResponse,
  type AutoRechargeConfig,
  type CheckoutResponse,
  type PortalResponse,
  type BillingInvoice,
  type BillingInvoicesResponse,
  type DowngradeResponse,
} from "./zero-billing";
export {
  zeroUsageMembersContract,
  type ZeroUsageMembersContract,
  // Inferred types
  type MemberUsage,
  type UsageMembersResponse,
} from "./zero-usage";
export {
  zeroTeamContract,
  teamComposeItemSchema,
  type ZeroTeamContract,
  type TeamComposeItem,
} from "./zero-team";
export {
  zeroIntegrationsSlackContract,
  slackOrgStatusSchema,
  type ZeroIntegrationsSlackContract,
  type SlackOrgStatus,
} from "./zero-integrations-slack";
export {
  zeroSlackConnectContract,
  type ZeroSlackConnectContract,
} from "./zero-slack-connect";
export {
  zeroSlackChannelsContract,
  slackChannelSchema,
  type ZeroSlackChannelsContract,
  type SlackChannel,
} from "./zero-slack-channels";
export {
  zeroQueuePositionContract,
  type ZeroQueuePositionContract,
} from "./zero-queue-position";
export {
  zeroMemberCreditCapContract,
  type ZeroMemberCreditCapContract,
} from "./zero-member-credit-cap";
