-- Final connector credential contraction reruns the exact immutable #22124
-- reconciliation before refusing unresolved state and installing hard constraints.
-- Immutable snapshot of the static connector credential contract at #22124.
-- Unknown or ambiguous rows deliberately remain unresolved for production
-- readiness diagnostics and the later #22126 contraction gate.
WITH connector_versions(connector_ref, auth_method, storage_version) AS (
  VALUES
    ('adzuna', 'api-token', 1),
    ('agentmail', 'api-token', 1),
    ('agora', 'api-token', 1),
    ('ahrefs', 'api-token', 1),
    ('ahrefs', 'oauth', 1),
    ('airtable', 'oauth', 1),
    ('alchemy', 'api-token', 1),
    ('altium-365', 'api-token', 1),
    ('amadeus', 'api-token', 1),
    ('amplitude', 'api-token', 1),
    ('anthropic-managed-agents', 'api-token', 1),
    ('apify', 'api-token', 1),
    ('apollo', 'api-token', 1),
    ('archer', 'api-token', 1),
    ('ardent', 'api-token', 1),
    ('arga-labs', 'api-token', 1),
    ('armature', 'api-token', 1),
    ('asana', 'oauth', 1),
    ('ashby', 'api-token', 1),
    ('atlascloud', 'api-token', 1),
    ('atlassian', 'api-token', 1),
    ('attio', 'api-token', 1),
    ('aviationstack', 'api-token', 1),
    ('aws', 'cli', 1),
    ('axiom', 'api-token', 1),
    ('base44', 'oauth', 1),
    ('bentolabs-ai', 'api-token', 1),
    ('bentoml', 'api-token', 1),
    ('bfl', 'api-token', 1),
    ('bill', 'api-token', 1),
    ('bitrefill', 'api-token', 1),
    ('bitrix', 'api-token', 1),
    ('bland', 'api-token', 1),
    ('bloom', 'api-token', 1),
    ('box', 'oauth', 1),
    ('brave-search', 'api-token', 1),
    ('brevo', 'api-token', 1),
    ('brex', 'api-token', 1),
    ('bright-data', 'api-token', 1),
    ('browser-use', 'api-token', 1),
    ('browserbase', 'api-token', 1),
    ('browserless', 'api-token', 1),
    ('browserstack', 'api-token', 1),
    ('bubblemaps', 'api-token', 1),
    ('buffer', 'api-token', 1),
    ('builtwith', 'api-token', 1),
    ('cal-com', 'api-token', 1),
    ('cal-com', 'oauth', 1),
    ('calendly', 'api-token', 1),
    ('canva', 'oauth', 1),
    ('chatwoot', 'api-token', 1),
    ('checkr', 'api-token', 1),
    ('chert', 'api-token', 1),
    ('clado', 'api-token', 1),
    ('clearbit', 'api-token', 1),
    ('clerk', 'api-token', 1),
    ('clickup', 'api-token', 1),
    ('close', 'oauth', 1),
    ('cloudflare', 'api-token', 1),
    ('cloudflare', 'oauth', 1),
    ('cloudinary', 'api-token', 1),
    ('coda', 'api-token', 1),
    ('coingecko', 'api-token', 1),
    ('copper', 'oauth', 1),
    ('coresignal', 'api-token', 1),
    ('cronlytic', 'api-token', 1),
    ('crustdata', 'api-token', 1),
    ('cursor', 'api-token', 1),
    ('customer-io', 'api-token', 1),
    ('datadog', 'oauth', 1),
    ('daytona', 'api-token', 1),
    ('db9', 'api-token', 1),
    ('deel', 'api-token', 1),
    ('deel', 'oauth', 1),
    ('deepseek', 'api-token', 1),
    ('defillama', 'api-token', 1),
    ('devto', 'api-token', 1),
    ('diffbot', 'api-token', 1),
    ('dify', 'api-token', 1),
    ('discord', 'api-token', 1),
    ('discord-webhook', 'api-token', 1),
    ('docusign', 'oauth', 1),
    ('doppler', 'api-token', 1),
    ('doubao', 'api-token', 1),
    ('drive9', 'api-token', 1),
    ('dropbox', 'api-token', 1),
    ('dropbox', 'oauth', 1),
    ('dropbox-sign', 'api-token', 1),
    ('duffel', 'api-token', 1),
    ('e2b', 'api-token', 1),
    ('elevenlabs', 'api-token', 1),
    ('etherscan', 'api-token', 1),
    ('etsy', 'api-token', 1),
    ('exa', 'api-token', 1),
    ('expensify', 'api-token', 1),
    ('explorium', 'api-token', 1),
    ('faire', 'api-token', 1),
    ('fal', 'api-token', 1),
    ('figma', 'api-token', 1),
    ('figma', 'oauth', 1),
    ('firecrawl', 'api-token', 1),
    ('fireflies', 'api-token', 1),
    ('flightaware', 'api-token', 1),
    ('freshdesk', 'api-token', 1),
    ('gamma', 'api-token', 1),
    ('garmin-connect', 'oauth', 1),
    ('gemini', 'api-token', 1),
    ('github', 'oauth', 1),
    ('gitlab', 'api-token', 1),
    ('gmail', 'oauth', 1),
    ('gong', 'api-token', 1),
    ('google-ads', 'oauth', 1),
    ('google-analytics', 'oauth', 1),
    ('google-calendar', 'oauth', 1),
    ('google-cloud', 'oauth', 1),
    ('google-contacts', 'oauth', 1),
    ('google-docs', 'oauth', 1),
    ('google-drive', 'oauth', 1),
    ('google-forms', 'oauth', 1),
    ('google-maps', 'oauth', 1),
    ('google-meet', 'oauth', 1),
    ('google-search-console', 'oauth', 1),
    ('google-sheets', 'oauth', 1),
    ('granola', 'api-token', 1),
    ('greenhouse', 'api-token', 1),
    ('groq', 'api-token', 1),
    ('gumroad', 'api-token', 1),
    ('gumroad', 'oauth', 1),
    ('helicone', 'api-token', 1),
    ('heygen', 'api-token', 1),
    ('hitem3d', 'api-token', 1),
    ('honcho', 'api-token', 1),
    ('htmlcsstoimage', 'api-token', 1),
    ('hubspot', 'oauth', 1),
    ('hugging-face', 'api-token', 1),
    ('hume', 'api-token', 1),
    ('hunter', 'api-token', 1),
    ('imgur', 'api-token', 1),
    ('infisical', 'api-token', 1),
    ('insforge', 'api-token', 1),
    ('instagram', 'api-token', 1),
    ('instantly', 'api-token', 1),
    ('intercom', 'api-token', 1),
    ('interfaze', 'api-token', 1),
    ('intervals-icu', 'oauth', 1),
    ('inth', 'api-token', 1),
    ('ironclad', 'api-token', 1),
    ('jam', 'api-token', 1),
    ('jira', 'api-token', 1),
    ('jotform', 'api-token', 1),
    ('keyframe-labs', 'api-token', 1),
    ('klaviyo', 'api-token', 1),
    ('kommo', 'api-token', 1),
    ('kugelaudio', 'api-token', 1),
    ('langfuse', 'api-token', 1),
    ('langsmith', 'api-token', 1),
    ('lark', 'api-token', 1),
    ('limrun', 'api-token', 1),
    ('line', 'api-token', 1),
    ('linear', 'oauth', 1),
    ('loops', 'api-token', 1),
    ('luma', 'api-token', 1),
    ('luma-ai', 'api-token', 1),
    ('mailchimp', 'api-token', 1),
    ('mailchimp', 'oauth', 1),
    ('mailsac', 'api-token', 1),
    ('make', 'api-token', 1),
    ('manus', 'api-token', 1),
    ('mapbox', 'api-token', 1),
    ('maskdb', 'api-token', 1),
    ('massive', 'api-token', 1),
    ('mathpix', 'api-token', 1),
    ('mem0', 'api-token', 1),
    ('mercury', 'api-token', 1),
    ('mercury', 'oauth', 1),
    ('meshy', 'api-token', 1),
    ('meta-ads', 'oauth', 1),
    ('metabase', 'api-token', 1),
    ('microsoft-365', 'oauth', 1),
    ('minicor', 'api-token', 1),
    ('minimax', 'api-token', 1),
    ('minio', 'api-token', 1),
    ('miro', 'api-token', 1),
    ('mixpanel', 'api-token', 1),
    ('modal', 'api-token', 1),
    ('monday', 'oauth', 1),
    ('moss', 'api-token', 1),
    ('msg9', 'api-token', 1),
    ('n8n', 'api-token', 1),
    ('neon', 'api-token', 1),
    ('neon', 'oauth', 1),
    ('netdata', 'api-token', 1),
    ('netsuite', 'api-token', 1),
    ('netter', 'api-token', 1),
    ('nintendo-store', 'api', 1),
    ('nintendo-switch-parental-controls', 'api', 1),
    ('notion', 'oauth', 1),
    ('novita', 'api-token', 1),
    ('nyne', 'api-token', 1),
    ('oddpool', 'api-token', 1),
    ('onyx', 'api-token', 1),
    ('openai', 'api-token', 1),
    ('openrouter', 'api-token', 1),
    ('openweather', 'api-token', 1),
    ('outlook-calendar', 'oauth', 1),
    ('outlook-mail', 'oauth', 1),
    ('pandadoc', 'api-token', 1),
    ('parallel', 'api-token', 1),
    ('paypal', 'api-token', 1),
    ('pdf4me', 'api-token', 1),
    ('pdfco', 'api-token', 1),
    ('pdforge', 'api-token', 1),
    ('people-data-labs', 'api-token', 1),
    ('perplexity', 'api-token', 1),
    ('pexels', 'api-token', 1),
    ('pika', 'api-token', 1),
    ('pinecone', 'api-token', 1),
    ('pipedream', 'api-token', 1),
    ('pipedrive', 'api-token', 1),
    ('plain', 'api-token', 1),
    ('plausible', 'api-token', 1),
    ('playstation', 'api', 1),
    ('podchaser', 'api-token', 1),
    ('porkbun', 'api-token', 1),
    ('posthog', 'api-token', 1),
    ('posthog', 'oauth', 1),
    ('primitive', 'api-token', 1),
    ('printful', 'api-token', 1),
    ('prisma-postgres', 'api-token', 1),
    ('productlane', 'api-token', 1),
    ('profound', 'api-token', 1),
    ('pushinator', 'api-token', 1),
    ('qdrant', 'api-token', 1),
    ('qiita', 'api-token', 1),
    ('qomplement', 'api-token', 1),
    ('quickbooks', 'oauth', 1),
    ('railway', 'api-token', 1),
    ('railway-project', 'api-token', 1),
    ('ramp', 'api-token', 1),
    ('reap', 'api-token', 1),
    ('recraft', 'api-token', 1),
    ('reddit', 'oauth', 1),
    ('reducto', 'api-token', 1),
    ('render', 'api-token', 1),
    ('rentahuman', 'api-token', 1),
    ('rentcast', 'api-token', 1),
    ('replicas', 'api-token', 1),
    ('replicate', 'api-token', 1),
    ('reportei', 'api-token', 1),
    ('resend', 'api-token', 1),
    ('revenuecat', 'api-token', 1),
    ('river-markets', 'api-token', 1),
    ('runtime', 'api-token', 1),
    ('runway', 'api-token', 1),
    ('salesforce', 'api-token', 1),
    ('salesgraph', 'api-token', 1),
    ('scrapeninja', 'api-token', 1),
    ('segment', 'api-token', 1),
    ('semrush', 'api-token', 1),
    ('sendgrid', 'api-token', 1),
    ('sentry', 'oauth', 1),
    ('serpapi', 'api-token', 1),
    ('servicenow', 'api-token', 1),
    ('shopify', 'api-token', 1),
    ('shortio', 'api-token', 1),
    ('silmaril', 'api-token', 1),
    ('similarweb', 'api-token', 1),
    ('slack', 'oauth', 1),
    ('slack-webhook', 'api-token', 1),
    ('slock', 'oauth', 1),
    ('smol-machines', 'api-token', 1),
    ('snowflake', 'api-token', 1),
    ('sociavault', 'api-token', 1),
    ('sponge', 'api-token', 1),
    ('spotify', 'oauth', 1),
    ('sproutgigs', 'api-token', 1),
    ('square', 'api-token', 1),
    ('stability-ai', 'api-token', 1),
    ('stablebrowse', 'api-token', 1),
    ('steam', 'openid', 1),
    ('strapi', 'api-token', 1),
    ('strava', 'oauth', 1),
    ('streak', 'api-token', 1),
    ('stripe', 'api-token', 1),
    ('stripe', 'cli', 1),
    ('stripe', 'oauth', 1),
    ('supabase', 'api-token', 1),
    ('supabase', 'oauth', 1),
    ('supadata', 'api-token', 1),
    ('supermemory', 'api-token', 1),
    ('tavily', 'api-token', 1),
    ('test-oauth', 'api', 1),
    ('test-oauth', 'api-token', 1),
    ('test-oauth', 'oauth', 1),
    ('test-oauth-device', 'api', 1),
    ('test-oauth-device', 'oauth', 1),
    ('testerarmy', 'api-token', 1),
    ('testrail', 'api-token', 1),
    ('ticketmaster', 'api-token', 1),
    ('tiktok-ads', 'oauth', 1),
    ('tldv', 'api-token', 1),
    ('todoist', 'oauth', 1),
    ('together', 'api-token', 1),
    ('totalis', 'api-token', 1),
    ('trellis', 'api-token', 1),
    ('tripo', 'api-token', 1),
    ('twenty', 'api-token', 1),
    ('twilio', 'api-token', 1),
    ('typeform', 'api-token', 1),
    ('v0', 'api-token', 1),
    ('vercel', 'oauth', 1),
    ('voquill', 'api-token', 1),
    ('wandb', 'api-token', 1),
    ('webflow', 'api-token', 1),
    ('webflow', 'oauth', 1),
    ('weread', 'api-token', 1),
    ('whale-alert', 'api-token', 1),
    ('wix', 'api-token', 1),
    ('workday', 'api-token', 1),
    ('workos', 'api-token', 1),
    ('wrike', 'api-token', 1),
    ('x', 'oauth', 1),
    ('xero', 'oauth', 1),
    ('youtube', 'oauth', 1),
    ('zapier', 'api-token', 1),
    ('zapsign', 'api-token', 1),
    ('zendesk', 'api-token', 1),
    ('zep', 'api-token', 1),
    ('zeptomail', 'api-token', 1),
    ('zoom', 'oauth', 1)
)
UPDATE "connectors" AS connector
SET "storage_version" = mapping.storage_version
FROM connector_versions AS mapping
WHERE connector."storage_version" IS NULL
  AND connector."type" = mapping.connector_ref
  AND connector."auth_method" = mapping.auth_method;
--> statement-breakpoint
WITH connector_credential_names(connector_ref, credential_kind, credential_name) AS (
  VALUES
    ('adzuna', 'secret', 'ADZUNA_APP_KEY'),
    ('adzuna', 'variable', 'ADZUNA_APP_ID'),
    ('agentmail', 'secret', 'AGENTMAIL_TOKEN'),
    ('agora', 'secret', 'AGORA_APP_CERTIFICATE'),
    ('agora', 'secret', 'AGORA_CUSTOMER_ID'),
    ('agora', 'secret', 'AGORA_CUSTOMER_SECRET'),
    ('agora', 'variable', 'AGORA_APP_ID'),
    ('ahrefs', 'secret', 'AHREFS_ACCESS_TOKEN'),
    ('ahrefs', 'secret', 'AHREFS_REFRESH_TOKEN'),
    ('ahrefs', 'secret', 'AHREFS_TOKEN'),
    ('airtable', 'secret', 'AIRTABLE_ACCESS_TOKEN'),
    ('airtable', 'secret', 'AIRTABLE_REFRESH_TOKEN'),
    ('alchemy', 'secret', 'ALCHEMY_API_KEY'),
    ('altium-365', 'secret', 'ALTIUM365_TOKEN'),
    ('altium-365', 'variable', 'ALTIUM365_WORKSPACE_URL'),
    ('amadeus', 'secret', 'AMADEUS_API_KEY'),
    ('amadeus', 'secret', 'AMADEUS_API_SECRET'),
    ('amplitude', 'secret', 'AMPLITUDE_API_KEY'),
    ('amplitude', 'secret', 'AMPLITUDE_SECRET_KEY'),
    ('anthropic-managed-agents', 'secret', 'ANTHROPIC_MANAGED_AGENTS_TOKEN'),
    ('apify', 'secret', 'APIFY_TOKEN'),
    ('apollo', 'secret', 'APOLLO_TOKEN'),
    ('archer', 'secret', 'ARCHER_API_KEY'),
    ('ardent', 'secret', 'ARDENT_API_KEY'),
    ('arga-labs', 'secret', 'ARGA_LABS_API_KEY'),
    ('armature', 'secret', 'ARMATURE_API_KEY'),
    ('asana', 'secret', 'ASANA_ACCESS_TOKEN'),
    ('asana', 'secret', 'ASANA_REFRESH_TOKEN'),
    ('ashby', 'secret', 'ASHBY_TOKEN'),
    ('atlascloud', 'secret', 'ATLASCLOUD_API_KEY'),
    ('atlassian', 'secret', 'ATLASSIAN_TOKEN'),
    ('atlassian', 'variable', 'ATLASSIAN_DOMAIN'),
    ('atlassian', 'variable', 'ATLASSIAN_EMAIL'),
    ('attio', 'secret', 'ATTIO_TOKEN'),
    ('aviationstack', 'secret', 'AVIATIONSTACK_TOKEN'),
    ('aws', 'secret', 'AWS_ACCESS_KEY_ID'),
    ('aws', 'secret', 'AWS_LOGIN_DPOP_KEY'),
    ('aws', 'secret', 'AWS_LOGIN_REFRESH_TOKEN'),
    ('aws', 'secret', 'AWS_SECRET_ACCESS_KEY'),
    ('aws', 'secret', 'AWS_SESSION_TOKEN'),
    ('aws', 'variable', 'AWS_REGION'),
    ('aws', 'variable', 'AWS_SIGNIN_REGION'),
    ('axiom', 'secret', 'AXIOM_TOKEN'),
    ('base44', 'secret', 'BASE44_ACCESS_TOKEN'),
    ('base44', 'secret', 'BASE44_REFRESH_TOKEN'),
    ('bentolabs-ai', 'secret', 'BENTOLABS_AI_API_KEY'),
    ('bentoml', 'secret', 'BENTO_CLOUD_API_KEY'),
    ('bentoml', 'variable', 'BENTO_CLOUD_API_ENDPOINT'),
    ('bfl', 'secret', 'BFL_API_KEY'),
    ('bill', 'secret', 'BILL_TOKEN'),
    ('bitrefill', 'secret', 'BITREFILL_TOKEN'),
    ('bitrix', 'secret', 'BITRIX_WEBHOOK_URL'),
    ('bland', 'secret', 'BLAND_API_KEY'),
    ('bloom', 'secret', 'BLOOM_API_KEY'),
    ('box', 'secret', 'BOX_ACCESS_TOKEN'),
    ('box', 'secret', 'BOX_REFRESH_TOKEN'),
    ('brave-search', 'secret', 'BRAVE_API_KEY'),
    ('brevo', 'secret', 'BREVO_TOKEN'),
    ('brex', 'secret', 'BREX_TOKEN'),
    ('bright-data', 'secret', 'BRIGHTDATA_TOKEN'),
    ('browser-use', 'secret', 'BROWSER_USE_TOKEN'),
    ('browserbase', 'secret', 'BROWSERBASE_TOKEN'),
    ('browserbase', 'variable', 'BROWSERBASE_PROJECT_ID'),
    ('browserless', 'secret', 'BROWSERLESS_TOKEN'),
    ('browserstack', 'secret', 'BROWSERSTACK_ACCESS_KEY'),
    ('browserstack', 'secret', 'BROWSERSTACK_USERNAME'),
    ('bubblemaps', 'secret', 'BUBBLEMAPS_API_KEY'),
    ('buffer', 'secret', 'BUFFER_TOKEN'),
    ('builtwith', 'secret', 'BUILTWITH_TOKEN'),
    ('cal-com', 'secret', 'CALCOM_ACCESS_TOKEN'),
    ('cal-com', 'secret', 'CALCOM_REFRESH_TOKEN'),
    ('cal-com', 'secret', 'CALCOM_TOKEN'),
    ('calendly', 'secret', 'CALENDLY_TOKEN'),
    ('canva', 'secret', 'CANVA_ACCESS_TOKEN'),
    ('canva', 'secret', 'CANVA_REFRESH_TOKEN'),
    ('chatwoot', 'secret', 'CHATWOOT_TOKEN'),
    ('checkr', 'secret', 'CHECKR_TOKEN'),
    ('chert', 'secret', 'CHERT_API_KEY'),
    ('clado', 'secret', 'CLADO_TOKEN'),
    ('clearbit', 'secret', 'CLEARBIT_TOKEN'),
    ('clerk', 'secret', 'CLERK_TOKEN'),
    ('clickup', 'secret', 'CLICKUP_TOKEN'),
    ('close', 'secret', 'CLOSE_ACCESS_TOKEN'),
    ('close', 'secret', 'CLOSE_REFRESH_TOKEN'),
    ('cloudflare', 'secret', 'CLOUDFLARE_ACCESS_TOKEN'),
    ('cloudflare', 'secret', 'CLOUDFLARE_REFRESH_TOKEN'),
    ('cloudflare', 'secret', 'CLOUDFLARE_TOKEN'),
    ('cloudinary', 'secret', 'CLOUDINARY_API_SECRET'),
    ('cloudinary', 'secret', 'CLOUDINARY_TOKEN'),
    ('cloudinary', 'variable', 'CLOUDINARY_CLOUD_NAME'),
    ('coda', 'secret', 'CODA_TOKEN'),
    ('coingecko', 'secret', 'COINGECKO_TOKEN'),
    ('copper', 'secret', 'COPPER_ACCESS_TOKEN'),
    ('coresignal', 'secret', 'CORESIGNAL_TOKEN'),
    ('cronlytic', 'secret', 'CRONLYTIC_API_KEY'),
    ('cronlytic', 'variable', 'CRONLYTIC_USER_ID'),
    ('crustdata', 'secret', 'CRUSTDATA_TOKEN'),
    ('cursor', 'secret', 'CURSOR_TOKEN'),
    ('customer-io', 'secret', 'CUSTOMERIO_APP_TOKEN'),
    ('datadog', 'secret', 'DATADOG_ACCESS_TOKEN'),
    ('datadog', 'secret', 'DATADOG_REFRESH_TOKEN'),
    ('datadog', 'variable', 'DATADOG_DOMAIN'),
    ('daytona', 'secret', 'DAYTONA_API_KEY'),
    ('db9', 'secret', 'DB9_API_KEY'),
    ('deel', 'secret', 'DEEL_ACCESS_TOKEN'),
    ('deel', 'secret', 'DEEL_REFRESH_TOKEN'),
    ('deel', 'secret', 'DEEL_TOKEN'),
    ('deepseek', 'secret', 'DEEPSEEK_TOKEN'),
    ('defillama', 'secret', 'DEFILLAMA_TOKEN'),
    ('devto', 'secret', 'DEVTO_TOKEN'),
    ('diffbot', 'secret', 'DIFFBOT_TOKEN'),
    ('dify', 'secret', 'DIFY_TOKEN'),
    ('discord', 'secret', 'DISCORD_BOT_TOKEN'),
    ('discord-webhook', 'secret', 'DISCORD_WEBHOOK_URL'),
    ('docusign', 'secret', 'DOCUSIGN_ACCESS_TOKEN'),
    ('docusign', 'secret', 'DOCUSIGN_REFRESH_TOKEN'),
    ('doppler', 'secret', 'DOPPLER_TOKEN'),
    ('doubao', 'secret', 'DOUBAO_API_KEY'),
    ('drive9', 'secret', 'DRIVE9_TOKEN'),
    ('dropbox', 'secret', 'DROPBOX_ACCESS_TOKEN'),
    ('dropbox', 'secret', 'DROPBOX_REFRESH_TOKEN'),
    ('dropbox', 'secret', 'DROPBOX_TOKEN'),
    ('dropbox-sign', 'secret', 'DROPBOX_SIGN_TOKEN'),
    ('duffel', 'secret', 'DUFFEL_TOKEN'),
    ('e2b', 'secret', 'E2B_TOKEN'),
    ('elevenlabs', 'secret', 'ELEVENLABS_TOKEN'),
    ('etherscan', 'secret', 'ETHERSCAN_API_KEY'),
    ('etsy', 'secret', 'ETSY_TOKEN'),
    ('exa', 'secret', 'EXA_TOKEN'),
    ('expensify', 'secret', 'EXPENSIFY_PARTNER_USER_SECRET'),
    ('expensify', 'variable', 'EXPENSIFY_PARTNER_USER_ID'),
    ('explorium', 'secret', 'EXPLORIUM_TOKEN'),
    ('faire', 'secret', 'FAIRE_TOKEN'),
    ('fal', 'secret', 'FAL_TOKEN'),
    ('figma', 'secret', 'FIGMA_ACCESS_TOKEN'),
    ('figma', 'secret', 'FIGMA_REFRESH_TOKEN'),
    ('figma', 'secret', 'FIGMA_TOKEN'),
    ('firecrawl', 'secret', 'FIRECRAWL_TOKEN'),
    ('fireflies', 'secret', 'FIREFLIES_TOKEN'),
    ('flightaware', 'secret', 'FLIGHTAWARE_TOKEN'),
    ('freshdesk', 'secret', 'FRESHDESK_TOKEN'),
    ('freshdesk', 'variable', 'FRESHDESK_DOMAIN'),
    ('gamma', 'secret', 'GAMMA_TOKEN'),
    ('garmin-connect', 'secret', 'GARMIN_CONNECT_ACCESS_TOKEN'),
    ('garmin-connect', 'secret', 'GARMIN_CONNECT_REFRESH_TOKEN'),
    ('gemini', 'secret', 'GEMINI_TOKEN'),
    ('github', 'secret', 'GITHUB_ACCESS_TOKEN'),
    ('gitlab', 'secret', 'GITLAB_TOKEN'),
    ('gitlab', 'variable', 'GITLAB_HOST'),
    ('gmail', 'secret', 'GMAIL_ACCESS_TOKEN'),
    ('gmail', 'secret', 'GMAIL_REFRESH_TOKEN'),
    ('gong', 'secret', 'GONG_ACCESS_KEY'),
    ('gong', 'secret', 'GONG_ACCESS_KEY_SECRET'),
    ('gong', 'variable', 'GONG_API_BASE'),
    ('google-ads', 'secret', 'GOOGLE_ADS_ACCESS_TOKEN'),
    ('google-ads', 'secret', 'GOOGLE_ADS_REFRESH_TOKEN'),
    ('google-analytics', 'secret', 'GOOGLE_ANALYTICS_ACCESS_TOKEN'),
    ('google-analytics', 'secret', 'GOOGLE_ANALYTICS_REFRESH_TOKEN'),
    ('google-calendar', 'secret', 'GOOGLE_CALENDAR_ACCESS_TOKEN'),
    ('google-calendar', 'secret', 'GOOGLE_CALENDAR_REFRESH_TOKEN'),
    ('google-cloud', 'secret', 'GOOGLE_CLOUD_ACCESS_TOKEN'),
    ('google-cloud', 'secret', 'GOOGLE_CLOUD_REFRESH_TOKEN'),
    ('google-contacts', 'secret', 'GOOGLE_CONTACTS_ACCESS_TOKEN'),
    ('google-contacts', 'secret', 'GOOGLE_CONTACTS_REFRESH_TOKEN'),
    ('google-docs', 'secret', 'GOOGLE_DOCS_ACCESS_TOKEN'),
    ('google-docs', 'secret', 'GOOGLE_DOCS_REFRESH_TOKEN'),
    ('google-drive', 'secret', 'GOOGLE_DRIVE_ACCESS_TOKEN'),
    ('google-drive', 'secret', 'GOOGLE_DRIVE_REFRESH_TOKEN'),
    ('google-forms', 'secret', 'GOOGLE_FORMS_ACCESS_TOKEN'),
    ('google-forms', 'secret', 'GOOGLE_FORMS_REFRESH_TOKEN'),
    ('google-maps', 'secret', 'GOOGLE_MAPS_ACCESS_TOKEN'),
    ('google-maps', 'secret', 'GOOGLE_MAPS_REFRESH_TOKEN'),
    ('google-meet', 'secret', 'GOOGLE_MEET_ACCESS_TOKEN'),
    ('google-meet', 'secret', 'GOOGLE_MEET_REFRESH_TOKEN'),
    ('google-search-console', 'secret', 'GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN'),
    ('google-search-console', 'secret', 'GOOGLE_SEARCH_CONSOLE_REFRESH_TOKEN'),
    ('google-sheets', 'secret', 'GOOGLE_SHEETS_ACCESS_TOKEN'),
    ('google-sheets', 'secret', 'GOOGLE_SHEETS_REFRESH_TOKEN'),
    ('granola', 'secret', 'GRANOLA_TOKEN'),
    ('greenhouse', 'secret', 'GREENHOUSE_TOKEN'),
    ('groq', 'secret', 'GROQ_TOKEN'),
    ('gumroad', 'secret', 'GUMROAD_ACCESS_TOKEN'),
    ('gumroad', 'secret', 'GUMROAD_REFRESH_TOKEN'),
    ('gumroad', 'secret', 'GUMROAD_TOKEN'),
    ('helicone', 'secret', 'HELICONE_TOKEN'),
    ('heygen', 'secret', 'HEYGEN_TOKEN'),
    ('hitem3d', 'secret', 'HITEM3D_CLIENT_ID'),
    ('hitem3d', 'secret', 'HITEM3D_CLIENT_SECRET'),
    ('honcho', 'secret', 'HONCHO_API_KEY'),
    ('htmlcsstoimage', 'secret', 'HCTI_API_KEY'),
    ('htmlcsstoimage', 'variable', 'HCTI_USER_ID'),
    ('hubspot', 'secret', 'HUBSPOT_ACCESS_TOKEN'),
    ('hubspot', 'secret', 'HUBSPOT_REFRESH_TOKEN'),
    ('hugging-face', 'secret', 'HUGGING_FACE_TOKEN'),
    ('hume', 'secret', 'HUME_TOKEN'),
    ('hunter', 'secret', 'HUNTER_TOKEN'),
    ('imgur', 'secret', 'IMGUR_CLIENT_ID'),
    ('infisical', 'secret', 'INFISICAL_TOKEN'),
    ('insforge', 'secret', 'INSFORGE_API_KEY'),
    ('insforge', 'variable', 'INSFORGE_DOMAIN'),
    ('instagram', 'secret', 'INSTAGRAM_TOKEN'),
    ('instagram', 'variable', 'INSTAGRAM_BUSINESS_ACCOUNT_ID'),
    ('instantly', 'secret', 'INSTANTLY_API_KEY'),
    ('intercom', 'secret', 'INTERCOM_TOKEN'),
    ('interfaze', 'secret', 'INTERFAZE_API_KEY'),
    ('intervals-icu', 'secret', 'INTERVALS_ICU_ACCESS_TOKEN'),
    ('inth', 'secret', 'INTH_API_KEY'),
    ('ironclad', 'secret', 'IRONCLAD_API_KEY'),
    ('ironclad', 'variable', 'IRONCLAD_HOST'),
    ('jam', 'secret', 'JAM_TOKEN'),
    ('jira', 'secret', 'JIRA_API_TOKEN'),
    ('jira', 'variable', 'JIRA_DOMAIN'),
    ('jira', 'variable', 'JIRA_EMAIL'),
    ('jotform', 'secret', 'JOTFORM_TOKEN'),
    ('keyframe-labs', 'secret', 'KEYFRAME_LABS_API_KEY'),
    ('klaviyo', 'secret', 'KLAVIYO_TOKEN'),
    ('kommo', 'secret', 'KOMMO_API_KEY'),
    ('kommo', 'variable', 'KOMMO_SUBDOMAIN'),
    ('kugelaudio', 'secret', 'KUGELAUDIO_API_KEY'),
    ('langfuse', 'secret', 'LANGFUSE_PUBLIC_KEY'),
    ('langfuse', 'secret', 'LANGFUSE_SECRET_KEY'),
    ('langsmith', 'secret', 'LANGSMITH_TOKEN'),
    ('lark', 'secret', 'LARK_ACCESS_TOKEN'),
    ('lark', 'secret', 'LARK_APP_SECRET'),
    ('lark', 'variable', 'LARK_APP_ID'),
    ('limrun', 'secret', 'LIMRUN_API_KEY'),
    ('line', 'secret', 'LINE_TOKEN'),
    ('linear', 'secret', 'LINEAR_ACCESS_TOKEN'),
    ('linear', 'secret', 'LINEAR_REFRESH_TOKEN'),
    ('loops', 'secret', 'LOOPS_TOKEN'),
    ('luma', 'secret', 'LUMA_API_KEY'),
    ('luma-ai', 'secret', 'LUMA_TOKEN'),
    ('mailchimp', 'secret', 'MAILCHIMP_ACCESS_TOKEN'),
    ('mailchimp', 'secret', 'MAILCHIMP_TOKEN'),
    ('mailsac', 'secret', 'MAILSAC_TOKEN'),
    ('make', 'secret', 'MAKE_TOKEN'),
    ('manus', 'secret', 'MANUS_TOKEN'),
    ('mapbox', 'secret', 'MAPBOX_TOKEN'),
    ('maskdb', 'secret', 'MASKDB_TOKEN'),
    ('massive', 'secret', 'MASSIVE_TOKEN'),
    ('mathpix', 'secret', 'MATHPIX_APP_KEY'),
    ('mathpix', 'variable', 'MATHPIX_APP_ID'),
    ('mem0', 'secret', 'MEM0_TOKEN'),
    ('mercury', 'secret', 'MERCURY_ACCESS_TOKEN'),
    ('mercury', 'secret', 'MERCURY_REFRESH_TOKEN'),
    ('mercury', 'secret', 'MERCURY_TOKEN'),
    ('meshy', 'secret', 'MESHY_API_KEY'),
    ('meta-ads', 'secret', 'META_ADS_ACCESS_TOKEN'),
    ('meta-ads', 'secret', 'META_ADS_REFRESH_TOKEN'),
    ('metabase', 'secret', 'METABASE_TOKEN'),
    ('metabase', 'variable', 'METABASE_BASE_URL'),
    ('microsoft-365', 'secret', 'MICROSOFT_365_ACCESS_TOKEN'),
    ('microsoft-365', 'secret', 'MICROSOFT_365_REFRESH_TOKEN'),
    ('minicor', 'secret', 'MINICOR_API_KEY'),
    ('minimax', 'secret', 'MINIMAX_TOKEN'),
    ('minio', 'secret', 'MINIO_SECRET_TOKEN'),
    ('minio', 'secret', 'MINIO_TOKEN'),
    ('minio', 'variable', 'MINIO_ENDPOINT'),
    ('miro', 'secret', 'MIRO_TOKEN'),
    ('mixpanel', 'secret', 'MIXPANEL_SERVICE_ACCOUNT_SECRET'),
    ('mixpanel', 'secret', 'MIXPANEL_SERVICE_ACCOUNT_USERNAME'),
    ('mixpanel', 'variable', 'MIXPANEL_PROJECT_ID'),
    ('modal', 'secret', 'MODAL_TOKEN_ID'),
    ('modal', 'secret', 'MODAL_TOKEN_SECRET'),
    ('modal', 'variable', 'MODAL_ENVIRONMENT'),
    ('monday', 'secret', 'MONDAY_ACCESS_TOKEN'),
    ('monday', 'secret', 'MONDAY_REFRESH_TOKEN'),
    ('moss', 'secret', 'MOSS_PROJECT_ID'),
    ('moss', 'secret', 'MOSS_PROJECT_KEY'),
    ('msg9', 'secret', 'MSG9_TOKEN'),
    ('n8n', 'secret', 'N8N_TOKEN'),
    ('n8n', 'variable', 'N8N_BASE_URL'),
    ('neon', 'secret', 'NEON_ACCESS_TOKEN'),
    ('neon', 'secret', 'NEON_REFRESH_TOKEN'),
    ('neon', 'secret', 'NEON_TOKEN'),
    ('netdata', 'secret', 'NETDATA_TOKEN'),
    ('netsuite', 'secret', 'NETSUITE_ACCESS_TOKEN'),
    ('netsuite', 'secret', 'NETSUITE_CLIENT_SECRET'),
    ('netsuite', 'secret', 'NETSUITE_REFRESH_TOKEN'),
    ('netsuite', 'variable', 'NETSUITE_ACCOUNT_SUBDOMAIN'),
    ('netsuite', 'variable', 'NETSUITE_CLIENT_ID'),
    ('netter', 'secret', 'NETTER_API_KEY'),
    ('nintendo-store', 'secret', 'NINTENDO_STORE_ACCESS_TOKEN'),
    ('nintendo-store', 'secret', 'NINTENDO_STORE_ID_TOKEN'),
    ('nintendo-store', 'secret', 'NINTENDO_STORE_SESSION_TOKEN'),
    ('nintendo-store', 'variable', 'NINTENDO_STORE_ACCOUNT_ID'),
    ('nintendo-store', 'variable', 'NINTENDO_STORE_LOCALE'),
    ('nintendo-switch-parental-controls', 'secret', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_ACCESS_TOKEN'),
    ('nintendo-switch-parental-controls', 'secret', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_ID_TOKEN'),
    ('nintendo-switch-parental-controls', 'secret', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_SESSION_TOKEN'),
    ('nintendo-switch-parental-controls', 'secret', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_SMART_DEVICE_ID'),
    ('nintendo-switch-parental-controls', 'variable', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_ACCOUNT_ID'),
    ('nintendo-switch-parental-controls', 'variable', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_DEVICE_CATALOG'),
    ('nintendo-switch-parental-controls', 'variable', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_LANGUAGE'),
    ('notion', 'secret', 'NOTION_ACCESS_TOKEN'),
    ('notion', 'secret', 'NOTION_REFRESH_TOKEN'),
    ('novita', 'secret', 'NOVITA_TOKEN'),
    ('nyne', 'secret', 'NYNE_API_KEY'),
    ('nyne', 'secret', 'NYNE_API_SECRET'),
    ('oddpool', 'secret', 'ODDPOOL_API_KEY'),
    ('onyx', 'secret', 'ONYX_TOKEN'),
    ('openai', 'secret', 'OPENAI_TOKEN'),
    ('openrouter', 'secret', 'OPENROUTER_TOKEN'),
    ('openweather', 'secret', 'OPENWEATHER_TOKEN'),
    ('outlook-calendar', 'secret', 'OUTLOOK_CALENDAR_ACCESS_TOKEN'),
    ('outlook-calendar', 'secret', 'OUTLOOK_CALENDAR_REFRESH_TOKEN'),
    ('outlook-mail', 'secret', 'OUTLOOK_MAIL_ACCESS_TOKEN'),
    ('outlook-mail', 'secret', 'OUTLOOK_MAIL_REFRESH_TOKEN'),
    ('pandadoc', 'secret', 'PANDADOC_TOKEN'),
    ('parallel', 'secret', 'PARALLEL_API_KEY'),
    ('paypal', 'secret', 'PAYPAL_ACCESS_TOKEN'),
    ('paypal', 'secret', 'PAYPAL_CLIENT_SECRET'),
    ('paypal', 'variable', 'PAYPAL_CLIENT_ID'),
    ('pdf4me', 'secret', 'PDF4ME_TOKEN'),
    ('pdfco', 'secret', 'PDFCO_TOKEN'),
    ('pdforge', 'secret', 'PDFORGE_API_KEY'),
    ('people-data-labs', 'secret', 'PEOPLE_DATA_LABS_API_KEY'),
    ('perplexity', 'secret', 'PERPLEXITY_TOKEN'),
    ('pexels', 'secret', 'PEXELS_API_KEY'),
    ('pika', 'secret', 'PIKA_TOKEN'),
    ('pinecone', 'secret', 'PINECONE_TOKEN'),
    ('pipedream', 'secret', 'PIPEDREAM_TOKEN'),
    ('pipedrive', 'secret', 'PIPEDRIVE_TOKEN'),
    ('plain', 'secret', 'PLAIN_TOKEN'),
    ('plausible', 'secret', 'PLAUSIBLE_TOKEN'),
    ('playstation', 'secret', 'PLAYSTATION_ACCESS_TOKEN'),
    ('playstation', 'secret', 'PLAYSTATION_ID_TOKEN'),
    ('playstation', 'secret', 'PLAYSTATION_REFRESH_TOKEN'),
    ('playstation', 'variable', 'PLAYSTATION_ACCOUNT_ID'),
    ('playstation', 'variable', 'PLAYSTATION_ONLINE_ID'),
    ('podchaser', 'secret', 'PODCHASER_TOKEN'),
    ('porkbun', 'secret', 'PORKBUN_API_KEY'),
    ('porkbun', 'secret', 'PORKBUN_SECRET_API_KEY'),
    ('posthog', 'secret', 'POSTHOG_ACCESS_TOKEN'),
    ('posthog', 'secret', 'POSTHOG_REFRESH_TOKEN'),
    ('posthog', 'secret', 'POSTHOG_TOKEN'),
    ('primitive', 'secret', 'PRIMITIVE_API_KEY'),
    ('printful', 'secret', 'PRINTFUL_TOKEN'),
    ('prisma-postgres', 'secret', 'PRISMA_POSTGRES_TOKEN'),
    ('productlane', 'secret', 'PRODUCTLANE_TOKEN'),
    ('profound', 'secret', 'PROFOUND_API_KEY'),
    ('pushinator', 'secret', 'PUSHINATOR_TOKEN'),
    ('qdrant', 'secret', 'QDRANT_TOKEN'),
    ('qdrant', 'variable', 'QDRANT_BASE_URL'),
    ('qiita', 'secret', 'QIITA_TOKEN'),
    ('qomplement', 'secret', 'QOMPLEMENT_API_KEY'),
    ('quickbooks', 'secret', 'QUICKBOOKS_ACCESS_TOKEN'),
    ('quickbooks', 'secret', 'QUICKBOOKS_REFRESH_TOKEN'),
    ('quickbooks', 'variable', 'QUICKBOOKS_REALM_ID'),
    ('railway', 'secret', 'RAILWAY_TOKEN'),
    ('railway-project', 'secret', 'RAILWAY_PROJECT_TOKEN'),
    ('ramp', 'secret', 'RAMP_ACCESS_TOKEN'),
    ('ramp', 'secret', 'RAMP_CLIENT_SECRET'),
    ('ramp', 'variable', 'RAMP_CLIENT_ID'),
    ('ramp', 'variable', 'RAMP_SCOPE'),
    ('reap', 'secret', 'REAP_API_KEY'),
    ('reap', 'variable', 'REAP_API_BASE_URL'),
    ('recraft', 'secret', 'RECRAFT_API_TOKEN'),
    ('reddit', 'secret', 'REDDIT_ACCESS_TOKEN'),
    ('reddit', 'secret', 'REDDIT_REFRESH_TOKEN'),
    ('reducto', 'secret', 'REDUCTO_TOKEN'),
    ('render', 'secret', 'RENDER_API_KEY'),
    ('rentahuman', 'secret', 'RENTAHUMAN_API_KEY'),
    ('rentcast', 'secret', 'RENTCAST_API_KEY'),
    ('replicas', 'secret', 'REPLICAS_API_KEY'),
    ('replicate', 'secret', 'REPLICATE_TOKEN'),
    ('reportei', 'secret', 'REPORTEI_TOKEN'),
    ('resend', 'secret', 'RESEND_TOKEN'),
    ('revenuecat', 'secret', 'REVENUECAT_TOKEN'),
    ('river-markets', 'secret', 'RIVER_MARKETS_API_KEY'),
    ('runtime', 'secret', 'RUNTIME_API_KEY'),
    ('runway', 'secret', 'RUNWAY_TOKEN'),
    ('salesforce', 'secret', 'SALESFORCE_TOKEN'),
    ('salesforce', 'variable', 'SALESFORCE_INSTANCE'),
    ('salesgraph', 'secret', 'SALESGRAPH_API_KEY'),
    ('scrapeninja', 'secret', 'SCRAPENINJA_TOKEN'),
    ('segment', 'secret', 'SEGMENT_TOKEN'),
    ('semrush', 'secret', 'SEMRUSH_TOKEN'),
    ('sendgrid', 'secret', 'SENDGRID_TOKEN'),
    ('sentry', 'secret', 'SENTRY_ACCESS_TOKEN'),
    ('sentry', 'secret', 'SENTRY_REFRESH_TOKEN'),
    ('serpapi', 'secret', 'SERPAPI_TOKEN'),
    ('servicenow', 'secret', 'SERVICENOW_PASSWORD'),
    ('servicenow', 'secret', 'SERVICENOW_USERNAME'),
    ('servicenow', 'variable', 'SERVICENOW_INSTANCE'),
    ('shopify', 'secret', 'SHOPIFY_TOKEN'),
    ('shopify', 'variable', 'SHOPIFY_SHOP'),
    ('shortio', 'secret', 'SHORTIO_TOKEN'),
    ('silmaril', 'secret', 'SILMARIL_API_KEY'),
    ('similarweb', 'secret', 'SIMILARWEB_TOKEN'),
    ('slack', 'secret', 'SLACK_ACCESS_TOKEN'),
    ('slack-webhook', 'secret', 'SLACK_WEBHOOK_URL'),
    ('slock', 'secret', 'SLOCK_ACCESS_TOKEN'),
    ('slock', 'secret', 'SLOCK_REFRESH_TOKEN'),
    ('slock', 'secret', 'SLOCK_SERVER_ID'),
    ('smol-machines', 'secret', 'SMOL_MACHINES_API_KEY'),
    ('snowflake', 'secret', 'SNOWFLAKE_PAT'),
    ('snowflake', 'variable', 'SNOWFLAKE_ACCOUNT'),
    ('sociavault', 'secret', 'SOCIAVAULT_TOKEN'),
    ('sponge', 'secret', 'SPONGE_MASTER_KEY'),
    ('spotify', 'secret', 'SPOTIFY_ACCESS_TOKEN'),
    ('spotify', 'secret', 'SPOTIFY_REFRESH_TOKEN'),
    ('sproutgigs', 'secret', 'SPROUTGIGS_API_SECRET'),
    ('sproutgigs', 'variable', 'SPROUTGIGS_USER_ID'),
    ('square', 'secret', 'SQUARE_TOKEN'),
    ('stability-ai', 'secret', 'STABILITY_TOKEN'),
    ('stablebrowse', 'secret', 'STABLEBROWSE_API_KEY'),
    ('steam', 'variable', 'STEAM_ID'),
    ('strapi', 'secret', 'STRAPI_TOKEN'),
    ('strapi', 'variable', 'STRAPI_BASE_URL'),
    ('strava', 'secret', 'STRAVA_ACCESS_TOKEN'),
    ('strava', 'secret', 'STRAVA_REFRESH_TOKEN'),
    ('streak', 'secret', 'STREAK_TOKEN'),
    ('stripe', 'secret', 'STRIPE_ACCESS_TOKEN'),
    ('stripe', 'secret', 'STRIPE_REFRESH_TOKEN'),
    ('stripe', 'secret', 'STRIPE_TOKEN'),
    ('supabase', 'secret', 'SUPABASE_ACCESS_TOKEN'),
    ('supabase', 'secret', 'SUPABASE_REFRESH_TOKEN'),
    ('supabase', 'secret', 'SUPABASE_TOKEN'),
    ('supadata', 'secret', 'SUPADATA_TOKEN'),
    ('supermemory', 'secret', 'SUPERMEMORY_API_KEY'),
    ('tavily', 'secret', 'TAVILY_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_ACCESS_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_API_ACCESS_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_API_REFRESH_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_API_SECONDARY_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_API_TOKEN_ACCESS_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_REFRESH_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_TOKEN'),
    ('test-oauth', 'variable', 'TEST_OAUTH_API_TENANT_ID'),
    ('test-oauth', 'variable', 'TEST_OAUTH_API_TOKEN_INPUT_VAR'),
    ('test-oauth-device', 'secret', 'TEST_OAUTH_DEVICE_ACCESS_TOKEN'),
    ('test-oauth-device', 'secret', 'TEST_OAUTH_DEVICE_API_ACCESS_TOKEN'),
    ('testerarmy', 'secret', 'TESTERARMY_API_KEY'),
    ('testrail', 'secret', 'TESTRAIL_EMAIL'),
    ('testrail', 'secret', 'TESTRAIL_TOKEN'),
    ('testrail', 'variable', 'TESTRAIL_INSTANCE'),
    ('ticketmaster', 'secret', 'TICKETMASTER_API_KEY'),
    ('tiktok-ads', 'secret', 'TIKTOK_ADS_ACCESS_TOKEN'),
    ('tiktok-ads', 'secret', 'TIKTOK_ADS_REFRESH_TOKEN'),
    ('tldv', 'secret', 'TLDV_TOKEN'),
    ('todoist', 'secret', 'TODOIST_ACCESS_TOKEN'),
    ('together', 'secret', 'TOGETHER_TOKEN'),
    ('totalis', 'secret', 'TOTALIS_API_KEY'),
    ('trellis', 'secret', 'TRELLIS_API_KEY'),
    ('tripo', 'secret', 'TRIPO_API_KEY'),
    ('twenty', 'secret', 'TWENTY_TOKEN'),
    ('twilio', 'secret', 'TWILIO_ACCOUNT_SID'),
    ('twilio', 'secret', 'TWILIO_AUTH_TOKEN'),
    ('typeform', 'secret', 'TYPEFORM_TOKEN'),
    ('v0', 'secret', 'V0_TOKEN'),
    ('vercel', 'secret', 'VERCEL_ACCESS_TOKEN'),
    ('voquill', 'secret', 'VOQUILL_API_KEY'),
    ('wandb', 'secret', 'WANDB_TOKEN'),
    ('webflow', 'secret', 'WEBFLOW_ACCESS_TOKEN'),
    ('webflow', 'secret', 'WEBFLOW_TOKEN'),
    ('weread', 'secret', 'WEREAD_TOKEN'),
    ('whale-alert', 'secret', 'WHALE_ALERT_API_KEY'),
    ('wix', 'secret', 'WIX_TOKEN'),
    ('workday', 'secret', 'WORKDAY_ACCESS_TOKEN'),
    ('workday', 'secret', 'WORKDAY_CLIENT_SECRET'),
    ('workday', 'secret', 'WORKDAY_REFRESH_TOKEN'),
    ('workday', 'variable', 'WORKDAY_CLIENT_ID'),
    ('workday', 'variable', 'WORKDAY_HOST'),
    ('workday', 'variable', 'WORKDAY_TENANT'),
    ('workos', 'secret', 'WORKOS_TOKEN'),
    ('wrike', 'secret', 'WRIKE_TOKEN'),
    ('x', 'secret', 'X_ACCESS_TOKEN'),
    ('x', 'secret', 'X_REFRESH_TOKEN'),
    ('xero', 'secret', 'XERO_ACCESS_TOKEN'),
    ('xero', 'secret', 'XERO_REFRESH_TOKEN'),
    ('youtube', 'secret', 'YOUTUBE_ACCESS_TOKEN'),
    ('youtube', 'secret', 'YOUTUBE_REFRESH_TOKEN'),
    ('zapier', 'secret', 'ZAPIER_TOKEN'),
    ('zapsign', 'secret', 'ZAPSIGN_TOKEN'),
    ('zendesk', 'secret', 'ZENDESK_API_TOKEN'),
    ('zendesk', 'variable', 'ZENDESK_EMAIL'),
    ('zendesk', 'variable', 'ZENDESK_SUBDOMAIN'),
    ('zep', 'secret', 'ZEP_TOKEN'),
    ('zeptomail', 'secret', 'ZEPTOMAIL_TOKEN'),
    ('zoom', 'secret', 'ZOOM_ACCESS_TOKEN'),
    ('zoom', 'secret', 'ZOOM_REFRESH_TOKEN')
),
candidate_matches AS MATERIALIZED (
  SELECT
    credential."id" AS credential_id,
    connector."id" AS connector_id
  FROM "secrets" AS credential
  INNER JOIN connector_credential_names AS mapping
    ON mapping.credential_kind = 'secret'
    AND mapping.credential_name = credential."name"
  INNER JOIN "connectors" AS connector
    ON connector."org_id" = credential."org_id"
    AND connector."user_id" = credential."user_id"
    AND connector."type" = mapping.connector_ref
  WHERE credential."type" = 'connector'
    AND credential."connector_id" IS NULL
  -- Keep the parent alive until this migration transaction commits. Without
  -- this lock, a concurrent disconnect can delete the connector after this
  -- match and make the connector_id update fail its foreign key check.
  FOR KEY SHARE OF connector
),
candidate_owners AS (
  SELECT
    credential_id,
    min(connector_id::text)::uuid AS connector_id
  FROM candidate_matches
  GROUP BY credential_id
  HAVING count(DISTINCT connector_id) = 1
)
UPDATE "secrets" AS credential
SET "connector_id" = candidate.connector_id
FROM candidate_owners AS candidate
WHERE credential."id" = candidate.credential_id
  AND credential."type" = 'connector'
  AND credential."connector_id" IS NULL;
--> statement-breakpoint
WITH connector_credential_names(connector_ref, credential_kind, credential_name) AS (
  VALUES
    ('adzuna', 'secret', 'ADZUNA_APP_KEY'),
    ('adzuna', 'variable', 'ADZUNA_APP_ID'),
    ('agentmail', 'secret', 'AGENTMAIL_TOKEN'),
    ('agora', 'secret', 'AGORA_APP_CERTIFICATE'),
    ('agora', 'secret', 'AGORA_CUSTOMER_ID'),
    ('agora', 'secret', 'AGORA_CUSTOMER_SECRET'),
    ('agora', 'variable', 'AGORA_APP_ID'),
    ('ahrefs', 'secret', 'AHREFS_ACCESS_TOKEN'),
    ('ahrefs', 'secret', 'AHREFS_REFRESH_TOKEN'),
    ('ahrefs', 'secret', 'AHREFS_TOKEN'),
    ('airtable', 'secret', 'AIRTABLE_ACCESS_TOKEN'),
    ('airtable', 'secret', 'AIRTABLE_REFRESH_TOKEN'),
    ('alchemy', 'secret', 'ALCHEMY_API_KEY'),
    ('altium-365', 'secret', 'ALTIUM365_TOKEN'),
    ('altium-365', 'variable', 'ALTIUM365_WORKSPACE_URL'),
    ('amadeus', 'secret', 'AMADEUS_API_KEY'),
    ('amadeus', 'secret', 'AMADEUS_API_SECRET'),
    ('amplitude', 'secret', 'AMPLITUDE_API_KEY'),
    ('amplitude', 'secret', 'AMPLITUDE_SECRET_KEY'),
    ('anthropic-managed-agents', 'secret', 'ANTHROPIC_MANAGED_AGENTS_TOKEN'),
    ('apify', 'secret', 'APIFY_TOKEN'),
    ('apollo', 'secret', 'APOLLO_TOKEN'),
    ('archer', 'secret', 'ARCHER_API_KEY'),
    ('ardent', 'secret', 'ARDENT_API_KEY'),
    ('arga-labs', 'secret', 'ARGA_LABS_API_KEY'),
    ('armature', 'secret', 'ARMATURE_API_KEY'),
    ('asana', 'secret', 'ASANA_ACCESS_TOKEN'),
    ('asana', 'secret', 'ASANA_REFRESH_TOKEN'),
    ('ashby', 'secret', 'ASHBY_TOKEN'),
    ('atlascloud', 'secret', 'ATLASCLOUD_API_KEY'),
    ('atlassian', 'secret', 'ATLASSIAN_TOKEN'),
    ('atlassian', 'variable', 'ATLASSIAN_DOMAIN'),
    ('atlassian', 'variable', 'ATLASSIAN_EMAIL'),
    ('attio', 'secret', 'ATTIO_TOKEN'),
    ('aviationstack', 'secret', 'AVIATIONSTACK_TOKEN'),
    ('aws', 'secret', 'AWS_ACCESS_KEY_ID'),
    ('aws', 'secret', 'AWS_LOGIN_DPOP_KEY'),
    ('aws', 'secret', 'AWS_LOGIN_REFRESH_TOKEN'),
    ('aws', 'secret', 'AWS_SECRET_ACCESS_KEY'),
    ('aws', 'secret', 'AWS_SESSION_TOKEN'),
    ('aws', 'variable', 'AWS_REGION'),
    ('aws', 'variable', 'AWS_SIGNIN_REGION'),
    ('axiom', 'secret', 'AXIOM_TOKEN'),
    ('base44', 'secret', 'BASE44_ACCESS_TOKEN'),
    ('base44', 'secret', 'BASE44_REFRESH_TOKEN'),
    ('bentolabs-ai', 'secret', 'BENTOLABS_AI_API_KEY'),
    ('bentoml', 'secret', 'BENTO_CLOUD_API_KEY'),
    ('bentoml', 'variable', 'BENTO_CLOUD_API_ENDPOINT'),
    ('bfl', 'secret', 'BFL_API_KEY'),
    ('bill', 'secret', 'BILL_TOKEN'),
    ('bitrefill', 'secret', 'BITREFILL_TOKEN'),
    ('bitrix', 'secret', 'BITRIX_WEBHOOK_URL'),
    ('bland', 'secret', 'BLAND_API_KEY'),
    ('bloom', 'secret', 'BLOOM_API_KEY'),
    ('box', 'secret', 'BOX_ACCESS_TOKEN'),
    ('box', 'secret', 'BOX_REFRESH_TOKEN'),
    ('brave-search', 'secret', 'BRAVE_API_KEY'),
    ('brevo', 'secret', 'BREVO_TOKEN'),
    ('brex', 'secret', 'BREX_TOKEN'),
    ('bright-data', 'secret', 'BRIGHTDATA_TOKEN'),
    ('browser-use', 'secret', 'BROWSER_USE_TOKEN'),
    ('browserbase', 'secret', 'BROWSERBASE_TOKEN'),
    ('browserbase', 'variable', 'BROWSERBASE_PROJECT_ID'),
    ('browserless', 'secret', 'BROWSERLESS_TOKEN'),
    ('browserstack', 'secret', 'BROWSERSTACK_ACCESS_KEY'),
    ('browserstack', 'secret', 'BROWSERSTACK_USERNAME'),
    ('bubblemaps', 'secret', 'BUBBLEMAPS_API_KEY'),
    ('buffer', 'secret', 'BUFFER_TOKEN'),
    ('builtwith', 'secret', 'BUILTWITH_TOKEN'),
    ('cal-com', 'secret', 'CALCOM_ACCESS_TOKEN'),
    ('cal-com', 'secret', 'CALCOM_REFRESH_TOKEN'),
    ('cal-com', 'secret', 'CALCOM_TOKEN'),
    ('calendly', 'secret', 'CALENDLY_TOKEN'),
    ('canva', 'secret', 'CANVA_ACCESS_TOKEN'),
    ('canva', 'secret', 'CANVA_REFRESH_TOKEN'),
    ('chatwoot', 'secret', 'CHATWOOT_TOKEN'),
    ('checkr', 'secret', 'CHECKR_TOKEN'),
    ('chert', 'secret', 'CHERT_API_KEY'),
    ('clado', 'secret', 'CLADO_TOKEN'),
    ('clearbit', 'secret', 'CLEARBIT_TOKEN'),
    ('clerk', 'secret', 'CLERK_TOKEN'),
    ('clickup', 'secret', 'CLICKUP_TOKEN'),
    ('close', 'secret', 'CLOSE_ACCESS_TOKEN'),
    ('close', 'secret', 'CLOSE_REFRESH_TOKEN'),
    ('cloudflare', 'secret', 'CLOUDFLARE_ACCESS_TOKEN'),
    ('cloudflare', 'secret', 'CLOUDFLARE_REFRESH_TOKEN'),
    ('cloudflare', 'secret', 'CLOUDFLARE_TOKEN'),
    ('cloudinary', 'secret', 'CLOUDINARY_API_SECRET'),
    ('cloudinary', 'secret', 'CLOUDINARY_TOKEN'),
    ('cloudinary', 'variable', 'CLOUDINARY_CLOUD_NAME'),
    ('coda', 'secret', 'CODA_TOKEN'),
    ('coingecko', 'secret', 'COINGECKO_TOKEN'),
    ('copper', 'secret', 'COPPER_ACCESS_TOKEN'),
    ('coresignal', 'secret', 'CORESIGNAL_TOKEN'),
    ('cronlytic', 'secret', 'CRONLYTIC_API_KEY'),
    ('cronlytic', 'variable', 'CRONLYTIC_USER_ID'),
    ('crustdata', 'secret', 'CRUSTDATA_TOKEN'),
    ('cursor', 'secret', 'CURSOR_TOKEN'),
    ('customer-io', 'secret', 'CUSTOMERIO_APP_TOKEN'),
    ('datadog', 'secret', 'DATADOG_ACCESS_TOKEN'),
    ('datadog', 'secret', 'DATADOG_REFRESH_TOKEN'),
    ('datadog', 'variable', 'DATADOG_DOMAIN'),
    ('daytona', 'secret', 'DAYTONA_API_KEY'),
    ('db9', 'secret', 'DB9_API_KEY'),
    ('deel', 'secret', 'DEEL_ACCESS_TOKEN'),
    ('deel', 'secret', 'DEEL_REFRESH_TOKEN'),
    ('deel', 'secret', 'DEEL_TOKEN'),
    ('deepseek', 'secret', 'DEEPSEEK_TOKEN'),
    ('defillama', 'secret', 'DEFILLAMA_TOKEN'),
    ('devto', 'secret', 'DEVTO_TOKEN'),
    ('diffbot', 'secret', 'DIFFBOT_TOKEN'),
    ('dify', 'secret', 'DIFY_TOKEN'),
    ('discord', 'secret', 'DISCORD_BOT_TOKEN'),
    ('discord-webhook', 'secret', 'DISCORD_WEBHOOK_URL'),
    ('docusign', 'secret', 'DOCUSIGN_ACCESS_TOKEN'),
    ('docusign', 'secret', 'DOCUSIGN_REFRESH_TOKEN'),
    ('doppler', 'secret', 'DOPPLER_TOKEN'),
    ('doubao', 'secret', 'DOUBAO_API_KEY'),
    ('drive9', 'secret', 'DRIVE9_TOKEN'),
    ('dropbox', 'secret', 'DROPBOX_ACCESS_TOKEN'),
    ('dropbox', 'secret', 'DROPBOX_REFRESH_TOKEN'),
    ('dropbox', 'secret', 'DROPBOX_TOKEN'),
    ('dropbox-sign', 'secret', 'DROPBOX_SIGN_TOKEN'),
    ('duffel', 'secret', 'DUFFEL_TOKEN'),
    ('e2b', 'secret', 'E2B_TOKEN'),
    ('elevenlabs', 'secret', 'ELEVENLABS_TOKEN'),
    ('etherscan', 'secret', 'ETHERSCAN_API_KEY'),
    ('etsy', 'secret', 'ETSY_TOKEN'),
    ('exa', 'secret', 'EXA_TOKEN'),
    ('expensify', 'secret', 'EXPENSIFY_PARTNER_USER_SECRET'),
    ('expensify', 'variable', 'EXPENSIFY_PARTNER_USER_ID'),
    ('explorium', 'secret', 'EXPLORIUM_TOKEN'),
    ('faire', 'secret', 'FAIRE_TOKEN'),
    ('fal', 'secret', 'FAL_TOKEN'),
    ('figma', 'secret', 'FIGMA_ACCESS_TOKEN'),
    ('figma', 'secret', 'FIGMA_REFRESH_TOKEN'),
    ('figma', 'secret', 'FIGMA_TOKEN'),
    ('firecrawl', 'secret', 'FIRECRAWL_TOKEN'),
    ('fireflies', 'secret', 'FIREFLIES_TOKEN'),
    ('flightaware', 'secret', 'FLIGHTAWARE_TOKEN'),
    ('freshdesk', 'secret', 'FRESHDESK_TOKEN'),
    ('freshdesk', 'variable', 'FRESHDESK_DOMAIN'),
    ('gamma', 'secret', 'GAMMA_TOKEN'),
    ('garmin-connect', 'secret', 'GARMIN_CONNECT_ACCESS_TOKEN'),
    ('garmin-connect', 'secret', 'GARMIN_CONNECT_REFRESH_TOKEN'),
    ('gemini', 'secret', 'GEMINI_TOKEN'),
    ('github', 'secret', 'GITHUB_ACCESS_TOKEN'),
    ('gitlab', 'secret', 'GITLAB_TOKEN'),
    ('gitlab', 'variable', 'GITLAB_HOST'),
    ('gmail', 'secret', 'GMAIL_ACCESS_TOKEN'),
    ('gmail', 'secret', 'GMAIL_REFRESH_TOKEN'),
    ('gong', 'secret', 'GONG_ACCESS_KEY'),
    ('gong', 'secret', 'GONG_ACCESS_KEY_SECRET'),
    ('gong', 'variable', 'GONG_API_BASE'),
    ('google-ads', 'secret', 'GOOGLE_ADS_ACCESS_TOKEN'),
    ('google-ads', 'secret', 'GOOGLE_ADS_REFRESH_TOKEN'),
    ('google-analytics', 'secret', 'GOOGLE_ANALYTICS_ACCESS_TOKEN'),
    ('google-analytics', 'secret', 'GOOGLE_ANALYTICS_REFRESH_TOKEN'),
    ('google-calendar', 'secret', 'GOOGLE_CALENDAR_ACCESS_TOKEN'),
    ('google-calendar', 'secret', 'GOOGLE_CALENDAR_REFRESH_TOKEN'),
    ('google-cloud', 'secret', 'GOOGLE_CLOUD_ACCESS_TOKEN'),
    ('google-cloud', 'secret', 'GOOGLE_CLOUD_REFRESH_TOKEN'),
    ('google-contacts', 'secret', 'GOOGLE_CONTACTS_ACCESS_TOKEN'),
    ('google-contacts', 'secret', 'GOOGLE_CONTACTS_REFRESH_TOKEN'),
    ('google-docs', 'secret', 'GOOGLE_DOCS_ACCESS_TOKEN'),
    ('google-docs', 'secret', 'GOOGLE_DOCS_REFRESH_TOKEN'),
    ('google-drive', 'secret', 'GOOGLE_DRIVE_ACCESS_TOKEN'),
    ('google-drive', 'secret', 'GOOGLE_DRIVE_REFRESH_TOKEN'),
    ('google-forms', 'secret', 'GOOGLE_FORMS_ACCESS_TOKEN'),
    ('google-forms', 'secret', 'GOOGLE_FORMS_REFRESH_TOKEN'),
    ('google-maps', 'secret', 'GOOGLE_MAPS_ACCESS_TOKEN'),
    ('google-maps', 'secret', 'GOOGLE_MAPS_REFRESH_TOKEN'),
    ('google-meet', 'secret', 'GOOGLE_MEET_ACCESS_TOKEN'),
    ('google-meet', 'secret', 'GOOGLE_MEET_REFRESH_TOKEN'),
    ('google-search-console', 'secret', 'GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN'),
    ('google-search-console', 'secret', 'GOOGLE_SEARCH_CONSOLE_REFRESH_TOKEN'),
    ('google-sheets', 'secret', 'GOOGLE_SHEETS_ACCESS_TOKEN'),
    ('google-sheets', 'secret', 'GOOGLE_SHEETS_REFRESH_TOKEN'),
    ('granola', 'secret', 'GRANOLA_TOKEN'),
    ('greenhouse', 'secret', 'GREENHOUSE_TOKEN'),
    ('groq', 'secret', 'GROQ_TOKEN'),
    ('gumroad', 'secret', 'GUMROAD_ACCESS_TOKEN'),
    ('gumroad', 'secret', 'GUMROAD_REFRESH_TOKEN'),
    ('gumroad', 'secret', 'GUMROAD_TOKEN'),
    ('helicone', 'secret', 'HELICONE_TOKEN'),
    ('heygen', 'secret', 'HEYGEN_TOKEN'),
    ('hitem3d', 'secret', 'HITEM3D_CLIENT_ID'),
    ('hitem3d', 'secret', 'HITEM3D_CLIENT_SECRET'),
    ('honcho', 'secret', 'HONCHO_API_KEY'),
    ('htmlcsstoimage', 'secret', 'HCTI_API_KEY'),
    ('htmlcsstoimage', 'variable', 'HCTI_USER_ID'),
    ('hubspot', 'secret', 'HUBSPOT_ACCESS_TOKEN'),
    ('hubspot', 'secret', 'HUBSPOT_REFRESH_TOKEN'),
    ('hugging-face', 'secret', 'HUGGING_FACE_TOKEN'),
    ('hume', 'secret', 'HUME_TOKEN'),
    ('hunter', 'secret', 'HUNTER_TOKEN'),
    ('imgur', 'secret', 'IMGUR_CLIENT_ID'),
    ('infisical', 'secret', 'INFISICAL_TOKEN'),
    ('insforge', 'secret', 'INSFORGE_API_KEY'),
    ('insforge', 'variable', 'INSFORGE_DOMAIN'),
    ('instagram', 'secret', 'INSTAGRAM_TOKEN'),
    ('instagram', 'variable', 'INSTAGRAM_BUSINESS_ACCOUNT_ID'),
    ('instantly', 'secret', 'INSTANTLY_API_KEY'),
    ('intercom', 'secret', 'INTERCOM_TOKEN'),
    ('interfaze', 'secret', 'INTERFAZE_API_KEY'),
    ('intervals-icu', 'secret', 'INTERVALS_ICU_ACCESS_TOKEN'),
    ('inth', 'secret', 'INTH_API_KEY'),
    ('ironclad', 'secret', 'IRONCLAD_API_KEY'),
    ('ironclad', 'variable', 'IRONCLAD_HOST'),
    ('jam', 'secret', 'JAM_TOKEN'),
    ('jira', 'secret', 'JIRA_API_TOKEN'),
    ('jira', 'variable', 'JIRA_DOMAIN'),
    ('jira', 'variable', 'JIRA_EMAIL'),
    ('jotform', 'secret', 'JOTFORM_TOKEN'),
    ('keyframe-labs', 'secret', 'KEYFRAME_LABS_API_KEY'),
    ('klaviyo', 'secret', 'KLAVIYO_TOKEN'),
    ('kommo', 'secret', 'KOMMO_API_KEY'),
    ('kommo', 'variable', 'KOMMO_SUBDOMAIN'),
    ('kugelaudio', 'secret', 'KUGELAUDIO_API_KEY'),
    ('langfuse', 'secret', 'LANGFUSE_PUBLIC_KEY'),
    ('langfuse', 'secret', 'LANGFUSE_SECRET_KEY'),
    ('langsmith', 'secret', 'LANGSMITH_TOKEN'),
    ('lark', 'secret', 'LARK_ACCESS_TOKEN'),
    ('lark', 'secret', 'LARK_APP_SECRET'),
    ('lark', 'variable', 'LARK_APP_ID'),
    ('limrun', 'secret', 'LIMRUN_API_KEY'),
    ('line', 'secret', 'LINE_TOKEN'),
    ('linear', 'secret', 'LINEAR_ACCESS_TOKEN'),
    ('linear', 'secret', 'LINEAR_REFRESH_TOKEN'),
    ('loops', 'secret', 'LOOPS_TOKEN'),
    ('luma', 'secret', 'LUMA_API_KEY'),
    ('luma-ai', 'secret', 'LUMA_TOKEN'),
    ('mailchimp', 'secret', 'MAILCHIMP_ACCESS_TOKEN'),
    ('mailchimp', 'secret', 'MAILCHIMP_TOKEN'),
    ('mailsac', 'secret', 'MAILSAC_TOKEN'),
    ('make', 'secret', 'MAKE_TOKEN'),
    ('manus', 'secret', 'MANUS_TOKEN'),
    ('mapbox', 'secret', 'MAPBOX_TOKEN'),
    ('maskdb', 'secret', 'MASKDB_TOKEN'),
    ('massive', 'secret', 'MASSIVE_TOKEN'),
    ('mathpix', 'secret', 'MATHPIX_APP_KEY'),
    ('mathpix', 'variable', 'MATHPIX_APP_ID'),
    ('mem0', 'secret', 'MEM0_TOKEN'),
    ('mercury', 'secret', 'MERCURY_ACCESS_TOKEN'),
    ('mercury', 'secret', 'MERCURY_REFRESH_TOKEN'),
    ('mercury', 'secret', 'MERCURY_TOKEN'),
    ('meshy', 'secret', 'MESHY_API_KEY'),
    ('meta-ads', 'secret', 'META_ADS_ACCESS_TOKEN'),
    ('meta-ads', 'secret', 'META_ADS_REFRESH_TOKEN'),
    ('metabase', 'secret', 'METABASE_TOKEN'),
    ('metabase', 'variable', 'METABASE_BASE_URL'),
    ('microsoft-365', 'secret', 'MICROSOFT_365_ACCESS_TOKEN'),
    ('microsoft-365', 'secret', 'MICROSOFT_365_REFRESH_TOKEN'),
    ('minicor', 'secret', 'MINICOR_API_KEY'),
    ('minimax', 'secret', 'MINIMAX_TOKEN'),
    ('minio', 'secret', 'MINIO_SECRET_TOKEN'),
    ('minio', 'secret', 'MINIO_TOKEN'),
    ('minio', 'variable', 'MINIO_ENDPOINT'),
    ('miro', 'secret', 'MIRO_TOKEN'),
    ('mixpanel', 'secret', 'MIXPANEL_SERVICE_ACCOUNT_SECRET'),
    ('mixpanel', 'secret', 'MIXPANEL_SERVICE_ACCOUNT_USERNAME'),
    ('mixpanel', 'variable', 'MIXPANEL_PROJECT_ID'),
    ('modal', 'secret', 'MODAL_TOKEN_ID'),
    ('modal', 'secret', 'MODAL_TOKEN_SECRET'),
    ('modal', 'variable', 'MODAL_ENVIRONMENT'),
    ('monday', 'secret', 'MONDAY_ACCESS_TOKEN'),
    ('monday', 'secret', 'MONDAY_REFRESH_TOKEN'),
    ('moss', 'secret', 'MOSS_PROJECT_ID'),
    ('moss', 'secret', 'MOSS_PROJECT_KEY'),
    ('msg9', 'secret', 'MSG9_TOKEN'),
    ('n8n', 'secret', 'N8N_TOKEN'),
    ('n8n', 'variable', 'N8N_BASE_URL'),
    ('neon', 'secret', 'NEON_ACCESS_TOKEN'),
    ('neon', 'secret', 'NEON_REFRESH_TOKEN'),
    ('neon', 'secret', 'NEON_TOKEN'),
    ('netdata', 'secret', 'NETDATA_TOKEN'),
    ('netsuite', 'secret', 'NETSUITE_ACCESS_TOKEN'),
    ('netsuite', 'secret', 'NETSUITE_CLIENT_SECRET'),
    ('netsuite', 'secret', 'NETSUITE_REFRESH_TOKEN'),
    ('netsuite', 'variable', 'NETSUITE_ACCOUNT_SUBDOMAIN'),
    ('netsuite', 'variable', 'NETSUITE_CLIENT_ID'),
    ('netter', 'secret', 'NETTER_API_KEY'),
    ('nintendo-store', 'secret', 'NINTENDO_STORE_ACCESS_TOKEN'),
    ('nintendo-store', 'secret', 'NINTENDO_STORE_ID_TOKEN'),
    ('nintendo-store', 'secret', 'NINTENDO_STORE_SESSION_TOKEN'),
    ('nintendo-store', 'variable', 'NINTENDO_STORE_ACCOUNT_ID'),
    ('nintendo-store', 'variable', 'NINTENDO_STORE_LOCALE'),
    ('nintendo-switch-parental-controls', 'secret', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_ACCESS_TOKEN'),
    ('nintendo-switch-parental-controls', 'secret', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_ID_TOKEN'),
    ('nintendo-switch-parental-controls', 'secret', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_SESSION_TOKEN'),
    ('nintendo-switch-parental-controls', 'secret', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_SMART_DEVICE_ID'),
    ('nintendo-switch-parental-controls', 'variable', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_ACCOUNT_ID'),
    ('nintendo-switch-parental-controls', 'variable', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_DEVICE_CATALOG'),
    ('nintendo-switch-parental-controls', 'variable', 'NINTENDO_SWITCH_PARENTAL_CONTROLS_LANGUAGE'),
    ('notion', 'secret', 'NOTION_ACCESS_TOKEN'),
    ('notion', 'secret', 'NOTION_REFRESH_TOKEN'),
    ('novita', 'secret', 'NOVITA_TOKEN'),
    ('nyne', 'secret', 'NYNE_API_KEY'),
    ('nyne', 'secret', 'NYNE_API_SECRET'),
    ('oddpool', 'secret', 'ODDPOOL_API_KEY'),
    ('onyx', 'secret', 'ONYX_TOKEN'),
    ('openai', 'secret', 'OPENAI_TOKEN'),
    ('openrouter', 'secret', 'OPENROUTER_TOKEN'),
    ('openweather', 'secret', 'OPENWEATHER_TOKEN'),
    ('outlook-calendar', 'secret', 'OUTLOOK_CALENDAR_ACCESS_TOKEN'),
    ('outlook-calendar', 'secret', 'OUTLOOK_CALENDAR_REFRESH_TOKEN'),
    ('outlook-mail', 'secret', 'OUTLOOK_MAIL_ACCESS_TOKEN'),
    ('outlook-mail', 'secret', 'OUTLOOK_MAIL_REFRESH_TOKEN'),
    ('pandadoc', 'secret', 'PANDADOC_TOKEN'),
    ('parallel', 'secret', 'PARALLEL_API_KEY'),
    ('paypal', 'secret', 'PAYPAL_ACCESS_TOKEN'),
    ('paypal', 'secret', 'PAYPAL_CLIENT_SECRET'),
    ('paypal', 'variable', 'PAYPAL_CLIENT_ID'),
    ('pdf4me', 'secret', 'PDF4ME_TOKEN'),
    ('pdfco', 'secret', 'PDFCO_TOKEN'),
    ('pdforge', 'secret', 'PDFORGE_API_KEY'),
    ('people-data-labs', 'secret', 'PEOPLE_DATA_LABS_API_KEY'),
    ('perplexity', 'secret', 'PERPLEXITY_TOKEN'),
    ('pexels', 'secret', 'PEXELS_API_KEY'),
    ('pika', 'secret', 'PIKA_TOKEN'),
    ('pinecone', 'secret', 'PINECONE_TOKEN'),
    ('pipedream', 'secret', 'PIPEDREAM_TOKEN'),
    ('pipedrive', 'secret', 'PIPEDRIVE_TOKEN'),
    ('plain', 'secret', 'PLAIN_TOKEN'),
    ('plausible', 'secret', 'PLAUSIBLE_TOKEN'),
    ('playstation', 'secret', 'PLAYSTATION_ACCESS_TOKEN'),
    ('playstation', 'secret', 'PLAYSTATION_ID_TOKEN'),
    ('playstation', 'secret', 'PLAYSTATION_REFRESH_TOKEN'),
    ('playstation', 'variable', 'PLAYSTATION_ACCOUNT_ID'),
    ('playstation', 'variable', 'PLAYSTATION_ONLINE_ID'),
    ('podchaser', 'secret', 'PODCHASER_TOKEN'),
    ('porkbun', 'secret', 'PORKBUN_API_KEY'),
    ('porkbun', 'secret', 'PORKBUN_SECRET_API_KEY'),
    ('posthog', 'secret', 'POSTHOG_ACCESS_TOKEN'),
    ('posthog', 'secret', 'POSTHOG_REFRESH_TOKEN'),
    ('posthog', 'secret', 'POSTHOG_TOKEN'),
    ('primitive', 'secret', 'PRIMITIVE_API_KEY'),
    ('printful', 'secret', 'PRINTFUL_TOKEN'),
    ('prisma-postgres', 'secret', 'PRISMA_POSTGRES_TOKEN'),
    ('productlane', 'secret', 'PRODUCTLANE_TOKEN'),
    ('profound', 'secret', 'PROFOUND_API_KEY'),
    ('pushinator', 'secret', 'PUSHINATOR_TOKEN'),
    ('qdrant', 'secret', 'QDRANT_TOKEN'),
    ('qdrant', 'variable', 'QDRANT_BASE_URL'),
    ('qiita', 'secret', 'QIITA_TOKEN'),
    ('qomplement', 'secret', 'QOMPLEMENT_API_KEY'),
    ('quickbooks', 'secret', 'QUICKBOOKS_ACCESS_TOKEN'),
    ('quickbooks', 'secret', 'QUICKBOOKS_REFRESH_TOKEN'),
    ('quickbooks', 'variable', 'QUICKBOOKS_REALM_ID'),
    ('railway', 'secret', 'RAILWAY_TOKEN'),
    ('railway-project', 'secret', 'RAILWAY_PROJECT_TOKEN'),
    ('ramp', 'secret', 'RAMP_ACCESS_TOKEN'),
    ('ramp', 'secret', 'RAMP_CLIENT_SECRET'),
    ('ramp', 'variable', 'RAMP_CLIENT_ID'),
    ('ramp', 'variable', 'RAMP_SCOPE'),
    ('reap', 'secret', 'REAP_API_KEY'),
    ('reap', 'variable', 'REAP_API_BASE_URL'),
    ('recraft', 'secret', 'RECRAFT_API_TOKEN'),
    ('reddit', 'secret', 'REDDIT_ACCESS_TOKEN'),
    ('reddit', 'secret', 'REDDIT_REFRESH_TOKEN'),
    ('reducto', 'secret', 'REDUCTO_TOKEN'),
    ('render', 'secret', 'RENDER_API_KEY'),
    ('rentahuman', 'secret', 'RENTAHUMAN_API_KEY'),
    ('rentcast', 'secret', 'RENTCAST_API_KEY'),
    ('replicas', 'secret', 'REPLICAS_API_KEY'),
    ('replicate', 'secret', 'REPLICATE_TOKEN'),
    ('reportei', 'secret', 'REPORTEI_TOKEN'),
    ('resend', 'secret', 'RESEND_TOKEN'),
    ('revenuecat', 'secret', 'REVENUECAT_TOKEN'),
    ('river-markets', 'secret', 'RIVER_MARKETS_API_KEY'),
    ('runtime', 'secret', 'RUNTIME_API_KEY'),
    ('runway', 'secret', 'RUNWAY_TOKEN'),
    ('salesforce', 'secret', 'SALESFORCE_TOKEN'),
    ('salesforce', 'variable', 'SALESFORCE_INSTANCE'),
    ('salesgraph', 'secret', 'SALESGRAPH_API_KEY'),
    ('scrapeninja', 'secret', 'SCRAPENINJA_TOKEN'),
    ('segment', 'secret', 'SEGMENT_TOKEN'),
    ('semrush', 'secret', 'SEMRUSH_TOKEN'),
    ('sendgrid', 'secret', 'SENDGRID_TOKEN'),
    ('sentry', 'secret', 'SENTRY_ACCESS_TOKEN'),
    ('sentry', 'secret', 'SENTRY_REFRESH_TOKEN'),
    ('serpapi', 'secret', 'SERPAPI_TOKEN'),
    ('servicenow', 'secret', 'SERVICENOW_PASSWORD'),
    ('servicenow', 'secret', 'SERVICENOW_USERNAME'),
    ('servicenow', 'variable', 'SERVICENOW_INSTANCE'),
    ('shopify', 'secret', 'SHOPIFY_TOKEN'),
    ('shopify', 'variable', 'SHOPIFY_SHOP'),
    ('shortio', 'secret', 'SHORTIO_TOKEN'),
    ('silmaril', 'secret', 'SILMARIL_API_KEY'),
    ('similarweb', 'secret', 'SIMILARWEB_TOKEN'),
    ('slack', 'secret', 'SLACK_ACCESS_TOKEN'),
    ('slack-webhook', 'secret', 'SLACK_WEBHOOK_URL'),
    ('slock', 'secret', 'SLOCK_ACCESS_TOKEN'),
    ('slock', 'secret', 'SLOCK_REFRESH_TOKEN'),
    ('slock', 'secret', 'SLOCK_SERVER_ID'),
    ('smol-machines', 'secret', 'SMOL_MACHINES_API_KEY'),
    ('snowflake', 'secret', 'SNOWFLAKE_PAT'),
    ('snowflake', 'variable', 'SNOWFLAKE_ACCOUNT'),
    ('sociavault', 'secret', 'SOCIAVAULT_TOKEN'),
    ('sponge', 'secret', 'SPONGE_MASTER_KEY'),
    ('spotify', 'secret', 'SPOTIFY_ACCESS_TOKEN'),
    ('spotify', 'secret', 'SPOTIFY_REFRESH_TOKEN'),
    ('sproutgigs', 'secret', 'SPROUTGIGS_API_SECRET'),
    ('sproutgigs', 'variable', 'SPROUTGIGS_USER_ID'),
    ('square', 'secret', 'SQUARE_TOKEN'),
    ('stability-ai', 'secret', 'STABILITY_TOKEN'),
    ('stablebrowse', 'secret', 'STABLEBROWSE_API_KEY'),
    ('steam', 'variable', 'STEAM_ID'),
    ('strapi', 'secret', 'STRAPI_TOKEN'),
    ('strapi', 'variable', 'STRAPI_BASE_URL'),
    ('strava', 'secret', 'STRAVA_ACCESS_TOKEN'),
    ('strava', 'secret', 'STRAVA_REFRESH_TOKEN'),
    ('streak', 'secret', 'STREAK_TOKEN'),
    ('stripe', 'secret', 'STRIPE_ACCESS_TOKEN'),
    ('stripe', 'secret', 'STRIPE_REFRESH_TOKEN'),
    ('stripe', 'secret', 'STRIPE_TOKEN'),
    ('supabase', 'secret', 'SUPABASE_ACCESS_TOKEN'),
    ('supabase', 'secret', 'SUPABASE_REFRESH_TOKEN'),
    ('supabase', 'secret', 'SUPABASE_TOKEN'),
    ('supadata', 'secret', 'SUPADATA_TOKEN'),
    ('supermemory', 'secret', 'SUPERMEMORY_API_KEY'),
    ('tavily', 'secret', 'TAVILY_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_ACCESS_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_API_ACCESS_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_API_REFRESH_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_API_SECONDARY_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_API_TOKEN_ACCESS_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_REFRESH_TOKEN'),
    ('test-oauth', 'secret', 'TEST_OAUTH_TOKEN'),
    ('test-oauth', 'variable', 'TEST_OAUTH_API_TENANT_ID'),
    ('test-oauth', 'variable', 'TEST_OAUTH_API_TOKEN_INPUT_VAR'),
    ('test-oauth-device', 'secret', 'TEST_OAUTH_DEVICE_ACCESS_TOKEN'),
    ('test-oauth-device', 'secret', 'TEST_OAUTH_DEVICE_API_ACCESS_TOKEN'),
    ('testerarmy', 'secret', 'TESTERARMY_API_KEY'),
    ('testrail', 'secret', 'TESTRAIL_EMAIL'),
    ('testrail', 'secret', 'TESTRAIL_TOKEN'),
    ('testrail', 'variable', 'TESTRAIL_INSTANCE'),
    ('ticketmaster', 'secret', 'TICKETMASTER_API_KEY'),
    ('tiktok-ads', 'secret', 'TIKTOK_ADS_ACCESS_TOKEN'),
    ('tiktok-ads', 'secret', 'TIKTOK_ADS_REFRESH_TOKEN'),
    ('tldv', 'secret', 'TLDV_TOKEN'),
    ('todoist', 'secret', 'TODOIST_ACCESS_TOKEN'),
    ('together', 'secret', 'TOGETHER_TOKEN'),
    ('totalis', 'secret', 'TOTALIS_API_KEY'),
    ('trellis', 'secret', 'TRELLIS_API_KEY'),
    ('tripo', 'secret', 'TRIPO_API_KEY'),
    ('twenty', 'secret', 'TWENTY_TOKEN'),
    ('twilio', 'secret', 'TWILIO_ACCOUNT_SID'),
    ('twilio', 'secret', 'TWILIO_AUTH_TOKEN'),
    ('typeform', 'secret', 'TYPEFORM_TOKEN'),
    ('v0', 'secret', 'V0_TOKEN'),
    ('vercel', 'secret', 'VERCEL_ACCESS_TOKEN'),
    ('voquill', 'secret', 'VOQUILL_API_KEY'),
    ('wandb', 'secret', 'WANDB_TOKEN'),
    ('webflow', 'secret', 'WEBFLOW_ACCESS_TOKEN'),
    ('webflow', 'secret', 'WEBFLOW_TOKEN'),
    ('weread', 'secret', 'WEREAD_TOKEN'),
    ('whale-alert', 'secret', 'WHALE_ALERT_API_KEY'),
    ('wix', 'secret', 'WIX_TOKEN'),
    ('workday', 'secret', 'WORKDAY_ACCESS_TOKEN'),
    ('workday', 'secret', 'WORKDAY_CLIENT_SECRET'),
    ('workday', 'secret', 'WORKDAY_REFRESH_TOKEN'),
    ('workday', 'variable', 'WORKDAY_CLIENT_ID'),
    ('workday', 'variable', 'WORKDAY_HOST'),
    ('workday', 'variable', 'WORKDAY_TENANT'),
    ('workos', 'secret', 'WORKOS_TOKEN'),
    ('wrike', 'secret', 'WRIKE_TOKEN'),
    ('x', 'secret', 'X_ACCESS_TOKEN'),
    ('x', 'secret', 'X_REFRESH_TOKEN'),
    ('xero', 'secret', 'XERO_ACCESS_TOKEN'),
    ('xero', 'secret', 'XERO_REFRESH_TOKEN'),
    ('youtube', 'secret', 'YOUTUBE_ACCESS_TOKEN'),
    ('youtube', 'secret', 'YOUTUBE_REFRESH_TOKEN'),
    ('zapier', 'secret', 'ZAPIER_TOKEN'),
    ('zapsign', 'secret', 'ZAPSIGN_TOKEN'),
    ('zendesk', 'secret', 'ZENDESK_API_TOKEN'),
    ('zendesk', 'variable', 'ZENDESK_EMAIL'),
    ('zendesk', 'variable', 'ZENDESK_SUBDOMAIN'),
    ('zep', 'secret', 'ZEP_TOKEN'),
    ('zeptomail', 'secret', 'ZEPTOMAIL_TOKEN'),
    ('zoom', 'secret', 'ZOOM_ACCESS_TOKEN'),
    ('zoom', 'secret', 'ZOOM_REFRESH_TOKEN')
),
candidate_matches AS MATERIALIZED (
  SELECT
    credential."id" AS credential_id,
    connector."id" AS connector_id
  FROM "variables" AS credential
  INNER JOIN connector_credential_names AS mapping
    ON mapping.credential_kind = 'variable'
    AND mapping.credential_name = credential."name"
  INNER JOIN "connectors" AS connector
    ON connector."org_id" = credential."org_id"
    AND connector."user_id" = credential."user_id"
    AND connector."type" = mapping.connector_ref
  WHERE credential."type" = 'connector'
    AND credential."connector_id" IS NULL
  -- Keep the parent alive until this migration transaction commits. Without
  -- this lock, a concurrent disconnect can delete the connector after this
  -- match and make the connector_id update fail its foreign key check.
  FOR KEY SHARE OF connector
),
candidate_owners AS (
  SELECT
    credential_id,
    min(connector_id::text)::uuid AS connector_id
  FROM candidate_matches
  GROUP BY credential_id
  HAVING count(DISTINCT connector_id) = 1
)
UPDATE "variables" AS credential
SET "connector_id" = candidate.connector_id
FROM candidate_owners AS candidate
WHERE credential."id" = candidate.credential_id
  AND credential."type" = 'connector'
  AND credential."connector_id" IS NULL;
--> statement-breakpoint
DO $$
DECLARE
  missing_connector_versions bigint;
  unowned_connector_secrets bigint;
  unowned_connector_variables bigint;
  non_connector_secrets_with_owners bigint;
  non_connector_variables_with_owners bigint;
BEGIN
  SELECT count(*)
  INTO missing_connector_versions
  FROM "connectors"
  WHERE "storage_version" IS NULL OR "storage_version" <= 0;

  SELECT count(*)
  INTO unowned_connector_secrets
  FROM "secrets"
  WHERE "type" = 'connector' AND "connector_id" IS NULL;

  SELECT count(*)
  INTO unowned_connector_variables
  FROM "variables"
  WHERE "type" = 'connector' AND "connector_id" IS NULL;

  SELECT count(*)
  INTO non_connector_secrets_with_owners
  FROM "secrets"
  WHERE "type" <> 'connector' AND "connector_id" IS NOT NULL;

  SELECT count(*)
  INTO non_connector_variables_with_owners
  FROM "variables"
  WHERE "type" <> 'connector' AND "connector_id" IS NOT NULL;

  IF missing_connector_versions > 0
    OR unowned_connector_secrets > 0
    OR unowned_connector_variables > 0
    OR non_connector_secrets_with_owners > 0
    OR non_connector_variables_with_owners > 0
  THEN
    RAISE EXCEPTION
      'connector credential contraction blocked: missing_connector_versions=%, unowned_connector_secrets=%, unowned_connector_variables=%, non_connector_secrets_with_owners=%, non_connector_variables_with_owners=%',
      missing_connector_versions,
      unowned_connector_secrets,
      unowned_connector_variables,
      non_connector_secrets_with_owners,
      non_connector_variables_with_owners
      USING ERRCODE = 'check_violation';
  END IF;
END
$$;
--> statement-breakpoint
ALTER TABLE "connectors"
  ADD CONSTRAINT "chk_connectors_storage_version_not_null_contract"
  CHECK ("storage_version" IS NOT NULL) NOT VALID;
--> statement-breakpoint
ALTER TABLE "connectors"
  VALIDATE CONSTRAINT "chk_connectors_storage_version_not_null_contract";
--> statement-breakpoint
ALTER TABLE "connectors"
  ADD CONSTRAINT "chk_connectors_storage_version_positive_contract"
  CHECK ("storage_version" > 0) NOT VALID;
--> statement-breakpoint
ALTER TABLE "connectors"
  VALIDATE CONSTRAINT "chk_connectors_storage_version_positive_contract";
--> statement-breakpoint
ALTER TABLE "secrets"
  ADD CONSTRAINT "chk_secrets_connector_owner_type_contract"
  CHECK (("type" = 'connector') = ("connector_id" IS NOT NULL)) NOT VALID;
--> statement-breakpoint
ALTER TABLE "secrets"
  VALIDATE CONSTRAINT "chk_secrets_connector_owner_type_contract";
--> statement-breakpoint
ALTER TABLE "variables"
  ADD CONSTRAINT "chk_variables_connector_owner_type_contract"
  CHECK (("type" = 'connector') = ("connector_id" IS NOT NULL)) NOT VALID;
--> statement-breakpoint
ALTER TABLE "variables"
  VALIDATE CONSTRAINT "chk_variables_connector_owner_type_contract";
--> statement-breakpoint
ALTER TABLE "connectors" ALTER COLUMN "storage_version" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "connectors"
  DROP CONSTRAINT "chk_connectors_storage_version_not_null_contract";
--> statement-breakpoint
ALTER TABLE "connectors"
  DROP CONSTRAINT "chk_connectors_storage_version_positive";
--> statement-breakpoint
ALTER TABLE "connectors"
  RENAME CONSTRAINT "chk_connectors_storage_version_positive_contract"
  TO "chk_connectors_storage_version_positive";
--> statement-breakpoint
ALTER TABLE "secrets"
  DROP CONSTRAINT "chk_secrets_connector_owner_type";
--> statement-breakpoint
ALTER TABLE "secrets"
  RENAME CONSTRAINT "chk_secrets_connector_owner_type_contract"
  TO "chk_secrets_connector_owner_type";
--> statement-breakpoint
ALTER TABLE "variables"
  DROP CONSTRAINT "chk_variables_connector_owner_type";
--> statement-breakpoint
ALTER TABLE "variables"
  RENAME CONSTRAINT "chk_variables_connector_owner_type_contract"
  TO "chk_variables_connector_owner_type";
