-- Reclassify stored media already in the artifact catalog.
--
-- The catalog used to call a file `image` or `video` only when its metadata
-- carried a built-in generation marker, so images produced through a connector
-- provider and delivered by /uploads/complete or /uploads/import-image were
-- filed as `file`. The catalog now derives the kind from the file's own media
-- type, and `syncArtifactCatalogFile` only recomputes a row when its file is
-- touched, so existing rows need this one-time pass.
--
-- The kind entity carries whatever generation metadata the row happens to have;
-- `model`, `provider`, and `durationSeconds` stay null for media that was not
-- generated by a built-in pipeline. Nothing here changes `created_at`, so the
-- catalog keeps its order.
CREATE TEMP TABLE vm0_media_artifact_reclassify_plan ON COMMIT DROP AS
SELECT DISTINCT ON (file."id")
  artifact."id" AS artifact_id,
  file."id" AS file_id,
  CASE
    WHEN effective.content_type IN (
      'video/mp4',
      'video/webm',
      'video/quicktime'
    ) THEN 'video'
    ELSE 'image'
  END AS kind,
  file."metadata" ->> 'model' AS model,
  file."metadata" ->> 'provider' AS provider,
  CASE
    WHEN jsonb_typeof(file."metadata" -> 'durationSeconds') = 'number'
      THEN round((file."metadata" ->> 'durationSeconds')::numeric)::integer
    ELSE NULL
  END AS duration_seconds
FROM "artifacts" AS artifact
INNER JOIN "run_uploaded_files" AS file
  ON file."id" = artifact."projection_file_id"
CROSS JOIN LATERAL (
  -- Mirror of the API: the declared content type wins, and a row that never
  -- recorded one falls back to the extension map used by `inferMimetype`.
  SELECT COALESCE(
    NULLIF(btrim(lower(split_part(file."content_type", ';', 1))), ''),
    CASE lower(
      substring(COALESCE(file."filename", file."external_id") from '[.]([^.]*)$')
    )
      WHEN 'png' THEN 'image/png'
      WHEN 'jpg' THEN 'image/jpeg'
      WHEN 'jpeg' THEN 'image/jpeg'
      WHEN 'gif' THEN 'image/gif'
      WHEN 'webp' THEN 'image/webp'
      WHEN 'avif' THEN 'image/avif'
      WHEN 'svg' THEN 'image/svg+xml'
      WHEN 'mp4' THEN 'video/mp4'
      WHEN 'webm' THEN 'video/webm'
      WHEN 'mov' THEN 'video/quicktime'
      ELSE NULL
    END
  ) AS content_type
) AS effective
WHERE artifact."kind" = 'file'
  AND effective.content_type IN (
    'image/png',
    'image/jpeg',
    'image/gif',
    'image/webp',
    'image/avif',
    'image/svg+xml',
    'image/bmp',
    'image/heic',
    'image/heif',
    'video/mp4',
    'video/webm',
    'video/quicktime'
  )
ORDER BY file."id", artifact."id";--> statement-breakpoint

INSERT INTO "image_artifacts" ("file_id", "model", "provider")
SELECT plan.file_id, plan.model, plan.provider
FROM pg_temp.vm0_media_artifact_reclassify_plan AS plan
WHERE plan.kind = 'image'
ON CONFLICT ("file_id") DO NOTHING;--> statement-breakpoint

INSERT INTO "video_artifacts" ("file_id", "model", "duration_seconds")
SELECT plan.file_id, plan.model, plan.duration_seconds
FROM pg_temp.vm0_media_artifact_reclassify_plan AS plan
WHERE plan.kind = 'video'
ON CONFLICT ("file_id") DO NOTHING;--> statement-breakpoint

UPDATE "artifacts" AS artifact
SET
  "kind" = plan.kind,
  "entity_id" = COALESCE(image_entity."id", video_entity."id"),
  "updated_at" = now()
FROM pg_temp.vm0_media_artifact_reclassify_plan AS plan
LEFT JOIN "image_artifacts" AS image_entity
  ON plan.kind = 'image' AND image_entity."file_id" = plan.file_id
LEFT JOIN "video_artifacts" AS video_entity
  ON plan.kind = 'video' AND video_entity."file_id" = plan.file_id
WHERE artifact."id" = plan.artifact_id
  AND artifact."kind" = 'file'
  AND COALESCE(image_entity."id", video_entity."id") IS NOT NULL;--> statement-breakpoint

DO $$
DECLARE
  planned_artifacts bigint;
  remaining_file_kind bigint;
  orphan_rows bigint;
BEGIN
  SELECT count(*) INTO planned_artifacts
  FROM pg_temp.vm0_media_artifact_reclassify_plan;

  SELECT count(*) INTO remaining_file_kind
  FROM "artifacts" AS artifact
  INNER JOIN pg_temp.vm0_media_artifact_reclassify_plan AS plan
    ON plan.artifact_id = artifact."id"
  WHERE artifact."kind" = 'file';

  SELECT count(*) INTO orphan_rows
  FROM "artifacts" AS artifact
  WHERE (
      artifact."kind" = 'image'
      AND NOT EXISTS (
        SELECT 1 FROM "image_artifacts" AS entity
        WHERE entity."id" = artifact."entity_id"
      )
    )
    OR (
      artifact."kind" = 'video'
      AND NOT EXISTS (
        SELECT 1 FROM "video_artifacts" AS entity
        WHERE entity."id" = artifact."entity_id"
      )
    );

  IF orphan_rows > 0 THEN
    RAISE EXCEPTION
      'media artifact reclassification left % artifacts without a kind entity',
      orphan_rows
      USING ERRCODE = 'check_violation';
  END IF;

  IF remaining_file_kind > 0 THEN
    RAISE EXCEPTION
      'media artifact reclassification planned % artifacts but % kept kind file',
      planned_artifacts,
      remaining_file_kind
      USING ERRCODE = 'check_violation';
  END IF;

  RAISE NOTICE
    'media artifact reclassification covered % artifacts',
    planned_artifacts;
END
$$;
