ALTER TABLE "org_metadata" ADD COLUMN "acquisition_source_type" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_vm0_source" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_campaign_id" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_ad_group_id" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_campaign" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_utm_source" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_utm_medium" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_utm_content" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_utm_term" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_gclid" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_gbraid" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_wbraid" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_ga_client_id" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_landing_host" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_landing_path" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_referrer_domain" text;--> statement-breakpoint
ALTER TABLE "org_metadata" ADD COLUMN "acquisition_recorded_at" timestamp;--> statement-breakpoint
CREATE INDEX "idx_org_metadata_acquisition_campaign_id" ON "org_metadata" USING btree ("acquisition_campaign_id");--> statement-breakpoint
CREATE INDEX "idx_org_metadata_acquisition_ad_group_id" ON "org_metadata" USING btree ("acquisition_ad_group_id");