INSERT INTO "usage_pricing" ("kind", "provider", "category", "unit_price", "unit_size")
SELECT 'social', 'socialkit', "category", 5, 1
FROM unnest(ARRAY[
  'linkedin.profiles.extract',
  'linkedin.companies.extract',
  'linkedin.company-posts.extract',
  'linkedin.posts.extract',
  'linkedin.transcripts.extract',
  'twitter.profiles.extract',
  'twitter.timelines.extract',
  'twitter.posts.extract',
  'twitter.threads.extract',
  'twitter.transcripts.extract',
  'facebook.post-stats.extract',
  'facebook.page-stats.extract',
  'facebook.transcripts.extract',
  'facebook.comments.extract',
  'facebook.summaries.generate',
  'instagram.post-stats.extract',
  'instagram.channel-stats.extract',
  'instagram.transcripts.extract',
  'instagram.comments.extract',
  'instagram.channel-posts.extract',
  'instagram.channel-reels.extract',
  'instagram.reels-search',
  'instagram.summaries.generate',
  'tiktok.video-stats.extract',
  'tiktok.comments.extract',
  'tiktok.transcripts.extract',
  'tiktok.channel-stats.extract',
  'tiktok.channel-videos.extract',
  'tiktok.search',
  'tiktok.hashtag-search',
  'tiktok.summaries.generate',
  'youtube.transcripts.extract',
  'youtube.video-stats.extract',
  'youtube.comments.extract',
  'youtube.channel-stats.extract',
  'youtube.search',
  'youtube.videos.extract',
  'youtube.summaries.generate',
  'video.transcripts.extract',
  'video.summaries.generate'
]) AS "categories"("category")
ON CONFLICT ("kind", "provider", "category")
DO UPDATE SET
  "unit_price" = EXCLUDED."unit_price",
  "unit_size" = EXCLUDED."unit_size",
  "updated_at" = now();
