[package]
name = "child-exit-notifier"
version = "0.1.0"
edition.workspace = true

[dependencies]
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "process"] }

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { workspace = true, features = ["process"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }

[lints]
workspace = true
