/**
 * Generate Amplitude firewall config.
 *
 * Data source: https://amplitude.com/docs/apis/authentication
 *
 * Amplitude uses HTTP Basic Auth with the project's API key as the
 * username and secret key as the password for dashboard REST and Export
 * endpoints. The HTTP V2 ingestion API puts the api_key in the request
 * body instead — the ingestion host is still listed here so the proxy
 * allows egress, but no auth header is injected.
 *
 * Both credentials are 32-char hex strings.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://amplitude.com/docs/apis/authentication";
// 32-char hex placeholders built from Coffee/Safe/Local hex vocab.
const API_KEY_PLACEHOLDER = "c0ffee5afe10ca1c0ffee5afe10ca1c0";
const SECRET_KEY_PLACEHOLDER = "5afe10ca1c0ffee5afe10ca1c0ffee5a";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Amplitude API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:amplitude",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const amplitudeFirewall = {",
    '  name: "amplitude",',
    '  description: "Amplitude product analytics API",',
    "  placeholders: {",
    `    AMPLITUDE_API_KEY: "${API_KEY_PLACEHOLDER}",`,
    `    AMPLITUDE_SECRET_KEY: "${SECRET_KEY_PLACEHOLDER}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://amplitude.com",',
    "      auth: {",
    "        headers: {",
    "          Authorization:",
    '            "${{ basic(secrets.AMPLITUDE_API_KEY, secrets.AMPLITUDE_SECRET_KEY) }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "    {",
    '      base: "https://analytics.eu.amplitude.com",',
    "      auth: {",
    "        headers: {",
    "          Authorization:",
    '            "${{ basic(secrets.AMPLITUDE_API_KEY, secrets.AMPLITUDE_SECRET_KEY) }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "    {",
    '      base: "https://api2.amplitude.com",',
    "      auth: {},",
    "      permissions: [],",
    "    },",
    "    {",
    '      base: "https://api.eu.amplitude.com",',
    "      auth: {},",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Amplitude firewall config...");
  const ts = generateTypeScript();
  writeOutput("amplitude", ts, import.meta.dirname);
}
