import { writeOutput } from "./codegen";

const DOCS_URL = "https://docs.apollo.io/docs/api-overview";
const PLACEHOLDER_VALUE = "CoffeeSafeLocalCoffeeSafeLocalCoffee00";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Apollo.io API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:apollo",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const apolloFirewall = {",
    '  name: "apollo",',
    '  description: "Apollo",',
    "  placeholders: {",
    `    APOLLO_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.apollo.io",',
    "      auth: {",
    "        headers: {",
    '          "X-Api-Key": "${{ secrets.APOLLO_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Apollo firewall config...");
  const ts = generateTypeScript();
  writeOutput("apollo", ts, import.meta.dirname);
}
