/**
 * Generate Axiom firewall config.
 *
 * Data source: https://axiom.co/docs/reference/tokens
 *
 * Axiom is an observability platform for logs and metrics.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://axiom.co/docs/reference/tokens";
// Format: xaat- prefix + UUID (8-4-4-4-12 hex) = 41 total
const PLACEHOLDER_VALUE = "xaat-00000000-0000-0000-0000-000000000000";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Axiom API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:axiom",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const axiomFirewall: FirewallConfig = {",
    '  name: "axiom",',
    '  description: "Axiom API",',
    "  placeholders: {",
    `    AXIOM_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.axiom.co",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.AXIOM_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "};",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Axiom firewall config...");
  const ts = generateTypeScript();
  writeOutput("axiom", ts, import.meta.dirname);
}
