import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://developer.bill.com/docs/authentication-with-api-token";
const PLACEHOLDER = "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal";

export async function generate(): Promise<void> {
  writeOutput(
    "bill",
    [
      "// Auto-generated from BILL Spend & Expense API docs.",
      `// Source: ${DOCS_URL}`,
      "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:bill",
      "//",
      "// DO NOT EDIT THIS FILE MANUALLY.",
      "",
      'import type { FirewallConfig } from "../firewall-types";',
      "",
      "export const billFirewall = {",
      '  name: "bill",',
      '  description: "BILL Spend & Expense API",',
      "  placeholders: {",
      `    BILL_TOKEN: "${PLACEHOLDER}",`,
      "  },",
      "  apis: [",
      "    {",
      '      base: "https://gateway.prod.bill.com/connect",',
      "      auth: {",
      "        headers: {",
      '          apiToken: "${{ secrets.BILL_TOKEN }}",',
      "        },",
      "      },",
      "      permissions: [],",
      "    },",
      "  ],",
      "} as const satisfies FirewallConfig;",
      "",
    ].join("\n"),
  );
}
