/**
 * Bland API firewall config generator.
 *
 * Data source: https://docs.bland.ai/api-v1/post/calls
 *
 * Bland uses an API key in the Authorization header.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://docs.bland.ai/api-v1/post/calls";
const PLACEHOLDER_VALUE = "sk-CoffeeSafeLocalCoffeeSafeLocalCoffeeSafe";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Bland API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:bland",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const blandFirewall = {",
    '  name: "bland",',
    '  description: "Bland API",',
    "  placeholders: {",
    `    BLAND_API_KEY: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.bland.ai",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "${{ secrets.BLAND_API_KEY }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Bland firewall config...");
  const ts = generateTypeScript();
  writeOutput("bland", ts, import.meta.dirname);
}
