import { renderPermissions, writeOutput } from "./codegen";
import type { PermissionGroup } from "./codegen";

const DOCS_URL = "https://developer.box.com/reference/";
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal";

const API_PERMISSIONS: PermissionGroup[] = [
  {
    name: "users",
    description: "Read current user and user profile information.",
    rules: ["GET /2.0/users/me", "GET /2.0/users/{user-id}"],
  },
  {
    name: "folders",
    description: "Read and manage folders and folder items.",
    rules: [
      "GET /2.0/folders/{folder-id}",
      "GET /2.0/folders/{folder-id}/items",
      "POST /2.0/folders",
      "PUT /2.0/folders/{folder-id}",
      "DELETE /2.0/folders/{folder-id}",
    ],
  },
  {
    name: "files",
    description: "Read and manage files, content, versions, and metadata.",
    rules: [
      "GET /2.0/files/{file-id}",
      "GET /2.0/files/{file-id}/content",
      "GET /2.0/files/{file-id}/versions",
      "POST /2.0/files/{file-id}/copy",
      "PUT /2.0/files/{file-id}",
      "DELETE /2.0/files/{file-id}",
    ],
  },
  {
    name: "collaboration",
    description: "Read and manage collaborations, comments, tasks, and links.",
    rules: [
      "GET /2.0/collaborations/{collaboration-id}",
      "POST /2.0/collaborations",
      "DELETE /2.0/collaborations/{collaboration-id}",
      "GET /2.0/comments/{comment-id}",
      "POST /2.0/comments",
      "DELETE /2.0/comments/{comment-id}",
      "GET /2.0/tasks/{task-id}",
      "POST /2.0/tasks",
      "DELETE /2.0/tasks/{task-id}",
    ],
  },
  {
    name: "search-events",
    description: "Search Box content and read event streams.",
    rules: ["GET /2.0/search", "GET /2.0/events"],
  },
  {
    name: "webhooks",
    description: "Read and manage Box webhooks.",
    rules: [
      "GET /2.0/webhooks",
      "GET /2.0/webhooks/{webhook-id}",
      "POST /2.0/webhooks",
      "PUT /2.0/webhooks/{webhook-id}",
      "DELETE /2.0/webhooks/{webhook-id}",
    ],
  },
];

const UPLOAD_PERMISSIONS: PermissionGroup[] = [
  {
    name: "uploads",
    description: "Upload file content and new file versions.",
    rules: [
      "POST /api/2.0/files/content",
      "POST /api/2.0/files/{file-id}/content",
    ],
  },
];

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Box API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:box",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const boxFirewall = {",
    '  name: "box",',
    '  description: "Box API",',
    "  placeholders: {",
    `    BOX_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.box.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.BOX_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
    ...renderPermissions(API_PERMISSIONS),
    "      ],",
    "    },",
    "    {",
    '      base: "https://upload.box.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.BOX_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
    ...renderPermissions(UPLOAD_PERMISSIONS),
    "      ],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Box firewall config...");
  writeOutput("box", generateTypeScript(), import.meta.dirname);
}
