/**
 * Brave Search API firewall config generator.
 *
 * Data source: https://api-dashboard.search.brave.com/documentation/guides/authentication
 *
 * Brave Search uses a custom X-Subscription-Token header (not Bearer).
 * API key format: BSA prefix + 28 alphanumeric/dash/underscore chars (31 total).
 */

import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://api-dashboard.search.brave.com/documentation/guides/authentication";
// Format: BSA + 28 chars [a-zA-Z0-9_-] = 31 total
const PLACEHOLDER_VALUE = "BSACoffeeSafeLocalCoffeeSafe000";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Brave Search API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:brave-search",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const braveSearchFirewall = {",
    '  name: "brave-search",',
    '  description: "Brave Search API",',
    "  placeholders: {",
    `    BRAVE_API_KEY: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.search.brave.com",',
    "      auth: {",
    "        headers: {",
    '          "X-Subscription-Token": "${{ secrets.BRAVE_API_KEY }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Brave Search firewall config...");
  const ts = generateTypeScript();
  writeOutput("brave-search", ts, import.meta.dirname);
}
