/**
 * Generate Brevo firewall config.
 *
 * Data source: https://developers.brevo.com/docs/authentication-schemes
 *
 * Brevo (formerly Sendinblue) is an email marketing and CRM platform.
 * Uses custom "api-key" header (not Bearer).
 * Token format: xkeysib- prefix + hex string, ~70 chars total.
 * Only unrestricted permissions for now.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://developers.brevo.com/docs/authentication-schemes";
// Token format: xkeysib- prefix + hex-like string
const PLACEHOLDER_VALUE =
  "xkeysib-Vm0PlaceHolder0000000000000000000000000000000000000000000000a";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Brevo API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:brevo",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const brevoFirewall: FirewallConfig = {",
    '  name: "brevo",',
    '  description: "Brevo API",',
    "  placeholders: {",
    `    BREVO_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.brevo.com/v3",',
    "      auth: {",
    "        headers: {",
    '          "api-key": "${{ secrets.BREVO_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
    "        {",
    '          name: "unrestricted",',
    '          description: "Allow all endpoints",',
    '          rules: ["ANY /{path*}"],',
    "        },",
    "      ],",
    "    },",
    "  ],",
    "};",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Brevo firewall config...");
  const ts = generateTypeScript();
  writeOutput("brevo", ts, import.meta.dirname);
}
