import { writeOutput } from "./codegen";

const DOCS_URL = "https://www.canva.dev/docs/connect/authentication/";
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSa0";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Canva Connect API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:canva",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const canvaFirewall = {",
    '  name: "canva",',
    '  description: "Canva Connect API",',
    "  placeholders: {",
    `    CANVA_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.canva.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.CANVA_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Canva firewall config...");
  const ts = generateTypeScript();
  writeOutput("canva", ts, import.meta.dirname);
}
