/**
 * Generate Confluence Cloud firewall config from the official OpenAPI spec.
 *
 * Data source: https://developer.atlassian.com/cloud/confluence/swagger.v3.json
 * (Official OpenAPI 3.0.1 spec from Atlassian.)
 *
 * Permission groups are derived from OAuth 2.0 (3LO) scopes annotated
 * on each endpoint in the spec's security requirements (oAuthDefinitions).
 * Endpoints without OAuth2 security are skipped.
 */

import * as fs from "node:fs";
import * as path from "node:path";

const OPENAPI_URL =
  "https://developer.atlassian.com/cloud/confluence/swagger.v3.json";

// Atlassian API token placeholder.
// Format: ATATT3[A-Za-z0-9_\-=]{186} (192 chars total)
const PLACEHOLDER_VALUE =
  "ATATT3xVm0PlaceHolder000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

const OAUTH_SCHEME_KEY = "oAuthDefinitions";
const ALL_METHODS = new Set(["get", "head", "post", "put", "patch", "delete"]);
const OPENAPI_PATH_KEYS = new Set([
  "summary",
  "description",
  "servers",
  "parameters",
  "$ref",
  "options",
  "trace",
]);

// ── OpenAPI types ────────────────────────────────────────────────────────

interface OpenApiOperation {
  security?: Array<Record<string, string[]>>;
}

type OpenApiPathItem = Record<string, OpenApiOperation | unknown>;

interface OpenApiSpec {
  info?: { version?: string };
  paths?: Record<string, OpenApiPathItem>;
  components?: {
    securitySchemes?: {
      [key: string]: {
        flows?: {
          authorizationCode?: {
            scopes?: Record<string, string>;
          };
        };
      };
    };
  };
}

// ── Grouping ─────────────────────────────────────────────────────────────

interface PermissionGroup {
  name: string;
  description: string;
  rules: string[];
}

const METHOD_ORDER: Record<string, number> = {
  GET: 0,
  HEAD: 1,
  POST: 2,
  PUT: 3,
  PATCH: 4,
  DELETE: 5,
};

function ruleKey(rule: string): [string, number] {
  const [method, rulePath] = rule.split(" ", 2) as [string, string];
  return [rulePath, METHOD_ORDER[method] ?? 9];
}

function sortRules(rules: string[]): string[] {
  return [...rules].sort((a, b) => {
    const [pathA, orderA] = ruleKey(a);
    const [pathB, orderB] = ruleKey(b);
    return pathA < pathB ? -1 : pathA > pathB ? 1 : orderA - orderB;
  });
}

function buildGroups(spec: OpenApiSpec): PermissionGroup[] {
  const groups = new Map<string, Set<string>>();
  if (!spec.paths) {
    throw new Error("OpenAPI spec has no 'paths'");
  }

  for (const [apiPath, methods] of Object.entries(spec.paths)) {
    for (const [methodLower, op] of Object.entries(methods)) {
      if (typeof op !== "object" || op === null) continue;
      if (!ALL_METHODS.has(methodLower)) {
        if (OPENAPI_PATH_KEYS.has(methodLower) || methodLower.startsWith("x-"))
          continue;
        throw new Error(`Unexpected key '${methodLower}' on ${apiPath}`);
      }

      const operation: OpenApiOperation = op;
      const security = operation.security ?? [];
      let oauthScopes: string[] | null = null;
      for (const s of security) {
        if (OAUTH_SCHEME_KEY in s) {
          oauthScopes = s[OAUTH_SCHEME_KEY] ?? [];
          break;
        }
      }

      if (!oauthScopes || oauthScopes.length === 0) continue;

      const rule = `${methodLower.toUpperCase()} /ex/confluence/{cloudId}${apiPath}`;
      for (const scope of oauthScopes) {
        let ruleSet = groups.get(scope);
        if (!ruleSet) {
          ruleSet = new Set();
          groups.set(scope, ruleSet);
        }
        ruleSet.add(rule);
      }
    }
  }

  // Get scope descriptions from OAuth2 security scheme
  const scopeDescs =
    spec.components?.securitySchemes?.[OAUTH_SCHEME_KEY]?.flows
      ?.authorizationCode?.scopes ?? {};

  return [...groups.entries()]
    .filter(([, ruleSet]) => ruleSet.size > 0)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, ruleSet]) => ({
      name,
      description: scopeDescs[name] ?? "",
      rules: sortRules([...ruleSet]),
    }));
}

// ── TypeScript generation ────────────────────────────────────────────────

function escapeString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function generateTypeScript(permissions: PermissionGroup[]): string {
  const lines: string[] = [
    "// Auto-generated from Confluence Cloud's official OpenAPI spec.",
    `// Source: ${OPENAPI_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:confluence",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const confluenceFirewall: FirewallConfig = {",
    '  name: "confluence",',
    '  description: "Confluence Cloud API",',
    "  placeholders: {",
    `    CONFLUENCE_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.atlassian.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.CONFLUENCE_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
  ];

  // Catch-all: allows all endpoints
  lines.push("        {");
  lines.push('          name: "unrestricted",');
  lines.push('          description: "Allow all endpoints",');
  lines.push("          rules: [");
  lines.push('            "ANY /{path*}",');
  lines.push("          ],");
  lines.push("        },");

  for (const perm of permissions) {
    lines.push("        {");
    lines.push(`          name: "${escapeString(perm.name)}",`);
    if (perm.description) {
      lines.push(`          description: "${escapeString(perm.description)}",`);
    }
    lines.push("          rules: [");
    for (const rule of perm.rules) {
      lines.push(`            "${escapeString(rule)}",`);
    }
    lines.push("          ],");
    lines.push("        },");
  }

  lines.push("      ],");
  lines.push("    },");
  lines.push("  ],");
  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

// ── Main ─────────────────────────────────────────────────────────────────

export async function generate(): Promise<void> {
  console.error("Downloading Confluence OpenAPI spec…");
  const res = await fetch(OPENAPI_URL);
  if (!res.ok) {
    throw new Error(
      `Failed to fetch OpenAPI spec: ${res.status} ${res.statusText}`,
    );
  }
  const spec = (await res.json()) as OpenApiSpec;
  console.error(`  Spec version: ${spec.info?.version ?? "unknown"}`);

  const permissions = buildGroups(spec);
  const ts = generateTypeScript(permissions);

  const totalRules = permissions.reduce((sum, p) => sum + p.rules.length, 0);
  console.error(
    `  ${permissions.length} permission groups, ${totalRules} rules`,
  );

  const outPath = path.resolve(
    import.meta.dirname,
    "../../core/src/firewalls/confluence.generated.ts",
  );
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, ts);
  console.error(`  Written to ${outPath}`);

  const stat = fs.statSync(outPath);
  if (stat.size === 0) {
    throw new Error("Generated file is empty");
  }
  console.error(`  Validated (${(stat.size / 1024).toFixed(1)} KB)`);
}
