import { writeOutput } from "./codegen";

const DOCS_URL = "https://developer.copper.com/introduction/oauth/flow.html";

export async function generate(): Promise<void> {
  writeOutput(
    "copper",
    [
      "// Auto-generated from Copper Developer API docs.",
      `// Source: ${DOCS_URL}`,
      "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:copper",
      "//",
      "// DO NOT EDIT THIS FILE MANUALLY.",
      "",
      'import type { FirewallConfig } from "../firewall-types";',
      "",
      "export const copperFirewall = {",
      '  name: "copper",',
      '  description: "Copper Developer API",',
      "  placeholders: {",
      '    COPPER_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal",',
      "  },",
      "  apis: [",
      "    {",
      '      base: "https://api.copper.com/developer_api/v1",',
      "      auth: {",
      "        headers: {",
      '          Authorization: "Bearer ${{ secrets.COPPER_TOKEN }}",',
      "        },",
      "      },",
      "      permissions: [],",
      "    },",
      "  ],",
      "} as const satisfies FirewallConfig;",
      "",
    ].join("\n"),
  );
}
