import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://docs.datadoghq.com/extend/authorization/oauth2_in_datadog/";

export async function generate(): Promise<void> {
  writeOutput(
    "datadog",
    [
      "// Auto-generated from Datadog OAuth and API docs.",
      `// Source: ${DOCS_URL}`,
      "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:datadog",
      "//",
      "// DO NOT EDIT THIS FILE MANUALLY.",
      "",
      'import type { FirewallConfig } from "../firewall-types";',
      "",
      "export const datadogFirewall = {",
      '  name: "datadog",',
      '  description: "Datadog API",',
      "  placeholders: {",
      '    DATADOG_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal",',
      "  },",
      "  apis: [",
      "    {",
      '      base: "https://api.${{ vars.DATADOG_DOMAIN }}",',
      '      hostPolicy: { kind: "providerOwned", suffixes: [".datadoghq.com", ".datadoghq.eu", ".ddog-gov.com"] },',
      "      auth: {",
      "        headers: {",
      '          Authorization: "Bearer ${{ secrets.DATADOG_TOKEN }}",',
      "        },",
      "      },",
      "      permissions: [],",
      "    },",
      "  ],",
      "} as const satisfies FirewallConfig;",
      "",
    ].join("\n"),
  );
}
