import { writeOutput } from "./codegen";

const DOCS_URL = "https://db9.ai/docs/quickstart";
// 128-char hex placeholder (db9 bearer tokens are 128 hex chars, no prefix).
const PLACEHOLDER_VALUE =
  "c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5a";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from db9.ai API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:db9",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const db9Firewall = {",
    '  name: "db9",',
    '  description: "db9 API",',
    "  placeholders: {",
    `    DB9_API_KEY: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.db9.ai",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.DB9_API_KEY }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating db9 firewall config...");
  const ts = generateTypeScript();
  writeOutput("db9", ts, import.meta.dirname);
}
