/**
 * Generate DeepSeek firewall config.
 *
 * Data source: https://api-docs.deepseek.com/
 *
 * DeepSeek uses Bearer token authentication via Authorization header.
 * OpenAI-compatible API. Token format: sk- + 48 alphanumeric chars.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://api-docs.deepseek.com/";
// Format: sk- + 48 alphanumeric chars (total 51)
const PLACEHOLDER_VALUE = "sk-Vm0PlaceHolder0000000000000000000000000000000000";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from DeepSeek API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:deepseek",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const deepseekFirewall: FirewallConfig = {",
    '  name: "deepseek",',
    '  description: "DeepSeek API",',
    "  placeholders: {",
    `    DEEPSEEK_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.deepseek.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.DEEPSEEK_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "};",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating DeepSeek firewall config...");
  const ts = generateTypeScript();
  writeOutput("deepseek", ts, import.meta.dirname);
}
