/**
 * DefiLlama Pro API firewall config generator.
 *
 * Data source: https://defillama.com/pro-api/docs
 *
 * DefiLlama Pro authenticates by placing the API key in the URL path:
 * https://pro-api.llama.fi/{YOUR_API_KEY}/...
 *
 * Uses auth.base for URL rewriting so callers can use a stable placeholder
 * base URL and the proxy replaces the path segment with the real key.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://defillama.com/pro-api/docs";
// No documented key format; generic alphanumeric.
const PLACEHOLDER_VALUE = "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCof";
const PLACEHOLDER_BASE = `https://pro-api.llama.fi/${PLACEHOLDER_VALUE}`;

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from DefiLlama Pro API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:defillama",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const defillamaFirewall = {",
    '  name: "defillama",',
    '  description: "DefiLlama Pro API",',
    "  placeholders: {",
    `    DEFILLAMA_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    `      base: "${PLACEHOLDER_BASE}",`,
    "      auth: {",
    '        base: "https://pro-api.llama.fi/${{ secrets.DEFILLAMA_TOKEN }}",',
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating DefiLlama firewall config...");
  const ts = generateTypeScript();
  writeOutput("defillama", ts, import.meta.dirname);
}
