/**
 * Generate Discord Webhook firewall config.
 *
 * Discord Webhooks use a URL that embeds credentials in the path:
 *   https://discord.com/api/webhooks/{webhook_id}/{webhook_token}
 *
 * Uses auth.base for URL rewriting — agent sends to a placeholder
 * host, mitmproxy rewrites to the real webhook URL.
 */

import { FIREWALL_PLACEHOLDER_HOST, writeOutput } from "./codegen";

const PLACEHOLDER_BASE = `https://${FIREWALL_PLACEHOLDER_HOST}/discord-webhook/hook`;

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated firewall config for Discord Webhook.",
    "// Webhook URL contains credentials in the path — uses auth.base for URL rewriting.",
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:discord-webhook",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const discordWebhookFirewall = {",
    '  name: "discord-webhook",',
    '  description: "Discord Webhook",',
    "  placeholders: {",
    `    DISCORD_WEBHOOK_URL: "${PLACEHOLDER_BASE}",`,
    "  },",
    "  apis: [",
    "    {",
    `      base: "${PLACEHOLDER_BASE}",`,
    "      auth: {",
    '        base: "${{ secrets.DISCORD_WEBHOOK_URL }}",',
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Discord Webhook firewall config...");
  const ts = generateTypeScript();
  writeOutput("discord-webhook", ts, import.meta.dirname);
}
