/**
 * Generate DocuSign firewall config.
 *
 * Data source: https://developers.docusign.com/platform/api-endpoint-base-paths/
 *
 * DocuSign uses region-specific domains. Production servers:
 * www (na1), na2, na3, na4, eu, au, ca + demo for sandbox.
 * All regions share the same Bearer token auth.
 */

import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://developers.docusign.com/platform/api-endpoint-base-paths/";

// DocuSign access tokens are JWTs (eyJ...), typically 600-900+ chars.
// Use a shortened JWT-like placeholder.
const PLACEHOLDER_VALUE =
  "eyJ0eXAiOiJNVCIsImFsZyI6IlJTMjU2In0.CoffeeSafeLocalCoffeeSafeLocal.CoffeeSaf";

// All known DocuSign API server domains (production + demo).
// See: https://developers.docusign.com/platform/api-endpoint-base-paths/
const DOCUSIGN_DOMAINS = [
  "www.docusign.net",
  "na2.docusign.net",
  "na3.docusign.net",
  "na4.docusign.net",
  "eu.docusign.net",
  "au.docusign.net",
  "ca.docusign.net",
  "demo.docusign.net",
];

// OAuth/userinfo endpoints — required to discover the correct regional
// API base URI before making any eSignature API calls.
// See: https://developers.docusign.com/platform/auth/reference/user-info/
const DOCUSIGN_OAUTH_DOMAINS = [
  "account.docusign.com", // production
  "account-d.docusign.com", // demo/development
];

function generateTypeScript(): string {
  const apiEntries = [...DOCUSIGN_DOMAINS, ...DOCUSIGN_OAUTH_DOMAINS]
    .map(
      (domain) => `    {
      base: "https://${domain}",
      auth: {
        headers: {
          Authorization: "Bearer $\{{ secrets.DOCUSIGN_TOKEN }}",
        },
      },
      permissions: [],
    }`,
    )
    .join(",\n");

  const lines: string[] = [
    "// Auto-generated from DocuSign API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:docusign",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const docusignFirewall = {",
    '  name: "docusign",',
    '  description: "DocuSign eSignature REST API",',
    "  placeholders: {",
    `    DOCUSIGN_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    apiEntries + ",",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating DocuSign firewall config...");
  const ts = generateTypeScript();
  writeOutput("docusign", ts, import.meta.dirname);
}
