/**
 * Generate Dropbox Sign (formerly HelloSign) firewall config.
 *
 * Data source: https://developer.hellosign.com/api/api-reference-authentication
 *
 * Dropbox Sign uses HTTP Basic Auth with the API key as the username and
 * an empty password. The `basic(secrets.X, )` template helper produces
 * `Basic base64(apikey:)` at request time.
 *
 * Token format: 40-character hex string.
 */

import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://developer.hellosign.com/api/api-reference-authentication";
// 40-char hex to match Dropbox Sign API key format
const PLACEHOLDER_VALUE = "c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Dropbox Sign (HelloSign) API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:dropbox-sign",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const dropboxSignFirewall = {",
    '  name: "dropbox-sign",',
    '  description: "Dropbox Sign (HelloSign) e-signature API",',
    "  placeholders: {",
    `    DROPBOX_SIGN_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.hellosign.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "${{ basic(secrets.DROPBOX_SIGN_TOKEN, ) }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Dropbox Sign firewall config...");
  const ts = generateTypeScript();
  writeOutput("dropbox-sign", ts, import.meta.dirname);
}
