/**
 * Generate ElevenLabs firewall config.
 *
 * Data source: https://elevenlabs.io/docs/api-reference/authentication
 *
 * ElevenLabs uses a custom header `xi-api-key` for authentication.
 * No documented token format; using generic alphanumeric placeholder.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://elevenlabs.io/docs/api-reference/authentication";
// No documented format; generic 32-char alphanumeric
const PLACEHOLDER_VALUE = "Vm0PlaceHolder00000000000000000a";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from ElevenLabs API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:elevenlabs",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const elevenlabsFirewall: FirewallConfig = {",
    '  name: "elevenlabs",',
    '  description: "ElevenLabs API",',
    "  placeholders: {",
    `    ELEVENLABS_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.elevenlabs.io",',
    "      auth: {",
    "        headers: {",
    '          "xi-api-key": "${{ secrets.ELEVENLABS_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
    "        {",
    '          name: "unrestricted",',
    '          description: "Allow all endpoints",',
    '          rules: ["ANY /{path*}"],',
    "        },",
    "      ],",
    "    },",
    "  ],",
    "};",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating ElevenLabs firewall config...");
  const ts = generateTypeScript();
  writeOutput("elevenlabs", ts, import.meta.dirname);
}
