import { writeOutput } from "./codegen";

const DOCS_URL = "https://exa.ai/docs/reference/search-api-guide";
const PLACEHOLDER_VALUE = "exa_CoffeeSafeLocalCoffeeSafeLocalCof";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Exa API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:exa",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const exaFirewall = {",
    '  name: "exa",',
    '  description: "Exa",',
    "  placeholders: {",
    `    EXA_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.exa.ai",',
    "      auth: {",
    "        headers: {",
    '          "x-api-key": "${{ secrets.EXA_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Exa firewall config...");
  const ts = generateTypeScript();
  writeOutput("exa", ts, import.meta.dirname);
}
