/**
 * Generate Fireflies.ai firewall config.
 *
 * Data source: https://docs.fireflies.ai/fundamentals/authorization
 *
 * Fireflies.ai is a meeting transcription and note-taking platform.
 * Uses Bearer token authentication over GraphQL.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://docs.fireflies.ai/fundamentals/authorization";
// Token format not publicly documented; using generic placeholder
const PLACEHOLDER_VALUE = "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalC";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Fireflies.ai API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:fireflies",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const firefliesFirewall = {",
    '  name: "fireflies",',
    '  description: "Fireflies.ai API",',
    "  placeholders: {",
    `    FIREFLIES_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.fireflies.ai/graphql",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.FIREFLIES_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Fireflies.ai firewall config...");
  const ts = generateTypeScript();
  writeOutput("fireflies", ts, import.meta.dirname);
}
