/**
 * Generate Google Analytics firewall configs from Google Discovery API
 * documents.
 *
 * Google Analytics exposes GA4 reporting through analyticsdata.googleapis.com
 * and administration through analyticsadmin.googleapis.com. Keep those API
 * roots separate so generated rules only apply to the host that owns them.
 */

import {
  escapeString,
  fetchSpec,
  logStats,
  renderPermissions,
  sanitizeAndSortRules,
  writeOutput,
} from "./codegen";
import type { PermissionGroup } from "./codegen";

const SCOPE_PREFIX = "https://www.googleapis.com/auth/";
const OAUTH_PLACEHOLDER =
  "ya29.A0CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSa";

function shortScope(scope: string): string {
  if (scope.startsWith(SCOPE_PREFIX)) {
    return scope.slice(SCOPE_PREFIX.length);
  }
  return scope;
}

interface DiscoveryMethod {
  id?: string;
  httpMethod?: string;
  path?: string;
  flatPath?: string;
  scopes?: string[];
}

interface DiscoveryResource {
  methods?: Record<string, DiscoveryMethod>;
  resources?: Record<string, DiscoveryResource>;
}

interface DiscoveryDocument {
  version?: string;
  resources?: Record<string, DiscoveryResource>;
  auth?: {
    oauth2?: {
      scopes?: Record<string, { description?: string }>;
    };
  };
}

interface AnalyticsApiConfig {
  discoveryUrl: string;
  baseUrl: string;
}

interface AnalyticsApiEntry {
  base: string;
  permissions: PermissionGroup[];
}

function extractMethods(
  resources: Record<string, DiscoveryResource>,
): DiscoveryMethod[] {
  const methods: DiscoveryMethod[] = [];
  for (const resource of Object.values(resources)) {
    if (resource.methods) {
      methods.push(...Object.values(resource.methods));
    }
    if (resource.resources) {
      methods.push(...extractMethods(resource.resources));
    }
  }
  return methods;
}

function buildGroups(discovery: DiscoveryDocument): PermissionGroup[] {
  const groups = new Map<string, Set<string>>();

  for (const method of extractMethods(discovery.resources ?? {})) {
    const httpMethod = method.httpMethod;
    const methodPath = method.flatPath ?? method.path;
    const scopes = method.scopes;

    if (!httpMethod || !methodPath) {
      throw new Error(
        `Method missing httpMethod or path: ${method.id ?? "unknown"}`,
      );
    }
    if (!scopes || scopes.length === 0) {
      throw new Error(
        `Method has no scopes: ${method.id ?? `${httpMethod} ${methodPath}`}`,
      );
    }

    const normalizedPath = methodPath.replace(/^\/+/, "");
    const rule = `${httpMethod.toUpperCase()} /${normalizedPath}`;
    for (const scope of scopes) {
      const name = shortScope(scope);
      let rules = groups.get(name);
      if (!rules) {
        rules = new Set();
        groups.set(name, rules);
      }
      rules.add(rule);
    }
  }

  const scopeDescriptions = new Map<string, string>();
  const oauthScopes = discovery.auth?.oauth2?.scopes ?? {};
  for (const [scopeUrl, info] of Object.entries(oauthScopes)) {
    scopeDescriptions.set(shortScope(scopeUrl), info.description ?? "");
  }

  return [...groups.entries()]
    .filter(([, rules]) => rules.size > 0)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, rules]) => ({
      name,
      description: scopeDescriptions.get(name) ?? "",
      rules: sanitizeAndSortRules([...rules]),
    }));
}

function generateTypeScript(
  apis: AnalyticsApiEntry[],
  discoveryUrls: readonly string[],
): string {
  const lines: string[] = [
    "// Auto-generated from Google's Discovery API.",
    ...discoveryUrls.map((url) => `// Source: ${url}`),
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:google-analytics",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const googleAnalyticsFirewall = {",
    '  name: "google-analytics",',
    '  description: "Google Analytics Data and Admin APIs",',
    "  placeholders: {",
    `    GOOGLE_ANALYTICS_TOKEN: "${OAUTH_PLACEHOLDER}",`,
    "  },",
    "  apis: [",
  ];

  for (const api of apis) {
    lines.push("    {");
    lines.push(`      base: "${escapeString(api.base)}",`);
    lines.push("      auth: {");
    lines.push("        headers: {");
    lines.push(
      '          Authorization: "Bearer ${{ secrets.GOOGLE_ANALYTICS_TOKEN }}",',
    );
    lines.push("        },");
    lines.push("      },");
    lines.push("      permissions: [");
    lines.push(...renderPermissions(api.permissions));
    lines.push("      ],");
    lines.push("    },");
  }

  lines.push("  ],");
  lines.push("} as const satisfies FirewallConfig;");
  lines.push("");

  return lines.join("\n");
}

const APIS: readonly AnalyticsApiConfig[] = [
  {
    discoveryUrl:
      "https://analyticsdata.googleapis.com/$discovery/rest?version=v1beta",
    baseUrl: "https://analyticsdata.googleapis.com",
  },
  {
    discoveryUrl:
      "https://analyticsadmin.googleapis.com/$discovery/rest?version=v1beta",
    baseUrl: "https://analyticsadmin.googleapis.com",
  },
];

export async function generate(): Promise<void> {
  console.error("Generating Google Analytics firewall config...");

  const apis: AnalyticsApiEntry[] = [];
  for (const api of APIS) {
    const res = await fetchSpec(api.discoveryUrl, "google-analytics discovery");
    const discovery = (await res.json()) as DiscoveryDocument;
    console.error(
      `  ${api.baseUrl} API version: ${discovery.version ?? "unknown"}`,
    );
    const permissions = buildGroups(discovery);
    logStats(permissions);
    apis.push({ base: api.baseUrl, permissions });
  }

  const ts = generateTypeScript(
    apis,
    APIS.map((api) => api.discoveryUrl),
  );
  writeOutput("google-analytics", ts, import.meta.dirname);
}
