/**
 * Generate Groq firewall config.
 *
 * Data source: https://console.groq.com/docs/overview
 *
 * Groq uses Bearer token authentication via Authorization header.
 * Token format: gsk_ + 52 base62 chars [A-Za-z0-9]
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://console.groq.com/docs/overview";
// Format: gsk_ + [A-Za-z0-9]{52}
const PLACEHOLDER_VALUE =
  "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";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Groq API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:groq",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const groqFirewall = {",
    '  name: "groq",',
    '  description: "Groq",',
    "  placeholders: {",
    `    GROQ_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.groq.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.GROQ_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Groq firewall config...");
  const ts = generateTypeScript();
  writeOutput("groq", ts, import.meta.dirname);
}
