/**
 * Generate Gumroad firewall config.
 *
 * Data source: https://gumroad.com/api
 *
 * Gumroad uses Bearer token authentication via Authorization header.
 * Token format: opaque alphanumeric string (~40 chars), no prefix.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://gumroad.com/api";
const PLACEHOLDER_VALUE = "c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Gumroad API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:gumroad",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const gumroadFirewall = {",
    '  name: "gumroad",',
    '  description: "Gumroad",',
    "  placeholders: {",
    `    GUMROAD_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.gumroad.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.GUMROAD_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Gumroad firewall config...");
  const ts = generateTypeScript();
  writeOutput("gumroad", ts, import.meta.dirname);
}
