/**
 * Generate Honcho firewall config.
 *
 * Data sources:
 * - https://honcho.dev/docs/v3/documentation/introduction/quickstart
 * - https://honcho.dev/docs/v3/api-reference/introduction
 *
 * Honcho API keys authenticate via Bearer auth in the Authorization header.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://honcho.dev/docs/v3/api-reference/introduction";
const PLACEHOLDER_VALUE = "hch-v3-CoffeeSafeLocalCoffeeSafeLocalCoffeeSafe";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Honcho API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:honcho",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const honchoFirewall = {",
    '  name: "honcho",',
    '  description: "Honcho API",',
    "  placeholders: {",
    `    HONCHO_API_KEY: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.honcho.dev",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.HONCHO_API_KEY }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Honcho firewall config...");
  const ts = generateTypeScript();
  writeOutput("honcho", ts, import.meta.dirname);
}
