/**
 * Generate Hume firewall config.
 *
 * Data source: https://dev.hume.ai/docs/introduction/api-key
 *
 * Hume AI is an emotion AI platform.
 * Uses custom X-Hume-Api-Key header authentication.
 * Token format: opaque API key string.
 * Only unrestricted permissions for now.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://dev.hume.ai/docs/introduction/api-key";
// API key format not documented; using generic placeholder
const PLACEHOLDER_VALUE =
  "vm0placeholder00000000000000000000000000000000000000000000000000a";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Hume AI API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:hume",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const humeFirewall: FirewallConfig = {",
    '  name: "hume",',
    '  description: "Hume AI API",',
    "  placeholders: {",
    `    HUME_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.hume.ai",',
    "      auth: {",
    "        headers: {",
    '          "X-Hume-Api-Key": "${{ secrets.HUME_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
    "        {",
    '          name: "unrestricted",',
    '          description: "Allow all endpoints",',
    '          rules: ["ANY /{path*}"],',
    "        },",
    "      ],",
    "    },",
    "  ],",
    "};",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Hume AI firewall config...");
  const ts = generateTypeScript();
  writeOutput("hume", ts, import.meta.dirname);
}
