/**
 * Generate Intercom firewall config.
 *
 * Data source: https://developers.intercom.com/docs/build-an-integration/learn-more/authentication
 *
 * Intercom is a customer messaging platform.
 * Uses Bearer token authentication.
 * Token format: base64 string with "dG9rOi" prefix (base64 of "tok:"), ~60-80 chars.
 */

import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication";
// Token format: dG9rOi (base64 "tok:") + base64 chars, ~70 chars total
const PLACEHOLDER_VALUE =
  "dG9rOiCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCof";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Intercom API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:intercom",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const intercomFirewall = {",
    '  name: "intercom",',
    '  description: "Intercom API",',
    "  placeholders: {",
    `    INTERCOM_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.intercom.io",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.INTERCOM_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Intercom firewall config...");
  const ts = generateTypeScript();
  writeOutput("intercom", ts, import.meta.dirname);
}
