/**
 * Generate Ironclad firewall config.
 *
 * Data source: https://developer.ironcladapp.com/
 *
 * Ironclad (API token auth) uses a static API key as a Bearer token.
 * The API host is region-specific (ironcladapp.com for North America,
 * eu1.ironcladapp.com for Europe, demo.ironcladapp.com for demo), so it
 * is supplied as a variable.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://developer.ironcladapp.com/";
// Ironclad API keys are long base62 strings.
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Ironclad API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:ironclad",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const ironcladFirewall = {",
    '  name: "ironclad",',
    '  description: "Ironclad API (API key auth)",',
    "  placeholders: {",
    `    IRONCLAD_API_KEY: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://${{ vars.IRONCLAD_HOST }}",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.IRONCLAD_API_KEY }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Ironclad firewall config...");
  const ts = generateTypeScript();
  writeOutput("ironclad", ts, import.meta.dirname);
}
