/**
 * Generate Jam firewall config.
 *
 * Data source: https://jam.dev/docs/debug-a-jam/mcp/personal-access-tokens
 *
 * Jam is a bug reporting and debugging platform. Its API is exposed
 * exclusively through a single MCP endpoint. Bearer token authentication
 * via Personal Access Tokens (format: jam_pat_...).
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://jam.dev/docs/debug-a-jam/mcp/personal-access-tokens";
// Format: jam_pat_ + opaque string
const PLACEHOLDER_VALUE = "jam_pat_CoffeeSafeLocalCoffeeSafeLocalCoff";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Jam API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:jam",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const jamFirewall = {",
    '  name: "jam",',
    '  description: "Jam API",',
    "  placeholders: {",
    `    JAM_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://mcp.jam.dev",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.JAM_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Jam firewall config...");
  const ts = generateTypeScript();
  writeOutput("jam", ts, import.meta.dirname);
}
