/**
 * Generate Jira Cloud firewall config from the official OpenAPI spec.
 *
 * Data source: https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json
 * (Official OpenAPI 3.0.1 spec from Atlassian.)
 *
 * Permission groups are derived from OAuth 2.0 (3LO) scopes annotated
 * on each endpoint in the spec's security requirements (OAuth2).
 * Endpoints without OAuth2 security are skipped.
 */

import {
  ALL_METHODS,
  OPENAPI_PATH_KEYS,
  fetchSpec,
  logStats,
  renderPermissions,
  sortRules,
  writeOutput,
} from "./codegen";
import type { OpenApiOperation, OpenApiSpec, PermissionGroup } from "./codegen";

const OPENAPI_URL =
  "https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json";

// Atlassian API token placeholder.
// Format: ATATT3[A-Za-z0-9_\-=]{186} (192 chars total)
const PLACEHOLDER_VALUE =
  "ATATT3xVm0PlaceHolder000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

const OAUTH_SCHEME_KEY = "OAuth2";

// ── Grouping ─────────────────────────────────────────────────────────────

function buildGroups(spec: OpenApiSpec): PermissionGroup[] {
  const groups = new Map<string, Set<string>>();
  if (!spec.paths) {
    throw new Error("OpenAPI spec has no 'paths'");
  }

  for (const [apiPath, methods] of Object.entries(spec.paths)) {
    for (const [methodLower, op] of Object.entries(methods)) {
      if (typeof op !== "object" || op === null) continue;
      if (!ALL_METHODS.has(methodLower)) {
        if (OPENAPI_PATH_KEYS.has(methodLower) || methodLower.startsWith("x-"))
          continue;
        throw new Error(`Unexpected key '${methodLower}' on ${apiPath}`);
      }

      const operation: OpenApiOperation = op;
      const security = operation.security ?? [];
      let oauthScopes: string[] | null = null;
      for (const s of security) {
        if (OAUTH_SCHEME_KEY in s) {
          oauthScopes = s[OAUTH_SCHEME_KEY] ?? [];
          break;
        }
      }

      if (!oauthScopes || oauthScopes.length === 0) continue;

      const rule = `${methodLower.toUpperCase()} /ex/jira/{cloudId}${apiPath}`;
      for (const scope of oauthScopes) {
        let ruleSet = groups.get(scope);
        if (!ruleSet) {
          ruleSet = new Set();
          groups.set(scope, ruleSet);
        }
        ruleSet.add(rule);
      }
    }
  }

  // Get scope descriptions from OAuth2 security scheme
  const scopeDescs =
    spec.components?.securitySchemes?.[OAUTH_SCHEME_KEY]?.flows
      ?.authorizationCode?.scopes ?? {};

  return [...groups.entries()]
    .filter(([, ruleSet]) => ruleSet.size > 0)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, ruleSet]) => ({
      name,
      description: scopeDescs[name] ?? "",
      rules: sortRules([...ruleSet]),
    }));
}

// ── TypeScript generation ────────────────────────────────────────────────

function generateTypeScript(permissions: PermissionGroup[]): string {
  const lines: string[] = [
    "// Auto-generated from Jira Cloud's official OpenAPI spec.",
    `// Source: ${OPENAPI_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:jira",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const jiraFirewall: FirewallConfig = {",
    '  name: "jira",',
    '  description: "Jira Cloud API",',
    "  placeholders: {",
    `    ATLASSIAN_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.atlassian.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.ATLASSIAN_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
  ];

  lines.push(...renderPermissions(permissions));

  lines.push("      ],");
  lines.push("    },");
  lines.push("  ],");
  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

// ── Main ─────────────────────────────────────────────────────────────────

export async function generate(): Promise<void> {
  const res = await fetchSpec(OPENAPI_URL, "Jira OpenAPI spec");
  const spec = (await res.json()) as OpenApiSpec;
  console.error(`  Spec version: ${spec.info?.version ?? "unknown"}`);

  const permissions = buildGroups(spec);
  const ts = generateTypeScript(permissions);

  logStats(permissions);
  writeOutput("jira", ts, import.meta.dirname);
}
