/**
 * Generate Jotform firewall config.
 *
 * Data source: https://api.jotform.com/docs/
 *
 * Jotform is an online form builder platform.
 * Uses custom APIKEY header authentication.
 * Three base URLs: api.jotform.com, eu-api.jotform.com, hipaa-api.jotform.com.
 * Token format: opaque string, no known prefix.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://api.jotform.com/docs/";
// API key format not documented; using generic placeholder
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffe";

const DOMAINS = [
  "api.jotform.com",
  "eu-api.jotform.com",
  "hipaa-api.jotform.com",
] as const;

function generateTypeScript(): string {
  const apiEntries = DOMAINS.map(
    (domain) => `    {
      base: "https://${domain}",
      auth: {
        headers: {
          APIKEY: "$\{{ secrets.JOTFORM_TOKEN }}",
        },
      },
      permissions: [],
    }`,
  );

  const lines: string[] = [
    "// Auto-generated from Jotform API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:jotform",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const jotformFirewall = {",
    '  name: "jotform",',
    '  description: "Jotform API",',
    "  placeholders: {",
    `    JOTFORM_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    apiEntries.join(",\n"),
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Jotform firewall config...");
  const ts = generateTypeScript();
  writeOutput("jotform", ts, import.meta.dirname);
}
