import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://docs.mailsac.com/en/master/api_examples/getting_started/getting_started.html";
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafe";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Mailsac API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:mailsac",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const mailsacFirewall = {",
    '  name: "mailsac",',
    '  description: "Mailsac Email API",',
    "  placeholders: {",
    `    MAILSAC_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://mailsac.com",',
    "      auth: {",
    "        headers: {",
    '          "Mailsac-Key": "${{ secrets.MAILSAC_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Mailsac firewall config...");
  const ts = generateTypeScript();
  writeOutput("mailsac", ts, import.meta.dirname);
}
