/**
 * Massive API firewall config generator.
 *
 * Data sources:
 * - https://massive.com/docs/rest/quickstart
 * - https://github.com/polygon-io
 *
 * Massive, formerly Polygon.io, supports API key authentication via
 * Authorization: Bearer and continues to support the legacy api.polygon.io
 * host. API key format is not publicly documented; using generic placeholder.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://massive.com/docs/rest/quickstart";
const PLACEHOLDER_VALUE = "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCof";

function authLines(indent: string): string[] {
  return [
    `${indent}auth: {`,
    `${indent}  headers: {`,
    `${indent}    Authorization: "Bearer \${{ secrets.MASSIVE_TOKEN }}",`,
    `${indent}  },`,
    `${indent}},`,
  ];
}

function apiLines(base: string): string[] {
  return [
    "    {",
    `      base: "${base}",`,
    ...authLines("      "),
    "      permissions: [],",
    "    },",
  ];
}

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Massive API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:massive",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const massiveFirewall = {",
    '  name: "massive",',
    '  description: "Massive market data API",',
    "  placeholders: {",
    `    MASSIVE_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    ...apiLines("https://api.massive.com"),
    ...apiLines("https://api.polygon.io"),
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Massive firewall config...");
  const ts = generateTypeScript();
  writeOutput("massive", ts, import.meta.dirname);
}
