import * as fs from "node:fs";
import * as path from "node:path";
import { createHash } from "node:crypto";

import { MODEL_PROVIDER_FIREWALL_CONFIGS } from "@vm0/api-contracts/contracts/model-provider-firewalls";
import type { ConnectorType } from "@vm0/connectors/connectors";
import type {
  FirewallPermissionDefaultPolicyMetadata,
  FirewallPermissionDetailMetadata,
  FirewallPermissionMetadataPermission,
  FirewallPermissionSummaryMetadata,
} from "@vm0/connectors/firewall-metadata";
import type {
  FirewallRoutingIndexMetadata,
  FirewallRoutingMetadata,
} from "@vm0/connectors/firewall-metadata/routing";
import {
  createRunnerRuntimeFirewallCatalog,
  projectRunnerRuntimeFirewall,
} from "@vm0/connectors/firewall-metadata/runner-runtime-catalog";
import type { FirewallExecutionMetadata } from "@vm0/connectors/firewall-metadata/server";
import {
  extractFirewallTemplateReferences,
  type FirewallConfig,
  type Firewall,
  type FirewallBaseHostPolicy,
  type FirewallPolicy,
  type FirewallPolicyValue,
} from "@vm0/connectors/firewall-types";
import type { FirewallConnectorType } from "./connector-firewall-manifest";
import {
  generatedConnectorMetadataFileName,
  loadConnectorFirewallSourceSet,
  type ConnectorEnvBindingEntry,
  type ConnectorFirewallSource,
} from "./connector-firewall-sources";
import {
  renderLazyLoaderRecord,
  type LazyLoaderEntry,
} from "./lazy-loader-renderer";

const POLICY_VALUES = ["allow", "deny", "ask"] as const;
const GENERATED_METADATA_FILE_STEM_PATTERN = /^[a-z0-9][a-z0-9-]*$/;
const DEFAULT_FIREWALL_SECRET_PLACEHOLDER =
  "c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe";
const BASE_URL_VARS_PATTERN = /\$\{\{\s*vars\.([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}/;
const BASE_URL_VARS_PATTERN_G = new RegExp(BASE_URL_VARS_PATTERN.source, "g");
const AUTH_SECRET_REFERENCE_PATTERN = /\bsecrets\.([a-zA-Z_][a-zA-Z0-9_]*)\b/g;

interface GeneratedPathReplacement {
  commit: () => void;
  rollback: () => void;
}

function buildDefaultPolicy(
  firewall: FirewallConfig,
  defaultAllowed: readonly string[] | null,
  defaultUnknownPolicy: FirewallPolicyValue,
): FirewallPolicy {
  const allowSet = defaultAllowed ? new Set<string>(defaultAllowed) : null;
  const policies: Record<string, FirewallPolicyValue> = {};
  for (const api of firewall.apis) {
    for (const permission of api.permissions ?? []) {
      policies[permission.name] =
        !allowSet || allowSet.has(permission.name) ? "allow" : "deny";
    }
  }
  return { policies, unknownPolicy: defaultUnknownPolicy };
}

function compareStrings(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function generatedHeader(): string {
  return [
    "// Auto-generated by @vm0/firewalls-generator.",
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
  ].join("\n");
}

function stableJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function writeGeneratedFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  const stat = fs.statSync(filePath);
  if (stat.size === 0) {
    throw new Error(`Generated metadata file is empty: ${filePath}`);
  }
}

function generatedPermissionDetailModuleSpecifier(
  type: FirewallConnectorType,
): string {
  return `./permission-details/${generatedConnectorMetadataFileName(type).replace(/\.ts$/, "")}`;
}

function generatedRoutingDetailModuleSpecifier(
  type: FirewallConnectorType,
): string {
  return `./routing-details/${generatedConnectorMetadataFileName(type).replace(/\.ts$/, "")}`;
}

function generatedRunnerRuntimeDetailModuleSpecifier(name: string): string {
  return `./runner-runtime-details/${generatedRunnerRuntimeDetailFileName(name).replace(/\.ts$/, "")}`;
}

function runnerRuntimeDetailFileStem(name: string): string {
  if (GENERATED_METADATA_FILE_STEM_PATTERN.test(name)) {
    return name;
  }

  const sanitized = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-");
  const base = sanitized.length > 0 ? sanitized : "firewall";
  const hash = createHash("sha256").update(name).digest("hex").slice(0, 12);
  const maxPrefixLength = 96 - hash.length - "-".length;
  const prefix = base.slice(0, maxPrefixLength).replace(/-+$/g, "");
  return `${prefix.length > 0 ? prefix : "firewall"}-${hash}`;
}

function generatedRunnerRuntimeDetailFileName(name: string): string {
  return `${runnerRuntimeDetailFileStem(name)}.generated.ts`;
}

function replaceGeneratedPath(
  targetPath: string,
  nextPath: string,
): GeneratedPathReplacement {
  const previousPath = fs.existsSync(targetPath)
    ? path.join(
        path.dirname(targetPath),
        `.${path.basename(targetPath)}.previous-${process.pid}-${Date.now()}`,
      )
    : null;
  let previousMoved = false;
  let nextMoved = false;

  try {
    if (previousPath) {
      fs.renameSync(targetPath, previousPath);
      previousMoved = true;
    }
    fs.renameSync(nextPath, targetPath);
    nextMoved = true;
  } catch (error) {
    if (previousPath && previousMoved && !fs.existsSync(targetPath)) {
      fs.renameSync(previousPath, targetPath);
    }
    throw error;
  } finally {
    if (!nextMoved) {
      fs.rmSync(nextPath, { recursive: true, force: true });
    }
  }

  return {
    commit: () => {
      if (previousPath) {
        fs.rmSync(previousPath, { recursive: true, force: true });
      }
    },
    rollback: () => {
      fs.rmSync(targetPath, { recursive: true, force: true });
      if (previousPath && fs.existsSync(previousPath)) {
        fs.renameSync(previousPath, targetPath);
      }
    },
  };
}

function rollbackGeneratedReplacements(
  replacements: readonly GeneratedPathReplacement[],
): void {
  for (const replacement of [...replacements].reverse()) {
    replacement.rollback();
  }
}

function collectPermissions(
  firewall: FirewallConfig,
): FirewallPermissionMetadataPermission[] {
  const permissions = new Map<string, FirewallPermissionMetadataPermission>();
  for (const api of firewall.apis) {
    for (const permission of api.permissions ?? []) {
      if (!permissions.has(permission.name)) {
        permissions.set(permission.name, {
          name: permission.name,
          ...(permission.description !== undefined
            ? { description: permission.description }
            : {}),
        });
      }
    }
  }
  return [...permissions.values()].sort((a, b) => {
    return compareStrings(a.name, b.name);
  });
}

function sortedRecord(
  entries: Iterable<readonly [string, string]>,
): Record<string, string> {
  return Object.fromEntries(
    [...entries].sort(([a], [b]) => compareStrings(a, b)),
  );
}

function sortedStrings(values: Iterable<string>): string[] {
  return [...values].sort(compareStrings);
}

function fixedFirewallApiBaseHost(base: string): string | null {
  if (base.includes("${{")) {
    return null;
  }
  try {
    return new URL(base).host;
  } catch {
    return null;
  }
}

function buildFixedHostOwners(
  sources: readonly ConnectorFirewallSource[],
): Record<string, string> {
  const owners = new Map<string, string>();
  for (const source of sources) {
    for (const api of source.firewall.apis) {
      const host = fixedFirewallApiBaseHost(api.base);
      if (!host || owners.has(host)) {
        continue;
      }
      owners.set(host, source.type);
    }
  }
  return sortedRecord(owners.entries());
}

interface RunnerRuntimeDetail {
  readonly name: string;
  readonly fileName: string;
  readonly moduleSpecifier: string;
  readonly firewall: Firewall;
  readonly content: string;
}

function assertUniqueRunnerRuntimeDetails(
  details: readonly RunnerRuntimeDetail[],
): void {
  const names = new Set<string>();
  const fileNames = new Map<string, string>();
  for (const detail of details) {
    if (names.has(detail.name)) {
      throw new Error(`Duplicate runner runtime firewall name: ${detail.name}`);
    }
    names.add(detail.name);

    const previousFileOwner = fileNames.get(detail.fileName);
    if (previousFileOwner) {
      throw new Error(
        `Duplicate runner runtime firewall file name: ${detail.fileName} (${previousFileOwner}, ${detail.name})`,
      );
    }
    fileNames.set(detail.fileName, detail.name);
  }
}

function choosePermissionDefault(policy: FirewallPolicy): FirewallPolicyValue {
  const counts = new Map<FirewallPolicyValue, number>(
    POLICY_VALUES.map((value) => {
      return [value, 0];
    }),
  );
  for (const value of Object.values(policy.policies)) {
    counts.set(value, (counts.get(value) ?? 0) + 1);
  }

  return POLICY_VALUES.reduce<FirewallPolicyValue>((best, candidate) => {
    const bestCount = counts.get(best) ?? 0;
    const candidateCount = counts.get(candidate) ?? 0;
    return candidateCount > bestCount ? candidate : best;
  }, "allow");
}

function compactDefaultPolicy(
  policy: FirewallPolicy,
): FirewallPermissionDefaultPolicyMetadata {
  const permissionDefault = choosePermissionDefault(policy);
  const permissionOverrides: Partial<Record<FirewallPolicyValue, string[]>> =
    {};

  for (const value of POLICY_VALUES) {
    if (value === permissionDefault) {
      continue;
    }
    const permissions = Object.entries(policy.policies)
      .filter(([, policyValue]) => {
        return policyValue === value;
      })
      .map(([permission]) => {
        return permission;
      })
      .sort(compareStrings);
    if (permissions.length > 0) {
      permissionOverrides[value] = permissions;
    }
  }

  return {
    permissionDefault,
    ...(Object.keys(permissionOverrides).length > 0
      ? { permissionOverrides }
      : {}),
    unknownPolicy: policy.unknownPolicy ?? "allow",
  };
}

function hasDefaultPolicyOverrides(
  defaultPolicy: FirewallPermissionDefaultPolicyMetadata,
): boolean {
  return (
    defaultPolicy.permissionDefault !== "allow" ||
    defaultPolicy.unknownPolicy !== "allow" ||
    Object.keys(defaultPolicy.permissionOverrides ?? {}).length > 0
  );
}

function buildDetailMetadata(
  source: ConnectorFirewallSource,
): FirewallPermissionDetailMetadata {
  const permissions = collectPermissions(source.firewall);
  const defaultPolicy = compactDefaultPolicy(
    buildDefaultPolicy(
      source.firewall,
      source.defaultAllowed,
      source.defaultUnknownPolicy,
    ),
  );

  return {
    type: source.type as FirewallConnectorType & ConnectorType,
    label: source.label,
    permissionCount: permissions.length,
    permissions,
    ...(source.categories
      ? {
          categories: {
            categories: sortedRecord(
              Object.entries(source.categories.categories),
            ),
            displayOrder: [...source.categories.displayOrder],
          },
        }
      : {}),
    defaultPolicy,
  };
}

function buildSummaryMetadata(
  detail: FirewallPermissionDetailMetadata,
): FirewallPermissionSummaryMetadata {
  return {
    type: detail.type,
    label: detail.label,
    hasPermissions: detail.permissionCount > 0,
    permissionCount: detail.permissionCount,
    hasCategories: detail.categories !== undefined,
    hasDefaultPolicyOverrides: hasDefaultPolicyOverrides(detail.defaultPolicy),
  };
}

function hasBaseUrlVars(base: string): boolean {
  return BASE_URL_VARS_PATTERN.test(base);
}

function extractBaseUrlVarNames(base: string): string[] {
  const names = new Set<string>();
  for (const match of base.matchAll(BASE_URL_VARS_PATTERN_G)) {
    names.add(match[1]!);
  }
  return [...names];
}

function firewallAuthInjectsCredentials(
  auth: FirewallConfig["apis"][number]["auth"],
): boolean {
  return (
    Object.keys(auth.headers ?? {}).length > 0 ||
    Object.keys(auth.query ?? {}).length > 0 ||
    Object.keys(auth.awsSigv4 ?? {}).length > 0 ||
    (typeof auth.base === "string" && auth.base.length > 0)
  );
}

function extractSecretNamesFromTemplate(template: string): string[] {
  const names = new Set<string>();
  for (const match of template.matchAll(AUTH_SECRET_REFERENCE_PATTERN)) {
    names.add(match[1]!);
  }
  return [...names];
}

function extractSecretNamesFromApis(apis: FirewallConfig["apis"]): string[] {
  const names = new Set<string>();
  for (const entry of apis) {
    for (const value of Object.values(entry.auth.headers ?? {})) {
      for (const name of extractSecretNamesFromTemplate(value)) {
        names.add(name);
      }
    }
    if (entry.auth.base) {
      for (const name of extractSecretNamesFromTemplate(entry.auth.base)) {
        names.add(name);
      }
    }
    for (const value of Object.values(entry.auth.query ?? {})) {
      for (const name of extractSecretNamesFromTemplate(value)) {
        names.add(name);
      }
    }
    for (const value of Object.values(entry.auth.awsSigv4 ?? {})) {
      if (!value) {
        continue;
      }
      for (const name of extractSecretNamesFromTemplate(value)) {
        names.add(name);
      }
    }
  }
  return [...names];
}

function expandFirewallPlaceholders(
  firewall: FirewallConfig,
  envBindingEntries: readonly ConnectorEnvBindingEntry[],
): FirewallConfig {
  if (!firewall.placeholders || envBindingEntries.length === 0) {
    return firewall;
  }

  const expanded: Record<string, string> = { ...firewall.placeholders };

  for (const [key, placeholderValue] of Object.entries(firewall.placeholders)) {
    const valueRefs = envBindingEntries
      .filter(({ envName }) => {
        return envName === key;
      })
      .map(({ valueRef }) => {
        return valueRef;
      });
    for (const valueRef of valueRefs) {
      if (!valueRef.startsWith("$secrets.")) {
        continue;
      }
      const rawName = valueRef.slice("$secrets.".length);
      if (!expanded[rawName]) {
        expanded[rawName] = placeholderValue;
      }
      for (const entry of envBindingEntries) {
        if (entry.valueRef === valueRef && !expanded[entry.envName]) {
          expanded[entry.envName] = placeholderValue;
        }
      }
    }

    const rawRef = `$secrets.${key}`;
    for (const entry of envBindingEntries) {
      if (entry.valueRef === rawRef && !expanded[entry.envName]) {
        expanded[entry.envName] = placeholderValue;
      }
    }
  }

  return { ...firewall, placeholders: expanded };
}

interface ExecutionBaseUrlTemplateAccumulator {
  readonly credentialed: boolean;
  readonly hostPolicy?: FirewallBaseHostPolicy;
}

function hostPolicyKey(hostPolicy: FirewallBaseHostPolicy | undefined): string {
  return stableJson(hostPolicy ?? null);
}

function mergeExecutionBaseUrlTemplate(
  templates: Map<string, ExecutionBaseUrlTemplateAccumulator>,
  api: FirewallConfig["apis"][number],
): void {
  const existing = templates.get(api.base);
  if (!existing) {
    templates.set(api.base, {
      credentialed: firewallAuthInjectsCredentials(api.auth),
      ...(api.hostPolicy !== undefined ? { hostPolicy: api.hostPolicy } : {}),
    });
    return;
  }

  if (hostPolicyKey(existing.hostPolicy) !== hostPolicyKey(api.hostPolicy)) {
    throw new Error(
      `Conflicting host policies for dynamic base URL template: ${api.base}`,
    );
  }
  templates.set(api.base, {
    ...existing,
    credentialed:
      existing.credentialed || firewallAuthInjectsCredentials(api.auth),
  });
}

function buildExecutionBaseUrlTemplates(
  firewall: FirewallConfig,
): FirewallExecutionMetadata["baseUrlTemplates"] {
  const templates = new Map<string, ExecutionBaseUrlTemplateAccumulator>();
  for (const api of firewall.apis) {
    if (!hasBaseUrlVars(api.base)) {
      continue;
    }
    mergeExecutionBaseUrlTemplate(templates, api);
  }
  return [...templates.entries()]
    .sort(([a], [b]) => {
      return compareStrings(a, b);
    })
    .map(([base, template]) => {
      return {
        base,
        credentialed: template.credentialed,
        ...(template.hostPolicy !== undefined
          ? { hostPolicy: template.hostPolicy }
          : {}),
      };
    });
}

function buildExecutionPlaceholderValues(
  firewall: FirewallConfig,
): Record<string, string> {
  const placeholders: Record<string, string> = {};
  const secretNames = extractSecretNamesFromApis(firewall.apis);
  for (const name of secretNames) {
    placeholders[name] =
      firewall.placeholders?.[name] ?? DEFAULT_FIREWALL_SECRET_PLACEHOLDER;
  }
  for (const [name, value] of Object.entries(firewall.placeholders ?? {})) {
    placeholders[name] = value;
  }
  return sortedRecord(Object.entries(placeholders));
}

function buildExecutionMetadata(
  source: ConnectorFirewallSource,
  billableTypes: ReadonlySet<FirewallConnectorType>,
): FirewallExecutionMetadata {
  const firewall = expandFirewallPlaceholders(
    source.firewall,
    source.envBindingEntries,
  );
  const baseUrlTemplates = buildExecutionBaseUrlTemplates(firewall);
  const baseUrlVarNames = sortedStrings(
    new Set(
      baseUrlTemplates.flatMap((template) => {
        return extractBaseUrlVarNames(template.base);
      }),
    ),
  );
  const placeholderValues = buildExecutionPlaceholderValues(firewall);

  return {
    type: source.type,
    billable: billableTypes.has(source.type),
    baseUrlVarNames,
    baseUrlTemplates,
    secretPlaceholderNames: Object.keys(placeholderValues),
    placeholderValues,
  };
}

function buildRoutingMetadata(
  source: ConnectorFirewallSource,
): FirewallRoutingMetadata {
  return {
    type: source.type as FirewallConnectorType & ConnectorType,
    label: source.label,
    apis: source.firewall.apis.map((api) => {
      const references = extractFirewallTemplateReferences([api]);
      return {
        base: api.base,
        environmentNames: sortedStrings([
          ...references.secrets,
          ...references.vars,
        ]),
        routes: (api.permissions ?? []).flatMap((permission) => {
          return permission.rules.map((rule) => {
            return {
              permissionName: permission.name,
              rule,
            };
          });
        }),
      };
    }),
  };
}

function buildRoutingIndexMetadata(
  source: ConnectorFirewallSource,
): FirewallRoutingIndexMetadata {
  return {
    type: source.type as FirewallConnectorType & ConnectorType,
    label: source.label,
    apis: source.firewall.apis.map((api) => {
      return {
        base: api.base,
      };
    }),
  };
}

function renderDetailFile(metadata: FirewallPermissionDetailMetadata): string {
  return `${generatedHeader()}import type { FirewallPermissionDetailMetadata } from "../types";

const firewallPermissionMetadataJson = ${JSON.stringify(stableJson(metadata))};
const firewallPermissionMetadataValue: unknown = JSON.parse(firewallPermissionMetadataJson);

export const firewallPermissionMetadata = firewallPermissionMetadataValue as FirewallPermissionDetailMetadata;
`;
}

function renderRoutingDetailFile(metadata: FirewallRoutingMetadata): string {
  return `${generatedHeader()}import type { FirewallRoutingMetadata } from "../types";

const firewallRoutingMetadataJson = ${JSON.stringify(stableJson(metadata))};
const firewallRoutingMetadataValue: unknown = JSON.parse(firewallRoutingMetadataJson);

export const firewallRoutingMetadata = firewallRoutingMetadataValue as FirewallRoutingMetadata;
`;
}

function renderRunnerRuntimeDetailFile(firewall: Firewall): string {
  return `${generatedHeader()}import type { Firewall } from "../../firewall-types";

const runnerRuntimeFirewallJson = ${JSON.stringify(stableJson(firewall))};
const runnerRuntimeFirewallValue: unknown = JSON.parse(runnerRuntimeFirewallJson);

export const runnerRuntimeFirewall = runnerRuntimeFirewallValue as Firewall;
`;
}

function renderRoutingIndexFile(
  metadata: Record<string, FirewallRoutingIndexMetadata>,
): string {
  const connectorTypes = Object.keys(metadata);
  return `${generatedHeader()}import type { FirewallRoutingIndexMetadata } from "./types";

export const FIREWALL_ROUTING_METADATA_CONNECTOR_TYPES = Object.freeze(${stableJson(connectorTypes)} as const);
export type FirewallRoutingMetadataConnectorType =
  (typeof FIREWALL_ROUTING_METADATA_CONNECTOR_TYPES)[number];

const firewallRoutingMetadataIndexJson = ${JSON.stringify(stableJson(metadata))};
const firewallRoutingMetadataIndexValue: unknown = JSON.parse(firewallRoutingMetadataIndexJson);

export const FIREWALL_ROUTING_METADATA_INDEX =
  firewallRoutingMetadataIndexValue as Readonly<
    Record<FirewallRoutingMetadataConnectorType, FirewallRoutingIndexMetadata>
  >;
`;
}

function renderSummaryFile(
  summaries: Record<string, FirewallPermissionSummaryMetadata>,
): string {
  const connectorTypes = Object.keys(summaries);
  return `${generatedHeader()}import type { FirewallPermissionSummaryMetadata } from "./types";

export const FIREWALL_PERMISSION_METADATA_CONNECTOR_TYPES = Object.freeze(${stableJson(connectorTypes)} as const);
export type FirewallPermissionMetadataConnectorType =
  (typeof FIREWALL_PERMISSION_METADATA_CONNECTOR_TYPES)[number];

const firewallPermissionMetadataSummariesJson = ${JSON.stringify(stableJson(summaries))};
const firewallPermissionMetadataSummariesValue: unknown = JSON.parse(firewallPermissionMetadataSummariesJson);

export const FIREWALL_PERMISSION_METADATA_SUMMARIES =
  firewallPermissionMetadataSummariesValue as Readonly<
    Record<FirewallPermissionMetadataConnectorType, FirewallPermissionSummaryMetadata>
  >;
`;
}

function renderServerExecutionFile(
  metadata: Record<string, FirewallExecutionMetadata>,
): string {
  const connectorTypes = Object.keys(metadata);
  return `${generatedHeader()}import type { FirewallExecutionMetadata } from "./types";

export const FIREWALL_SERVER_EXECUTION_METADATA_CONNECTOR_TYPES = Object.freeze(${stableJson(connectorTypes)} as const);
export type FirewallServerExecutionMetadataConnectorType =
  (typeof FIREWALL_SERVER_EXECUTION_METADATA_CONNECTOR_TYPES)[number];

const firewallServerExecutionMetadataJson = ${JSON.stringify(stableJson(metadata))};
const firewallServerExecutionMetadataValue: unknown = JSON.parse(firewallServerExecutionMetadataJson);

export const FIREWALL_SERVER_EXECUTION_METADATA =
  firewallServerExecutionMetadataValue as Readonly<
    Record<FirewallServerExecutionMetadataConnectorType, FirewallExecutionMetadata>
  >;
`;
}

function renderServerFile(fixedHostOwners: Record<string, string>): string {
  return `${generatedHeader()}import type { FirewallPermissionMetadataConnectorType } from "./permission-summaries.generated";

const builtinFirewallFixedHostOwnersJson = ${JSON.stringify(stableJson(fixedHostOwners))};
const builtinFirewallFixedHostOwnersValue: unknown = JSON.parse(builtinFirewallFixedHostOwnersJson);

export const BUILTIN_FIREWALL_FIXED_HOST_OWNERS =
  builtinFirewallFixedHostOwnersValue as Readonly<
    Record<string, FirewallPermissionMetadataConnectorType>
  >;
`;
}

function renderLoaderFile(types: readonly FirewallConnectorType[]): string {
  const loaderEntries = types.map((type): LazyLoaderEntry => {
    return {
      key: type,
      moduleSpecifier: generatedPermissionDetailModuleSpecifier(type),
      exportName: "firewallPermissionMetadata",
    };
  });

  return `${generatedHeader()}// The platform build serves these dynamic imports from /firewall-metadata/permission-details/v1/.
// Bump that URL version before shipping an incompatible metadata module shape or import contract change.
import type { FirewallPermissionDetailMetadata } from "./types";

${renderLazyLoaderRecord({
  constName: "FIREWALL_PERMISSION_METADATA_LOADERS",
  recordType: "Record<string, () => Promise<FirewallPermissionDetailMetadata>>",
  entries: loaderEntries,
})}

export async function loadGeneratedFirewallPermissionMetadata(
  type: string,
): Promise<FirewallPermissionDetailMetadata | null> {
  const load = FIREWALL_PERMISSION_METADATA_LOADERS[type];
  if (!load) {
    return null;
  }
  return await load();
}
`;
}

function renderRoutingLoaderFile(
  types: readonly FirewallConnectorType[],
): string {
  const loaderEntries = types.map((type): LazyLoaderEntry => {
    return {
      key: type,
      moduleSpecifier: generatedRoutingDetailModuleSpecifier(type),
      exportName: "firewallRoutingMetadata",
    };
  });

  return `${generatedHeader()}import type { FirewallRoutingMetadata } from "./types";

${renderLazyLoaderRecord({
  constName: "FIREWALL_ROUTING_METADATA_LOADERS",
  recordType: "Record<string, () => Promise<FirewallRoutingMetadata>>",
  entries: loaderEntries,
})}

export async function loadGeneratedFirewallRoutingMetadata(
  type: string,
): Promise<FirewallRoutingMetadata | null> {
  const load = FIREWALL_ROUTING_METADATA_LOADERS[type];
  if (!load) {
    return null;
  }
  return await load();
}
`;
}

function renderRunnerRuntimeLoaderFile(args: {
  readonly catalogDigest: string;
  readonly catalogVersion: string;
  readonly entries: readonly {
    readonly name: string;
    readonly moduleSpecifier: string;
  }[];
}): string {
  const loaderEntries = args.entries.map((entry): LazyLoaderEntry => {
    return {
      key: entry.name,
      moduleSpecifier: entry.moduleSpecifier,
      exportName: "runnerRuntimeFirewall",
    };
  });

  return `${generatedHeader()}import type { Firewall } from "../firewall-types";

export const RUNNER_RUNTIME_FIREWALL_CATALOG_DIGEST = ${JSON.stringify(args.catalogDigest)};
export const RUNNER_RUNTIME_FIREWALL_CATALOG_VERSION = ${JSON.stringify(args.catalogVersion)};
export const RUNNER_RUNTIME_FIREWALL_NAMES = Object.freeze(${stableJson(args.entries.map((entry) => entry.name))});

${renderLazyLoaderRecord({
  constName: "RUNNER_RUNTIME_FIREWALL_LOADERS",
  recordType: "Record<string, () => Promise<Firewall>>",
  entries: loaderEntries,
})}

export function hasGeneratedRunnerRuntimeFirewall(
  type: string,
): boolean {
  return Object.prototype.hasOwnProperty.call(
    RUNNER_RUNTIME_FIREWALL_LOADERS,
    type,
  );
}

export async function loadGeneratedRunnerRuntimeFirewall(
  type: string,
): Promise<Firewall | null> {
  const load = RUNNER_RUNTIME_FIREWALL_LOADERS[type];
  if (!load) {
    return null;
  }
  return await load();
}
`;
}

export async function generateFirewallMetadata(): Promise<void> {
  console.error("\n=== firewall metadata ===");

  const connectorsDir = path.resolve(
    import.meta.dirname,
    "../../connectors/src/connectors",
  );
  const outputDir = path.resolve(
    import.meta.dirname,
    "../../connectors/src/firewall-metadata",
  );
  const permissionSummariesFile = path.join(
    outputDir,
    "permission-summaries.generated.ts",
  );
  const permissionDetailLoaderFile = path.join(
    outputDir,
    "permission-detail-loader.generated.ts",
  );
  const routingIndexFile = path.join(outputDir, "routing-index.generated.ts");
  const routingLoaderFile = path.join(outputDir, "routing-loader.generated.ts");
  const obsoleteRoutingFile = path.join(outputDir, "routing.generated.ts");
  const obsoleteSummaryFile = path.join(outputDir, "summary.generated.ts");
  const obsoleteLoaderFile = path.join(outputDir, "loader.generated.ts");
  const obsoleteDetailsDir = path.join(outputDir, "details");
  const serverFile = path.join(outputDir, "server.generated.ts");
  const serverExecutionFile = path.join(
    outputDir,
    "server-execution.generated.ts",
  );
  const runnerRuntimeLoaderFile = path.join(
    outputDir,
    "runner-runtime-loader.generated.ts",
  );
  const permissionDetailsDir = path.join(outputDir, "permission-details");
  const routingDetailsDir = path.join(outputDir, "routing-details");
  const runnerRuntimeDetailsDir = path.join(
    outputDir,
    "runner-runtime-details",
  );

  const { sources, registryOrderedSources, billableTypes } =
    await loadConnectorFirewallSourceSet({
      connectorsDir,
    });
  const summaries: Record<string, FirewallPermissionSummaryMetadata> = {};
  const routingIndexMetadata: Record<string, FirewallRoutingIndexMetadata> = {};
  const executionMetadata: Record<string, FirewallExecutionMetadata> = {};
  const permissionDetails: {
    readonly type: FirewallConnectorType;
    readonly content: string;
  }[] = [];
  const routingDetails: {
    readonly type: FirewallConnectorType;
    readonly content: string;
  }[] = [];
  const runnerRuntimeDetails: RunnerRuntimeDetail[] = [];

  for (const source of sources) {
    const detail = buildDetailMetadata(source);
    const executionDetail = buildExecutionMetadata(source, billableTypes);
    const runnerRuntimeFirewall = projectRunnerRuntimeFirewall(source.firewall);
    summaries[source.type] = buildSummaryMetadata(detail);
    executionMetadata[source.type] = executionDetail;
    permissionDetails.push({
      type: source.type,
      content: renderDetailFile(detail),
    });
    routingIndexMetadata[source.type] = buildRoutingIndexMetadata(source);
    routingDetails.push({
      type: source.type,
      content: renderRoutingDetailFile(buildRoutingMetadata(source)),
    });
    runnerRuntimeDetails.push({
      name: runnerRuntimeFirewall.name,
      fileName: generatedRunnerRuntimeDetailFileName(
        runnerRuntimeFirewall.name,
      ),
      moduleSpecifier: generatedRunnerRuntimeDetailModuleSpecifier(
        runnerRuntimeFirewall.name,
      ),
      firewall: runnerRuntimeFirewall,
      content: renderRunnerRuntimeDetailFile(runnerRuntimeFirewall),
    });
  }
  for (const firewall of Object.values(MODEL_PROVIDER_FIREWALL_CONFIGS)) {
    const runnerRuntimeFirewall = projectRunnerRuntimeFirewall(firewall);
    runnerRuntimeDetails.push({
      name: runnerRuntimeFirewall.name,
      fileName: generatedRunnerRuntimeDetailFileName(
        runnerRuntimeFirewall.name,
      ),
      moduleSpecifier: generatedRunnerRuntimeDetailModuleSpecifier(
        runnerRuntimeFirewall.name,
      ),
      firewall: runnerRuntimeFirewall,
      content: renderRunnerRuntimeDetailFile(runnerRuntimeFirewall),
    });
  }
  assertUniqueRunnerRuntimeDetails(runnerRuntimeDetails);
  const runnerRuntimeCatalog = createRunnerRuntimeFirewallCatalog(
    runnerRuntimeDetails.map((detail) => {
      return detail.firewall;
    }),
  );

  const nextOutputDir = fs.mkdtempSync(path.join(outputDir, ".metadata-"));
  const nextPermissionDetailsDir = path.join(
    nextOutputDir,
    "permission-details",
  );
  const nextRoutingDetailsDir = path.join(nextOutputDir, "routing-details");
  const nextRunnerRuntimeDetailsDir = path.join(
    nextOutputDir,
    "runner-runtime-details",
  );

  for (const detail of permissionDetails) {
    writeGeneratedFile(
      path.join(
        nextPermissionDetailsDir,
        generatedConnectorMetadataFileName(detail.type),
      ),
      detail.content,
    );
  }
  for (const detail of routingDetails) {
    writeGeneratedFile(
      path.join(
        nextRoutingDetailsDir,
        generatedConnectorMetadataFileName(detail.type),
      ),
      detail.content,
    );
  }
  for (const detail of runnerRuntimeDetails) {
    writeGeneratedFile(
      path.join(nextRunnerRuntimeDetailsDir, detail.fileName),
      detail.content,
    );
  }
  writeGeneratedFile(
    path.join(nextOutputDir, "permission-summaries.generated.ts"),
    renderSummaryFile(summaries),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "routing-index.generated.ts"),
    renderRoutingIndexFile(routingIndexMetadata),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "routing-loader.generated.ts"),
    renderRoutingLoaderFile(
      sources.map((source) => {
        return source.type;
      }),
    ),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "server-execution.generated.ts"),
    renderServerExecutionFile(executionMetadata),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "server.generated.ts"),
    renderServerFile(buildFixedHostOwners(registryOrderedSources)),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "permission-detail-loader.generated.ts"),
    renderLoaderFile(
      sources.map((source) => {
        return source.type;
      }),
    ),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "runner-runtime-loader.generated.ts"),
    renderRunnerRuntimeLoaderFile({
      catalogDigest: runnerRuntimeCatalog.catalogDigest,
      catalogVersion: runnerRuntimeCatalog.catalogVersion,
      entries: runnerRuntimeDetails
        .map((detail) => {
          return {
            name: detail.name,
            moduleSpecifier: detail.moduleSpecifier,
          };
        })
        .sort((a, b) => {
          return compareStrings(a.name, b.name);
        }),
    }),
  );
  const replacements: GeneratedPathReplacement[] = [];
  try {
    replacements.push(
      replaceGeneratedPath(permissionDetailsDir, nextPermissionDetailsDir),
    );
    replacements.push(
      replaceGeneratedPath(routingDetailsDir, nextRoutingDetailsDir),
    );
    replacements.push(
      replaceGeneratedPath(
        runnerRuntimeDetailsDir,
        nextRunnerRuntimeDetailsDir,
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        permissionSummariesFile,
        path.join(nextOutputDir, "permission-summaries.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        permissionDetailLoaderFile,
        path.join(nextOutputDir, "permission-detail-loader.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        routingIndexFile,
        path.join(nextOutputDir, "routing-index.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        routingLoaderFile,
        path.join(nextOutputDir, "routing-loader.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        serverFile,
        path.join(nextOutputDir, "server.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        serverExecutionFile,
        path.join(nextOutputDir, "server-execution.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        runnerRuntimeLoaderFile,
        path.join(nextOutputDir, "runner-runtime-loader.generated.ts"),
      ),
    );
  } catch (error) {
    rollbackGeneratedReplacements(replacements);
    throw error;
  } finally {
    fs.rmSync(nextOutputDir, { recursive: true, force: true });
  }

  for (const replacement of replacements) {
    replacement.commit();
  }
  fs.rmSync(obsoleteDetailsDir, { recursive: true, force: true });
  fs.rmSync(obsoleteSummaryFile, { force: true });
  fs.rmSync(obsoleteLoaderFile, { force: true });
  fs.rmSync(obsoleteRoutingFile, { force: true });

  console.error(`  Written ${sources.length} metadata detail files`);
}
