import * as fs from "node:fs";
import * as path from "node:path";

import { CONNECTOR_TYPES } from "../../connectors/src/connectors";
import type { ConnectorType } from "../../connectors/src/connectors";
import type {
  FirewallConfig,
  FirewallPolicy,
  FirewallPolicyValue,
} from "../../connectors/src/firewall-types";
import type {
  FirewallPermissionDefaultPolicyMetadata,
  FirewallPermissionDetailMetadata,
  FirewallPermissionMetadataPermission,
  FirewallPermissionSummaryMetadata,
} from "../../connectors/src/firewall-metadata/types";
import type { FirewallConnectorType } from "../../connectors/src/firewalls";

const POLICY_VALUES = ["allow", "deny", "ask"] as const;

type FirewallRegistry = typeof import("../../connectors/src/firewalls");

type FirewallMetadataRuntime = Pick<
  FirewallRegistry,
  "getDefaultFirewallPolicies" | "getPermissionCategories"
>;

function isConnectorType(type: string): type is ConnectorType {
  return Object.prototype.hasOwnProperty.call(CONNECTOR_TYPES, type);
}

function assertConnectorType(
  type: FirewallConnectorType,
): asserts type is FirewallConnectorType & ConnectorType {
  if (!isConnectorType(type)) {
    throw new Error(
      `Firewall connector is missing connector metadata: ${type}`,
    );
  }
}

function compareStrings(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function generatedHeader(): string {
  return [
    "// Auto-generated by @vm0/firewalls-generator.",
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
  ].join("\n");
}

function stableJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function writeGeneratedFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  const stat = fs.statSync(filePath);
  if (stat.size === 0) {
    throw new Error(`Generated metadata file is empty: ${filePath}`);
  }
}

function collectPermissions(
  firewall: FirewallConfig,
): FirewallPermissionMetadataPermission[] {
  const permissions = new Map<string, FirewallPermissionMetadataPermission>();
  for (const api of firewall.apis) {
    for (const permission of api.permissions ?? []) {
      if (!permissions.has(permission.name)) {
        permissions.set(permission.name, {
          name: permission.name,
          ...(permission.description !== undefined
            ? { description: permission.description }
            : {}),
        });
      }
    }
  }
  return [...permissions.values()].sort((a, b) => {
    return compareStrings(a.name, b.name);
  });
}

function sortedRecord(
  entries: Iterable<readonly [string, string]>,
): Record<string, string> {
  return Object.fromEntries(
    [...entries].sort(([a], [b]) => compareStrings(a, b)),
  );
}

function choosePermissionDefault(policy: FirewallPolicy): FirewallPolicyValue {
  const counts = new Map<FirewallPolicyValue, number>(
    POLICY_VALUES.map((value) => {
      return [value, 0];
    }),
  );
  for (const value of Object.values(policy.policies)) {
    counts.set(value, (counts.get(value) ?? 0) + 1);
  }

  return POLICY_VALUES.reduce<FirewallPolicyValue>((best, candidate) => {
    const bestCount = counts.get(best) ?? 0;
    const candidateCount = counts.get(candidate) ?? 0;
    return candidateCount > bestCount ? candidate : best;
  }, "allow");
}

function compactDefaultPolicy(
  policy: FirewallPolicy,
): FirewallPermissionDefaultPolicyMetadata {
  const permissionDefault = choosePermissionDefault(policy);
  const permissionOverrides: Partial<Record<FirewallPolicyValue, string[]>> =
    {};

  for (const value of POLICY_VALUES) {
    if (value === permissionDefault) {
      continue;
    }
    const permissions = Object.entries(policy.policies)
      .filter(([, policyValue]) => {
        return policyValue === value;
      })
      .map(([permission]) => {
        return permission;
      })
      .sort(compareStrings);
    if (permissions.length > 0) {
      permissionOverrides[value] = permissions;
    }
  }

  return {
    permissionDefault,
    ...(Object.keys(permissionOverrides).length > 0
      ? { permissionOverrides }
      : {}),
    unknownPolicy: policy.unknownPolicy ?? "allow",
  };
}

function hasDefaultPolicyOverrides(
  defaultPolicy: FirewallPermissionDefaultPolicyMetadata,
): boolean {
  return (
    defaultPolicy.permissionDefault !== "allow" ||
    defaultPolicy.unknownPolicy !== "allow" ||
    Object.keys(defaultPolicy.permissionOverrides ?? {}).length > 0
  );
}

function buildDetailMetadata(
  type: FirewallConnectorType,
  firewall: FirewallConfig,
  runtime: FirewallMetadataRuntime,
): FirewallPermissionDetailMetadata {
  assertConnectorType(type);
  const permissions = collectPermissions(firewall);
  const categoryData = runtime.getPermissionCategories(type);
  const defaultPolicy = compactDefaultPolicy(
    runtime.getDefaultFirewallPolicies(type),
  );

  return {
    type,
    label: CONNECTOR_TYPES[type].label,
    permissionCount: permissions.length,
    permissions,
    ...(categoryData
      ? {
          categories: {
            categories: sortedRecord(Object.entries(categoryData.categories)),
            displayOrder: [...categoryData.displayOrder],
          },
        }
      : {}),
    defaultPolicy,
  };
}

function buildSummaryMetadata(
  detail: FirewallPermissionDetailMetadata,
): FirewallPermissionSummaryMetadata {
  return {
    type: detail.type,
    label: detail.label,
    hasPermissions: detail.permissionCount > 0,
    permissionCount: detail.permissionCount,
    hasCategories: detail.categories !== undefined,
    hasDefaultPolicyOverrides: hasDefaultPolicyOverrides(detail.defaultPolicy),
  };
}

function renderDetailFile(metadata: FirewallPermissionDetailMetadata): string {
  return `${generatedHeader()}import type { FirewallPermissionDetailMetadata } from "../types";

export const firewallPermissionMetadata = ${stableJson(metadata)} as const satisfies FirewallPermissionDetailMetadata;
`;
}

function renderSummaryFile(
  summaries: Record<string, FirewallPermissionSummaryMetadata>,
): string {
  return `${generatedHeader()}import type { FirewallPermissionSummaryMetadata } from "./types";

export const FIREWALL_PERMISSION_METADATA_SUMMARIES = ${stableJson(summaries)} as const satisfies Readonly<Record<string, FirewallPermissionSummaryMetadata>>;
`;
}

function renderLoaderFile(types: readonly string[]): string {
  const loaders = types
    .map((type) => {
      return `  "${type}": async () => {
    return (await import("./details/${type}.generated")).firewallPermissionMetadata;
  },`;
    })
    .join("\n");

  return `${generatedHeader()}import type { FirewallPermissionDetailMetadata } from "./types";

const FIREWALL_PERMISSION_METADATA_LOADERS: Readonly<
  Record<string, () => Promise<FirewallPermissionDetailMetadata>>
> = {
${loaders}
};

export async function loadGeneratedFirewallPermissionMetadata(
  type: string,
): Promise<FirewallPermissionDetailMetadata | null> {
  const load = FIREWALL_PERMISSION_METADATA_LOADERS[type];
  if (!load) {
    return null;
  }
  return await load();
}
`;
}

export async function generateFirewallMetadata(): Promise<void> {
  console.error("\n=== firewall metadata ===");
  const runtime = await import("../../connectors/src/firewalls");

  const outputDir = path.resolve(
    import.meta.dirname,
    "../../connectors/src/firewall-metadata",
  );
  const detailsDir = path.join(outputDir, "details");
  fs.rmSync(detailsDir, { recursive: true, force: true });
  fs.mkdirSync(detailsDir, { recursive: true });

  const entries = Object.entries(runtime.getAllConnectorFirewalls()).sort(
    ([a], [b]) => {
      return compareStrings(a, b);
    },
  ) as [FirewallConnectorType, FirewallConfig][];
  const summaries: Record<string, FirewallPermissionSummaryMetadata> = {};

  for (const [type, firewall] of entries) {
    const detail = buildDetailMetadata(type, firewall, runtime);
    summaries[type] = buildSummaryMetadata(detail);
    writeGeneratedFile(
      path.join(detailsDir, `${type}.generated.ts`),
      renderDetailFile(detail),
    );
  }

  writeGeneratedFile(
    path.join(outputDir, "summary.generated.ts"),
    renderSummaryFile(summaries),
  );
  writeGeneratedFile(
    path.join(outputDir, "loader.generated.ts"),
    renderLoaderFile(
      entries.map(([type]) => {
        return type;
      }),
    ),
  );

  console.error(`  Written ${entries.length} metadata detail files`);
}
