import * as fs from "node:fs";
import * as path from "node:path";

import type { ConnectorType } from "@vm0/connectors/connectors";
import type {
  FirewallPermissionDefaultPolicyMetadata,
  FirewallPermissionDetailMetadata,
  FirewallPermissionMetadataPermission,
  FirewallPermissionSummaryMetadata,
} from "@vm0/connectors/firewall-metadata";
import type {
  FirewallRoutingIndexMetadata,
  FirewallRoutingMetadata,
} from "@vm0/connectors/firewall-metadata/routing";
import type { FirewallExecutionMetadata } from "@vm0/connectors/firewall-metadata/server";
import type {
  FirewallConfig,
  FirewallPolicy,
  FirewallPolicyValue,
} from "@vm0/connectors/firewall-types";
import type { FirewallConnectorType } from "./connector-firewall-manifest";
import {
  generatedConnectorMetadataFileName,
  loadConnectorFirewallSourceSet,
  type ConnectorEnvBindingEntry,
  type ConnectorFirewallSource,
} from "./connector-firewall-sources";
import {
  renderLazyLoaderRecord,
  type LazyLoaderEntry,
} from "./lazy-loader-renderer";

const POLICY_VALUES = ["allow", "deny", "ask"] as const;
const DEFAULT_FIREWALL_SECRET_PLACEHOLDER =
  "c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe";
const BASE_URL_VARS_PATTERN = /\$\{\{\s*vars\.([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}/;
const BASE_URL_VARS_PATTERN_G = new RegExp(BASE_URL_VARS_PATTERN.source, "g");
const AUTH_SECRET_REFERENCE_PATTERN = /\bsecrets\.([a-zA-Z_][a-zA-Z0-9_]*)\b/g;

interface GeneratedPathReplacement {
  commit: () => void;
  rollback: () => void;
}

function buildDefaultPolicy(
  firewall: FirewallConfig,
  defaultAllowed: readonly string[] | null,
  defaultUnknownPolicy: FirewallPolicyValue,
): FirewallPolicy {
  const allowSet = defaultAllowed ? new Set<string>(defaultAllowed) : null;
  const policies: Record<string, FirewallPolicyValue> = {};
  for (const api of firewall.apis) {
    for (const permission of api.permissions ?? []) {
      policies[permission.name] =
        !allowSet || allowSet.has(permission.name) ? "allow" : "deny";
    }
  }
  return { policies, unknownPolicy: defaultUnknownPolicy };
}

function compareStrings(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function generatedHeader(): string {
  return [
    "// Auto-generated by @vm0/firewalls-generator.",
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
  ].join("\n");
}

function stableJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function writeGeneratedFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  const stat = fs.statSync(filePath);
  if (stat.size === 0) {
    throw new Error(`Generated metadata file is empty: ${filePath}`);
  }
}

function generatedPermissionDetailModuleSpecifier(
  type: FirewallConnectorType,
): string {
  return `./permission-details/${generatedConnectorMetadataFileName(type).replace(/\.ts$/, "")}`;
}

function generatedRoutingDetailModuleSpecifier(
  type: FirewallConnectorType,
): string {
  return `./routing-details/${generatedConnectorMetadataFileName(type).replace(/\.ts$/, "")}`;
}

function replaceGeneratedPath(
  targetPath: string,
  nextPath: string,
): GeneratedPathReplacement {
  const previousPath = fs.existsSync(targetPath)
    ? path.join(
        path.dirname(targetPath),
        `.${path.basename(targetPath)}.previous-${process.pid}-${Date.now()}`,
      )
    : null;
  let previousMoved = false;
  let nextMoved = false;

  try {
    if (previousPath) {
      fs.renameSync(targetPath, previousPath);
      previousMoved = true;
    }
    fs.renameSync(nextPath, targetPath);
    nextMoved = true;
  } catch (error) {
    if (previousPath && previousMoved && !fs.existsSync(targetPath)) {
      fs.renameSync(previousPath, targetPath);
    }
    throw error;
  } finally {
    if (!nextMoved) {
      fs.rmSync(nextPath, { recursive: true, force: true });
    }
  }

  return {
    commit: () => {
      if (previousPath) {
        fs.rmSync(previousPath, { recursive: true, force: true });
      }
    },
    rollback: () => {
      fs.rmSync(targetPath, { recursive: true, force: true });
      if (previousPath && fs.existsSync(previousPath)) {
        fs.renameSync(previousPath, targetPath);
      }
    },
  };
}

function rollbackGeneratedReplacements(
  replacements: readonly GeneratedPathReplacement[],
): void {
  for (const replacement of [...replacements].reverse()) {
    replacement.rollback();
  }
}

function collectPermissions(
  firewall: FirewallConfig,
): FirewallPermissionMetadataPermission[] {
  const permissions = new Map<string, FirewallPermissionMetadataPermission>();
  for (const api of firewall.apis) {
    for (const permission of api.permissions ?? []) {
      if (!permissions.has(permission.name)) {
        permissions.set(permission.name, {
          name: permission.name,
          ...(permission.description !== undefined
            ? { description: permission.description }
            : {}),
        });
      }
    }
  }
  return [...permissions.values()].sort((a, b) => {
    return compareStrings(a.name, b.name);
  });
}

function sortedRecord(
  entries: Iterable<readonly [string, string]>,
): Record<string, string> {
  return Object.fromEntries(
    [...entries].sort(([a], [b]) => compareStrings(a, b)),
  );
}

function sortedStrings(values: Iterable<string>): string[] {
  return [...values].sort(compareStrings);
}

function fixedFirewallApiBaseHost(base: string): string | null {
  if (base.includes("${{")) {
    return null;
  }
  try {
    return new URL(base).host;
  } catch {
    return null;
  }
}

function buildFixedHostOwners(
  sources: readonly ConnectorFirewallSource[],
): Record<string, string> {
  const owners = new Map<string, string>();
  for (const source of sources) {
    for (const api of source.firewall.apis) {
      const host = fixedFirewallApiBaseHost(api.base);
      if (!host || owners.has(host)) {
        continue;
      }
      owners.set(host, source.type);
    }
  }
  return sortedRecord(owners.entries());
}

function choosePermissionDefault(policy: FirewallPolicy): FirewallPolicyValue {
  const counts = new Map<FirewallPolicyValue, number>(
    POLICY_VALUES.map((value) => {
      return [value, 0];
    }),
  );
  for (const value of Object.values(policy.policies)) {
    counts.set(value, (counts.get(value) ?? 0) + 1);
  }

  return POLICY_VALUES.reduce<FirewallPolicyValue>((best, candidate) => {
    const bestCount = counts.get(best) ?? 0;
    const candidateCount = counts.get(candidate) ?? 0;
    return candidateCount > bestCount ? candidate : best;
  }, "allow");
}

function compactDefaultPolicy(
  policy: FirewallPolicy,
): FirewallPermissionDefaultPolicyMetadata {
  const permissionDefault = choosePermissionDefault(policy);
  const permissionOverrides: Partial<Record<FirewallPolicyValue, string[]>> =
    {};

  for (const value of POLICY_VALUES) {
    if (value === permissionDefault) {
      continue;
    }
    const permissions = Object.entries(policy.policies)
      .filter(([, policyValue]) => {
        return policyValue === value;
      })
      .map(([permission]) => {
        return permission;
      })
      .sort(compareStrings);
    if (permissions.length > 0) {
      permissionOverrides[value] = permissions;
    }
  }

  return {
    permissionDefault,
    ...(Object.keys(permissionOverrides).length > 0
      ? { permissionOverrides }
      : {}),
    unknownPolicy: policy.unknownPolicy ?? "allow",
  };
}

function hasDefaultPolicyOverrides(
  defaultPolicy: FirewallPermissionDefaultPolicyMetadata,
): boolean {
  return (
    defaultPolicy.permissionDefault !== "allow" ||
    defaultPolicy.unknownPolicy !== "allow" ||
    Object.keys(defaultPolicy.permissionOverrides ?? {}).length > 0
  );
}

function buildDetailMetadata(
  source: ConnectorFirewallSource,
): FirewallPermissionDetailMetadata {
  const permissions = collectPermissions(source.firewall);
  const defaultPolicy = compactDefaultPolicy(
    buildDefaultPolicy(
      source.firewall,
      source.defaultAllowed,
      source.defaultUnknownPolicy,
    ),
  );

  return {
    type: source.type as FirewallConnectorType & ConnectorType,
    label: source.label,
    permissionCount: permissions.length,
    permissions,
    ...(source.categories
      ? {
          categories: {
            categories: sortedRecord(
              Object.entries(source.categories.categories),
            ),
            displayOrder: [...source.categories.displayOrder],
          },
        }
      : {}),
    defaultPolicy,
  };
}

function buildSummaryMetadata(
  detail: FirewallPermissionDetailMetadata,
): FirewallPermissionSummaryMetadata {
  return {
    type: detail.type,
    label: detail.label,
    hasPermissions: detail.permissionCount > 0,
    permissionCount: detail.permissionCount,
    hasCategories: detail.categories !== undefined,
    hasDefaultPolicyOverrides: hasDefaultPolicyOverrides(detail.defaultPolicy),
  };
}

function hasBaseUrlVars(base: string): boolean {
  return BASE_URL_VARS_PATTERN.test(base);
}

function extractBaseUrlVarNames(base: string): string[] {
  const names = new Set<string>();
  for (const match of base.matchAll(BASE_URL_VARS_PATTERN_G)) {
    names.add(match[1]!);
  }
  return [...names];
}

function firewallAuthInjectsCredentials(
  auth: FirewallConfig["apis"][number]["auth"],
): boolean {
  return (
    Object.keys(auth.headers ?? {}).length > 0 ||
    Object.keys(auth.query ?? {}).length > 0 ||
    Object.keys(auth.awsSigv4 ?? {}).length > 0 ||
    (typeof auth.base === "string" && auth.base.length > 0)
  );
}

function extractSecretNamesFromTemplate(template: string): string[] {
  const names = new Set<string>();
  for (const match of template.matchAll(AUTH_SECRET_REFERENCE_PATTERN)) {
    names.add(match[1]!);
  }
  return [...names];
}

function extractSecretNamesFromApis(apis: FirewallConfig["apis"]): string[] {
  const names = new Set<string>();
  for (const entry of apis) {
    for (const value of Object.values(entry.auth.headers ?? {})) {
      for (const name of extractSecretNamesFromTemplate(value)) {
        names.add(name);
      }
    }
    if (entry.auth.base) {
      for (const name of extractSecretNamesFromTemplate(entry.auth.base)) {
        names.add(name);
      }
    }
    for (const value of Object.values(entry.auth.query ?? {})) {
      for (const name of extractSecretNamesFromTemplate(value)) {
        names.add(name);
      }
    }
    for (const value of Object.values(entry.auth.awsSigv4 ?? {})) {
      if (!value) {
        continue;
      }
      for (const name of extractSecretNamesFromTemplate(value)) {
        names.add(name);
      }
    }
  }
  return [...names];
}

function expandFirewallPlaceholders(
  firewall: FirewallConfig,
  envBindingEntries: readonly ConnectorEnvBindingEntry[],
): FirewallConfig {
  if (!firewall.placeholders || envBindingEntries.length === 0) {
    return firewall;
  }

  const expanded: Record<string, string> = { ...firewall.placeholders };

  for (const [key, placeholderValue] of Object.entries(firewall.placeholders)) {
    const valueRefs = envBindingEntries
      .filter(({ envName }) => {
        return envName === key;
      })
      .map(({ valueRef }) => {
        return valueRef;
      });
    for (const valueRef of valueRefs) {
      if (!valueRef.startsWith("$secrets.")) {
        continue;
      }
      const rawName = valueRef.slice("$secrets.".length);
      if (!expanded[rawName]) {
        expanded[rawName] = placeholderValue;
      }
      for (const entry of envBindingEntries) {
        if (entry.valueRef === valueRef && !expanded[entry.envName]) {
          expanded[entry.envName] = placeholderValue;
        }
      }
    }

    const rawRef = `$secrets.${key}`;
    for (const entry of envBindingEntries) {
      if (entry.valueRef === rawRef && !expanded[entry.envName]) {
        expanded[entry.envName] = placeholderValue;
      }
    }
  }

  return { ...firewall, placeholders: expanded };
}

function buildExecutionBaseUrlTemplates(
  firewall: FirewallConfig,
): FirewallExecutionMetadata["baseUrlTemplates"] {
  const templates = new Map<string, boolean>();
  for (const api of firewall.apis) {
    if (!hasBaseUrlVars(api.base)) {
      continue;
    }
    templates.set(
      api.base,
      (templates.get(api.base) ?? false) ||
        firewallAuthInjectsCredentials(api.auth),
    );
  }
  return [...templates.entries()]
    .sort(([a], [b]) => {
      return compareStrings(a, b);
    })
    .map(([base, credentialed]) => {
      return { base, credentialed };
    });
}

function buildExecutionPlaceholderValues(
  firewall: FirewallConfig,
): Record<string, string> {
  const placeholders: Record<string, string> = {};
  const secretNames = extractSecretNamesFromApis(firewall.apis);
  for (const name of secretNames) {
    placeholders[name] =
      firewall.placeholders?.[name] ?? DEFAULT_FIREWALL_SECRET_PLACEHOLDER;
  }
  for (const [name, value] of Object.entries(firewall.placeholders ?? {})) {
    placeholders[name] = value;
  }
  return sortedRecord(Object.entries(placeholders));
}

function buildExecutionMetadata(
  source: ConnectorFirewallSource,
  billableTypes: ReadonlySet<FirewallConnectorType>,
): FirewallExecutionMetadata {
  const firewall = expandFirewallPlaceholders(
    source.firewall,
    source.envBindingEntries,
  );
  const baseUrlTemplates = buildExecutionBaseUrlTemplates(firewall);
  const baseUrlVarNames = sortedStrings(
    new Set(
      baseUrlTemplates.flatMap((template) => {
        return extractBaseUrlVarNames(template.base);
      }),
    ),
  );
  const placeholderValues = buildExecutionPlaceholderValues(firewall);

  return {
    type: source.type,
    billable: billableTypes.has(source.type),
    baseUrlVarNames,
    baseUrlTemplates,
    secretPlaceholderNames: Object.keys(placeholderValues),
    placeholderValues,
  };
}

function buildRoutingMetadata(
  source: ConnectorFirewallSource,
): FirewallRoutingMetadata {
  return {
    type: source.type as FirewallConnectorType & ConnectorType,
    label: source.label,
    apis: source.firewall.apis.map((api) => {
      return {
        base: api.base,
        routes: (api.permissions ?? []).flatMap((permission) => {
          return permission.rules.map((rule) => {
            return {
              permissionName: permission.name,
              rule,
            };
          });
        }),
      };
    }),
  };
}

function buildRoutingIndexMetadata(
  source: ConnectorFirewallSource,
): FirewallRoutingIndexMetadata {
  return {
    type: source.type as FirewallConnectorType & ConnectorType,
    label: source.label,
    apis: source.firewall.apis.map((api) => {
      return {
        base: api.base,
      };
    }),
  };
}

function renderDetailFile(metadata: FirewallPermissionDetailMetadata): string {
  return `${generatedHeader()}import type { FirewallPermissionDetailMetadata } from "../types";

export const firewallPermissionMetadata = ${stableJson(metadata)} as const satisfies FirewallPermissionDetailMetadata;
`;
}

function renderRoutingDetailFile(metadata: FirewallRoutingMetadata): string {
  return `${generatedHeader()}import type { FirewallRoutingMetadata } from "../types";

export const firewallRoutingMetadata = ${stableJson(metadata)} as const satisfies FirewallRoutingMetadata;
`;
}

function renderRoutingIndexFile(
  metadata: Record<string, FirewallRoutingIndexMetadata>,
): string {
  return `${generatedHeader()}import type { FirewallRoutingIndexMetadata } from "./types";

export const FIREWALL_ROUTING_METADATA_INDEX = ${stableJson(metadata)} as const satisfies Readonly<Record<string, FirewallRoutingIndexMetadata>>;
`;
}

function renderSummaryFile(
  summaries: Record<string, FirewallPermissionSummaryMetadata>,
): string {
  return `${generatedHeader()}import type { FirewallPermissionSummaryMetadata } from "./types";

export const FIREWALL_PERMISSION_METADATA_SUMMARIES = ${stableJson(summaries)} as const satisfies Readonly<Record<string, FirewallPermissionSummaryMetadata>>;
`;
}

function renderServerExecutionFile(
  metadata: Record<string, FirewallExecutionMetadata>,
): string {
  return `${generatedHeader()}import type { FirewallExecutionMetadata } from "./types";

export const FIREWALL_SERVER_EXECUTION_METADATA = ${stableJson(metadata)} as const satisfies Readonly<Record<string, FirewallExecutionMetadata>>;
`;
}

function renderServerFile(fixedHostOwners: Record<string, string>): string {
  return `${generatedHeader()}import type { FirewallPermissionSummaryMetadata } from "./types";

export const BUILTIN_FIREWALL_FIXED_HOST_OWNERS = ${stableJson(fixedHostOwners)} as const satisfies Readonly<Record<string, FirewallPermissionSummaryMetadata["type"]>>;
`;
}

function renderLoaderFile(types: readonly FirewallConnectorType[]): string {
  const loaderEntries = types.map((type): LazyLoaderEntry => {
    return {
      key: type,
      moduleSpecifier: generatedPermissionDetailModuleSpecifier(type),
      exportName: "firewallPermissionMetadata",
    };
  });

  return `${generatedHeader()}// The platform build serves these dynamic imports from /firewall-metadata/permission-details/v1/.
// Bump that URL version before shipping an incompatible metadata module shape or import contract change.
import type { FirewallPermissionDetailMetadata } from "./types";

${renderLazyLoaderRecord({
  constName: "FIREWALL_PERMISSION_METADATA_LOADERS",
  recordType: "Record<string, () => Promise<FirewallPermissionDetailMetadata>>",
  entries: loaderEntries,
})}

export async function loadGeneratedFirewallPermissionMetadata(
  type: string,
): Promise<FirewallPermissionDetailMetadata | null> {
  const load = FIREWALL_PERMISSION_METADATA_LOADERS[type];
  if (!load) {
    return null;
  }
  return await load();
}
`;
}

function renderRoutingLoaderFile(
  types: readonly FirewallConnectorType[],
): string {
  const loaderEntries = types.map((type): LazyLoaderEntry => {
    return {
      key: type,
      moduleSpecifier: generatedRoutingDetailModuleSpecifier(type),
      exportName: "firewallRoutingMetadata",
    };
  });

  return `${generatedHeader()}import type { FirewallRoutingMetadata } from "./types";

${renderLazyLoaderRecord({
  constName: "FIREWALL_ROUTING_METADATA_LOADERS",
  recordType: "Record<string, () => Promise<FirewallRoutingMetadata>>",
  entries: loaderEntries,
})}

export async function loadGeneratedFirewallRoutingMetadata(
  type: string,
): Promise<FirewallRoutingMetadata | null> {
  const load = FIREWALL_ROUTING_METADATA_LOADERS[type];
  if (!load) {
    return null;
  }
  return await load();
}
`;
}

export async function generateFirewallMetadata(): Promise<void> {
  console.error("\n=== firewall metadata ===");

  const connectorsDir = path.resolve(
    import.meta.dirname,
    "../../connectors/src/connectors",
  );
  const outputDir = path.resolve(
    import.meta.dirname,
    "../../connectors/src/firewall-metadata",
  );
  const permissionSummariesFile = path.join(
    outputDir,
    "permission-summaries.generated.ts",
  );
  const permissionDetailLoaderFile = path.join(
    outputDir,
    "permission-detail-loader.generated.ts",
  );
  const routingIndexFile = path.join(outputDir, "routing-index.generated.ts");
  const routingLoaderFile = path.join(outputDir, "routing-loader.generated.ts");
  const obsoleteRoutingFile = path.join(outputDir, "routing.generated.ts");
  const obsoleteSummaryFile = path.join(outputDir, "summary.generated.ts");
  const obsoleteLoaderFile = path.join(outputDir, "loader.generated.ts");
  const obsoleteDetailsDir = path.join(outputDir, "details");
  const serverFile = path.join(outputDir, "server.generated.ts");
  const serverExecutionFile = path.join(
    outputDir,
    "server-execution.generated.ts",
  );
  const permissionDetailsDir = path.join(outputDir, "permission-details");
  const routingDetailsDir = path.join(outputDir, "routing-details");

  const { sources, registryOrderedSources, billableTypes } =
    await loadConnectorFirewallSourceSet({
      connectorsDir,
    });
  const summaries: Record<string, FirewallPermissionSummaryMetadata> = {};
  const routingIndexMetadata: Record<string, FirewallRoutingIndexMetadata> = {};
  const executionMetadata: Record<string, FirewallExecutionMetadata> = {};
  const permissionDetails: {
    readonly type: FirewallConnectorType;
    readonly content: string;
  }[] = [];
  const routingDetails: {
    readonly type: FirewallConnectorType;
    readonly content: string;
  }[] = [];

  for (const source of sources) {
    const detail = buildDetailMetadata(source);
    const executionDetail = buildExecutionMetadata(source, billableTypes);
    summaries[source.type] = buildSummaryMetadata(detail);
    executionMetadata[source.type] = executionDetail;
    permissionDetails.push({
      type: source.type,
      content: renderDetailFile(detail),
    });
    routingIndexMetadata[source.type] = buildRoutingIndexMetadata(source);
    routingDetails.push({
      type: source.type,
      content: renderRoutingDetailFile(buildRoutingMetadata(source)),
    });
  }

  const nextOutputDir = fs.mkdtempSync(path.join(outputDir, ".metadata-"));
  const nextPermissionDetailsDir = path.join(
    nextOutputDir,
    "permission-details",
  );
  const nextRoutingDetailsDir = path.join(nextOutputDir, "routing-details");

  for (const detail of permissionDetails) {
    writeGeneratedFile(
      path.join(
        nextPermissionDetailsDir,
        generatedConnectorMetadataFileName(detail.type),
      ),
      detail.content,
    );
  }
  for (const detail of routingDetails) {
    writeGeneratedFile(
      path.join(
        nextRoutingDetailsDir,
        generatedConnectorMetadataFileName(detail.type),
      ),
      detail.content,
    );
  }
  writeGeneratedFile(
    path.join(nextOutputDir, "permission-summaries.generated.ts"),
    renderSummaryFile(summaries),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "routing-index.generated.ts"),
    renderRoutingIndexFile(routingIndexMetadata),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "routing-loader.generated.ts"),
    renderRoutingLoaderFile(
      sources.map((source) => {
        return source.type;
      }),
    ),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "server-execution.generated.ts"),
    renderServerExecutionFile(executionMetadata),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "server.generated.ts"),
    renderServerFile(buildFixedHostOwners(registryOrderedSources)),
  );
  writeGeneratedFile(
    path.join(nextOutputDir, "permission-detail-loader.generated.ts"),
    renderLoaderFile(
      sources.map((source) => {
        return source.type;
      }),
    ),
  );
  const replacements: GeneratedPathReplacement[] = [];
  try {
    replacements.push(
      replaceGeneratedPath(permissionDetailsDir, nextPermissionDetailsDir),
    );
    replacements.push(
      replaceGeneratedPath(routingDetailsDir, nextRoutingDetailsDir),
    );
    replacements.push(
      replaceGeneratedPath(
        permissionSummariesFile,
        path.join(nextOutputDir, "permission-summaries.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        permissionDetailLoaderFile,
        path.join(nextOutputDir, "permission-detail-loader.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        routingIndexFile,
        path.join(nextOutputDir, "routing-index.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        routingLoaderFile,
        path.join(nextOutputDir, "routing-loader.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        serverFile,
        path.join(nextOutputDir, "server.generated.ts"),
      ),
    );
    replacements.push(
      replaceGeneratedPath(
        serverExecutionFile,
        path.join(nextOutputDir, "server-execution.generated.ts"),
      ),
    );
  } catch (error) {
    rollbackGeneratedReplacements(replacements);
    throw error;
  } finally {
    fs.rmSync(nextOutputDir, { recursive: true, force: true });
  }

  for (const replacement of replacements) {
    replacement.commit();
  }
  fs.rmSync(obsoleteDetailsDir, { recursive: true, force: true });
  fs.rmSync(obsoleteSummaryFile, { force: true });
  fs.rmSync(obsoleteLoaderFile, { force: true });
  fs.rmSync(obsoleteRoutingFile, { force: true });

  console.error(`  Written ${sources.length} metadata detail files`);
}
