import { renderPermissions, writeOutput } from "./codegen";
import type { PermissionGroup } from "./codegen";

const DOCS_URL = "https://learn.microsoft.com/en-us/graph/overview";
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal";

const PERMISSIONS: PermissionGroup[] = [
  {
    name: "User.Read",
    description: "Read the signed-in Microsoft Graph user profile.",
    rules: ["GET /v1.0/me", "GET /beta/me"],
  },
  {
    name: "Files.ReadWrite.All",
    description: "Read and write OneDrive and document library files.",
    rules: [
      "ANY /v1.0/me/drive/{path*}",
      "ANY /v1.0/drives/{drive-id}/{path*}",
      "ANY /v1.0/users/{user-id}/drive/{path*}",
      "ANY /beta/me/drive/{path*}",
      "ANY /beta/drives/{drive-id}/{path*}",
    ],
  },
  {
    name: "Sites.ReadWrite.All",
    description: "Read and write SharePoint sites, lists, and site drives.",
    rules: [
      "ANY /v1.0/sites/{path*}",
      "ANY /v1.0/groups/{group-id}/sites/{path*}",
      "ANY /beta/sites/{path*}",
      "ANY /beta/groups/{group-id}/sites/{path*}",
    ],
  },
  {
    name: "Team.ReadBasic.All",
    description: "Read basic team information.",
    rules: [
      "GET /v1.0/me/joinedTeams",
      "GET /v1.0/teams",
      "GET /v1.0/teams/{team-id}",
      "GET /beta/me/joinedTeams",
      "GET /beta/teams",
      "GET /beta/teams/{team-id}",
    ],
  },
  {
    name: "Channel.ReadBasic.All",
    description: "Read Microsoft Teams channel metadata.",
    rules: [
      "GET /v1.0/teams/{team-id}/channels",
      "GET /v1.0/teams/{team-id}/channels/{channel-id}",
      "GET /beta/teams/{team-id}/channels",
      "GET /beta/teams/{team-id}/channels/{channel-id}",
    ],
  },
  {
    name: "ChannelMessage.Read.All",
    description: "Read Microsoft Teams channel messages.",
    rules: [
      "GET /v1.0/teams/{team-id}/channels/{channel-id}/messages",
      "GET /v1.0/teams/{team-id}/channels/{channel-id}/messages/{message-id}",
      "GET /v1.0/teams/{team-id}/channels/{channel-id}/messages/{message-id}/replies",
      "GET /beta/teams/{team-id}/channels/{channel-id}/messages",
      "GET /beta/teams/{team-id}/channels/{channel-id}/messages/{message-id}",
      "GET /beta/teams/{team-id}/channels/{channel-id}/messages/{message-id}/replies",
    ],
  },
  {
    name: "ChannelMessage.Send",
    description: "Send Microsoft Teams channel messages and replies.",
    rules: [
      "POST /v1.0/teams/{team-id}/channels/{channel-id}/messages",
      "POST /v1.0/teams/{team-id}/channels/{channel-id}/messages/{message-id}/replies",
      "POST /beta/teams/{team-id}/channels/{channel-id}/messages",
      "POST /beta/teams/{team-id}/channels/{channel-id}/messages/{message-id}/replies",
    ],
  },
  {
    name: "Chat.ReadWrite",
    description: "Read and write Microsoft Teams chats.",
    rules: [
      "ANY /v1.0/chats",
      "ANY /v1.0/chats/{chat-id}",
      "ANY /v1.0/chats/{chat-id}/{path*}",
      "ANY /beta/chats",
      "ANY /beta/chats/{chat-id}",
      "ANY /beta/chats/{chat-id}/{path*}",
    ],
  },
  {
    name: "ChatMessage.Send",
    description: "Send chat messages.",
    rules: [
      "POST /v1.0/chats/{chat-id}/messages",
      "POST /beta/chats/{chat-id}/messages",
    ],
  },
];

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Microsoft Graph API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:microsoft-365",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const microsoft365Firewall = {",
    '  name: "microsoft-365",',
    '  description: "Microsoft Graph API (Microsoft 365)",',
    "  placeholders: {",
    `    MICROSOFT_365_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://graph.microsoft.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.MICROSOFT_365_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
    ...renderPermissions(PERMISSIONS),
    "      ],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Microsoft 365 firewall config...");
  writeOutput("microsoft-365", generateTypeScript(), import.meta.dirname);
}
