import { writeOutput } from "./codegen";

const DOCS_URL = "https://developers.miro.com/reference/overview";
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Miro REST API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:miro",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const miroFirewall = {",
    '  name: "miro",',
    '  description: "Miro",',
    "  placeholders: {",
    `    MIRO_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.miro.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.MIRO_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Miro firewall config...");
  const ts = generateTypeScript();
  writeOutput("miro", ts, import.meta.dirname);
}
