/**
 * Generate Monday.com firewall config.
 *
 * Data source: https://developer.monday.com/api-reference/docs/authentication
 *
 * Monday.com uses token authentication via Authorization header.
 * OAuth access tokens use Bearer prefix in Authorization header.
 * OAuth tokens are JWTs (header.payload.signature).
 */

import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://developer.monday.com/api-reference/docs/authentication";
// Monday OAuth tokens are JWTs: base64url(header).base64url(payload).base64url(signature)
const PLACEHOLDER_VALUE =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkNvZmZlZVNhZmVMb2NhbCIsImlhdCI6MTUxNjIzOTAyMn0.CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLoc";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Monday.com API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:monday",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const mondayFirewall = {",
    '  name: "monday",',
    '  description: "Monday.com API",',
    "  placeholders: {",
    `    MONDAY_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.monday.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.MONDAY_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Monday.com firewall config...");
  const ts = generateTypeScript();
  writeOutput("monday", ts, import.meta.dirname);
}
