/**
 * Neon API firewall config generator.
 *
 * Data source: https://api-docs.neon.tech/reference/authentication
 *
 * Neon uses Bearer token authentication via OAuth.
 * OAuth token format is not publicly documented; using generic placeholder.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://api-docs.neon.tech/reference/authentication";
// OAuth access token; format not documented
const PLACEHOLDER_VALUE = "CoffeeSafeLocalCoffeeSafeLocalCo";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Neon API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:neon",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const neonFirewall = {",
    '  name: "neon",',
    '  description: "Neon API",',
    "  placeholders: {",
    `    NEON_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://console.neon.tech/api",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.NEON_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Neon firewall config...");
  const ts = generateTypeScript();
  writeOutput("neon", ts, import.meta.dirname);
}
