import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1546938065.html";

export async function generate(): Promise<void> {
  writeOutput(
    "netsuite",
    [
      "// Auto-generated from Oracle NetSuite REST API docs.",
      `// Source: ${DOCS_URL}`,
      "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:netsuite",
      "//",
      "// DO NOT EDIT THIS FILE MANUALLY.",
      "",
      'import type { FirewallConfig } from "../firewall-types";',
      "",
      "export const netsuiteFirewall = {",
      '  name: "netsuite",',
      '  description: "Oracle NetSuite REST APIs",',
      "  placeholders: {",
      '    NETSUITE_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal",',
      "  },",
      "  apis: [",
      "    {",
      '      base: "https://${{ vars.NETSUITE_ACCOUNT_SUBDOMAIN }}.suitetalk.api.netsuite.com",',
      '      hostPolicy: { kind: "providerOwned", suffixes: [".suitetalk.api.netsuite.com"] },',
      '      auth: { headers: { Authorization: "Bearer ${{ secrets.NETSUITE_TOKEN }}" } },',
      "      permissions: [],",
      "    },",
      "    {",
      '      base: "https://${{ vars.NETSUITE_ACCOUNT_SUBDOMAIN }}.restlets.api.netsuite.com",',
      '      hostPolicy: { kind: "providerOwned", suffixes: [".restlets.api.netsuite.com"] },',
      '      auth: { headers: { Authorization: "Bearer ${{ secrets.NETSUITE_TOKEN }}" } },',
      "      permissions: [],",
      "    },",
      "  ],",
      "} as const satisfies FirewallConfig;",
      "",
    ].join("\n"),
  );
}
