/**
 * Generate Nintendo Store firewall config.
 *
 * Data source: verified Nintendo Account / Nintendo Store app APIs.
 */

import {
  logStats,
  renderDefaultUnknownPolicy,
  renderPermissions,
  writeOutput,
  type PermissionGroup,
} from "./codegen";

const PLACEHOLDER_VALUE = "nintendo_store_access_token_placeholder";
const RUNTIME_TOKEN_SECRET = "NINTENDO_STORE_TOKEN";
const RUNTIME_LOCALE_VAR = "NINTENDO_STORE_LOCALE";
const USER_AGENT = "com.nintendo.znej/1.13.0 (Android/7.1.2)";

interface NintendoStoreApi {
  readonly base: string;
  readonly localeHeader?: boolean;
  readonly permissions: readonly PermissionGroup[];
}

const NINTENDO_STORE_APIS: readonly NintendoStoreApi[] = [
  {
    base: "https://api.accounts.nintendo.com",
    permissions: [
      {
        name: "nintendo-account-profile-read",
        description: "Read Nintendo Account profile for the connected account",
        rules: ["GET /2.0.0/users/me"],
      },
    ],
  },
  {
    base: "https://app-api.znej.nintendo.com",
    localeHeader: true,
    permissions: [
      {
        name: "nintendo-store-catalog-read",
        description:
          "Read Nintendo Store app public catalog, search, shelves, news, and product metadata",
        rules: [
          "GET /api/v2.0/check_in_events",
          "GET /api/v2.0/check_in_events/{eventId}/check_in_points",
          "GET /api/v2.0/check_in_events/{eventId}/check_in_points/{checkInPointId}",
          "GET /api/v2.0/maintenance_check",
          "GET /api/v2.0/news",
          "GET /api/v2.0/news/app_news/{appNewsId}",
          "GET /api/v2.0/news_tab_config",
          "GET /api/v2.0/notifications",
          "GET /api/v2.0/now",
          "GET /api/v2.0/point_goods_shelves",
          "GET /api/v2.0/search_shelves",
          "GET /api/v2.0/search_shelves/{shelfId}",
          "GET /api/v2.0/shelves/summary",
          "POST /api/v2.0/product_details",
          "POST /api/v2.0/products/-/images:batch_get",
          "POST /api/v2.0/products/-/meta:batch_get",
          "POST /api/v2.0/products:search",
        ],
      },
      {
        name: "nintendo-store-account-read",
        description:
          "Read Nintendo Store app account age, family, points, rights, and notification settings",
        rules: [
          "GET /api/v2.0/users/me/age",
          "GET /api/v2.0/users/me/family/children",
          "GET /api/v2.0/users/me/points",
          "GET /api/v2.0/users/me/push_notification_config",
          "GET /api/v2.0/users/me/rights",
          "GET /api/v2.0/users/{naid}/qrcode_param",
        ],
      },
      {
        name: "nintendo-store-play-activity-read",
        description: "Read Nintendo Store app play activity history",
        rules: [
          "GET /api/v2.0/users/me/play_histories",
          "GET /api/v2.0/users/me/play_histories/game_titles/{titleId}",
          "GET /api/v2.0/users/me/play_histories/hidden_list",
        ],
      },
      {
        name: "nintendo-store-wishlist-read",
        description: "Read Nintendo Store app wishlist",
        rules: [
          "GET /api/v2.0/users/me/wishlist",
          "GET /api/v2.0/users/me/wishlist/{productId}",
        ],
      },
      {
        name: "nintendo-store-check-in-history-read",
        description:
          "Read Nintendo Store app check-in and prize receipt history",
        rules: [
          "GET /api/v2.0/users/me/check_in_histories",
          "GET /api/v2.0/users/me/received_prize_histories",
        ],
      },
    ],
  },
];

function renderApi(api: NintendoStoreApi): string[] {
  return [
    "    {",
    `      base: "${api.base}",`,
    "      auth: {",
    "        headers: {",
    `          Authorization: "Bearer \${{ secrets.${RUNTIME_TOKEN_SECRET} }}",`,
    `          "User-Agent": "${USER_AGENT}",`,
    ...(api.localeHeader === true
      ? [`          "gentry-locale": "\${{ vars.${RUNTIME_LOCALE_VAR} }}",`]
      : []),
    "        },",
    "      },",
    "      permissions: [",
    ...renderPermissions([...api.permissions]),
    "      ],",
    "    },",
  ];
}

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from verified Nintendo Account / Nintendo Store app APIs.",
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:nintendo-store",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig, FirewallPolicyValue } from "../firewall-types";',
    "",
    "export const nintendoStoreFirewall = {",
    '  name: "nintendo-store",',
    '  description: "Nintendo Store API",',
    "  placeholders: {",
    `    ${RUNTIME_TOKEN_SECRET}: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    ...NINTENDO_STORE_APIS.flatMap(renderApi),
    "  ],",
    "} as const satisfies FirewallConfig;",
    ...renderDefaultUnknownPolicy("nintendoStoreDefaultUnknownPolicy", "deny"),
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Nintendo Store firewall config...");
  const ts = generateTypeScript();
  writeOutput("nintendo-store", ts);
  logStats(NINTENDO_STORE_APIS.flatMap((api) => [...api.permissions]));
}
