/**
 * Generate Nintendo Play Activity firewall config.
 *
 * Data source: verified Nintendo Account / Nintendo Store app APIs.
 */

import {
  logStats,
  renderDefaultUnknownPolicy,
  renderPermissions,
  writeOutput,
  type PermissionGroup,
} from "./codegen";

const PLACEHOLDER_VALUE = "nintendo_play_activity_access_token_placeholder";
const RUNTIME_TOKEN_SECRET = "NINTENDO_PLAY_ACTIVITY_TOKEN";
const RUNTIME_LOCALE_VAR = "NINTENDO_PLAY_ACTIVITY_LOCALE";
const USER_AGENT = "com.nintendo.znej/1.13.0 (Android/7.1.2)";

interface NintendoPlayActivityApi {
  readonly base: string;
  readonly localeHeader?: boolean;
  readonly permissions: readonly PermissionGroup[];
}

const NINTENDO_PLAY_ACTIVITY_APIS: readonly NintendoPlayActivityApi[] = [
  {
    base: "https://api.accounts.nintendo.com",
    permissions: [
      {
        name: "nintendo-account-profile-read",
        description: "Read Nintendo Account profile for the connected account",
        rules: ["GET /2.0.0/users/me"],
      },
    ],
  },
  {
    base: "https://app-api.znej.nintendo.com",
    localeHeader: true,
    permissions: [
      {
        name: "nintendo-store-play-activity-read",
        description: "Read Nintendo Store app play activity history",
        rules: ["GET /api/v2.0/users/me/play_histories"],
      },
    ],
  },
];

function renderApi(api: NintendoPlayActivityApi): string[] {
  return [
    "    {",
    `      base: "${api.base}",`,
    "      auth: {",
    "        headers: {",
    `          Authorization: "Bearer \${{ secrets.${RUNTIME_TOKEN_SECRET} }}",`,
    `          "User-Agent": "${USER_AGENT}",`,
    ...(api.localeHeader === true
      ? [`          "gentry-locale": "\${{ vars.${RUNTIME_LOCALE_VAR} }}",`]
      : []),
    "        },",
    "      },",
    "      permissions: [",
    ...renderPermissions([...api.permissions]),
    "      ],",
    "    },",
  ];
}

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from verified Nintendo Account / Nintendo Store app APIs.",
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:nintendo-play-activity",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig, FirewallPolicyValue } from "../firewall-types";',
    "",
    "export const nintendoPlayActivityFirewall = {",
    '  name: "nintendo-play-activity",',
    '  description: "Nintendo Play Activity API",',
    "  placeholders: {",
    `    ${RUNTIME_TOKEN_SECRET}: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    ...NINTENDO_PLAY_ACTIVITY_APIS.flatMap(renderApi),
    "  ],",
    "} as const satisfies FirewallConfig;",
    ...renderDefaultUnknownPolicy(
      "nintendoPlayActivityDefaultUnknownPolicy",
      "deny",
    ),
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Nintendo Play Activity firewall config...");
  const ts = generateTypeScript();
  writeOutput("nintendo-play-activity", ts);
  logStats(NINTENDO_PLAY_ACTIVITY_APIS.flatMap((api) => [...api.permissions]));
}
