import { writeOutput } from "./codegen";

const DOCS_URL = "https://dev.pdf4me.com/apiv2/documentation/";
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSa";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from PDF4me API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:pdf4me",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const pdf4meFirewall = {",
    '  name: "pdf4me",',
    '  description: "PDF4me Document API",',
    "  placeholders: {",
    `    PDF4ME_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.pdf4me.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "${{ secrets.PDF4ME_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating PDF4me firewall config...");
  const ts = generateTypeScript();
  writeOutput("pdf4me", ts, import.meta.dirname);
}
