import { writeOutput } from "./codegen";

const DOCS_URL = "https://docs.pinecone.io/reference/api/";
const PLACEHOLDER_VALUE =
  "pcsk_CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSa";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Pinecone API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:pinecone",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const pineconeFirewall = {",
    '  name: "pinecone",',
    '  description: "Pinecone",',
    "  placeholders: {",
    `    PINECONE_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.pinecone.io",',
    "      auth: {",
    "        headers: {",
    '          "Api-Key": "${{ secrets.PINECONE_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Pinecone firewall config...");
  const ts = generateTypeScript();
  writeOutput("pinecone", ts, import.meta.dirname);
}
