/**
 * Generate PlayStation Network firewall config.
 *
 * Data source: psn-api 2.18.0 source, https://github.com/achievements-app/psn-api
 *
 * PlayStation Network's consumer APIs are not documented as a stable public API.
 * This curated read-only firewall follows the endpoints currently exposed by
 * psn-api and denies unknown paths by default.
 */

import {
  renderDefaultUnknownPolicy,
  renderPermissions,
  sanitizeAndSortRules,
  writeOutput,
  type PermissionGroup,
} from "./codegen";

const SOURCE_URL = "https://github.com/achievements-app/psn-api";
const PLACEHOLDER_VALUE = "psn_access_token_placeholder";

const MOBILE_PERMISSIONS: PermissionGroup[] = [
  {
    name: "playstation-profile-read",
    description: "Read PlayStation Network profile and presence data",
    rules: sanitizeAndSortRules([
      "GET /api/userProfile/v1/internal/users/{accountId}/basicPresences",
      "GET /api/userProfile/v1/internal/users/{accountId}/profiles",
      "GET /api/cpss/v1/share/profile/{accountId}",
    ]),
  },
  {
    name: "playstation-social-read",
    description:
      "Read PlayStation Network friend, friend request, and block lists",
    rules: sanitizeAndSortRules([
      "GET /api/userProfile/v1/internal/users/{accountId}/blocks",
      "GET /api/userProfile/v1/internal/users/{accountId}/friends",
      "GET /api/userProfile/v1/internal/users/{accountId}/friends/receivedRequests",
    ]),
  },
  {
    name: "playstation-games-read",
    description: "Read PlayStation played games and playtime data",
    rules: sanitizeAndSortRules([
      "GET /api/gamelist/v2/users/{accountId}/titles",
    ]),
  },
  {
    name: "playstation-trophies-read",
    description: "Read PlayStation trophy summaries, titles, groups, and lists",
    rules: sanitizeAndSortRules([
      "GET /api/trophy/v1/npCommunicationIds/{npCommunicationId}/trophyGroups",
      "GET /api/trophy/v1/npCommunicationIds/{npCommunicationId}/trophyGroups/{trophyGroupId}/trophies",
      "GET /api/trophy/v1/users/{accountId}/npCommunicationIds/{npCommunicationId}/trophyGroups",
      "GET /api/trophy/v1/users/{accountId}/npCommunicationIds/{npCommunicationId}/trophyGroups/{trophyGroupId}/trophies",
      "GET /api/trophy/v1/users/{accountId}/titles/trophyTitles",
      "GET /api/trophy/v1/users/{accountId}/trophySummary",
      "GET /api/trophy/v1/users/{accountId}/trophyTitles",
    ]),
  },
  {
    name: "playstation-search-read",
    description: "Search PlayStation Network users and content",
    rules: sanitizeAndSortRules(["POST /api/search/v1/universalSearch"]),
  },
];

const LEGACY_PROFILE_PERMISSIONS: PermissionGroup[] = [
  {
    name: "playstation-legacy-profile-read",
    description: "Read legacy PlayStation Network profile data by online ID",
    rules: sanitizeAndSortRules([
      "GET /userProfile/v1/users/{userName}/profile2",
    ]),
  },
];

const GRAPHQL_PERMISSIONS: PermissionGroup[] = [
  {
    name: "playstation-graphql-games-read",
    description:
      "Read PlayStation purchased and recently played game lists through psn-api GraphQL operations",
    rules: sanitizeAndSortRules(["GET /api/graphql/v1/op"]),
  },
];

const DMS_PERMISSIONS: PermissionGroup[] = [
  {
    name: "playstation-devices-read",
    description: "Read devices associated with a PlayStation Network account",
    rules: sanitizeAndSortRules(["GET /api/v1/devices/accounts/{accountId}"]),
  },
];

function renderApi(args: {
  readonly base: string;
  readonly permissions: readonly PermissionGroup[];
}): string[] {
  return [
    "    {",
    `      base: "${args.base}",`,
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.PLAYSTATION_ACCESS_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
    ...renderPermissions([...args.permissions]),
    "      ],",
    "    },",
  ];
}

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from psn-api endpoint definitions.",
    `// Source: ${SOURCE_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:playstation",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig, FirewallPolicyValue } from "../firewall-types";',
    "",
    "export const playstationFirewall = {",
    '  name: "playstation",',
    '  description: "PlayStation Network API",',
    "  placeholders: {",
    `    PLAYSTATION_ACCESS_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    ...renderApi({
      base: "https://m.np.playstation.com",
      permissions: MOBILE_PERMISSIONS,
    }),
    ...renderApi({
      base: "https://us-prof.np.community.playstation.net",
      permissions: LEGACY_PROFILE_PERMISSIONS,
    }),
    ...renderApi({
      base: "https://web.np.playstation.com",
      permissions: GRAPHQL_PERMISSIONS,
    }),
    ...renderApi({
      base: "https://dms.api.playstation.com",
      permissions: DMS_PERMISSIONS,
    }),
    "  ],",
    "} as const satisfies FirewallConfig;",
    ...renderDefaultUnknownPolicy("playstationDefaultUnknownPolicy", "deny"),
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating PlayStation firewall config...");
  writeOutput("playstation", generateTypeScript());
}
