import { writeOutput } from "./codegen";

const DOCS_URL = "https://productlane.com/docs/api-reference/authentication";
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSa";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Productlane API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:productlane",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const productlaneFirewall = {",
    '  name: "productlane",',
    '  description: "Productlane API",',
    "  placeholders: {",
    `    PRODUCTLANE_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://productlane.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.PRODUCTLANE_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Productlane firewall config...");
  const ts = generateTypeScript();
  writeOutput("productlane", ts, import.meta.dirname);
}
