import { writeOutput } from "./codegen";

const DOCS_URL = "https://qiita.com/api/v2/docs";
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSa";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Qiita API v2 docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:qiita",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const qiitaFirewall = {",
    '  name: "qiita",',
    '  description: "Qiita API",',
    "  placeholders: {",
    `    QIITA_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://qiita.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.QIITA_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Qiita firewall config...");
  const ts = generateTypeScript();
  writeOutput("qiita", ts, import.meta.dirname);
}
