import { renderPermissions, writeOutput } from "./codegen";
import type { PermissionGroup } from "./codegen";

const DOCS_URL =
  "https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account";
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal";

const PERMISSIONS: PermissionGroup[] = [
  {
    name: "company-info",
    description: "Read QuickBooks company information.",
    rules: [
      "GET /companyinfo/{company-id}",
      "GET /preferences/{preference-id}",
    ],
  },
  {
    name: "query",
    description: "Run QuickBooks Online SQL-like entity queries.",
    rules: ["GET /query", "POST /query"],
  },
  {
    name: "customers",
    description: "Read and manage customers.",
    rules: [
      "GET /customer/{customer-id}",
      "POST /customer",
      "POST /customer/{customer-id}",
    ],
  },
  {
    name: "vendors",
    description: "Read and manage vendors.",
    rules: [
      "GET /vendor/{vendor-id}",
      "POST /vendor",
      "POST /vendor/{vendor-id}",
    ],
  },
  {
    name: "items",
    description: "Read and manage products and services.",
    rules: ["GET /item/{item-id}", "POST /item", "POST /item/{item-id}"],
  },
  {
    name: "invoices",
    description: "Read and manage invoices and invoice payments.",
    rules: [
      "GET /invoice/{invoice-id}",
      "POST /invoice",
      "POST /invoice/{invoice-id}",
      "GET /payment/{payment-id}",
      "POST /payment",
      "POST /payment/{payment-id}",
    ],
  },
  {
    name: "bills",
    description: "Read and manage bills and bill payments.",
    rules: [
      "GET /bill/{bill-id}",
      "POST /bill",
      "POST /bill/{bill-id}",
      "GET /billpayment/{bill-payment-id}",
      "POST /billpayment",
      "POST /billpayment/{bill-payment-id}",
    ],
  },
  {
    name: "accounts",
    description: "Read and manage chart-of-accounts entities.",
    rules: [
      "GET /account/{account-id}",
      "POST /account",
      "POST /account/{account-id}",
    ],
  },
  {
    name: "reports",
    description: "Read QuickBooks reports.",
    rules: ["GET /reports/{report-name}"],
  },
  {
    name: "batch-cdc",
    description: "Use batch and change-data-capture endpoints.",
    rules: ["POST /batch", "POST /cdc"],
  },
  {
    name: "attachments",
    description: "Read and upload attachable metadata and files.",
    rules: [
      "GET /attachable/{attachable-id}",
      "POST /attachable",
      "POST /upload",
    ],
  },
];

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from QuickBooks Online Accounting API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:quickbooks",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const quickbooksFirewall = {",
    '  name: "quickbooks",',
    '  description: "QuickBooks Online Accounting API",',
    "  placeholders: {",
    `    QUICKBOOKS_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://quickbooks.api.intuit.com/v3/company/${{ vars.QUICKBOOKS_REALM_ID }}",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.QUICKBOOKS_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
    ...renderPermissions(PERMISSIONS),
    "      ],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating QuickBooks firewall config...");
  writeOutput("quickbooks", generateTypeScript(), import.meta.dirname);
}
