import { writeOutput } from "./codegen";

const DOCS_URL = "https://docs.ramp.com/developer-api/v1/getting-started";

export async function generate(): Promise<void> {
  writeOutput(
    "ramp",
    [
      "// Auto-generated from Ramp Developer API docs.",
      `// Source: ${DOCS_URL}`,
      "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:ramp",
      "//",
      "// DO NOT EDIT THIS FILE MANUALLY.",
      "",
      'import type { FirewallConfig } from "../firewall-types";',
      "",
      "export const rampFirewall = {",
      '  name: "ramp",',
      '  description: "Ramp Developer API",',
      "  placeholders: {",
      '    RAMP_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal",',
      "  },",
      "  apis: [",
      "    {",
      '      base: "https://api.ramp.com/developer/v1",',
      '      auth: { headers: { Authorization: "Bearer ${{ secrets.RAMP_TOKEN }}" } },',
      "      permissions: [],",
      "    },",
      "  ],",
      "} as const satisfies FirewallConfig;",
      "",
    ].join("\n"),
  );
}
