/**
 * Generate Salesforce firewall config.
 *
 * Data source: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/
 *
 * Salesforce uses Bearer token authentication via Authorization header.
 * The base URL is instance-specific: https://{instance}.my.salesforce.com
 * Users must provide a SALESFORCE_INSTANCE variable (e.g. "mycompany").
 *
 * Access token format: session ID string, typically 80-100+ chars,
 * alphanumeric with dots and exclamation marks.
 */

import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/";
// Format: session ID (~100 chars). Use a realistic-length placeholder.
const PLACEHOLDER_VALUE =
  "00D0x000000Vm0P!AQEAQFVm0PlaceHolder0000000000000000000000000000000000000000000000000000000000000000000";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Salesforce REST API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:salesforce",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const salesforceFirewall: FirewallConfig = {",
    '  name: "salesforce",',
    '  description: "Salesforce REST API",',
    "  placeholders: {",
    `    SALESFORCE_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://${{ vars.SALESFORCE_INSTANCE }}.my.salesforce.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.SALESFORCE_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "};",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Salesforce firewall config...");
  const ts = generateTypeScript();
  writeOutput("salesforce", ts, import.meta.dirname);
}
