/**
 * SerpApi firewall config generator.
 *
 * Data source: https://serpapi.com/search-api
 *
 * SerpApi supports Bearer token authentication via Authorization header.
 * API key format is not publicly documented; using generic placeholder.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://serpapi.com/search-api";
// No documented key format; generic alphanumeric
const PLACEHOLDER_VALUE = "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCof";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from SerpApi docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:serpapi",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const serpapiFirewall = {",
    '  name: "serpapi",',
    '  description: "SerpApi",',
    "  placeholders: {",
    `    SERPAPI_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://serpapi.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.SERPAPI_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating SerpApi firewall config...");
  const ts = generateTypeScript();
  writeOutput("serpapi", ts, import.meta.dirname);
}
