import { writeOutput } from "./codegen";

const DOCS_URL = "https://docs.sociavault.com/quickstart";
const PLACEHOLDER_VALUE = "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCof";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from SociaVault API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:sociavault",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const sociavaultFirewall = {",
    '  name: "sociavault",',
    '  description: "SociaVault",',
    "  placeholders: {",
    `    SOCIAVAULT_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.sociavault.com",',
    "      auth: {",
    "        headers: {",
    '          "X-API-Key": "${{ secrets.SOCIAVAULT_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating SociaVault firewall config...");
  const ts = generateTypeScript();
  writeOutput("sociavault", ts, import.meta.dirname);
}
