/**
 * Generate SproutGigs firewall config.
 *
 * Data source: https://sproutgigs.com/api/documentation.php
 *
 * SproutGigs authenticates every request with HTTP Basic auth using
 * USER_ID as the username and API_SECRET as the password.
 */

import {
  renderPermissions,
  sanitizeAndSortRules,
  writeOutput,
  type PermissionGroup,
} from "./codegen";

const DOCS_URL = "https://sproutgigs.com/api/documentation.php";
const API_SECRET_PLACEHOLDER = "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal";

const PERMISSIONS: PermissionGroup[] = [
  {
    name: "gigs:read",
    description:
      "Read gig categories, listings, details, questions, and reviews",
    rules: sanitizeAndSortRules([
      "GET /gigs/get-categories.php",
      "GET /gigs/get-gig.php",
      "GET /gigs/get-gigs.php",
      "GET /gigs/get-gig-public-questions.php",
      "GET /gigs/get-gig-reviews.php",
    ]),
  },
  {
    name: "jobs:read",
    description:
      "Read job categories, jobs, zones, rated and unrated tasks, and predicted position",
    rules: sanitizeAndSortRules([
      "GET /jobs/get-categories.php",
      "GET /jobs/get-job.php",
      "GET /jobs/get-jobs.php",
      "POST /jobs/get-predicted-position.php",
      "GET /jobs/get-rated-tasks.php",
      "GET /jobs/get-unrated-tasks.php",
      "GET /jobs/get-zones.php",
    ]),
  },
  {
    name: "jobs:write",
    description:
      "Create, update, feature, pause, resume, restart, stop, and configure jobs",
    rules: sanitizeAndSortRules([
      "POST /jobs/add-positions.php",
      "POST /jobs/edit-targeting.php",
      "POST /jobs/feature-job.php",
      "POST /jobs/job-pause.php",
      "POST /jobs/job-restart.php",
      "POST /jobs/job-resume.php",
      "POST /jobs/job-stop.php",
      "POST /jobs/post-job.php",
      "POST /jobs/set-daily-tasks-limit.php",
      "POST /jobs/set-distribution.php",
      "POST /jobs/set-speed.php",
      "POST /jobs/set-ttr.php",
    ]),
  },
  {
    name: "tasks:rate",
    description: "Approve or reject single and multiple submitted tasks",
    rules: sanitizeAndSortRules([
      "POST /jobs/rate-multiple-tasks.php",
      "POST /jobs/rate-single-task.php",
    ]),
  },
  {
    name: "lists:read",
    description: "Read public and account freelancer lists",
    rules: sanitizeAndSortRules([
      "GET /jobs/get-lists.php",
      "GET /lists/get-public-lists.php",
    ]),
  },
  {
    name: "lists:write",
    description: "Add, block, and unblock freelancers in lists",
    rules: sanitizeAndSortRules([
      "POST /lists/add-workers.php",
      "POST /lists/block-workers.php",
      "POST /lists/unblock-workers.php",
    ]),
  },
  {
    name: "profiles:read",
    description: "Read freelancer profile details",
    rules: sanitizeAndSortRules(["GET /profiles/get-profile.php"]),
  },
  {
    name: "users:read",
    description: "Read account balances",
    rules: sanitizeAndSortRules(["GET /users/get-balances.php"]),
  },
];

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from SproutGigs API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:sproutgigs",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const sproutgigsFirewall = {",
    '  name: "sproutgigs",',
    '  description: "SproutGigs buyer jobs, gigs, lists, profiles, and users API",',
    "  placeholders: {",
    `    SPROUTGIGS_API_SECRET: "${API_SECRET_PLACEHOLDER}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://sproutgigs.com/api",',
    "      auth: {",
    "        headers: {",
    "          Authorization:",
    '            "${{ basic(vars.SPROUTGIGS_USER_ID, secrets.SPROUTGIGS_API_SECRET) }}",',
    "        },",
    "      },",
    "      permissions: [",
  ];

  lines.push(...renderPermissions(PERMISSIONS));

  lines.push("      ],");
  lines.push("    },");
  lines.push("  ],");
  lines.push("} as const satisfies FirewallConfig;");
  lines.push("");

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating SproutGigs firewall config...");
  const ts = generateTypeScript();
  writeOutput("sproutgigs", ts, import.meta.dirname);
}
