import { writeOutput } from "./codegen";

const DOCS_URL = "https://developer.squareup.com/reference/square";
const PLACEHOLDER_VALUE =
  "EAAACoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocal";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Square API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:square",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const squareFirewall = {",
    '  name: "square",',
    '  description: "Square API",',
    "  placeholders: {",
    `    SQUARE_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://connect.squareup.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.SQUARE_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Square firewall config...");
  const ts = generateTypeScript();
  writeOutput("square", ts, import.meta.dirname);
}
