/**
 * Generate Stripe firewall config.
 *
 * Data source: https://docs.stripe.com/api/authentication
 *
 * Stripe uses Bearer token authentication via Authorization header.
 * Token format (gitleaks: stripe-access-token):
 *   (sk|rk)_(test|live|prod)_ + 10-99 alphanumeric chars
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://docs.stripe.com/api/authentication";
// Format: sk_live_ + [a-zA-Z0-9]{10,99} (gitleaks: stripe-access-token)
const PLACEHOLDER_VALUE = "sk_live_CoffeeSafeLocalCoffeeSafeLocalCoff";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Stripe API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:stripe",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const stripeFirewall = {",
    '  name: "stripe",',
    '  description: "Stripe API",',
    "  placeholders: {",
    `    STRIPE_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.stripe.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.STRIPE_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Stripe firewall config...");
  const ts = generateTypeScript();
  writeOutput("stripe", ts, import.meta.dirname);
}
