/**
 * Supabase Management API firewall config generator.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://supabase.com/docs/reference/api/introduction";

// sbp_oauth_ (10) + 40 hex chars = 50 chars total
const PLACEHOLDER_VALUE = "sbp_oauth_0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Supabase Management API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:supabase",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const supabaseFirewall: FirewallConfig = {",
    '  name: "supabase",',
    '  description: "Supabase Management API",',
    "  placeholders: {",
    `    SUPABASE_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.supabase.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.SUPABASE_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [",
    "        {",
    '          name: "unrestricted",',
    '          description: "Allow all endpoints",',
    '          rules: ["ANY /{path*}"],',
    "        },",
    "      ],",
    "    },",
    "  ],",
    "};",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Supabase firewall config...");
  const ts = generateTypeScript();
  writeOutput("supabase", ts, import.meta.dirname);
}
