import { writeOutput } from "./codegen";

const DOCS_URL = "https://doc.tldv.io/index.html";
const PLACEHOLDER_VALUE =
  "vm0placeholderTldvToken000000000000000000000000000000a";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from tl;dv API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:tldv",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const tldvFirewall: FirewallConfig = {",
    '  name: "tldv",',
    '  description: "tl;dv API",',
    "  placeholders: {",
    `    TLDV_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://pasta.tldv.io",',
    "      auth: {",
    "        headers: {",
    '          "x-api-key": "${{ secrets.TLDV_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "};",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating tl;dv firewall config...");
  const ts = generateTypeScript();
  writeOutput("tldv", ts, import.meta.dirname);
}
