/**
 * Generate Together AI firewall config.
 *
 * Data source: https://docs.together.ai/reference
 *
 * Together AI uses Bearer token authentication via Authorization header.
 * Token format: opaque 64-char hex string.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://docs.together.ai/reference";
// Format: 64-char hex (opaque)
const PLACEHOLDER_VALUE =
  "c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe10ca1c0ffee5afe10ca1c0ff";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Together AI API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:together",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const togetherFirewall = {",
    '  name: "together",',
    '  description: "Together AI",',
    "  placeholders: {",
    `    TOGETHER_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.together.ai",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.TOGETHER_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Together AI firewall config...");
  const ts = generateTypeScript();
  writeOutput("together", ts, import.meta.dirname);
}
