/**
 * Generate Twenty CRM firewall config (cloud-only).
 *
 * Data source: https://docs.twenty.com/developers/api-and-webhooks/api
 *
 * Twenty uses Bearer token authentication via Authorization header.
 * API key format: JWT (eyJ... ~200-300 chars, HMAC-SHA256 signed).
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://docs.twenty.com/developers/api-and-webhooks/api";
// Format: JWT token (~200 chars). Use a realistic-length placeholder.
const PLACEHOLDER_VALUE =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJDb2ZmZWVTYWZlTG9jYWxDb2ZmZWVTYWZlTG9jYWxDbyIsInR5cGUiOiJBUElfS0VZIiwid29ya3NwYWNlSWQiOiJDb2ZmZWVTYWZlTG9jYWxDb2YifQ.CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLo";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Twenty CRM API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:twenty",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const twentyFirewall = {",
    '  name: "twenty",',
    '  description: "Twenty CRM API",',
    "  placeholders: {",
    `    TWENTY_TOKEN:`,
    `      "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.twenty.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.TWENTY_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Twenty CRM firewall config...");
  const ts = generateTypeScript();
  writeOutput("twenty", ts, import.meta.dirname);
}
