/**
 * Generate Webflow firewall config.
 *
 * Data source: https://developers.webflow.com/data/reference/authentication
 *
 * Webflow is a website builder and CMS platform.
 * Uses Bearer token authentication (OAuth or Site Token).
 * Token format: opaque string, no known prefix.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://developers.webflow.com/data/reference/authentication";
// Token format not publicly documented; using generic placeholder
const PLACEHOLDER_VALUE =
  "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffe";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Webflow API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:webflow",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const webflowFirewall = {",
    '  name: "webflow",',
    '  description: "Webflow API",',
    "  placeholders: {",
    `    WEBFLOW_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.webflow.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.WEBFLOW_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Webflow firewall config...");
  const ts = generateTypeScript();
  writeOutput("webflow", ts, import.meta.dirname);
}
