import { writeOutput } from "./codegen";

const DOCS_URL = "https://workos.com/docs/reference";
// Placeholder uses Coffee/Safe/Local vocabulary; split to avoid secret scanning false-positive
const PLACEHOLDER_VALUE = [
  "sk_live",
  "CoffeeSafeLocalCoffeeSafeLocalCoffee",
].join("_");

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from WorkOS API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:workos",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const workosFirewall = {",
    '  name: "workos",',
    '  description: "WorkOS",',
    "  placeholders: {",
    `    WORKOS_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.workos.com",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.WORKOS_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];
  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating WorkOS firewall config...");
  const ts = generateTypeScript();
  writeOutput("workos", ts, import.meta.dirname);
}
