/**
 * Generate Zapier firewall config.
 *
 * Data source: https://actions.zapier.com/docs/guides/getting-started/intro
 *
 * Zapier AI Actions enables AI-powered workflow automation.
 * The legacy NLA API (nla.zapier.com) is deprecated; the current
 * endpoint is actions.zapier.com with x-api-key authentication.
 */

import { writeOutput } from "./codegen";

const DOCS_URL = "https://actions.zapier.com/docs/guides/getting-started/intro";
// Zapier API keys use "sk-ak-" prefix followed by alphanumeric characters.
const PLACEHOLDER_VALUE = "sk-ak-CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLo";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from Zapier AI Actions API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:zapier",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../firewall-types";',
    "",
    "export const zapierFirewall = {",
    '  name: "zapier",',
    '  description: "Zapier AI Actions API",',
    "  placeholders: {",
    `    ZAPIER_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://actions.zapier.com",',
    "      auth: {",
    "        headers: {",
    '          "x-api-key": "${{ secrets.ZAPIER_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating Zapier firewall config...");
  const ts = generateTypeScript();
  writeOutput("zapier", ts, import.meta.dirname);
}
