/**
 * Generate ZapSign firewall config.
 *
 * Data source: https://docs.zapsign.com.br/english/authentication/autenticacao
 *
 * ZapSign is an electronic signature platform.
 */

import { writeOutput } from "./codegen";

const DOCS_URL =
  "https://docs.zapsign.com.br/english/authentication/autenticacao";
// Format: 8-4-4-4-8 hex with hyphens (e.g. c7f35c84-7893-4087-b4fb-d1f06c23)
const PLACEHOLDER_VALUE = "c0ffee5a-fe10-ca1c-0ffe-e5afe10c";

function generateTypeScript(): string {
  const lines: string[] = [
    "// Auto-generated from ZapSign API docs.",
    `// Source: ${DOCS_URL}`,
    "// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:zapsign",
    "//",
    "// DO NOT EDIT THIS FILE MANUALLY.",
    "",
    'import type { FirewallConfig } from "../contracts/firewalls";',
    "",
    "export const zapsignFirewall = {",
    '  name: "zapsign",',
    '  description: "ZapSign API",',
    "  placeholders: {",
    `    ZAPSIGN_TOKEN: "${PLACEHOLDER_VALUE}",`,
    "  },",
    "  apis: [",
    "    {",
    '      base: "https://api.zapsign.com.br",',
    "      auth: {",
    "        headers: {",
    '          Authorization: "Bearer ${{ secrets.ZAPSIGN_TOKEN }}",',
    "        },",
    "      },",
    "      permissions: [],",
    "    },",
    "  ],",
    "} as const satisfies FirewallConfig;",
    "",
  ];

  return lines.join("\n");
}

export async function generate(): Promise<void> {
  console.error("Generating ZapSign firewall config...");
  const ts = generateTypeScript();
  writeOutput("zapsign", ts, import.meta.dirname);
}
