export const GOOGLE_ANALYTICS_MEASUREMENT_ID = "G-758ZHVCJHK";

const GOOGLE_ANALYTICS_CLIENT_ID_STORAGE_KEY = "vm0.googleAnalyticsClientId";
const GOOGLE_ANALYTICS_CLIENT_ID_TIMEOUT_MS = 500;

type GoogleAnalyticsEventParams = Readonly<
  Record<string, string | number | boolean>
>;

type GoogleTag = {
  (
    command: "config",
    targetId: string,
    params?: GoogleAnalyticsEventParams,
  ): void;
  (
    command: "event",
    eventName: string,
    params?: GoogleAnalyticsEventParams,
  ): void;
  (
    command: "get",
    targetId: string,
    fieldName: "client_id",
    callback: (value: unknown) => void,
  ): void;
};

type WindowWithGoogleTag = Window & {
  readonly gtag?: GoogleTag;
};

function googleTag(): GoogleTag | undefined {
  if (typeof window === "undefined") {
    return undefined;
  }

  const gtag = (window as WindowWithGoogleTag).gtag;
  return typeof gtag === "function" ? gtag : undefined;
}

function sessionStorageOrNull(): Storage | null {
  if (typeof window === "undefined") {
    return null;
  }

  return window.sessionStorage;
}

function validClientId(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function readGoogleAnalyticsClientIdFromCookie(
  cookieString: string,
): string | null {
  for (const part of cookieString.split(";")) {
    const trimmed = part.trim();
    if (!trimmed.startsWith("_ga=")) {
      continue;
    }

    const value = decodeURIComponent(trimmed.slice(4));
    const parts = value.split(".");
    if (parts.length < 2) {
      return null;
    }

    const clientId = parts.slice(-2).join(".");
    return validClientId(clientId) ? clientId : null;
  }

  return null;
}

function storedClientId(storage: Storage | null): string | null {
  const value = storage?.getItem(GOOGLE_ANALYTICS_CLIENT_ID_STORAGE_KEY);
  return validClientId(value) ? value : null;
}

export function getStoredGoogleAnalyticsClientId(
  storage: Storage | null = sessionStorageOrNull(),
): string | null {
  return storedClientId(storage);
}

function storeClientId(storage: Storage | null, clientId: string): void {
  storage?.setItem(GOOGLE_ANALYTICS_CLIENT_ID_STORAGE_KEY, clientId);
}

export function setGoogleAnalyticsUserId(userId: string): boolean {
  const gtag = googleTag();
  if (!gtag || !userId) {
    return false;
  }

  gtag("config", GOOGLE_ANALYTICS_MEASUREMENT_ID, {
    user_id: userId,
    send_page_view: false,
  });
  return true;
}

export function sendGoogleAnalyticsEvent(
  eventName: string,
  params: GoogleAnalyticsEventParams = {},
): boolean {
  const gtag = googleTag();
  if (!gtag) {
    return false;
  }

  gtag("event", eventName, params);
  return true;
}

/**
 * Resolve the GA4 client ID generated by gtag and retain it for checkout
 * metadata. This is intentionally best-effort so authentication and billing
 * never wait on analytics or fail when analytics is unavailable.
 */
export async function ensureGoogleAnalyticsClientId(
  signal?: AbortSignal,
): Promise<string | null> {
  const storage = sessionStorageOrNull();
  const existing = storedClientId(storage);
  if (existing) {
    return existing;
  }

  if (typeof document !== "undefined") {
    const fromCookie = readGoogleAnalyticsClientIdFromCookie(document.cookie);
    if (fromCookie) {
      storeClientId(storage, fromCookie);
      return fromCookie;
    }
  }

  const gtag = googleTag();
  if (!gtag || signal?.aborted) {
    return null;
  }

  return await new Promise<string | null>((resolve) => {
    let settled = false;
    const onAbort = () => finish(null);

    const finish = (clientId: string | null) => {
      if (settled) {
        return;
      }
      settled = true;
      window.clearTimeout(timeout);
      signal?.removeEventListener("abort", onAbort);
      if (clientId) {
        storeClientId(storage, clientId);
      }
      resolve(clientId);
    };

    const timeout = window.setTimeout(
      () => finish(null),
      GOOGLE_ANALYTICS_CLIENT_ID_TIMEOUT_MS,
    );
    signal?.addEventListener("abort", onAbort, { once: true });
    try {
      gtag("get", GOOGLE_ANALYTICS_MEASUREMENT_ID, "client_id", (value) => {
        finish(validClientId(value) ? value : null);
      });
    } catch {
      finish(null);
    }
  });
}
