- name: Run runner garbage collection
  ansible.builtin.command:
    argv:
      - "{{ bin_dir }}/runner"
      - gc
      - --keep-latest
      - "6"
      - --protect-version
      - "{{ runner_release }}"
