[package]
name = "guest-control-tests"
version = "0.10.3"
edition.workspace = true

[dependencies]
guest-write-file.workspace = true

[dev-dependencies]
libc = { workspace = true, features = ["std"] }
nix = { workspace = true, features = ["inotify"] }
shell-quote.workspace = true
tempfile = { workspace = true, features = ["getrandom"] }
guest-control-server = { workspace = true, features = ["test-support"] }
guest-control-client.workspace = true
guest-control-proto.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "net", "rt", "time"] }

[[test]]
name = "integration"
path = "tests/integration/main.rs"

[lints]
workspace = true
