[package]
name = "sandbox"
version = "0.21.1"
edition.workspace = true

[dependencies]
async-trait.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "io-util"] }
tokio-util = { workspace = true, features = ["rt"] }
uuid = { workspace = true, features = ["v4", "serde"] }

[dev-dependencies]
serde_json = { workspace = true }
trybuild = { workspace = true }

[lints]
workspace = true
