[package]
name = "guest-rpc"
version = "0.1.0"
edition.workspace = true

[dependencies]
libc.workspace = true
guest-rpc-proto.workspace = true
tokio = { workspace = true, features = ["rt", "io-util", "io-std", "net", "time"] }

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "test-util"] }

[lints]
workspace = true
