import type { ConnectorConfig } from "../connectors";

const CLOUDFLARE_OAUTH_SCOPES = [
  "agent-memory.write",
  "browser-rendering.write",
  "cf-agents.write",
  "cloud-connector.write",
  "cloudchamber.write",
  "constellation.write",
  "d1.write",
  "flagship.write",
  "flagship.evaluate",
  "flagship.read",
  "d1.read",
  "constellation.read",
  "cloudchamber.read",
  "cloud-connector.read",
  "cf-agents.read",
  "browser-rendering.read",
  "query-cache.write",
  "query-cache.read",
  "mcp-portals.read",
  "mcp-portals.write",
  "page.write",
  "page.read",
  "pipelines.read",
  "pipelines.send",
  "pipelines.write",
  "pubsub.write",
  "pubsub.read",
  "queues.read",
  "queues.write",
  "realtime.admin",
  "realtime.realtime",
  "secrets-store.read",
  "secrets-store.write",
  "vectorize.write",
  "vectorize.read",
  "workers-ci.read",
  "workers-ci.write",
  "containers.write",
  "containers.read",
  "workers-kv-storage.read",
  "workers-kv-storage.write",
  "workers-observability.write",
  "workers-observability.read",
  "workers-observability-telemetry.write",
  "r2-catalog.read",
  "r2-catalog.write",
  "r2-catalog-sql.read",
  "workers-r2.write",
  "workers-r2.read",
  "workers-r2-bucket-item.read",
  "workers-r2-bucket-item.write",
  "workers-routes.write",
  "workers-routes.read",
  "workers-scripts.read",
  "workers-scripts.write",
  "workers-tail.read",
  "agw.write",
  "agw.run",
  "agw.read",
  "aiaudit.read",
  "aiaudit.write",
  "aig.write",
  "aig.run",
  "aig.read",
  "ai-search.index",
  "ai-search.read",
  "ai-search.run",
  "ai-search.write",
  "rag.write",
  "rag.run",
  "rag.read",
  "firewall-for-ai.read",
  "firewall-for-ai.write",
  "websearch.run",
  "ai.read",
  "ai.write",
  "account-dns-settings.read",
  "account-dns-settings.write",
  "dns.write",
  "dns.read",
  "dns-firewall.write",
  "dns-firewall.read",
  "dns-view.read",
  "dns-view.write",
  "registrar-domains.admin",
  "registrar-domains.read",
  "zone.read",
  "zone.write",
  "zone-custom-asset.write",
  "zone-custom-asset.read",
  "zone-dns-settings.read",
  "zone-dns-settings.write",
  "zone-settings.write",
  "zone-settings.read",
  "zone-versioning.read",
  "zone-versioning.write",
  "fraud-detection-pii.read",
  "account-firewall-access-rules.read",
  "account-firewall-access-rules.write",
  "account-security-center-insights.write",
  "account-security-center-insights.read",
  "account-waf.read",
  "account-waf.write",
  "request-tracer.read",
  "reports-application-security-report.read",
  "bot-management.read",
  "bot-management.write",
  "bot-management-feedback.write",
  "bot-management-feedback.read",
  "cloudforce-one.read",
  "cloudforce-one.write",
  "ddos-botnet-feed.write",
  "ddos-botnet-feed.read",
  "ddos-protection.read",
  "ddos-protection.write",
  "api-gateway.write",
  "api-gateway.read",
  "domain-page.shield",
  "domain-page-shield.read",
  "firewall-services.read",
  "firewall-services.write",
  "fraud-detection.write",
  "fraud-detection.read",
  "fraud-events.write",
  "http-applications.read",
  "http-applications.write",
  "http-ddos-managed-ruleset.read",
  "http-ddos-managed-ruleset.write",
  "iot.write",
  "iot.read",
  "l4-ddos-managed-ruleset.read",
  "l4-ddos-managed-ruleset.write",
  "page-rules.write",
  "page-rules.read",
  "page.shield",
  "page-shield.read",
  "sanitize.write",
  "sanitize.read",
  "tag.read",
  "tag.write",
  "trust-and-safety.write",
  "trust-and-safety.read",
  "challenge-widgets.read",
  "challenge-widgets.write",
  "url-scanner.write",
  "url-scanner.read",
  "zaraz.edit",
  "zaraz.read",
  "zaraz.write",
  "zone-security-center-insights.write",
  "zone-security-center-insights.read",
  "zone-waf.read",
  "zone-waf.write",
  "account-custom-error-rules.write",
  "account-custom-error-rules.read",
  "account-custom-pages.read",
  "account-custom-pages.write",
  "account-rule-lists.write",
  "account-rule-lists.read",
  "account-rulesets.write",
  "account-rulesets.read",
  "config-settings.read",
  "config-settings.write",
  "custom-errors.write",
  "custom-errors.read",
  "custom-pages.read",
  "custom-pages.write",
  "dynamic-redirect.write",
  "dynamic-redirect.read",
  "managed-headers.read",
  "managed-headers.write",
  "mass-url-redirects.write",
  "mass-url-redirects.read",
  "origin.read",
  "origin.write",
  "response-compression.write",
  "response-compression.read",
  "select-configuration.read",
  "select-configuration.write",
  "snippets.read",
  "snippets.write",
  "transform-rules.write",
  "transform-rules.read",
  "zone-transform-rules.read",
  "zone-transform-rules.write",
  "intel.read",
  "intel.write",
  "account-analytics.read",
  "account-logs.write",
  "account-logs.read",
  "radar.read",
  "analytics.read",
  "logs.read",
  "logs.write",
  "access.revoke",
  "access.write",
  "access.read",
  "access-app.read",
  "access-app.revoke",
  "access-app.write",
  "zone-access.write",
  "zone-access.revoke",
  "zone-access.read",
  "access-audit-log.read",
  "access-custom-page.write",
  "access-custom-page.read",
  "access-device-posture.write",
  "access-device-posture.read",
  "access-group.read",
  "access-group.write",
  "access-idp.write",
  "access-idp.read",
  "access-key.read",
  "access-key.write",
  "access-certificate.write",
  "access-certificate.read",
  "access-org.read",
  "access-org.revoke",
  "access-org.write",
  "access-acct.write",
  "access-acct.revoke",
  "access-acct.read",
  "access-policy.read",
  "access-policy.write",
  "access-policy-test.write",
  "access-policy-test.read",
  "access-population.read",
  "access-population.write",
  "access-saml-certificate.write",
  "access-saml-certificate.read",
  "access-scim-log.read",
  "access-service-token.read",
  "access-service-token.write",
  "access-ssh-auditing.write",
  "access-ssh-auditing.read",
  "access-tag.read",
  "access-tag.write",
  "access-users.read",
  "access-users.write",
  "argotunnel.write",
  "argotunnel.read",
  "casb.read",
  "casb.write",
  "teams-cds-compute-account.write",
  "teams-cds-compute-account.read",
  "teams-dex.read",
  "teams-dex.write",
  "teams-connector-cloudflared.monitoring",
  "teams-connector-cloudflared.read",
  "teams-connector-cloudflared.write",
  "teams-connector-warp.write",
  "teams-connector-warp.read",
  "teams-connectors.read",
  "teams-connectors.write",
  "teams-networks.write",
  "teams-networks.read",
  "teams-secure.location",
  "dls.read",
  "dls.write",
  "teams.read",
  "teams.report",
  "teams.write",
  "teams-resilience.write",
  "teams-resilience.read",
  "teams-pii.read",
  "access-seats.write",
  "account-waiting-rooms.read",
  "address-maps.read",
  "address-maps.write",
  "chinanetwork-steering.write",
  "chinanetwork-steering.read",
  "connectivity-directory.read",
  "connectivity-directory.bind",
  "connectivity-directory.admin",
  "healthcheck.write",
  "healthcheck.read",
  "ip-prefix.read",
  "ip-prefix.write",
  "ip-prefix-bgp-on-demand.write",
  "ip-prefix-bgp-on-demand.read",
  "load-balancers.read",
  "load-balancers.write",
  "load-balancers-account.write",
  "load-balancers-account.read",
  "load-balancing-monitors-and-pools.read",
  "load-balancing-monitors-and-pools.write",
  "magic-firewall.write",
  "magic-firewall.read",
  "pcaps-api.write",
  "pcaps-api.read",
  "fbm.read",
  "fbm.write",
  "fbm.admin",
  "magic-transit.write",
  "magic-transit.read",
  "magic-wan.read",
  "magic-wan.write",
  "waiting-rooms.write",
  "waiting-rooms.read",
  "web3-hostnames.read",
  "web3-hostnames.write",
  "calls.read",
  "calls.write",
  "images.read",
  "images.write",
  "moq.write",
  "moq.read",
  "stream.read",
  "stream.write",
  "cloud-email-security.read",
  "cloud-email-security.write",
  "email-routing-address.write",
  "email-routing-address.read",
  "email-routing-rule.read",
  "email-routing-rule.write",
  "email-routing-suppression.write",
  "email-routing-suppression.read",
  "email-security-dmarcreports.write",
  "email-security-dmarcreports.read",
  "email-sending.read",
  "email-sending.write",
  "account-ssl-and-certificates.write",
  "account-ssl-and-certificates.read",
  "cache.purge",
  "cache-settings.read",
  "cache-settings.write",
  "account-disable-esc.write",
  "account-disable-esc.read",
  "zone-disable-esc.read",
  "zone-disable-esc.write",
  "ssl-and-certificates.write",
  "ssl-and-certificates.read",
  "account-api-gateway.read",
  "account-api-gateway.write",
  "account-custom-asset.write",
  "account-custom-asset.read",
  "account-settings.read",
  "account-settings.write",
  "apps.write",
  "integration.write",
  "memberships.read",
  "memberships.write",
  "notifications.write",
  "notifications.read",
  "scim-provisioning.write",
  "user-details.read",
  "user-details.write",
  "artifacts.read",
  "artifacts.write",
  "resource-library.write",
  "resource-library.read",
  "resource-sharing.read",
  "offline_access",
];

export const cloudflare = {
  cloudflare: {
    label: "Cloudflare",
    category: "engineering-team-execution",
    helpText:
      "Connect your Cloudflare account to manage DNS, zones, workers, and other Cloudflare services",
    authMethods: {
      oauth: {
        label: "OAuth",
        helpText: "Sign in with Cloudflare to grant access.",
        client: {
          clientRegistration: "static",
          clientType: "confidential",
          clientIdEnv: "CLOUDFLARE_OAUTH_CLIENT_ID",
          clientSecretEnv: "CLOUDFLARE_OAUTH_CLIENT_SECRET",
        },
        storage: {
          secrets: ["CLOUDFLARE_ACCESS_TOKEN", "CLOUDFLARE_REFRESH_TOKEN"],
          variables: [],
        },
        grant: {
          kind: "auth-code",
          scopes: CLOUDFLARE_OAUTH_SCOPES,
          callbackOrigin: "api",
          outputs: {
            accessToken: "$secrets.CLOUDFLARE_ACCESS_TOKEN",
            refreshToken: "$secrets.CLOUDFLARE_REFRESH_TOKEN",
          },
        },
        access: {
          kind: "refresh-token",
          inputs: {
            refreshToken: "$secrets.CLOUDFLARE_REFRESH_TOKEN",
          },
          outputs: {
            accessToken: "$secrets.CLOUDFLARE_ACCESS_TOKEN",
            refreshToken: "$secrets.CLOUDFLARE_REFRESH_TOKEN",
          },
          refreshableSecrets: ["CLOUDFLARE_ACCESS_TOKEN"],
          envBindings: {
            CLOUDFLARE_TOKEN: "$secrets.CLOUDFLARE_ACCESS_TOKEN",
          },
        },
        revoke: {
          kind: "token-revoke",
          inputs: {
            refreshToken: "$secrets.CLOUDFLARE_REFRESH_TOKEN",
          },
        },
      },
      "api-token": {
        label: "API Token",
        visible: false,
        helpText:
          "1. Log in to the [Cloudflare Dashboard](https://dash.cloudflare.com)\n2. Go to **My Profile** → **API Tokens**\n3. Click **Create Token** and configure the required permissions\n4. Copy the generated token",
        storage: {
          secrets: ["CLOUDFLARE_TOKEN"],
          variables: [],
        },
        grant: {
          kind: "manual",
          fields: {
            CLOUDFLARE_TOKEN: {
              label: "API Token",
              required: true,
            },
          },
        },
        access: {
          kind: "static",
          envBindings: {
            CLOUDFLARE_TOKEN: "$secrets.CLOUDFLARE_TOKEN",
          },
        },
        revoke: { kind: "none" },
      },
    },
  },
} as const satisfies Record<string, ConnectorConfig>;
