#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

digest_value() {
  local repo=$1 target=$2 revision=${3:-HEAD}
  RUNNER_BINARY_GIT_REVISION="$revision" \
    "${repo}/.github/scripts/runner-binary-build/digest.sh" "$target" \
    | sed -n 's/^binary-input-digest=//p'
}

commit_all() {
  local repo=$1 message=$2
  git -C "$repo" add --all
  git -C "$repo" commit -qm "$message"
}

assert_text_change_affects_digest() {
  local repo=$1 path=$2 label=$3 before after
  before=$(digest_value "$repo" aarch64-unknown-linux-musl)
  case "$path" in
    *.rs) printf '\n// %s\n' "$label" >> "${repo}/${path}" ;;
    *) printf '\n# %s\n' "$label" >> "${repo}/${path}" ;;
  esac
  git -C "$repo" add -- "$path"
  git -C "$repo" commit -qm "$label"
  after=$(digest_value "$repo" aarch64-unknown-linux-musl)
  [ "$after" != "$before" ] || fail "${label} must affect the input digest"
}

repo="${TMPDIR}/repo"
mkdir -p \
  "${repo}/.github/scripts" \
  "${repo}/crates/.cargo" \
  "${repo}/crates/guest-one/src" \
  "${repo}/crates/guest-one/tests" \
  "${repo}/crates/guest-one/examples" \
  "${repo}/crates/guest-one/benches" \
  "${repo}/crates/guest-one/fixtures" \
  "${repo}/crates/runner/src" \
  "${repo}/crates/runner/tests" \
  "${repo}/crates/runner/mitm-addon/src" \
  "${repo}/crates/runner/mitm-addon/tests" \
  "${repo}/crates/runner/scripts" \
  "${repo}/crates/other-one/src" \
  "${repo}/crates/other-one/src/feature/tests" \
  "${repo}/crates/other-one/tests" \
  "${TMPDIR}/bin"
cp -a \
  "${REPO_ROOT}/.github/scripts/runner-binary-build" \
  "${repo}/.github/scripts/runner-binary-build"

cat > "${repo}/crates/runner/guest-binaries.json" <<'JSON'
[
  {
    "package": "guest-one",
    "binary": "guest-one",
    "pathEnv": "GUEST_ONE_PATH",
    "bundledEnv": "BUNDLED_GUEST_ONE",
    "destination": "/usr/local/bin/guest-one"
  }
]
JSON
cat > "${repo}/crates/Cargo.toml" <<'TOML'
[workspace]
resolver = "2"
members = ["guest-one", "other-one", "runner"]
TOML
cat > "${repo}/crates/Cargo.lock" <<'TOML'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "guest-one"
version = "0.1.0"

[[package]]
name = "runner"
version = "0.1.0"
dependencies = [
 "guest-one",
]

[[package]]
name = "other-one"
version = "0.1.0"
TOML
cat > "${repo}/crates/guest-one/Cargo.toml" <<'TOML'
[package]
name = "guest-one"
version = "0.1.0"
edition = "2021"
TOML
cat > "${repo}/crates/runner/Cargo.toml" <<'TOML'
[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
guest-one = { path = "../guest-one" }
TOML
cat > "${repo}/crates/other-one/Cargo.toml" <<'TOML'
[package]
name = "other-one"
version = "0.1.0"
edition = "2021"
TOML
printf '[build]\ntarget-dir = "target"\n' > "${repo}/crates/.cargo/config.toml"
printf 'pub fn guest() {}\n' > "${repo}/crates/guest-one/src/lib.rs"
printf 'fn main() {}\n' > "${repo}/crates/runner/src/main.rs"
printf 'fn main() {}\n' > "${repo}/crates/runner/build.rs"
printf 'pub fn other() {}\n' > "${repo}/crates/other-one/src/lib.rs"
printf 'pub fn additional() {}\n' > "${repo}/crates/other-one/src/additional.rs"
printf 'nested source fixture\n' > "${repo}/crates/other-one/src/feature/tests/input.txt"
printf 'guest fixture\n' > "${repo}/crates/guest-one/fixtures/input.txt"
printf 'integration test\n' > "${repo}/crates/guest-one/tests/integration.rs"
printf 'example\n' > "${repo}/crates/guest-one/examples/example.rs"
printf 'bench\n' > "${repo}/crates/guest-one/benches/bench.rs"
printf 'runner integration test\n' > "${repo}/crates/runner/tests/integration.rs"
printf 'runtime\n' > "${repo}/crates/runner/mitm-addon/src/runtime.py"
printf 'mitm test\n' > "${repo}/crates/runner/mitm-addon/tests/test_runtime.py"
printf 'other integration test\n' > "${repo}/crates/other-one/tests/integration.rs"
printf '#!/usr/bin/env bash\nexit 0\n' > "${repo}/crates/runner/scripts/tool.sh"
chmod +x "${repo}/crates/runner/scripts/tool.sh"
printf 'unrelated\n' > "${repo}/README.md"
weird_relative=$'crates/guest-one/src/odd\tname\nline.txt'
printf 'odd tracked input\n' > "${repo}/${weird_relative}"

git -C "$repo" init -q
git -C "$repo" config user.email test@example.com
git -C "$repo" config user.name test
commit_all "$repo" baseline
baseline_revision=$(git -C "$repo" rev-parse HEAD)

baseline=$(digest_value "$repo" aarch64-unknown-linux-musl)
[[ "$baseline" =~ ^[0-9a-f]{64}$ ]] || fail "expected a SHA-256 input digest"
x86_digest=$(digest_value "$repo" x86_64-unknown-linux-musl)
[ "$baseline" != "$x86_digest" ] || fail "target must affect the input digest"

printf 'untracked\n' > "${repo}/crates/guest-one/src/untracked.rs"
[ "$(digest_value "$repo" aarch64-unknown-linux-musl)" = "$baseline" ] \
  || fail "untracked crate files must not affect the input digest"
rm "${repo}/crates/guest-one/src/untracked.rs"

printf 'changed test\n' >> "${repo}/crates/guest-one/tests/integration.rs"
printf 'changed example\n' >> "${repo}/crates/guest-one/examples/example.rs"
printf 'changed bench\n' >> "${repo}/crates/guest-one/benches/bench.rs"
printf 'changed runner test\n' >> "${repo}/crates/runner/tests/integration.rs"
printf 'changed mitm test\n' >> "${repo}/crates/runner/mitm-addon/tests/test_runtime.py"
printf 'changed other package test\n' >> "${repo}/crates/other-one/tests/integration.rs"
printf 'changed unrelated\n' >> "${repo}/README.md"
commit_all "$repo" excluded-changes
[ "$(digest_value "$repo" aarch64-unknown-linux-musl)" = "$baseline" ] \
  || fail "proven non-build paths must not affect the input digest"
[ "$(digest_value "$repo" aarch64-unknown-linux-musl "$baseline_revision")" = "$baseline" ] \
  || fail "historical revisions must use their own tracked context"

assert_text_change_affects_digest \
  "$repo" "crates/guest-one/src/lib.rs" "guest-source-change"
assert_text_change_affects_digest \
  "$repo" "crates/guest-one/fixtures/input.txt" "guest-fixture-change"
assert_text_change_affects_digest \
  "$repo" "crates/runner/mitm-addon/src/runtime.py" "mitm-source-change"
assert_text_change_affects_digest \
  "$repo" "crates/runner/Cargo.toml" "runner-manifest-change"
assert_text_change_affects_digest \
  "$repo" "crates/runner/build.rs" "build-script-change"
assert_text_change_affects_digest \
  "$repo" "crates/Cargo.toml" "workspace-manifest-change"
assert_text_change_affects_digest \
  "$repo" "crates/Cargo.lock" "lockfile-change"
assert_text_change_affects_digest \
  "$repo" "crates/.cargo/config.toml" "cargo-config-change"
assert_text_change_affects_digest \
  "$repo" "crates/other-one/Cargo.toml" "other-package-manifest-change"
assert_text_change_affects_digest \
  "$repo" "crates/other-one/src/lib.rs" "other-package-entry-change"
assert_text_change_affects_digest \
  "$repo" "crates/other-one/src/additional.rs" "other-package-source-change"
assert_text_change_affects_digest \
  "$repo" "crates/other-one/src/feature/tests/input.txt" "nested-source-test-path-change"
assert_text_change_affects_digest \
  "$repo" ".github/scripts/runner-binary-build/contract.env" "contract-change"

before=$(digest_value "$repo" aarch64-unknown-linux-musl)
jq '.[0].destination = "/usr/local/bin/guest-one-v2"' \
  "${repo}/crates/runner/guest-binaries.json" > "${TMPDIR}/guest-binaries.json"
mv "${TMPDIR}/guest-binaries.json" "${repo}/crates/runner/guest-binaries.json"
commit_all "$repo" guest-inventory-change
after=$(digest_value "$repo" aarch64-unknown-linux-musl)
[ "$after" != "$before" ] || fail "guest inventory must affect the input digest"

before=$after
chmod -x "${repo}/crates/runner/scripts/tool.sh"
commit_all "$repo" executable-mode-change
after=$(digest_value "$repo" aarch64-unknown-linux-musl)
[ "$after" != "$before" ] || fail "tracked executable mode must affect the input digest"

valid_revision=$(git -C "$repo" rev-parse HEAD)

ln -s ../../README.md "${repo}/crates/guest-one/src/linked.rs"
commit_all "$repo" selected-symlink
if digest_value "$repo" aarch64-unknown-linux-musl >/dev/null 2>&1; then
  fail "included symlinks must fail closed"
fi
git -C "$repo" rm -q crates/guest-one/src/linked.rs
git -C "$repo" commit -qm remove-selected-symlink

cat > "${TMPDIR}/bin/cargo" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
if [ "${1:-}" = "metadata" ]; then
  exit
fi

printf '%s\n' "$*" >> "$FAKE_CARGO_LOG"
target=""
profile=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --target) target=$2; shift 2 ;;
    --profile) profile=$2; shift 2 ;;
    *) shift ;;
  esac
done
[ -n "$target" ]
[ -n "$profile" ]
mkdir -p "${CARGO_TARGET_DIR}/${target}/${profile}"
printf 'guest-output\n' > "${CARGO_TARGET_DIR}/${target}/${profile}/guest-one"
printf 'runner-output\n' > "${CARGO_TARGET_DIR}/${target}/${profile}/runner"
BASH
chmod +x "${TMPDIR}/bin/cargo"

printf 'exit 99\n' > "${repo}/.github/scripts/runner-binary-build/compile.sh"
printf 'untracked again\n' > "${repo}/crates/guest-one/src/untracked.rs"
. "${repo}/.github/scripts/runner-binary-build/contract.env"
context_root="${TMPDIR}/materialized/runner-binary-build-context-aarch64-unknown-linux-musl"
build_digest=$(digest_value "$repo" aarch64-unknown-linux-musl)
PATH="${TMPDIR}/bin:${PATH}" \
FAKE_CARGO_LOG="${TMPDIR}/cargo.log" \
TARGET_TRIPLE=aarch64-unknown-linux-musl \
CARGO_TARGET_DIR="${TMPDIR}/target" \
RUNNER_BINARY_CONTEXT_ROOT="$context_root" \
RUNNER_BINARY_ACTUAL_TOOLCHAIN_IMAGE="$RUNNER_BINARY_TOOLCHAIN_IMAGE" \
RUNNER_BINARY_METADATA_PATH="${TMPDIR}/metadata.json" \
  "${repo}/.github/scripts/runner-binary-build/build.sh" build >/dev/null

[ "$(wc -l < "${TMPDIR}/cargo.log" | tr -d ' ')" -eq 2 ] \
  || fail "expected guest and runner Cargo entry points"
if [ "$(grep -c -- '--locked' "${TMPDIR}/cargo.log")" -ne 2 ]; then
  fail "every Cargo build must use the tracked lockfile"
fi
jq -e \
  --arg digest "$build_digest" \
  --arg toolchain "$RUNNER_BINARY_TOOLCHAIN_IMAGE" '
    .schemaVersion == 1 and
    .binaryInputDigest == $digest and
    .toolchainImage == $toolchain and
    .target == "aarch64-unknown-linux-musl" and
    (.guestSha256 | keys) == ["guest-one"] and
    (.runnerSizeBytes > 0)
  ' "${TMPDIR}/metadata.json" >/dev/null \
  || fail "expected fresh metadata from the extracted build contract"

[ -f "${context_root}/crates/guest-one/src/lib.rs" ] \
  || fail "expected guest package source"
[ -f "${context_root}/crates/runner/mitm-addon/src/runtime.py" ] \
  || fail "expected mitm source"
[ -f "${context_root}/crates/other-one/Cargo.toml" ] \
  || fail "expected other workspace package manifest"
[ -f "${context_root}/crates/other-one/src/lib.rs" ] \
  || fail "expected other workspace package entry"
[ -f "${context_root}/crates/other-one/src/additional.rs" ] \
  || fail "default inclusion must retain other workspace package source"
[ -f "${context_root}/crates/other-one/src/feature/tests/input.txt" ] \
  || fail "only package top-level test trees may be excluded"
[ -f "${context_root}/${weird_relative}" ] \
  || fail "expected unusual tracked filename"
[ ! -x "${context_root}/crates/runner/scripts/tool.sh" ] \
  || fail "expected materialized executable mode to match the index"
[ ! -e "${context_root}/crates/guest-one/tests/integration.rs" ] \
  || fail "materialization must exclude package integration tests"
[ ! -e "${context_root}/crates/guest-one/examples/example.rs" ] \
  || fail "materialization must exclude examples"
[ ! -e "${context_root}/crates/guest-one/benches/bench.rs" ] \
  || fail "materialization must exclude benches"
[ ! -e "${context_root}/crates/runner/mitm-addon/tests/test_runtime.py" ] \
  || fail "materialization must exclude mitm tests"
[ ! -e "${context_root}/crates/other-one/tests/integration.rs" ] \
  || fail "materialization must exclude other package integration tests"
[ ! -e "${context_root}/crates/guest-one/src/untracked.rs" ] \
  || fail "materialization must exclude untracked crate content"
[ ! -e "${context_root}/README.md" ] \
  || fail "materialization must exclude unrelated tracked content"

historical_valid_digest=$(digest_value "$repo" aarch64-unknown-linux-musl "$valid_revision")
[ "$historical_valid_digest" = "$build_digest" ] \
  || fail "equal historical context trees must produce equal digests"
[ "$historical_valid_digest" != "$baseline" ] \
  || fail "historical revision selection must distinguish included changes"

if TARGET_TRIPLE=powerpc-unknown-linux-musl \
  "${repo}/.github/scripts/runner-binary-build/build.sh" materialize >/dev/null 2>&1; then
  fail "expected unsupported target to fail"
fi
if TARGET_TRIPLE=aarch64-unknown-linux-musl \
  RUNNER_BINARY_ACTUAL_TOOLCHAIN_IMAGE=unexpected-toolchain \
  "${repo}/.github/scripts/runner-binary-build/build.sh" build >/dev/null 2>&1; then
  fail "expected a mismatched build toolchain to fail"
fi

"${REPO_ROOT}/.github/scripts/runner-binary-build/context.sh" \
  validate-workspace "$REPO_ROOT"

actual_repo="${TMPDIR}/actual-repo"
mkdir -p "${actual_repo}/.github/scripts"
git -C "$REPO_ROOT" archive HEAD crates | tar -xf - -C "$actual_repo"
cp -a \
  "${REPO_ROOT}/.github/scripts/runner-binary-build" \
  "${actual_repo}/.github/scripts/runner-binary-build"
git -C "$actual_repo" init -q
git -C "$actual_repo" config user.email test@example.com
git -C "$actual_repo" config user.name test
commit_all "$actual_repo" actual-workspace
actual_context="${TMPDIR}/actual-materialized/runner-binary-build-context-aarch64-unknown-linux-musl"
TARGET_TRIPLE=aarch64-unknown-linux-musl \
CARGO_TARGET_DIR="${TMPDIR}/actual-target" \
RUNNER_BINARY_CONTEXT_ROOT="$actual_context" \
  "${actual_repo}/.github/scripts/runner-binary-build/build.sh" materialize >/dev/null
"${actual_context}/.github/scripts/runner-binary-build/context.sh" \
  validate-workspace "$actual_context"
[ -f "${actual_context}/crates/runner/src/main.rs" ] \
  || fail "actual context must contain runner source"
[ ! -e "${actual_context}/crates/runner/mitm-addon/tests" ] \
  || fail "actual context must exclude runner mitm tests"
[ -f "${actual_context}/crates/sandbox-mock/src/lib.rs" ] \
  || fail "actual context must retain all workspace package entries"
[ -f "${actual_context}/crates/sandbox-mock/src/call_records.rs" ] \
  || fail "actual context must retain other workspace package source"

workflow_toolchain=$(awk '
  /^  compile:$/ { in_compile = 1; next }
  in_compile && /^      image: / { sub(/^      image: /, ""); print; exit }
' "${REPO_ROOT}/.github/workflows/runner-image.yml")
. "${REPO_ROOT}/.github/scripts/runner-binary-build/contract.env"
[ "$RUNNER_BINARY_INPUT_SCHEMA_VERSION" = "2" ] \
  || fail "runner binary input schema must start generation 2"
[ "$workflow_toolchain" = "$RUNNER_BINARY_TOOLCHAIN_IMAGE" ] \
  || fail "Runner Image workflow toolchain must match the hashed build contract"

echo "runner-binary-build-test: ok"
