import {
  AUTH_LINK_ACTION_CLASS,
  AUTH_PRIMARY_ACTION_CLASS,
} from "../auth/auth-action-styles.ts";

export const AUTH_V2_PRIMARY_ACTION_CLASS = AUTH_PRIMARY_ACTION_CLASS;
export const AUTH_V2_LINK_ACTION_CLASS = AUTH_LINK_ACTION_CLASS;
