[package]
name = "ably-subscriber"
version = "1.1.1"
edition.workspace = true

[dependencies]
base64 = { workspace = true, features = ["simd-unsafe", "std"] }
futures-util = { workspace = true, features = ["async-await", "async-await-macro", "std"] }
reqwest = { workspace = true, features = ["json", "rustls"] }
rmp-serde = { workspace = true }
rmpv = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tokio-tungstenite = { workspace = true, features = ["connect", "rustls-tls-native-roots"] }
tokio-util = { workspace = true, features = ["rt"] }
tracing = { workspace = true, features = ["attributes", "std"] }
url = { workspace = true, features = ["std"] }

[dev-dependencies]
hmac = { workspace = true }
httpmock = { workspace = true, features = ["cookies"] }
proptest = { workspace = true, features = ["std"] }
sha2 = { workspace = true, features = ["alloc", "oid"] }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "test-util"] }
tracing-subscriber = { workspace = true, features = ["ansi", "fmt", "smallvec", "std", "tracing-log"] }
tracing-test-support = { workspace = true }

[[test]]
name = "integration"
path = "tests/integration/mod.rs"

[lints]
workspace = true
