// DataForSEO Labs Google locations, snapshot published 2026-09-01.
// Source: https://cdn.dataforseo.com/v3/locations/locations_and_languages_dataforseo_labs_2026_09_01.csv
// Refresh from the latest CSV linked at https://docs.dataforseo.com/v3/dataforseo_labs_locations_and_languages/
// Keep Google entries, deduplicate by location_code, and retain supported regions.
// This local snapshot avoids a provider lookup on every request.
const DATAFORSEO_LABS_LOCATIONS = [
  { code: 2008, name: "Albania", isoCode: "AL" },
  { code: 2012, name: "Algeria", isoCode: "DZ" },
  { code: 2024, name: "Angola", isoCode: "AO" },
  { code: 2031, name: "Azerbaijan", isoCode: "AZ" },
  { code: 2032, name: "Argentina", isoCode: "AR" },
  { code: 2036, name: "Australia", isoCode: "AU" },
  { code: 2040, name: "Austria", isoCode: "AT" },
  { code: 2048, name: "Bahrain", isoCode: "BH" },
  { code: 2050, name: "Bangladesh", isoCode: "BD" },
  { code: 2051, name: "Armenia", isoCode: "AM" },
  { code: 2056, name: "Belgium", isoCode: "BE" },
  { code: 2068, name: "Bolivia", isoCode: "BO" },
  { code: 2070, name: "Bosnia and Herzegovina", isoCode: "BA" },
  { code: 2076, name: "Brazil", isoCode: "BR" },
  { code: 2100, name: "Bulgaria", isoCode: "BG" },
  { code: 2104, name: "Myanmar (Burma)", isoCode: "MM" },
  { code: 2116, name: "Cambodia", isoCode: "KH" },
  { code: 2120, name: "Cameroon", isoCode: "CM" },
  { code: 2124, name: "Canada", isoCode: "CA" },
  { code: 2144, name: "Sri Lanka", isoCode: "LK" },
  { code: 2152, name: "Chile", isoCode: "CL" },
  { code: 2158, name: "Taiwan", isoCode: "TW" },
  { code: 2170, name: "Colombia", isoCode: "CO" },
  { code: 2188, name: "Costa Rica", isoCode: "CR" },
  { code: 2191, name: "Croatia", isoCode: "HR" },
  { code: 2196, name: "Cyprus", isoCode: "CY" },
  { code: 2203, name: "Czechia", isoCode: "CZ" },
  { code: 2208, name: "Denmark", isoCode: "DK" },
  { code: 2218, name: "Ecuador", isoCode: "EC" },
  { code: 2222, name: "El Salvador", isoCode: "SV" },
  { code: 2233, name: "Estonia", isoCode: "EE" },
  { code: 2246, name: "Finland", isoCode: "FI" },
  { code: 2250, name: "France", isoCode: "FR" },
  { code: 2276, name: "Germany", isoCode: "DE" },
  { code: 2288, name: "Ghana", isoCode: "GH" },
  { code: 2300, name: "Greece", isoCode: "GR" },
  { code: 2320, name: "Guatemala", isoCode: "GT" },
  { code: 2344, name: "Hong Kong", isoCode: "HK" },
  { code: 2348, name: "Hungary", isoCode: "HU" },
  { code: 2356, name: "India", isoCode: "IN" },
  { code: 2360, name: "Indonesia", isoCode: "ID" },
  { code: 2372, name: "Ireland", isoCode: "IE" },
  { code: 2376, name: "Israel", isoCode: "IL" },
  { code: 2380, name: "Italy", isoCode: "IT" },
  { code: 2384, name: "Cote d'Ivoire", isoCode: "CI" },
  { code: 2392, name: "Japan", isoCode: "JP" },
  { code: 2398, name: "Kazakhstan", isoCode: "KZ" },
  { code: 2400, name: "Jordan", isoCode: "JO" },
  { code: 2404, name: "Kenya", isoCode: "KE" },
  { code: 2410, name: "South Korea", isoCode: "KR" },
  { code: 2428, name: "Latvia", isoCode: "LV" },
  { code: 2440, name: "Lithuania", isoCode: "LT" },
  { code: 2458, name: "Malaysia", isoCode: "MY" },
  { code: 2470, name: "Malta", isoCode: "MT" },
  { code: 2484, name: "Mexico", isoCode: "MX" },
  { code: 2492, name: "Monaco", isoCode: "MC" },
  { code: 2498, name: "Moldova", isoCode: "MD" },
  { code: 2504, name: "Morocco", isoCode: "MA" },
  { code: 2528, name: "Netherlands", isoCode: "NL" },
  { code: 2554, name: "New Zealand", isoCode: "NZ" },
  { code: 2558, name: "Nicaragua", isoCode: "NI" },
  { code: 2566, name: "Nigeria", isoCode: "NG" },
  { code: 2578, name: "Norway", isoCode: "NO" },
  { code: 2586, name: "Pakistan", isoCode: "PK" },
  { code: 2591, name: "Panama", isoCode: "PA" },
  { code: 2600, name: "Paraguay", isoCode: "PY" },
  { code: 2604, name: "Peru", isoCode: "PE" },
  { code: 2608, name: "Philippines", isoCode: "PH" },
  { code: 2616, name: "Poland", isoCode: "PL" },
  { code: 2620, name: "Portugal", isoCode: "PT" },
  { code: 2642, name: "Romania", isoCode: "RO" },
  { code: 2682, name: "Saudi Arabia", isoCode: "SA" },
  { code: 2686, name: "Senegal", isoCode: "SN" },
  { code: 2688, name: "Serbia", isoCode: "RS" },
  { code: 2702, name: "Singapore", isoCode: "SG" },
  { code: 2703, name: "Slovakia", isoCode: "SK" },
  { code: 2704, name: "Vietnam", isoCode: "VN" },
  { code: 2705, name: "Slovenia", isoCode: "SI" },
  { code: 2710, name: "South Africa", isoCode: "ZA" },
  { code: 2724, name: "Spain", isoCode: "ES" },
  { code: 2752, name: "Sweden", isoCode: "SE" },
  { code: 2756, name: "Switzerland", isoCode: "CH" },
  { code: 2764, name: "Thailand", isoCode: "TH" },
  { code: 2784, name: "United Arab Emirates", isoCode: "AE" },
  { code: 2788, name: "Tunisia", isoCode: "TN" },
  { code: 2792, name: "Turkiye", isoCode: "TR" },
  { code: 2804, name: "Ukraine", isoCode: "UA" },
  { code: 2807, name: "North Macedonia", isoCode: "MK" },
  { code: 2818, name: "Egypt", isoCode: "EG" },
  { code: 2826, name: "United Kingdom", isoCode: "GB" },
  { code: 2840, name: "United States", isoCode: "US" },
  { code: 2854, name: "Burkina Faso", isoCode: "BF" },
  { code: 2858, name: "Uruguay", isoCode: "UY" },
  { code: 2862, name: "Venezuela", isoCode: "VE" },
] as const;

export function dataForSeoLabsLocationCode(
  location: string,
): number | undefined {
  let normalized = location.trim().replace(/\s+/g, " ").toLowerCase();
  if (normalized === "usa") {
    normalized = "us";
  } else if (normalized === "uk") {
    normalized = "gb";
  }
  return DATAFORSEO_LABS_LOCATIONS.find(({ name, isoCode }) => {
    return (
      name.toLowerCase() === normalized || isoCode.toLowerCase() === normalized
    );
  })?.code;
}
