[package]
name = "process-launch"
version = "0.1.1"
edition.workspace = true

[dependencies]
libc = { workspace = true, features = ["std"] }
tokio = { workspace = true, optional = true, features = ["io-util", "net", "process", "rt", "sync", "time"] }

[features]
tokio = ["dep:tokio"]

[dev-dependencies]
tempfile = { workspace = true, features = ["getrandom"] }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "time"] }

[lints]
workspace = true
