import * as fs from "node:fs";
import * as path from "node:path";
import { describe, expect, it } from "vitest";

import {
  buildBuiltinFirewallCatalog,
  renderPythonBuiltinFirewallCatalogFiles,
} from "../builtin-firewall-catalog";

function findGeneratedContent(
  files: readonly { readonly path: string; readonly content: string }[],
  path: string,
): string {
  const file = files.find((candidate) => {
    return candidate.path === path;
  });
  if (file === undefined) {
    throw new Error(`missing generated file: ${path}`);
  }
  return file.content;
}

describe("builtin firewall catalog", () => {
  it("includes connector and model-provider firewalls", async () => {
    const catalog = await buildBuiltinFirewallCatalog();

    expect(catalog.firewalls.github?.apis[0]?.base).toBe(
      "https://api.github.com",
    );
    expect(catalog.firewalls.fal).not.toHaveProperty("label");
    expect(
      catalog.firewalls["model-provider:openai-api-key"]?.apis[0]?.base,
    ).toBe("https://api.openai.com/v1/responses");
  });

  it("preserves connector auth templates", async () => {
    const catalog = await buildBuiltinFirewallCatalog();

    expect(catalog.firewalls.cloudflare?.apis[0]?.auth).toStrictEqual({
      headers: {
        Authorization: "Bearer ${{ secrets.CLOUDFLARE_TOKEN }}",
      },
    });
    expect(catalog.firewalls.slock?.apis[0]?.auth).toStrictEqual({
      headers: {
        Authorization: "Bearer ${{ secrets.SLOCK_TOKEN }}",
        "X-Server-Id": "${{ secrets.SLOCK_SERVER_ID }}",
      },
    });
    expect(catalog.firewalls.serpapi?.apis[0]?.auth).toStrictEqual({
      query: {
        api_key: "${{ secrets.SERPAPI_TOKEN }}",
      },
    });
    expect(catalog.firewalls.aws?.apis[0]?.auth).toStrictEqual({
      awsSigv4: {
        accessKeyId: "${{ secrets.AWS_ACCESS_KEY_ID }}",
        secretAccessKey: "${{ secrets.AWS_SECRET_ACCESS_KEY }}",
        sessionToken: "${{ secrets.AWS_SESSION_TOKEN }}",
      },
    });
  });

  it("keeps the transitional Python renderer wrapper wired to the current catalog", async () => {
    const files = await renderPythonBuiltinFirewallCatalogFiles();
    const paths = files.map((file) => {
      return file.path;
    });

    expect(paths).toContain("__init__.py");
    expect(paths).toContain("loader.py");
    expect(paths).toContain("manifest.py");
    expect(paths).toContain("diagnostics.py");
    expect(paths).toContain("github_0.py");
    expect(paths).toContain("model_provider_openai_api_key_0.py");
    expect(findGeneratedContent(files, "__init__.py")).toContain(
      "# @generated by @vm0/api-contracts.",
    );
    expect(findGeneratedContent(files, "__init__.py")).toContain(
      "BUILTIN_FIREWALLS = _BuiltinFirewallCatalog()",
    );
    expect(findGeneratedContent(files, "loader.py")).toContain(
      "from . import github_0",
    );
    expect(findGeneratedContent(files, "manifest.py")).toContain(
      '"github": ("github_0",),',
    );
  });

  it("does not import the eager connector all-catalog", () => {
    const source = fs.readFileSync(
      path.resolve(import.meta.dirname, "../builtin-firewall-catalog.ts"),
      "utf-8",
    );

    expect(source).not.toContain("@vm0/connectors/firewalls/all");
  });
});
