export type RoutePath =
  | "/"
  | "/select-org"
  | "/:tab"
  | "/activity"
  | "/activity/:logId"
  | "/chat/:sessionId"
  | "/team"
  | "/team/:name"
  | "/talk/:name"
  | "/slack/connect"
  | "/queue"
  | "/activity"
  | "/activity/:logId"
  | "/__internal-connector-logos"
  | `/projects/${string}`;
