export type RoutePath =
  | "/"
  | "/logs"
  | "/logs/:id"
  | "/settings"
  | "/settings/slack"
  | "/agents"
  | "/agents/:name"
  | "/agents/:name/logs"
  | "/agents/:name/connections"
  | "/environment-variables-setup"
  | "/provider-setup"
  | "/slack/connect"
  | "/slack/connect/success"
  | `/projects/${string}`;
