/**
 * Build script for sandbox agent scripts
 *
 * Bundles TypeScript source files into self-contained ESM modules (.mjs)
 * that can be deployed and executed in E2B sandbox or Firecracker VM.
 *
 * Output (in src/sandbox/scripts/dist/):
 * - *.mjs - Bundled scripts for deployment
 * - *.py - Python scripts (copied as-is)
 * - bundled.ts - Exports bundled JS/Python as string constants for TypeScript imports
 */
import * as esbuild from "esbuild";
import * as fs from "fs";
import * as path from "path";

const SCRIPTS_SRC = "src/sandbox/scripts/src";
const SCRIPTS_DIST = "src/sandbox/scripts/dist";
const BUNDLED_TS = `${SCRIPTS_DIST}/bundled.ts`;

async function build() {
  console.log("[build-sandbox-scripts] Starting build...");

  // Ensure generated/dist directory exists
  fs.mkdirSync(SCRIPTS_DIST, { recursive: true });

  // Bundle entry points as ESM with .mjs extension
  await esbuild.build({
    entryPoints: [
      `${SCRIPTS_SRC}/run-agent.ts`,
      `${SCRIPTS_SRC}/download.ts`,
      `${SCRIPTS_SRC}/mock-claude.ts`,
      `${SCRIPTS_SRC}/env-loader.ts`,
      `${SCRIPTS_SRC}/vsock-agent.ts`,
    ],
    bundle: true,
    platform: "node",
    target: "node20",
    format: "esm",
    outExtension: { ".js": ".mjs" },
    outdir: SCRIPTS_DIST,
    minify: false,
    banner: {
      js: "#!/usr/bin/env node",
    },
  });

  console.log(`[build-sandbox-scripts] Bundled scripts to ${SCRIPTS_DIST}/`);

  // Copy Python scripts (not bundled, just copied as-is)
  copyPythonScripts();

  // Generate bundled.ts
  generateBundledTs();

  console.log("[build-sandbox-scripts] Build complete!");
}

function copyPythonScripts() {
  // Copy vsock-bridge.py to dist directory
  const srcPath = path.join(SCRIPTS_SRC, "vsock-bridge.py");
  const distPath = path.join(SCRIPTS_DIST, "vsock-bridge.py");

  if (fs.existsSync(srcPath)) {
    fs.copyFileSync(srcPath, distPath);
    console.log(
      `[build-sandbox-scripts] Copied vsock-bridge.py to ${SCRIPTS_DIST}/`,
    );
  } else {
    console.warn(
      `[build-sandbox-scripts] Warning: ${srcPath} not found, skipping`,
    );
  }
}

function generateBundledTs() {
  const runAgentMjs = fs.readFileSync(
    path.join(SCRIPTS_DIST, "run-agent.mjs"),
    "utf-8",
  );
  const downloadMjs = fs.readFileSync(
    path.join(SCRIPTS_DIST, "download.mjs"),
    "utf-8",
  );
  const mockClaudeMjs = fs.readFileSync(
    path.join(SCRIPTS_DIST, "mock-claude.mjs"),
    "utf-8",
  );
  const envLoaderMjs = fs.readFileSync(
    path.join(SCRIPTS_DIST, "env-loader.mjs"),
    "utf-8",
  );
  const vsockAgentMjs = fs.readFileSync(
    path.join(SCRIPTS_DIST, "vsock-agent.mjs"),
    "utf-8",
  );
  const vsockBridgePy = fs.readFileSync(
    path.join(SCRIPTS_DIST, "vsock-bridge.py"),
    "utf-8",
  );

  const output = `// Auto-generated by scripts/build-sandbox-scripts.ts - do not edit manually
// These are bundled ESM scripts for deployment to E2B sandbox or Firecracker VM

/** Main agent orchestrator script - handles CLI execution, events, checkpoints */
export const RUN_AGENT_SCRIPT = ${JSON.stringify(runAgentMjs)};

/** Storage download script - downloads volumes/artifacts from S3 via presigned URLs */
export const DOWNLOAD_SCRIPT = ${JSON.stringify(downloadMjs)};

/** Mock Claude CLI for testing - executes prompt as bash, outputs Claude-compatible JSONL */
export const MOCK_CLAUDE_SCRIPT = ${JSON.stringify(mockClaudeMjs)};

/** Environment loader for runner - loads env from JSON file before running agent */
export const ENV_LOADER_SCRIPT = ${JSON.stringify(envLoaderMjs)};

/** Vsock agent for host-guest communication in Firecracker VMs */
export const VSOCK_AGENT_SCRIPT = ${JSON.stringify(vsockAgentMjs)};

/** Python vsock bridge - bridges vsock to Unix socket (socat doesn't work on aarch64) */
export const VSOCK_BRIDGE_SCRIPT = ${JSON.stringify(vsockBridgePy)};
`;

  fs.writeFileSync(BUNDLED_TS, output);
  console.log(`[build-sandbox-scripts] Generated ${BUNDLED_TS}`);
}

build().catch((error) => {
  console.error("[build-sandbox-scripts] Build failed:", error);
  process.exit(1);
});
