/**
 * Feature switch keys
 *
 * Defines all available feature switch identifiers.
 */
export enum FeatureSwitchKey {
  Dummy = "_dummy",
  AhrefsConnector = "ahrefsConnector",
  BillConnector = "billConnector",
  BentomlConnector = "bentomlConnector",
  CanvaConnector = "canvaConnector",
  CalComConnector = "calComConnector",
  CopperConnector = "copperConnector",
  DatadogConnector = "datadogConnector",
  DeelConnector = "deelConnector",
  DocuSignConnector = "docusignConnector",
  DropboxConnector = "dropboxConnector",
  FigmaConnector = "figmaConnector",
  ExpensifyConnector = "expensifyConnector",
  MercuryConnector = "mercuryConnector",
  NeonConnector = "neonConnector",
  NetSuiteConnector = "netSuiteConnector",
  GarminConnectConnector = "garminConnectConnector",
  RedditConnector = "redditConnector",
  SupabaseConnector = "supabaseConnector",
  WebflowConnector = "webflowConnector",
  CloseConnector = "closeConnector",
  PosthogConnector = "posthogConnector",
  PayPalConnector = "payPalConnector",
  RampConnector = "rampConnector",
  MailchimpConnector = "mailchimpConnector",
  ResendConnector = "resendConnector",
  SpotifyConnector = "spotifyConnector",
  StripeMarketplaceOAuthConnector = "stripeMarketplaceOAuthConnector",
  OkouDebug = "_debug",
  Banking = "banking",
  Lab = "_lab",
  NotionWorkflowAutomations = "notionWorkflowAutomations",
  GoogleFormsWorkflowAutomations = "googleFormsWorkflowAutomations",
  StripeInvoicePaidWorkflowAutomations = "stripeInvoicePaidWorkflowAutomations",
  OfficialWorkflows = "officialWorkflows",
  MorningBrief = "morningBrief",
  TestOauthConnector = "_testOauthConnector",
  FreshdeskConnector = "freshdeskConnector",
  StabilityAiConnector = "stabilityAiConnector",
  ZoomConnector = "zoomConnector",
  WorkdayConnector = "workdayConnector",
  CodexFastMode = "_fastModel",
  ChatPreference = "chatPreference",
  RealAgentInPreview = "_realAgentInPreview",
  ZapierConnector = "zapierConnector",
  ComputerUseDesktopPlugins = "computerUseDesktopPlugins",
  ChatErrorRecovery = "chatErrorRecovery",
  ChatRunWorkFolding = "chatRunWorkFolding",
  ProgressiveArtifactPreview = "progressiveArtifactPreview",
  ChatThinkingSpinner = "chatThinkingSpinner",
  FollowUpOptimize = "followUpOptimize",
  ResponsiveFollowupCards = "responsiveFollowupCards",
  StableChatThreadNavigation = "stableChatThreadNavigation",
  SidebarSubscriptionUsage = "_sidebarSubscriptionUsage",
  PersonalModelProviderAccounts = "_multipleSubscriptions",
  FeishuIntegration = "_feishuIntegration",
  CustomConnectorMcp = "customConnectorMcp",
  SshAccess = "_sshAccess",
  SharedThreadSharing = "sharedThreadSharing",
  PiLoop = "piLoop",
  PresentationScreenshot = "presentationScreenshot",
  PresentationTemplates = "presentationTemplates",
  IntroVideo = "introVideo",
  ChatTranslation = "chatTranslation",
  VoiceInputV2 = "voiceInputV2",
  ComposerImageAnnotation = "composerImageAnnotation",
  GradientColorThemes = "gradientColorThemes",
  GeistTypeface = "geistTypeface",
  AvatarComposerV2 = "avatarComposerV2",
  AvatarNeckSweater = "avatarNeckSweater",
  NewUi = "newUi",
}
