/**
 * Feature switch keys
 *
 * Defines all available feature switch identifiers.
 */
export enum FeatureSwitchKey {
  Dummy = "dummy",
  Pricing = "pricing",
  Agents = "agents",
  Secrets = "secrets",
  Artifacts = "artifacts",
  ApiKeys = "apiKeys",
  AhrefsConnector = "ahrefsConnector",
  CanvaConnector = "canvaConnector",
  ComputerConnector = "computerConnector",
  DeelConnector = "deelConnector",
  DocuSignConnector = "docusignConnector",
  DropboxConnector = "dropboxConnector",
  FigmaConnector = "figmaConnector",
  GmailConnector = "gmailConnector",
  GoogleSheetsConnector = "googleSheetsConnector",
  GoogleDocsConnector = "googleDocsConnector",
  GoogleDriveConnector = "googleDriveConnector",
  GoogleCalendarConnector = "googleCalendarConnector",
  MercuryConnector = "mercuryConnector",
  NeonConnector = "neonConnector",
  GarminConnectConnector = "garminConnectConnector",
  RedditConnector = "redditConnector",
  IntervalsIcuConnector = "intervalsIcuConnector",
  SupabaseConnector = "supabaseConnector",
  WebflowConnector = "webflowConnector",
  CloseConnector = "closeConnector",
  OutlookMailConnector = "outlookMailConnector",
  OutlookCalendarConnector = "outlookCalendarConnector",
  MetaAdsConnector = "metaAdsConnector",
  StripeConnector = "stripeConnector",
  PosthogConnector = "posthogConnector",
  MailchimpConnector = "mailchimpConnector",
  ResendConnector = "resendConnector",
  GitHubIntegration = "githubIntegration",
  TelegramIntegration = "telegramIntegration",
  DataExport = "dataExport",
  ShowSystemPrompt = "showSystemPrompt",
}
