/**
 * Feature switch keys
 *
 * Defines all available feature switch identifiers.
 */
export enum FeatureSwitchKey {
  Dummy = "dummy",
  AhrefsConnector = "ahrefsConnector",
  BillConnector = "billConnector",
  BentomlConnector = "bentomlConnector",
  BoxConnector = "boxConnector",
  CanvaConnector = "canvaConnector",
  CalComConnector = "calComConnector",
  CopperConnector = "copperConnector",
  DatadogConnector = "datadogConnector",
  DeelConnector = "deelConnector",
  DocuSignConnector = "docusignConnector",
  DropboxConnector = "dropboxConnector",
  FigmaConnector = "figmaConnector",
  ExpensifyConnector = "expensifyConnector",
  JoggAiBuiltIn = "joggAiBuiltIn",
  MercuryConnector = "mercuryConnector",
  NeonConnector = "neonConnector",
  NetSuiteConnector = "netSuiteConnector",
  GarminConnectConnector = "garminConnectConnector",
  RedditConnector = "redditConnector",
  SupabaseConnector = "supabaseConnector",
  WebflowConnector = "webflowConnector",
  CloseConnector = "closeConnector",
  MetaAdsConnector = "metaAdsConnector",
  PosthogConnector = "posthogConnector",
  PayPalConnector = "payPalConnector",
  RampConnector = "rampConnector",
  MailchimpConnector = "mailchimpConnector",
  ResendConnector = "resendConnector",
  SpotifyConnector = "spotifyConnector",
  ZeroDebug = "zeroDebug",
  Banking = "banking",
  Lab = "lab",
  NotionWorkflowAutomations = "notionWorkflowAutomations",
  GoogleFormsWorkflowAutomations = "googleFormsWorkflowAutomations",
  StripeInvoicePaidWorkflowAutomations = "stripeInvoicePaidWorkflowAutomations",
  GithubWebhookAutomations = "githubWebhookAutomations",
  MorningBrief = "morningBrief",
  ManualMorningBrief = "manualMorningBrief",
  TestOauthConnector = "testOauthConnector",
  FreshdeskConnector = "freshdeskConnector",
  StabilityAiConnector = "stabilityAiConnector",
  ZoomConnector = "zoomConnector",
  WorkdayConnector = "workdayConnector",
  CodexFastMode = "codexFastMode",
  NewChatDefaultModelAction = "newChatDefaultModelAction",
  RealAgentInPreview = "realAgentInPreview",
  UsagePackPlans = "usagePackPlans",
  PaymentMethodManagement = "paymentMethodManagement",

  ZapierConnector = "zapierConnector",
  ComputerUseDesktopPlugins = "computerUseDesktopPlugins",
  ChatErrorRecovery = "chatErrorRecovery",
  ResponsiveFollowupCards = "responsiveFollowupCards",
  ConnectorDiscovery = "connectorDiscovery",
  ConnectorCatalogCount = "connectorCatalogCount",
  SidebarSubscriptionUsage = "sidebarSubscriptionUsage",
  PersonalModelProviderAccounts = "personalModelProviderAccounts",
  ConcurrencyMemberUsage = "concurrencyMemberUsage",
  TeamsIntegration = "teamsIntegration",
  FeishuIntegration = "feishuIntegration",
  StrapiIntegration = "strapiIntegration",
  WorkflowConnectorReadiness = "workflowConnectorReadiness",
  ComposerConnectorPermissions = "composerConnectorPermissions",
  CustomConnectorMcp = "customConnectorMcp",
  ThreeColumnNav = "threeColumnNav",
  SharedThreadSharing = "sharedThreadSharing",
  PiLoop = "piLoop",
  VideoTemplateOptions = "videoTemplateOptions",
  ChatEventSnapshotRead = "chatEventSnapshotRead",
  EmojiPickerCategoryRail = "emojiPickerCategoryRail",
  PresentationTemplates = "presentationTemplates",
}
