import type { AvatarVideoAvatar } from "@okouai/api-contracts/contracts/avatar-video";

/**
 * A curated intro-video presenter.
 *
 * `coverUrl` points at a background-removed cutout published under
 * `static.vm0.io`. Those objects are hard cached for one year and immutable, so
 * a re-cut of the artwork must be published under a new `v<n>/` prefix rather
 * than by overwriting the current one.
 *
 * The intrinsic cutout size is carried alongside the URL because the picker
 * lays the cards out as a masonry grid and needs the aspect ratio before the
 * image loads.
 */
export interface IntroVideoAvatar extends AvatarVideoAvatar {
  readonly coverUrl: string;
  readonly cutoutWidth: number;
  readonly cutoutHeight: number;
}

/**
 * Presenters offered by the intro-video wizard.
 *
 * `id` is the JoggAI public avatar id, which is what the generated prompt and
 * the avatar-video API both key off. Only avatars with a published cutout
 * appear here, so this list is deliberately narrower than the full JoggAI
 * catalog used by the generic avatar-video template picker.
 */
export const INTRO_VIDEO_AVATARS: readonly IntroVideoAvatar[] = [
  {
    id: 1785,
    name: "Amara",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1785.webp",
    cutoutWidth: 480,
    cutoutHeight: 1011,
  },
  {
    id: 1756,
    name: "Andrew",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1756.webp",
    cutoutWidth: 480,
    cutoutHeight: 538,
  },
  {
    id: 1146,
    name: "Archie Outdoors",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1146.webp",
    cutoutWidth: 480,
    cutoutHeight: 441,
  },
  {
    id: 1753,
    name: "Bradley",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1753.webp",
    cutoutWidth: 480,
    cutoutHeight: 528,
  },
  {
    id: 1780,
    name: "Cara",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1780.webp",
    cutoutWidth: 480,
    cutoutHeight: 1017,
  },
  {
    id: 715,
    name: "Chanju News",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/715.webp",
    cutoutWidth: 480,
    cutoutHeight: 545,
  },
  {
    id: 1788,
    name: "Charles",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1788.webp",
    cutoutWidth: 480,
    cutoutHeight: 968,
  },
  {
    id: 1246,
    name: "Chiara",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1246.webp",
    cutoutWidth: 480,
    cutoutHeight: 547,
  },
  {
    id: 1049,
    name: "Col Health & Fitness",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1049.webp",
    cutoutWidth: 480,
    cutoutHeight: 503,
  },
  {
    id: 1139,
    name: "Dan Education",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1139.webp",
    cutoutWidth: 480,
    cutoutHeight: 435,
  },
  {
    id: 284,
    name: "David in Studio",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/284.webp",
    cutoutWidth: 476,
    cutoutHeight: 702,
  },
  {
    id: 1722,
    name: "Dennis",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1722.webp",
    cutoutWidth: 480,
    cutoutHeight: 421,
  },
  {
    id: 419,
    name: "Dentist Kevin",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/419.webp",
    cutoutWidth: 480,
    cutoutHeight: 691,
  },
  {
    id: 1208,
    name: "Diego",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1208.webp",
    cutoutWidth: 480,
    cutoutHeight: 846,
  },
  {
    id: 235,
    name: "Dr. Müller in the Hospital",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/235.webp",
    cutoutWidth: 480,
    cutoutHeight: 736,
  },
  {
    id: 1769,
    name: "Eden",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1769.webp",
    cutoutWidth: 480,
    cutoutHeight: 1103,
  },
  {
    id: 613,
    name: "Edward Health & Fitness",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/613.webp",
    cutoutWidth: 480,
    cutoutHeight: 550,
  },
  {
    id: 1686,
    name: "Eleanor",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1686.webp",
    cutoutWidth: 480,
    cutoutHeight: 829,
  },
  {
    id: 1687,
    name: "Ellie",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1687.webp",
    cutoutWidth: 480,
    cutoutHeight: 756,
  },
  {
    id: 1695,
    name: "Ellie",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1695.webp",
    cutoutWidth: 480,
    cutoutHeight: 747,
  },
  {
    id: 1854,
    name: "Eric",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1854.webp",
    cutoutWidth: 480,
    cutoutHeight: 869,
  },
  {
    id: 1790,
    name: "Fiona",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1790.webp",
    cutoutWidth: 480,
    cutoutHeight: 1153,
  },
  {
    id: 1764,
    name: "Georgia",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1764.webp",
    cutoutWidth: 480,
    cutoutHeight: 797,
  },
  {
    id: 1470,
    name: "Giulia",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1470.webp",
    cutoutWidth: 480,
    cutoutHeight: 636,
  },
  {
    id: 1800,
    name: "Grant",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1800.webp",
    cutoutWidth: 480,
    cutoutHeight: 675,
  },
  {
    id: 1201,
    name: "Harper",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1201.webp",
    cutoutWidth: 480,
    cutoutHeight: 701,
  },
  {
    id: 828,
    name: "Hazel Health & Fitness",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/828.webp",
    cutoutWidth: 480,
    cutoutHeight: 457,
  },
  {
    id: 1787,
    name: "Isabella",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1787.webp",
    cutoutWidth: 480,
    cutoutHeight: 1167,
  },
  {
    id: 768,
    name: "Jabari Education",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/768.webp",
    cutoutWidth: 480,
    cutoutHeight: 472,
  },
  {
    id: 1844,
    name: "Jade",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1844.webp",
    cutoutWidth: 480,
    cutoutHeight: 776,
  },
  {
    id: 1694,
    name: "James",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1694.webp",
    cutoutWidth: 480,
    cutoutHeight: 476,
  },
  {
    id: 1112,
    name: "Jim Business",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1112.webp",
    cutoutWidth: 480,
    cutoutHeight: 781,
  },
  {
    id: 1690,
    name: "John",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1690.webp",
    cutoutWidth: 480,
    cutoutHeight: 757,
  },
  {
    id: 861,
    name: "Jordan Health & Fitness",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/861.webp",
    cutoutWidth: 480,
    cutoutHeight: 562,
  },
  {
    id: 1782,
    name: "Joseph",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1782.webp",
    cutoutWidth: 480,
    cutoutHeight: 734,
  },
  {
    id: 1818,
    name: "Juliet",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1818.webp",
    cutoutWidth: 480,
    cutoutHeight: 923,
  },
  {
    id: 260,
    name: "Kai Playing",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/260.webp",
    cutoutWidth: 480,
    cutoutHeight: 745,
  },
  {
    id: 1728,
    name: "Keith",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1728.webp",
    cutoutWidth: 480,
    cutoutHeight: 811,
  },
  {
    id: 330,
    name: "Kofi's Relaxing",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/330.webp",
    cutoutWidth: 480,
    cutoutHeight: 736,
  },
  {
    id: 261,
    name: "Lars Creating",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/261.webp",
    cutoutWidth: 480,
    cutoutHeight: 719,
  },
  {
    id: 653,
    name: "Layla Education",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/653.webp",
    cutoutWidth: 480,
    cutoutHeight: 589,
  },
  {
    id: 1851,
    name: "Lily",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1851.webp",
    cutoutWidth: 480,
    cutoutHeight: 830,
  },
  {
    id: 1475,
    name: "Linda",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1475.webp",
    cutoutWidth: 480,
    cutoutHeight: 830,
  },
  {
    id: 1820,
    name: "Mabel",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1820.webp",
    cutoutWidth: 480,
    cutoutHeight: 1029,
  },
  {
    id: 1428,
    name: "Madison",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1428.webp",
    cutoutWidth: 480,
    cutoutHeight: 775,
  },
  {
    id: 1789,
    name: "Madison",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1789.webp",
    cutoutWidth: 480,
    cutoutHeight: 1042,
  },
  {
    id: 1477,
    name: "Maggie Business",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1477.webp",
    cutoutWidth: 480,
    cutoutHeight: 705,
  },
  {
    id: 1245,
    name: "Maja",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1245.webp",
    cutoutWidth: 480,
    cutoutHeight: 694,
  },
  {
    id: 1240,
    name: "Marco",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1240.webp",
    cutoutWidth: 480,
    cutoutHeight: 724,
  },
  {
    id: 1281,
    name: "Mark",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1281.webp",
    cutoutWidth: 480,
    cutoutHeight: 899,
  },
  {
    id: 1204,
    name: "Megan",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1204.webp",
    cutoutWidth: 480,
    cutoutHeight: 940,
  },
  {
    id: 1786,
    name: "Michelle",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1786.webp",
    cutoutWidth: 480,
    cutoutHeight: 1016,
  },
  {
    id: 1429,
    name: "Natalie",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1429.webp",
    cutoutWidth: 480,
    cutoutHeight: 817,
  },
  {
    id: 1213,
    name: "Nicole",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1213.webp",
    cutoutWidth: 480,
    cutoutHeight: 935,
  },
  {
    id: 1781,
    name: "Nora",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1781.webp",
    cutoutWidth: 480,
    cutoutHeight: 1108,
  },
  {
    id: 434,
    name: "Nurse Elowen",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/434.webp",
    cutoutWidth: 480,
    cutoutHeight: 796,
  },
  {
    id: 76,
    name: "Pablo Black T-shirt",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/76.webp",
    cutoutWidth: 480,
    cutoutHeight: 733,
  },
  {
    id: 393,
    name: "Raven Office Room",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/393.webp",
    cutoutWidth: 480,
    cutoutHeight: 538,
  },
  {
    id: 1091,
    name: "Samuel Business",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1091.webp",
    cutoutWidth: 480,
    cutoutHeight: 688,
  },
  {
    id: 1425,
    name: "Savannah",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1425.webp",
    cutoutWidth: 480,
    cutoutHeight: 802,
  },
  {
    id: 1770,
    name: "Scarlett",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1770.webp",
    cutoutWidth: 480,
    cutoutHeight: 1133,
  },
  {
    id: 395,
    name: "Seraphina Room",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/395.webp",
    cutoutWidth: 480,
    cutoutHeight: 313,
  },
  {
    id: 1427,
    name: "Skylar",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1427.webp",
    cutoutWidth: 480,
    cutoutHeight: 443,
  },
  {
    id: 989,
    name: "Sonia News",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/989.webp",
    cutoutWidth: 480,
    cutoutHeight: 503,
  },
  {
    id: 1772,
    name: "Susan",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1772.webp",
    cutoutWidth: 480,
    cutoutHeight: 1634,
  },
  {
    id: 1431,
    name: "Taylor",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1431.webp",
    cutoutWidth: 480,
    cutoutHeight: 655,
  },
  {
    id: 1791,
    name: "Tessa",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1791.webp",
    cutoutWidth: 480,
    cutoutHeight: 769,
  },
  {
    id: 1713,
    name: "Tiffany",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1713.webp",
    cutoutWidth: 480,
    cutoutHeight: 594,
  },
  {
    id: 953,
    name: "Timothy Business",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/953.webp",
    cutoutWidth: 480,
    cutoutHeight: 502,
  },
  {
    id: 1721,
    name: "Uma",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1721.webp",
    cutoutWidth: 480,
    cutoutHeight: 1021,
  },
  {
    id: 1834,
    name: "Vanessa",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1834.webp",
    cutoutWidth: 480,
    cutoutHeight: 918,
  },
  {
    id: 442,
    name: "Victoria in Gallery",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/442.webp",
    cutoutWidth: 480,
    cutoutHeight: 882,
  },
  {
    id: 1144,
    name: "Wendy",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1144.webp",
    cutoutWidth: 480,
    cutoutHeight: 542,
  },
  {
    id: 1833,
    name: "Wendy",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1833.webp",
    cutoutWidth: 480,
    cutoutHeight: 761,
  },
  {
    id: 1691,
    name: "William",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1691.webp",
    cutoutWidth: 480,
    cutoutHeight: 397,
  },
  {
    id: 1792,
    name: "William",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1792.webp",
    cutoutWidth: 480,
    cutoutHeight: 813,
  },
  {
    id: 1749,
    name: "Willow",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1749.webp",
    cutoutWidth: 480,
    cutoutHeight: 949,
  },
  {
    id: 1842,
    name: "Wren",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1842.webp",
    cutoutWidth: 480,
    cutoutHeight: 1208,
  },
  {
    id: 1220,
    name: "Yuki",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1220.webp",
    cutoutWidth: 480,
    cutoutHeight: 596,
  },
  {
    id: 1217,
    name: "Zainab",
    coverUrl: "https://static.vm0.io/platform/avatars/intro-video/v1/1217.webp",
    cutoutWidth: 480,
    cutoutHeight: 586,
  },
];
