/**
 * Build script for sandbox agent scripts
 *
 * Bundles TypeScript source files into self-contained JavaScript
 * that can be deployed and executed in E2B sandbox or Firecracker VM.
 *
 * Usage: pnpm build:scripts
 */
import * as esbuild from "esbuild";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DIST_DIR = path.join(__dirname, "dist");
const SRC_DIR = path.join(__dirname, "src");
const SCRIPTS_OUTPUT = path.join(__dirname, "scripts.ts");

/**
 * Entry points to bundle
 * Each becomes a standalone JavaScript file that can be executed with Node.js
 */
const ENTRY_POINTS = [
  { name: "run-agent", entry: "run-agent.ts", executable: true },
  { name: "mock-claude", entry: "mock-claude.ts", executable: true },
  { name: "download", entry: "lib/download.ts", executable: true },
];

/**
 * Escape backticks and backslashes for template literal embedding
 */
function escapeForTemplateLiteral(content: string): string {
  return content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

async function build(): Promise<void> {
  console.log("Building sandbox scripts...");

  // Create dist directory
  fs.mkdirSync(DIST_DIR, { recursive: true });

  const bundledScripts: Record<string, string> = {};

  // Bundle each entry point
  for (const { name, entry, executable } of ENTRY_POINTS) {
    const entryPath = path.join(SRC_DIR, entry);

    if (!fs.existsSync(entryPath)) {
      console.log(`  Skipping ${name} (${entryPath} not found)`);
      continue;
    }

    console.log(`  Bundling ${name}...`);

    const outfile = path.join(DIST_DIR, `${name}.js`);

    await esbuild.build({
      entryPoints: [entryPath],
      bundle: true,
      platform: "node",
      target: "node24",
      format: "esm",
      outfile,
      minify: false, // Keep readable for debugging
      sourcemap: false, // No source maps in sandbox
      banner: executable
        ? {
            js: "#!/usr/bin/env node",
          }
        : undefined,
    });

    // Read bundled content
    const content = fs.readFileSync(outfile, "utf-8");
    bundledScripts[name] = content;

    console.log(`    -> ${outfile} (${content.length} bytes)`);
  }

  // Generate scripts.ts with string constants
  console.log("Generating scripts.ts...");

  const scriptNames = Object.keys(bundledScripts);
  const exports: string[] = [];

  // Generate script constants
  for (const name of scriptNames) {
    const constName = name.toUpperCase().replace(/-/g, "_").concat("_SCRIPT");
    const content = bundledScripts[name];
    if (!content) {
      throw new Error(`Missing bundled script for ${name}`);
    }
    const escaped = escapeForTemplateLiteral(content);
    exports.push(`export const ${constName} = \`${escaped}\`;`);
  }

  // Generate SCRIPT_PATHS constant
  exports.push(`
/**
 * Script paths in the sandbox/VM
 * These are the paths where scripts will be deployed and executed
 */
export const SCRIPT_PATHS = {
  baseDir: "/usr/local/bin/vm0-agent",
  runAgent: "/usr/local/bin/vm0-agent/run-agent.js",
  mockClaude: "/usr/local/bin/vm0-agent/mock-claude.js",
  download: "/usr/local/bin/vm0-agent/download.js",
} as const;`);

  const output = `/**
 * Auto-generated sandbox script bundles
 * DO NOT EDIT - This file is generated by build.ts
 *
 * Run \`pnpm build:scripts\` to regenerate
 */

${exports.join("\n\n")}
`;

  fs.writeFileSync(SCRIPTS_OUTPUT, output);
  console.log(`  -> ${SCRIPTS_OUTPUT}`);

  console.log("Build complete!");
}

build().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});
