/**
 * Auto-generated sandbox script bundles
 * DO NOT EDIT - This file is generated by build.ts
 *
 * Run `pnpm build:scripts` to regenerate
 */

export const RUN_AGENT_SCRIPT = `#!/usr/bin/env node
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// src/sandbox/scripts/src/run-agent.ts
var fs6 = __toESM(require("fs"), 1);
var import_child_process4 = require("child_process");

// src/sandbox/scripts/src/lib/common.ts
var RUN_ID = process.env.VM0_RUN_ID ?? "";
var API_URL = process.env.VM0_API_URL ?? "";
var API_TOKEN = process.env.VM0_API_TOKEN ?? "";
var PROMPT = process.env.VM0_PROMPT ?? "";
var VERCEL_BYPASS = process.env.VERCEL_PROTECTION_BYPASS ?? "";
var RESUME_SESSION_ID = process.env.VM0_RESUME_SESSION_ID ?? "";
var CLI_AGENT_TYPE = process.env.CLI_AGENT_TYPE ?? "claude-code";
var OPENAI_MODEL = process.env.OPENAI_MODEL ?? "";
var WORKING_DIR = process.env.VM0_WORKING_DIR ?? "";
var ARTIFACT_DRIVER = process.env.VM0_ARTIFACT_DRIVER ?? "";
var ARTIFACT_MOUNT_PATH = process.env.VM0_ARTIFACT_MOUNT_PATH ?? "";
var ARTIFACT_VOLUME_NAME = process.env.VM0_ARTIFACT_VOLUME_NAME ?? "";
var ARTIFACT_VERSION_ID = process.env.VM0_ARTIFACT_VERSION_ID ?? "";
var WEBHOOK_URL = \`\${API_URL}/api/webhooks/agent/events\`;
var CHECKPOINT_URL = \`\${API_URL}/api/webhooks/agent/checkpoints\`;
var COMPLETE_URL = \`\${API_URL}/api/webhooks/agent/complete\`;
var HEARTBEAT_URL = \`\${API_URL}/api/webhooks/agent/heartbeat\`;
var TELEMETRY_URL = \`\${API_URL}/api/webhooks/agent/telemetry\`;
var PROXY_URL = \`\${API_URL}/api/webhooks/agent/proxy\`;
var STORAGE_PREPARE_URL = \`\${API_URL}/api/webhooks/agent/storages/prepare\`;
var STORAGE_COMMIT_URL = \`\${API_URL}/api/webhooks/agent/storages/commit\`;
var HEARTBEAT_INTERVAL = 60;
var TELEMETRY_INTERVAL = 30;
var HTTP_CONNECT_TIMEOUT = 10;
var HTTP_MAX_TIME = 30;
var HTTP_MAX_TIME_UPLOAD = 60;
var HTTP_MAX_RETRIES = 3;
var SESSION_ID_FILE = \`/tmp/vm0-session-\${RUN_ID}.txt\`;
var SESSION_HISTORY_PATH_FILE = \`/tmp/vm0-session-history-\${RUN_ID}.txt\`;
var EVENT_ERROR_FLAG = \`/tmp/vm0-event-error-\${RUN_ID}\`;
var SYSTEM_LOG_FILE = \`/tmp/vm0-main-\${RUN_ID}.log\`;
var AGENT_LOG_FILE = \`/tmp/vm0-agent-\${RUN_ID}.log\`;
var METRICS_LOG_FILE = \`/tmp/vm0-metrics-\${RUN_ID}.jsonl\`;
var NETWORK_LOG_FILE = \`/tmp/vm0-network-\${RUN_ID}.jsonl\`;
var TELEMETRY_LOG_POS_FILE = \`/tmp/vm0-telemetry-log-pos-\${RUN_ID}.txt\`;
var TELEMETRY_METRICS_POS_FILE = \`/tmp/vm0-telemetry-metrics-pos-\${RUN_ID}.txt\`;
var TELEMETRY_NETWORK_POS_FILE = \`/tmp/vm0-telemetry-network-pos-\${RUN_ID}.txt\`;
var METRICS_INTERVAL = 5;
function validateConfig() {
  if (!WORKING_DIR) {
    throw new Error("VM0_WORKING_DIR is required but not set");
  }
}

// src/sandbox/scripts/src/lib/log.ts
var SCRIPT_NAME = process.env.LOG_SCRIPT_NAME ?? "run-agent";
function getTimestamp() {
  return (/* @__PURE__ */ new Date()).toISOString().replace(/\\.\\d{3}Z$/, "Z");
}
function logInfo(msg) {
  console.error(\`[\${getTimestamp()}] [INFO] [sandbox:\${SCRIPT_NAME}] \${msg}\`);
}
function logWarn(msg) {
  console.error(\`[\${getTimestamp()}] [WARN] [sandbox:\${SCRIPT_NAME}] \${msg}\`);
}
function logError(msg) {
  console.error(\`[\${getTimestamp()}] [ERROR] [sandbox:\${SCRIPT_NAME}] \${msg}\`);
}
function logDebug(msg) {
  if (process.env.VM0_DEBUG === "1") {
    console.error(
      \`[\${getTimestamp()}] [DEBUG] [sandbox:\${SCRIPT_NAME}] \${msg}\`
    );
  }
}

// src/sandbox/scripts/src/lib/events.ts
var fs = __toESM(require("fs"), 1);

// src/sandbox/scripts/src/lib/http-client.ts
var import_child_process = require("child_process");
async function httpPostJson(url, data, maxRetries = HTTP_MAX_RETRIES) {
  const headers = {
    "Content-Type": "application/json",
    Authorization: \`Bearer \${API_TOKEN}\`
  };
  if (VERCEL_BYPASS) {
    headers["x-vercel-protection-bypass"] = VERCEL_BYPASS;
  }
  const body = JSON.stringify(data);
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    logDebug(\`HTTP POST attempt \${attempt}/\${maxRetries} to \${url}\`);
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(
        () => controller.abort(),
        HTTP_MAX_TIME * 1e3
      );
      const response = await fetch(url, {
        method: "POST",
        headers,
        body,
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      if (!response.ok) {
        logWarn(
          \`HTTP POST failed (attempt \${attempt}/\${maxRetries}): HTTP \${response.status}\`
        );
        if (attempt < maxRetries) {
          await sleep(1e3);
          continue;
        }
        return null;
      }
      const responseText = await response.text();
      if (responseText) {
        return JSON.parse(responseText);
      }
      return {};
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      if (errorMsg.includes("abort")) {
        logWarn(\`HTTP POST failed (attempt \${attempt}/\${maxRetries}): Timeout\`);
      } else {
        logWarn(
          \`HTTP POST failed (attempt \${attempt}/\${maxRetries}): \${errorMsg}\`
        );
      }
      if (attempt < maxRetries) {
        await sleep(1e3);
      }
    }
  }
  logError(\`HTTP POST failed after \${maxRetries} attempts to \${url}\`);
  return null;
}
function httpPutPresigned(presignedUrl, filePath, contentType = "application/octet-stream", maxRetries = HTTP_MAX_RETRIES) {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    logDebug(\`HTTP PUT presigned attempt \${attempt}/\${maxRetries}\`);
    try {
      const curlCmd = [
        "curl",
        "-f",
        "-X",
        "PUT",
        "-H",
        \`Content-Type: \${contentType}\`,
        "--data-binary",
        \`@\${filePath}\`,
        "--connect-timeout",
        String(HTTP_CONNECT_TIMEOUT),
        "--max-time",
        String(HTTP_MAX_TIME_UPLOAD),
        "--silent",
        \`"\${presignedUrl}"\`
      ];
      (0, import_child_process.execSync)(curlCmd.join(" "), {
        stdio: ["pipe", "pipe", "pipe"],
        timeout: HTTP_MAX_TIME_UPLOAD * 1e3,
        shell: "/bin/bash"
      });
      return true;
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      logWarn(
        \`HTTP PUT presigned failed (attempt \${attempt}/\${maxRetries}): \${errorMsg}\`
      );
      if (attempt < maxRetries) {
        sleepSync(1e3);
      }
    }
  }
  logError(\`HTTP PUT presigned failed after \${maxRetries} attempts\`);
  return false;
}
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function sleepSync(ms) {
  const end = Date.now() + ms;
  while (Date.now() < end) {
  }
}

// src/sandbox/scripts/src/lib/secret-masker.ts
var MASK_PLACEHOLDER = "***";
var MIN_SECRET_LENGTH = 5;
var _masker = null;
var SecretMasker = class {
  patterns;
  /**
   * Initialize masker with secret values.
   *
   * @param secretValues - List of secret values to mask
   */
  constructor(secretValues) {
    this.patterns = /* @__PURE__ */ new Set();
    for (const secret of secretValues) {
      if (!secret || secret.length < MIN_SECRET_LENGTH) {
        continue;
      }
      this.patterns.add(secret);
      try {
        const b64 = Buffer.from(secret).toString("base64");
        if (b64.length >= MIN_SECRET_LENGTH) {
          this.patterns.add(b64);
        }
      } catch {
      }
      try {
        const urlEnc = encodeURIComponent(secret);
        if (urlEnc !== secret && urlEnc.length >= MIN_SECRET_LENGTH) {
          this.patterns.add(urlEnc);
        }
      } catch {
      }
    }
  }
  /**
   * Recursively mask all occurrences of secrets in the data.
   *
   * @param data - Data to mask (string, array, object, or primitive)
   * @returns Masked data with the same structure
   */
  mask(data) {
    return this.deepMask(data);
  }
  deepMask(data) {
    if (typeof data === "string") {
      let result = data;
      for (const pattern of this.patterns) {
        result = result.split(pattern).join(MASK_PLACEHOLDER);
      }
      return result;
    }
    if (Array.isArray(data)) {
      return data.map((item) => this.deepMask(item));
    }
    if (data !== null && typeof data === "object") {
      const result = {};
      for (const [key, value] of Object.entries(data)) {
        result[key] = this.deepMask(value);
      }
      return result;
    }
    return data;
  }
};
function getMasker() {
  if (_masker === null) {
    _masker = createMasker();
  }
  return _masker;
}
function createMasker() {
  const secretValuesStr = process.env.VM0_SECRET_VALUES ?? "";
  if (!secretValuesStr) {
    return new SecretMasker([]);
  }
  const secretValues = [];
  for (const encodedValue of secretValuesStr.split(",")) {
    const trimmed = encodedValue.trim();
    if (trimmed) {
      try {
        const decoded = Buffer.from(trimmed, "base64").toString("utf-8");
        if (decoded) {
          secretValues.push(decoded);
        }
      } catch {
      }
    }
  }
  return new SecretMasker(secretValues);
}
function maskData(data) {
  return getMasker().mask(data);
}

// src/sandbox/scripts/src/lib/events.ts
async function sendEvent(event, sequenceNumber) {
  const eventType = event.type;
  const eventSubtype = event.subtype;
  let sessionId;
  if (CLI_AGENT_TYPE === "codex") {
    if (eventType === "thread.started") {
      sessionId = event.thread_id;
    }
  } else {
    if (eventType === "system" && eventSubtype === "init") {
      sessionId = event.session_id;
    }
  }
  if (sessionId && !fs.existsSync(SESSION_ID_FILE)) {
    logInfo(\`Captured session ID: \${sessionId}\`);
    fs.writeFileSync(SESSION_ID_FILE, sessionId);
    const homeDir = process.env.HOME ?? "/home/user";
    let sessionHistoryPath;
    if (CLI_AGENT_TYPE === "codex") {
      const codexHome = process.env.CODEX_HOME ?? \`\${homeDir}/.codex\`;
      sessionHistoryPath = \`CODEX_SEARCH:\${codexHome}/sessions:\${sessionId}\`;
    } else {
      const projectName = WORKING_DIR.replace(/^\\//, "").replace(/\\//g, "-");
      sessionHistoryPath = \`\${homeDir}/.claude/projects/-\${projectName}/\${sessionId}.jsonl\`;
    }
    fs.writeFileSync(SESSION_HISTORY_PATH_FILE, sessionHistoryPath);
    logInfo(\`Session history will be at: \${sessionHistoryPath}\`);
  }
  const eventWithSequence = { ...event, sequenceNumber };
  const maskedEvent = maskData(eventWithSequence);
  const payload = {
    runId: RUN_ID,
    events: [maskedEvent]
  };
  const result = await httpPostJson(WEBHOOK_URL, payload);
  if (result === null) {
    logError("Failed to send event after retries");
    fs.writeFileSync(EVENT_ERROR_FLAG, "1");
    return false;
  }
  return true;
}

// src/sandbox/scripts/src/lib/checkpoint.ts
var fs3 = __toESM(require("fs"), 1);
var path2 = __toESM(require("path"), 1);

// src/sandbox/scripts/src/lib/direct-upload.ts
var fs2 = __toESM(require("fs"), 1);
var path = __toESM(require("path"), 1);
var crypto = __toESM(require("crypto"), 1);
var import_child_process2 = require("child_process");
function computeFileHash(filePath) {
  const hash = crypto.createHash("sha256");
  const content = fs2.readFileSync(filePath);
  hash.update(content);
  return hash.digest("hex");
}
function collectFileMetadata(dirPath) {
  const files = [];
  const originalDir = process.cwd();
  try {
    process.chdir(dirPath);
    const walkDir = (dir) => {
      const entries = fs2.readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        if (entry.isDirectory()) {
          if (entry.name !== ".git" && entry.name !== ".vm0") {
            walkDir(path.join(dir, entry.name));
          }
          continue;
        }
        if (entry.isFile()) {
          let relPath = path.join(dir, entry.name);
          if (relPath.startsWith("./")) {
            relPath = relPath.slice(2);
          }
          const fullPath = path.join(dirPath, relPath);
          try {
            const fileHash = computeFileHash(fullPath);
            const fileSize = fs2.statSync(fullPath).size;
            files.push({
              path: relPath,
              hash: fileHash,
              size: fileSize
            });
          } catch (err) {
            logWarn(\`Could not process file \${relPath}: \${err}\`);
          }
        }
      }
    };
    walkDir(".");
  } finally {
    process.chdir(originalDir);
  }
  return files;
}
function createArchive(dirPath, tarPath) {
  const originalDir = process.cwd();
  try {
    process.chdir(dirPath);
    const items = fs2.readdirSync(".").filter((item) => item !== ".git" && item !== ".vm0");
    if (items.length === 0) {
      (0, import_child_process2.execSync)(\`tar czf "\${tarPath}" --files-from /dev/null\`, {
        stdio: ["pipe", "pipe", "pipe"]
      });
    } else {
      const itemsStr = items.map((i) => \`"\${i}"\`).join(" ");
      (0, import_child_process2.execSync)(\`tar czf "\${tarPath}" \${itemsStr}\`, {
        stdio: ["pipe", "pipe", "pipe"],
        shell: "/bin/bash"
      });
    }
    return true;
  } catch (err) {
    logError(\`Failed to create archive: \${err}\`);
    return false;
  } finally {
    process.chdir(originalDir);
  }
}
function createManifest(files, manifestPath) {
  try {
    const manifest = {
      version: 1,
      files,
      createdAt: (/* @__PURE__ */ new Date()).toISOString()
    };
    fs2.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
    return true;
  } catch (err) {
    logError(\`Failed to create manifest: \${err}\`);
    return false;
  }
}
async function createDirectUploadSnapshot(mountPath, storageName, storageType = "artifact", runId, message) {
  logInfo(
    \`Creating direct upload snapshot for '\${storageName}' (type: \${storageType})\`
  );
  logInfo("Computing file hashes...");
  const files = collectFileMetadata(mountPath);
  logInfo(\`Found \${files.length} files\`);
  if (files.length === 0) {
    logInfo("No files to upload, creating empty version");
  }
  logInfo("Calling prepare endpoint...");
  const preparePayload = {
    storageName,
    storageType,
    files
  };
  if (runId) {
    preparePayload.runId = runId;
  }
  const prepareResponse = await httpPostJson(
    STORAGE_PREPARE_URL,
    preparePayload
  );
  if (!prepareResponse) {
    logError("Failed to call prepare endpoint");
    return null;
  }
  const versionId = prepareResponse.versionId;
  if (!versionId) {
    logError(\`Invalid prepare response: \${JSON.stringify(prepareResponse)}\`);
    return null;
  }
  if (prepareResponse.existing) {
    logInfo(\`Version already exists (deduplicated): \${versionId.slice(0, 8)}\`);
    logInfo("Updating HEAD pointer...");
    const commitPayload = {
      storageName,
      storageType,
      versionId,
      files
    };
    if (runId) {
      commitPayload.runId = runId;
    }
    const commitResponse = await httpPostJson(
      STORAGE_COMMIT_URL,
      commitPayload
    );
    if (!commitResponse || !commitResponse.success) {
      logError(\`Failed to update HEAD: \${JSON.stringify(commitResponse)}\`);
      return null;
    }
    return { versionId, deduplicated: true };
  }
  const uploads = prepareResponse.uploads;
  if (!uploads) {
    logError("No upload URLs in prepare response");
    return null;
  }
  const archiveInfo = uploads.archive;
  const manifestInfo = uploads.manifest;
  if (!archiveInfo || !manifestInfo) {
    logError("Missing archive or manifest upload info");
    return null;
  }
  const tempDir = \`/tmp/direct-upload-\${storageName}-\${Date.now()}\`;
  fs2.mkdirSync(tempDir, { recursive: true });
  try {
    logInfo("Creating archive...");
    const archivePath = path.join(tempDir, "archive.tar.gz");
    if (!createArchive(mountPath, archivePath)) {
      logError("Failed to create archive");
      return null;
    }
    logInfo("Creating manifest...");
    const manifestPath = path.join(tempDir, "manifest.json");
    if (!createManifest(files, manifestPath)) {
      logError("Failed to create manifest");
      return null;
    }
    logInfo("Uploading archive to S3...");
    if (!httpPutPresigned(
      archiveInfo.presignedUrl,
      archivePath,
      "application/gzip"
    )) {
      logError("Failed to upload archive to S3");
      return null;
    }
    logInfo("Uploading manifest to S3...");
    if (!httpPutPresigned(
      manifestInfo.presignedUrl,
      manifestPath,
      "application/json"
    )) {
      logError("Failed to upload manifest to S3");
      return null;
    }
    logInfo("Calling commit endpoint...");
    const commitPayload = {
      storageName,
      storageType,
      versionId,
      files
    };
    if (runId) {
      commitPayload.runId = runId;
    }
    if (message) {
      commitPayload.message = message;
    }
    const commitResponse = await httpPostJson(
      STORAGE_COMMIT_URL,
      commitPayload
    );
    if (!commitResponse) {
      logError("Failed to call commit endpoint");
      return null;
    }
    if (!commitResponse.success) {
      logError(\`Commit failed: \${JSON.stringify(commitResponse)}\`);
      return null;
    }
    logInfo(\`Direct upload snapshot created: \${versionId.slice(0, 8)}\`);
    return { versionId };
  } finally {
    try {
      fs2.rmSync(tempDir, { recursive: true, force: true });
    } catch {
    }
  }
}

// src/sandbox/scripts/src/lib/checkpoint.ts
function findCodexSessionFile(sessionsDir, sessionId) {
  const files = findFilesRecursive(sessionsDir, ".jsonl");
  logInfo(\`Searching for Codex session \${sessionId} in \${files.length} files\`);
  for (const filepath of files) {
    const filename = path2.basename(filepath);
    if (filename.includes(sessionId) || filename.replace(/-/g, "").includes(sessionId.replace(/-/g, ""))) {
      logInfo(\`Found Codex session file: \${filepath}\`);
      return filepath;
    }
  }
  if (files.length > 0) {
    files.sort((a, b) => {
      const statA = fs3.statSync(a);
      const statB = fs3.statSync(b);
      return statB.mtimeMs - statA.mtimeMs;
    });
    const mostRecent = files[0] ?? null;
    if (mostRecent) {
      logInfo(
        \`Session ID not found in filenames, using most recent: \${mostRecent}\`
      );
    }
    return mostRecent;
  }
  return null;
}
function findFilesRecursive(dir, ext) {
  const results = [];
  if (!fs3.existsSync(dir)) {
    return results;
  }
  const entries = fs3.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path2.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findFilesRecursive(fullPath, ext));
    } else if (entry.isFile() && entry.name.endsWith(ext)) {
      results.push(fullPath);
    }
  }
  return results;
}
async function createCheckpoint() {
  logInfo("Creating checkpoint...");
  if (!fs3.existsSync(SESSION_ID_FILE)) {
    logError("No session ID found, checkpoint creation failed");
    return false;
  }
  const cliAgentSessionId = fs3.readFileSync(SESSION_ID_FILE, "utf-8").trim();
  if (!fs3.existsSync(SESSION_HISTORY_PATH_FILE)) {
    logError("No session history path found, checkpoint creation failed");
    return false;
  }
  const sessionHistoryPathRaw = fs3.readFileSync(SESSION_HISTORY_PATH_FILE, "utf-8").trim();
  let sessionHistoryPath;
  if (sessionHistoryPathRaw.startsWith("CODEX_SEARCH:")) {
    const parts = sessionHistoryPathRaw.split(":");
    if (parts.length !== 3) {
      logError(\`Invalid Codex search marker format: \${sessionHistoryPathRaw}\`);
      return false;
    }
    const sessionsDir = parts[1];
    const codexSessionId = parts[2];
    logInfo(\`Searching for Codex session in \${sessionsDir}\`);
    const foundPath = findCodexSessionFile(sessionsDir, codexSessionId);
    if (!foundPath) {
      logError(
        \`Could not find Codex session file for \${codexSessionId} in \${sessionsDir}\`
      );
      return false;
    }
    sessionHistoryPath = foundPath;
  } else {
    sessionHistoryPath = sessionHistoryPathRaw;
  }
  if (!fs3.existsSync(sessionHistoryPath)) {
    logError(
      \`Session history file not found at \${sessionHistoryPath}, checkpoint creation failed\`
    );
    return false;
  }
  let cliAgentSessionHistory;
  try {
    cliAgentSessionHistory = fs3.readFileSync(sessionHistoryPath, "utf-8");
  } catch (err) {
    logError(\`Failed to read session history: \${err}\`);
    return false;
  }
  if (!cliAgentSessionHistory.trim()) {
    logError("Session history is empty, checkpoint creation failed");
    return false;
  }
  const lineCount = cliAgentSessionHistory.trim().split("\\n").length;
  logInfo(\`Session history loaded (\${lineCount} lines)\`);
  const cliAgentType = CLI_AGENT_TYPE;
  let artifactSnapshot = null;
  if (ARTIFACT_DRIVER && ARTIFACT_VOLUME_NAME) {
    logInfo(\`Processing artifact with driver: \${ARTIFACT_DRIVER}\`);
    if (ARTIFACT_DRIVER !== "vas") {
      logError(
        \`Unknown artifact driver: \${ARTIFACT_DRIVER} (only 'vas' is supported)\`
      );
      return false;
    }
    logInfo(
      \`Creating VAS snapshot for artifact '\${ARTIFACT_VOLUME_NAME}' at \${ARTIFACT_MOUNT_PATH}\`
    );
    logInfo("Using direct S3 upload...");
    const snapshot = await createDirectUploadSnapshot(
      ARTIFACT_MOUNT_PATH,
      ARTIFACT_VOLUME_NAME,
      "artifact",
      RUN_ID,
      \`Checkpoint from run \${RUN_ID}\`
    );
    if (!snapshot) {
      logError("Failed to create VAS snapshot for artifact");
      return false;
    }
    const artifactVersion = snapshot.versionId;
    if (!artifactVersion) {
      logError("Failed to extract versionId from snapshot");
      return false;
    }
    artifactSnapshot = {
      artifactName: ARTIFACT_VOLUME_NAME,
      artifactVersion
    };
    logInfo(
      \`VAS artifact snapshot created: \${ARTIFACT_VOLUME_NAME}@\${artifactVersion}\`
    );
  } else {
    logInfo(
      "No artifact configured, creating checkpoint without artifact snapshot"
    );
  }
  logInfo("Calling checkpoint API...");
  const checkpointPayload = {
    runId: RUN_ID,
    cliAgentType,
    cliAgentSessionId,
    cliAgentSessionHistory
  };
  if (artifactSnapshot) {
    checkpointPayload.artifactSnapshot = artifactSnapshot;
  }
  const result = await httpPostJson(CHECKPOINT_URL, checkpointPayload);
  if (result && result.checkpointId) {
    const checkpointId = result.checkpointId;
    logInfo(\`Checkpoint created successfully: \${checkpointId}\`);
    return true;
  } else {
    logError(
      \`Checkpoint API returned invalid response: \${JSON.stringify(result)}\`
    );
    return false;
  }
}

// src/sandbox/scripts/src/lib/metrics.ts
var fs4 = __toESM(require("fs"), 1);
var import_child_process3 = require("child_process");
function getCpuPercent() {
  try {
    const content = fs4.readFileSync("/proc/stat", "utf-8");
    const line = content.split("\\n")[0];
    if (!line) {
      return 0;
    }
    const parts = line.split(/\\s+/);
    if (parts[0] !== "cpu") {
      return 0;
    }
    const values = parts.slice(1).map((x) => parseInt(x, 10));
    const idle = (values[3] ?? 0) + (values[4] ?? 0);
    const total = values.reduce((a, b) => a + b, 0);
    if (total === 0) {
      return 0;
    }
    const cpuPercent = 100 * (1 - idle / total);
    return Math.round(cpuPercent * 100) / 100;
  } catch (e) {
    logDebug(\`Failed to get CPU percent: \${e}\`);
    return 0;
  }
}
function getMemoryInfo() {
  try {
    const result = (0, import_child_process3.execSync)("free -b", {
      encoding: "utf-8",
      timeout: 5e3,
      stdio: ["pipe", "pipe", "pipe"]
    });
    const lines = result.trim().split("\\n");
    for (const line of lines) {
      if (line.startsWith("Mem:")) {
        const parts = line.split(/\\s+/);
        const total = parseInt(parts[1] ?? "0", 10);
        const used = parseInt(parts[2] ?? "0", 10);
        return [used, total];
      }
    }
    return [0, 0];
  } catch (e) {
    logDebug(\`Failed to get memory info: \${e}\`);
    return [0, 0];
  }
}
function getDiskInfo() {
  try {
    const result = (0, import_child_process3.execSync)("df -B1 /", {
      encoding: "utf-8",
      timeout: 5e3,
      stdio: ["pipe", "pipe", "pipe"]
    });
    const lines = result.trim().split("\\n");
    if (lines.length < 2) {
      return [0, 0];
    }
    const dataLine = lines[1];
    if (!dataLine) {
      return [0, 0];
    }
    const parts = dataLine.split(/\\s+/);
    const total = parseInt(parts[1] ?? "0", 10);
    const used = parseInt(parts[2] ?? "0", 10);
    return [used, total];
  } catch (e) {
    logDebug(\`Failed to get disk info: \${e}\`);
    return [0, 0];
  }
}
function collectMetrics() {
  const cpu = getCpuPercent();
  const [memUsed, memTotal] = getMemoryInfo();
  const [diskUsed, diskTotal] = getDiskInfo();
  return {
    ts: (/* @__PURE__ */ new Date()).toISOString().replace(/\\.\\d{3}Z$/, "Z"),
    cpu,
    mem_used: memUsed,
    mem_total: memTotal,
    disk_used: diskUsed,
    disk_total: diskTotal
  };
}
var shutdownRequested = false;
function requestShutdown() {
  shutdownRequested = true;
}
function isShutdownRequested() {
  return shutdownRequested;
}
function metricsCollectorLoop() {
  logInfo(\`Metrics collector started, writing to \${METRICS_LOG_FILE}\`);
  const collectAndWrite = () => {
    if (shutdownRequested) {
      logInfo("Metrics collector stopped");
      return;
    }
    try {
      const metrics = collectMetrics();
      fs4.appendFileSync(METRICS_LOG_FILE, JSON.stringify(metrics) + "\\n");
      logDebug(
        \`Metrics collected: cpu=\${metrics.cpu}%, mem=\${metrics.mem_used}/\${metrics.mem_total}\`
      );
    } catch (e) {
      logError(\`Failed to collect/write metrics: \${e}\`);
    }
    if (!shutdownRequested) {
      setTimeout(collectAndWrite, METRICS_INTERVAL * 1e3);
    }
  };
  collectAndWrite();
}
function startMetricsCollector() {
  shutdownRequested = false;
  setImmediate(() => {
    metricsCollectorLoop();
  });
}

// src/sandbox/scripts/src/lib/upload-telemetry.ts
var fs5 = __toESM(require("fs"), 1);
function readFileFromPosition(filePath, posFile) {
  let lastPos = 0;
  if (fs5.existsSync(posFile)) {
    try {
      lastPos = parseInt(fs5.readFileSync(posFile, "utf-8").trim(), 10);
    } catch {
      lastPos = 0;
    }
  }
  let newContent = "";
  let newPos = lastPos;
  if (fs5.existsSync(filePath)) {
    try {
      const fd = fs5.openSync(filePath, "r");
      try {
        const stats = fs5.fstatSync(fd);
        const bytesToRead = stats.size - lastPos;
        if (bytesToRead > 0) {
          const buffer = Buffer.alloc(bytesToRead);
          fs5.readSync(fd, buffer, 0, bytesToRead, lastPos);
          newContent = buffer.toString("utf-8");
          newPos = stats.size;
        }
      } finally {
        fs5.closeSync(fd);
      }
    } catch (e) {
      logDebug(\`Failed to read \${filePath}: \${e}\`);
    }
  }
  return [newContent, newPos];
}
function savePosition(posFile, position) {
  try {
    fs5.writeFileSync(posFile, String(position));
  } catch (e) {
    logDebug(\`Failed to save position to \${posFile}: \${e}\`);
  }
}
function readJsonlFromPosition(filePath, posFile) {
  const [content, newPos] = readFileFromPosition(filePath, posFile);
  const entries = [];
  if (content) {
    for (const line of content.trim().split("\\n")) {
      if (line) {
        try {
          entries.push(JSON.parse(line));
        } catch {
        }
      }
    }
  }
  return [entries, newPos];
}
function readMetricsFromPosition(posFile) {
  return readJsonlFromPosition(METRICS_LOG_FILE, posFile);
}
function readNetworkLogsFromPosition(posFile) {
  return readJsonlFromPosition(NETWORK_LOG_FILE, posFile);
}
async function uploadTelemetry() {
  const [systemLog, logPos] = readFileFromPosition(
    SYSTEM_LOG_FILE,
    TELEMETRY_LOG_POS_FILE
  );
  const [metrics, metricsPos] = readMetricsFromPosition(
    TELEMETRY_METRICS_POS_FILE
  );
  const [networkLogs, networkPos] = readNetworkLogsFromPosition(
    TELEMETRY_NETWORK_POS_FILE
  );
  if (!systemLog && metrics.length === 0 && networkLogs.length === 0) {
    logDebug("No new telemetry data to upload");
    return true;
  }
  const maskedSystemLog = systemLog ? maskData(systemLog) : "";
  const maskedNetworkLogs = networkLogs.length > 0 ? maskData(networkLogs) : [];
  const payload = {
    runId: RUN_ID,
    systemLog: maskedSystemLog,
    metrics,
    // Metrics don't contain secrets (just numbers)
    networkLogs: maskedNetworkLogs
  };
  logDebug(
    \`Uploading telemetry: \${systemLog.length} bytes log, \${metrics.length} metrics, \${networkLogs.length} network logs\`
  );
  const result = await httpPostJson(TELEMETRY_URL, payload, 1);
  if (result) {
    savePosition(TELEMETRY_LOG_POS_FILE, logPos);
    savePosition(TELEMETRY_METRICS_POS_FILE, metricsPos);
    savePosition(TELEMETRY_NETWORK_POS_FILE, networkPos);
    logDebug(
      \`Telemetry uploaded successfully: \${result.id ?? "unknown"}\`
    );
    return true;
  } else {
    logWarn("Failed to upload telemetry (will retry next interval)");
    return false;
  }
}
function telemetryUploadLoop() {
  logInfo(\`Telemetry upload started (interval: \${TELEMETRY_INTERVAL}s)\`);
  const uploadAndSchedule = () => {
    if (isShutdownRequested()) {
      logInfo("Telemetry upload stopped");
      return;
    }
    uploadTelemetry().catch((e) => {
      logError(\`Telemetry upload error: \${e}\`);
    });
    if (!isShutdownRequested()) {
      setTimeout(uploadAndSchedule, TELEMETRY_INTERVAL * 1e3);
    }
  };
  setTimeout(uploadAndSchedule, TELEMETRY_INTERVAL * 1e3);
}
function startTelemetryUpload() {
  setImmediate(() => {
    telemetryUploadLoop();
  });
}
async function finalTelemetryUpload() {
  logInfo("Performing final telemetry upload...");
  return uploadTelemetry();
}

// src/sandbox/scripts/src/run-agent.ts
var heartbeatShouldStop = false;
function heartbeatLoop() {
  const sendHeartbeat = async () => {
    if (heartbeatShouldStop) {
      return;
    }
    try {
      const result = await httpPostJson(HEARTBEAT_URL, { runId: RUN_ID });
      if (result) {
        logInfo("Heartbeat sent");
      } else {
        logWarn("Heartbeat failed");
      }
    } catch (e) {
      logWarn(\`Heartbeat error: \${e}\`);
    }
    if (!heartbeatShouldStop) {
      setTimeout(() => void sendHeartbeat(), HEARTBEAT_INTERVAL * 1e3);
    }
  };
  setTimeout(() => void sendHeartbeat(), HEARTBEAT_INTERVAL * 1e3);
}
async function cleanup(exitCode, errorMessage) {
  logInfo("\\u25B7 Cleanup");
  try {
    await finalTelemetryUpload();
  } catch (e) {
    logError(\`Final telemetry upload failed: \${e}\`);
  }
  logInfo(\`Calling complete API with exitCode=\${exitCode}\`);
  const completePayload = {
    runId: RUN_ID,
    exitCode
  };
  if (errorMessage) {
    completePayload.error = errorMessage;
  }
  try {
    const result = await httpPostJson(COMPLETE_URL, completePayload);
    if (result) {
      logInfo("Complete API called successfully");
    } else {
      logError("Failed to call complete API (sandbox may not be cleaned up)");
    }
  } catch (e) {
    logError(\`Complete API call failed: \${e}\`);
  }
  heartbeatShouldStop = true;
  requestShutdown();
  logInfo("Background threads stopped");
  if (exitCode === 0) {
    logInfo("\\u2713 Sandbox finished successfully");
  } else {
    logInfo(\`\\u2717 Sandbox failed (exit code \${exitCode})\`);
  }
}
async function run() {
  validateConfig();
  logInfo(\`\\u25B6 VM0 Sandbox \${RUN_ID}\`);
  logInfo("\\u25B7 Initialization");
  const initStartTime = Date.now();
  logInfo(\`Working directory: \${WORKING_DIR}\`);
  heartbeatLoop();
  logInfo("Heartbeat thread started");
  startMetricsCollector();
  logInfo("Metrics collector thread started");
  startTelemetryUpload();
  logInfo("Telemetry upload thread started");
  try {
    fs6.mkdirSync(WORKING_DIR, { recursive: true });
    process.chdir(WORKING_DIR);
  } catch (e) {
    throw new Error(
      \`Failed to create/change to working directory: \${WORKING_DIR} - \${e}\`
    );
  }
  if (CLI_AGENT_TYPE === "codex") {
    const homeDir = process.env.HOME ?? "/home/user";
    const codexHome = \`\${homeDir}/.codex\`;
    fs6.mkdirSync(codexHome, { recursive: true });
    process.env.CODEX_HOME = codexHome;
    logInfo(\`Codex home directory: \${codexHome}\`);
    const apiKey = process.env.OPENAI_API_KEY ?? "";
    if (apiKey) {
      const { execSync: execSync4 } = await import("child_process");
      try {
        execSync4("codex login --with-api-key", {
          input: apiKey,
          encoding: "utf-8",
          stdio: ["pipe", "pipe", "pipe"]
        });
        logInfo("Codex authenticated with API key");
      } catch (e) {
        logError(\`Codex login failed: \${e}\`);
      }
    } else {
      logError("OPENAI_API_KEY not set");
    }
  }
  const initDuration = Math.floor((Date.now() - initStartTime) / 1e3);
  logInfo(\`\\u2713 Initialization complete (\${initDuration}s)\`);
  logInfo("\\u25B7 Execution");
  const execStartTime = Date.now();
  logInfo(\`Starting \${CLI_AGENT_TYPE} execution...\`);
  logInfo(\`Prompt: \${PROMPT}\`);
  const useMock = process.env.USE_MOCK_CLAUDE === "true";
  let cmd;
  let args;
  if (CLI_AGENT_TYPE === "codex") {
    if (useMock) {
      throw new Error("Mock mode not supported for Codex");
    }
    cmd = "codex";
    args = [
      "exec",
      "--json",
      "--dangerously-bypass-approvals-and-sandbox",
      "--skip-git-repo-check",
      "-C",
      WORKING_DIR
    ];
    if (OPENAI_MODEL) {
      args.push("-m", OPENAI_MODEL);
    }
    if (RESUME_SESSION_ID) {
      logInfo(\`Resuming session: \${RESUME_SESSION_ID}\`);
      args.push("resume", RESUME_SESSION_ID, PROMPT);
    } else {
      logInfo("Starting new session");
      args.push(PROMPT);
    }
  } else {
    args = [
      "--print",
      "--verbose",
      "--output-format",
      "stream-json",
      "--dangerously-skip-permissions"
    ];
    if (RESUME_SESSION_ID) {
      logInfo(\`Resuming session: \${RESUME_SESSION_ID}\`);
      args.push("--resume", RESUME_SESSION_ID);
    } else {
      logInfo("Starting new session");
    }
    if (useMock) {
      cmd = "/usr/local/bin/vm0-agent/mock-claude.js";
      logInfo("Using mock-claude for testing");
    } else {
      cmd = "claude";
    }
    args.push(PROMPT);
  }
  let agentExitCode = 0;
  const stderrLines = [];
  let logFile = null;
  try {
    logFile = fs6.createWriteStream(AGENT_LOG_FILE);
    const proc = (0, import_child_process4.spawn)(cmd, args, {
      cwd: WORKING_DIR,
      stdio: ["pipe", "pipe", "pipe"]
    });
    let eventSequence = 0;
    let stdoutBuffer = "";
    proc.stdout.on("data", (chunk) => {
      const text = chunk.toString();
      logFile?.write(text);
      stdoutBuffer += text;
      const lines = stdoutBuffer.split("\\n");
      stdoutBuffer = lines.pop() ?? "";
      for (const line of lines) {
        const stripped = line.trim();
        if (!stripped) continue;
        try {
          const event = JSON.parse(stripped);
          eventSequence += 1;
          sendEvent(event, eventSequence).catch(() => {
          });
          if (event.type === "result") {
            const resultContent = event.result;
            if (resultContent) {
              console.log(resultContent);
            }
          }
        } catch {
        }
      }
    });
    proc.stderr.on("data", (chunk) => {
      const text = chunk.toString();
      logFile?.write(\`[STDERR] \${text}\`);
      stderrLines.push(text);
    });
    agentExitCode = await new Promise((resolve) => {
      proc.on("close", (code) => {
        resolve(code ?? 1);
      });
      proc.on("error", (err) => {
        logError(\`Failed to execute \${CLI_AGENT_TYPE}: \${err}\`);
        resolve(1);
      });
    });
  } finally {
    if (logFile) {
      logFile.end();
    }
  }
  console.log();
  let finalExitCode = agentExitCode;
  let errorMessage = "";
  if (fs6.existsSync(EVENT_ERROR_FLAG)) {
    logError("Some events failed to send, marking run as failed");
    finalExitCode = 1;
    errorMessage = "Some events failed to send";
  }
  const execDuration = Math.floor((Date.now() - execStartTime) / 1e3);
  if (agentExitCode === 0 && finalExitCode === 0) {
    logInfo(\`\\u2713 Execution complete (\${execDuration}s)\`);
  } else {
    logInfo(\`\\u2717 Execution failed (\${execDuration}s)\`);
  }
  if (agentExitCode === 0 && finalExitCode === 0) {
    logInfo(\`\${CLI_AGENT_TYPE} completed successfully\`);
    logInfo("\\u25B7 Checkpoint");
    const checkpointStartTime = Date.now();
    const checkpointSuccess = await createCheckpoint();
    const checkpointDuration = Math.floor(
      (Date.now() - checkpointStartTime) / 1e3
    );
    if (checkpointSuccess) {
      logInfo(\`\\u2713 Checkpoint complete (\${checkpointDuration}s)\`);
    } else {
      logInfo(\`\\u2717 Checkpoint failed (\${checkpointDuration}s)\`);
    }
    if (!checkpointSuccess) {
      logError("Checkpoint creation failed, marking run as failed");
      finalExitCode = 1;
      errorMessage = "Checkpoint creation failed";
    }
  } else {
    if (agentExitCode !== 0) {
      logInfo(\`\${CLI_AGENT_TYPE} failed with exit code \${agentExitCode}\`);
      if (stderrLines.length > 0) {
        errorMessage = stderrLines.map((line) => line.trim()).join(" ");
        logInfo(\`Captured stderr: \${errorMessage}\`);
      } else {
        errorMessage = \`Agent exited with code \${agentExitCode}\`;
      }
    }
  }
  return [finalExitCode, errorMessage];
}
async function main() {
  let exitCode = 1;
  let errorMessage = "Unexpected termination";
  try {
    [exitCode, errorMessage] = await run();
  } catch (e) {
    if (e instanceof Error) {
      exitCode = 1;
      errorMessage = e.message;
      logError(\`Error: \${errorMessage}\`);
    } else {
      exitCode = 1;
      errorMessage = \`Unexpected error: \${e}\`;
      logError(errorMessage);
    }
  } finally {
    await cleanup(exitCode, errorMessage);
  }
  return exitCode;
}
main().then((code) => {
  process.exit(code);
}).catch((e) => {
  console.error("Fatal error:", e);
  process.exit(1);
});
`;

export const MOCK_CLAUDE_SCRIPT = `#!/usr/bin/env node
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// src/sandbox/scripts/src/mock-claude.ts
var fs = __toESM(require("fs"), 1);
var path = __toESM(require("path"), 1);
var import_child_process = require("child_process");
function createSessionHistory(sessionId, cwd) {
  const projectName = cwd.replace(/^\\//, "").replace(/\\//g, "-");
  const homeDir = process.env.HOME ?? "/home/user";
  const sessionDir = \`\${homeDir}/.claude/projects/-\${projectName}\`;
  fs.mkdirSync(sessionDir, { recursive: true });
  return path.join(sessionDir, \`\${sessionId}.jsonl\`);
}
function parseArgs() {
  const args = process.argv.slice(2);
  const result = {
    outputFormat: "text",
    print: false,
    verbose: false,
    dangerouslySkipPermissions: false,
    resume: null,
    prompt: ""
  };
  let i = 0;
  while (i < args.length) {
    const arg = args[i];
    if (!arg) {
      i += 1;
      continue;
    }
    if (arg === "--output-format" && i + 1 < args.length) {
      result.outputFormat = args[i + 1] ?? "text";
      i += 2;
    } else if (arg === "--print") {
      result.print = true;
      i += 1;
    } else if (arg === "--verbose") {
      result.verbose = true;
      i += 1;
    } else if (arg === "--dangerously-skip-permissions") {
      result.dangerouslySkipPermissions = true;
      i += 1;
    } else if (arg === "--resume" && i + 1 < args.length) {
      result.resume = args[i + 1] ?? null;
      i += 2;
    } else if (!arg.startsWith("-")) {
      result.prompt = arg;
      i += 1;
    } else {
      i += 1;
    }
  }
  return result;
}
async function main() {
  const sessionId = \`mock-\${Date.now()}\`;
  const args = parseArgs();
  const prompt = args.prompt;
  const outputFormat = args.outputFormat;
  if (prompt.startsWith("@fail:")) {
    const errorMsg = prompt.slice(6);
    console.error(errorMsg);
    process.exit(1);
  }
  const cwd = process.cwd();
  if (outputFormat === "stream-json") {
    const sessionHistoryFile = createSessionHistory(sessionId, cwd);
    const events = [];
    const initEvent = {
      type: "system",
      subtype: "init",
      cwd,
      session_id: sessionId,
      tools: ["Bash"],
      model: "mock-claude"
    };
    console.log(JSON.stringify(initEvent));
    events.push(initEvent);
    const textEvent = {
      type: "assistant",
      message: {
        role: "assistant",
        content: [{ type: "text", text: "Executing command..." }]
      },
      session_id: sessionId
    };
    console.log(JSON.stringify(textEvent));
    events.push(textEvent);
    const toolUseEvent = {
      type: "assistant",
      message: {
        role: "assistant",
        content: [
          {
            type: "tool_use",
            id: "toolu_mock_001",
            name: "Bash",
            input: { command: prompt }
          }
        ]
      },
      session_id: sessionId
    };
    console.log(JSON.stringify(toolUseEvent));
    events.push(toolUseEvent);
    let output = "";
    let exitCode = 0;
    try {
      const result = await new Promise((resolve) => {
        const proc = (0, import_child_process.spawn)("bash", ["-c", prompt], {
          stdio: ["pipe", "pipe", "pipe"]
        });
        let stdout = "";
        let stderr = "";
        proc.stdout.on("data", (chunk) => {
          stdout += chunk.toString();
        });
        proc.stderr.on("data", (chunk) => {
          stderr += chunk.toString();
        });
        proc.on("close", (code) => {
          resolve({ stdout, stderr, code: code ?? 1 });
        });
        proc.on("error", (err) => {
          resolve({ stdout: "", stderr: err.message, code: 1 });
        });
      });
      output = result.stdout + result.stderr;
      exitCode = result.code;
    } catch (e) {
      output = String(e);
      exitCode = 1;
    }
    const isError = exitCode !== 0;
    const toolResultEvent = {
      type: "user",
      message: {
        role: "user",
        content: [
          {
            type: "tool_result",
            tool_use_id: "toolu_mock_001",
            content: output,
            is_error: isError
          }
        ]
      },
      session_id: sessionId
    };
    console.log(JSON.stringify(toolResultEvent));
    events.push(toolResultEvent);
    const resultEvent = {
      type: "result",
      subtype: exitCode === 0 ? "success" : "error",
      is_error: exitCode !== 0,
      duration_ms: 100,
      num_turns: 1,
      result: output,
      session_id: sessionId,
      total_cost_usd: 0,
      usage: { input_tokens: 0, output_tokens: 0 }
    };
    console.log(JSON.stringify(resultEvent));
    events.push(resultEvent);
    const sessionContent = events.map((e) => JSON.stringify(e)).join("\\n") + "\\n";
    fs.writeFileSync(sessionHistoryFile, sessionContent);
    process.exit(exitCode);
  } else {
    const proc = (0, import_child_process.spawn)("bash", ["-c", prompt], {
      stdio: "inherit"
    });
    proc.on("close", (code) => {
      process.exit(code ?? 1);
    });
    proc.on("error", (err) => {
      console.error(err.message);
      process.exit(1);
    });
  }
}
main().catch((e) => {
  console.error(String(e));
  process.exit(1);
});
`;

export const DOWNLOAD_SCRIPT = `#!/usr/bin/env node
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/sandbox/scripts/src/lib/download.ts
var download_exports = {};
__export(download_exports, {
  downloadStorage: () => downloadStorage,
  main: () => main
});
module.exports = __toCommonJS(download_exports);
var fs = __toESM(require("fs"), 1);
var import_child_process2 = require("child_process");

// src/sandbox/scripts/src/lib/log.ts
var SCRIPT_NAME = process.env.LOG_SCRIPT_NAME ?? "run-agent";
function getTimestamp() {
  return (/* @__PURE__ */ new Date()).toISOString().replace(/\\.\\d{3}Z$/, "Z");
}
function logInfo(msg) {
  console.error(\`[\${getTimestamp()}] [INFO] [sandbox:\${SCRIPT_NAME}] \${msg}\`);
}
function logWarn(msg) {
  console.error(\`[\${getTimestamp()}] [WARN] [sandbox:\${SCRIPT_NAME}] \${msg}\`);
}
function logError(msg) {
  console.error(\`[\${getTimestamp()}] [ERROR] [sandbox:\${SCRIPT_NAME}] \${msg}\`);
}
function logDebug(msg) {
  if (process.env.VM0_DEBUG === "1") {
    console.error(
      \`[\${getTimestamp()}] [DEBUG] [sandbox:\${SCRIPT_NAME}] \${msg}\`
    );
  }
}

// src/sandbox/scripts/src/lib/http-client.ts
var import_child_process = require("child_process");

// src/sandbox/scripts/src/lib/common.ts
var RUN_ID = process.env.VM0_RUN_ID ?? "";
var API_URL = process.env.VM0_API_URL ?? "";
var API_TOKEN = process.env.VM0_API_TOKEN ?? "";
var PROMPT = process.env.VM0_PROMPT ?? "";
var VERCEL_BYPASS = process.env.VERCEL_PROTECTION_BYPASS ?? "";
var RESUME_SESSION_ID = process.env.VM0_RESUME_SESSION_ID ?? "";
var CLI_AGENT_TYPE = process.env.CLI_AGENT_TYPE ?? "claude-code";
var OPENAI_MODEL = process.env.OPENAI_MODEL ?? "";
var WORKING_DIR = process.env.VM0_WORKING_DIR ?? "";
var ARTIFACT_DRIVER = process.env.VM0_ARTIFACT_DRIVER ?? "";
var ARTIFACT_MOUNT_PATH = process.env.VM0_ARTIFACT_MOUNT_PATH ?? "";
var ARTIFACT_VOLUME_NAME = process.env.VM0_ARTIFACT_VOLUME_NAME ?? "";
var ARTIFACT_VERSION_ID = process.env.VM0_ARTIFACT_VERSION_ID ?? "";
var WEBHOOK_URL = \`\${API_URL}/api/webhooks/agent/events\`;
var CHECKPOINT_URL = \`\${API_URL}/api/webhooks/agent/checkpoints\`;
var COMPLETE_URL = \`\${API_URL}/api/webhooks/agent/complete\`;
var HEARTBEAT_URL = \`\${API_URL}/api/webhooks/agent/heartbeat\`;
var TELEMETRY_URL = \`\${API_URL}/api/webhooks/agent/telemetry\`;
var PROXY_URL = \`\${API_URL}/api/webhooks/agent/proxy\`;
var STORAGE_PREPARE_URL = \`\${API_URL}/api/webhooks/agent/storages/prepare\`;
var STORAGE_COMMIT_URL = \`\${API_URL}/api/webhooks/agent/storages/commit\`;
var HTTP_MAX_TIME_UPLOAD = 60;
var HTTP_MAX_RETRIES = 3;
var SESSION_ID_FILE = \`/tmp/vm0-session-\${RUN_ID}.txt\`;
var SESSION_HISTORY_PATH_FILE = \`/tmp/vm0-session-history-\${RUN_ID}.txt\`;
var EVENT_ERROR_FLAG = \`/tmp/vm0-event-error-\${RUN_ID}\`;
var SYSTEM_LOG_FILE = \`/tmp/vm0-main-\${RUN_ID}.log\`;
var AGENT_LOG_FILE = \`/tmp/vm0-agent-\${RUN_ID}.log\`;
var METRICS_LOG_FILE = \`/tmp/vm0-metrics-\${RUN_ID}.jsonl\`;
var NETWORK_LOG_FILE = \`/tmp/vm0-network-\${RUN_ID}.jsonl\`;
var TELEMETRY_LOG_POS_FILE = \`/tmp/vm0-telemetry-log-pos-\${RUN_ID}.txt\`;
var TELEMETRY_METRICS_POS_FILE = \`/tmp/vm0-telemetry-metrics-pos-\${RUN_ID}.txt\`;
var TELEMETRY_NETWORK_POS_FILE = \`/tmp/vm0-telemetry-network-pos-\${RUN_ID}.txt\`;

// src/sandbox/scripts/src/lib/http-client.ts
function httpDownload(url, destPath, maxRetries = HTTP_MAX_RETRIES) {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    logDebug(\`HTTP download attempt \${attempt}/\${maxRetries} from \${url}\`);
    try {
      const curlCmd = ["curl", "-fsSL", "-o", destPath, \`"\${url}"\`];
      (0, import_child_process.execSync)(curlCmd.join(" "), {
        stdio: ["pipe", "pipe", "pipe"],
        timeout: HTTP_MAX_TIME_UPLOAD * 1e3,
        shell: "/bin/bash"
      });
      return true;
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      logWarn(
        \`HTTP download failed (attempt \${attempt}/\${maxRetries}): \${errorMsg}\`
      );
      if (attempt < maxRetries) {
        sleepSync(1e3);
      }
    }
  }
  logError(\`HTTP download failed after \${maxRetries} attempts from \${url}\`);
  return false;
}
function sleepSync(ms) {
  const end = Date.now() + ms;
  while (Date.now() < end) {
  }
}

// src/sandbox/scripts/src/lib/download.ts
function downloadStorage(mountPath, archiveUrl) {
  logInfo(\`Downloading storage to \${mountPath}\`);
  const tempTar = \`/tmp/storage-\${Date.now()}.tar.gz\`;
  try {
    if (!httpDownload(archiveUrl, tempTar)) {
      logError(\`Failed to download archive for \${mountPath}\`);
      return false;
    }
    fs.mkdirSync(mountPath, { recursive: true });
    try {
      (0, import_child_process2.execSync)(\`tar xzf "\${tempTar}" -C "\${mountPath}"\`, {
        stdio: ["pipe", "pipe", "pipe"]
      });
    } catch {
      logInfo(\`Archive appears empty for \${mountPath}\`);
    }
    logInfo(\`Successfully extracted to \${mountPath}\`);
    return true;
  } finally {
    try {
      if (fs.existsSync(tempTar)) {
        fs.unlinkSync(tempTar);
      }
    } catch {
    }
  }
}
function main() {
  const args = process.argv.slice(2);
  if (args.length < 1) {
    logError("Usage: node download.js <manifest_path>");
    process.exit(1);
  }
  const manifestPath = args[0];
  if (!fs.existsSync(manifestPath)) {
    logError(\`Manifest file not found: \${manifestPath}\`);
    process.exit(1);
  }
  logInfo(\`Starting storage download from manifest: \${manifestPath}\`);
  let manifest;
  try {
    const content = fs.readFileSync(manifestPath, "utf-8");
    manifest = JSON.parse(content);
  } catch (err) {
    logError(\`Failed to load manifest: \${err}\`);
    process.exit(1);
  }
  const storages = manifest.storages ?? [];
  const artifact = manifest.artifact;
  const storageCount = storages.length;
  const hasArtifact = artifact !== void 0;
  logInfo(\`Found \${storageCount} storages, artifact: \${hasArtifact}\`);
  for (const storage of storages) {
    const { mountPath, archiveUrl } = storage;
    if (archiveUrl && archiveUrl !== "null") {
      downloadStorage(mountPath, archiveUrl);
    }
  }
  if (artifact) {
    const { mountPath: artifactMount, archiveUrl: artifactUrl } = artifact;
    if (artifactUrl && artifactUrl !== "null") {
      downloadStorage(artifactMount, artifactUrl);
    }
  }
  logInfo("All storages downloaded successfully");
}
main();
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  downloadStorage,
  main
});
`;

/**
 * Script paths in the sandbox/VM
 * These are the paths where scripts will be deployed and executed
 */
export const SCRIPT_PATHS = {
  baseDir: "/usr/local/bin/vm0-agent",
  runAgent: "/usr/local/bin/vm0-agent/run-agent.js",
  mockClaude: "/usr/local/bin/vm0-agent/mock-claude.js",
  download: "/usr/local/bin/vm0-agent/download.js",
} as const;
