// Auto-generated from Asana API docs.
// Source: https://developers.asana.com/docs/authentication
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:asana
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const asanaFirewall = {
  name: "asana",
  description: "Asana API",
  placeholders: {
    ASANA_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafe00",
  },
  apis: [
    {
      base: "https://app.asana.com/api",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.ASANA_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
