// Auto-generated from Axiom's official OpenAPI specs.
// Source: https://axiom.co/docs/restapi/versions/v2.json
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:axiom
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const axiomFirewall = {
  name: "axiom",
  description: "Axiom API",
  placeholders: {
    AXIOM_TOKEN: "xaat-c0ffee5a-fe10-ca1c-0ffe-e5afe10ca1c0",
  },
  apis: [
    {
      base: "https://api.axiom.co",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.AXIOM_TOKEN }}",
        },
      },
      permissions: [
        {
          name: "annotations|create",
          rules: ["POST /v2/annotations"],
        },
        {
          name: "annotations|delete",
          rules: ["DELETE /v2/annotations/{id}"],
        },
        {
          name: "annotations|read",
          rules: ["GET /v2/annotations", "GET /v2/annotations/{id}"],
        },
        {
          name: "annotations|update",
          rules: ["PUT /v2/annotations/{id}"],
        },
        {
          name: "apiTokens|create",
          rules: ["POST /v2/tokens"],
        },
        {
          name: "apiTokens|delete",
          rules: ["DELETE /v2/tokens/{id}"],
        },
        {
          name: "apiTokens|read",
          rules: ["GET /v2/tokens", "GET /v2/tokens/{id}"],
        },
        {
          name: "apiTokens|update",
          rules: ["POST /v2/tokens/{id}/regenerate"],
        },
        {
          name: "dashboards|create",
          rules: ["POST /v2/dashboards"],
        },
        {
          name: "dashboards|delete",
          rules: ["DELETE /v2/dashboards/uid/{uid}"],
        },
        {
          name: "dashboards|read",
          rules: ["GET /v2/dashboards", "GET /v2/dashboards/uid/{uid}"],
        },
        {
          name: "dashboards|update",
          rules: ["PUT /v2/dashboards/uid/{uid}"],
        },
        {
          name: "datasets|create",
          rules: ["POST /v2/datasets"],
        },
        {
          name: "datasets|delete",
          rules: ["DELETE /v2/datasets/{dataset_id}"],
        },
        {
          name: "datasets|read",
          rules: [
            "GET /v1/datasets",
            "GET /v1/datasets/{dataset_name}",
            "GET /v2/datasets",
            "GET /v2/datasets/{dataset_id}",
            "GET /v2/datasets/{dataset_id}/fields",
            "GET /v2/datasets/{dataset_id}/fields/{field_id}",
            "GET /v2/datasets/{dataset_id}/mapfields",
          ],
        },
        {
          name: "datasets|update",
          rules: [
            "POST /v1/datasets",
            "PUT /v1/datasets/{dataset_name}",
            "DELETE /v1/datasets/{dataset_name}",
            "POST /v1/datasets/{dataset_name}/trim",
            "PUT /v2/datasets/{dataset_id}",
            "PUT /v2/datasets/{dataset_id}/fields/{field_id}",
            "POST /v2/datasets/{dataset_id}/mapfields",
            "PUT /v2/datasets/{dataset_id}/mapfields",
            "DELETE /v2/datasets/{dataset_id}/mapfields/{map_field_name}",
          ],
        },
        {
          name: "ingest|create",
          rules: [
            "POST /v1/datasets/{dataset_name}/ingest",
            "POST /v1/ingest/{dataset-id}",
          ],
        },
        {
          name: "monitors|create",
          rules: ["POST /v2/monitors"],
        },
        {
          name: "monitors|delete",
          rules: ["DELETE /v2/monitors/{id}"],
        },
        {
          name: "monitors|read",
          rules: [
            "GET /v2/monitors",
            "GET /v2/monitors/{id}",
            "GET /v2/monitors/{id}/history",
          ],
        },
        {
          name: "monitors|update",
          rules: ["PUT /v2/monitors/{id}"],
        },
        {
          name: "notifiers|create",
          rules: ["POST /v2/notifiers"],
        },
        {
          name: "notifiers|delete",
          rules: ["DELETE /v2/notifiers/{id}"],
        },
        {
          name: "notifiers|read",
          rules: ["GET /v2/notifiers", "GET /v2/notifiers/{id}"],
        },
        {
          name: "notifiers|update",
          rules: ["PUT /v2/notifiers/{id}"],
        },
        {
          name: "orgs|create",
          rules: ["POST /v2/orgs"],
        },
        {
          name: "orgs|read",
          rules: ["GET /v2/orgs", "GET /v2/orgs/{id}"],
        },
        {
          name: "orgs|update",
          rules: ["PUT /v2/orgs/{id}"],
        },
        {
          name: "query|read",
          rules: [
            "POST /v1/datasets/_apl",
            "POST /v1/datasets/{dataset_name}/query",
            "POST /v1/query/_apl",
            "POST /v1/query/_mpl",
            "POST /v1/query/batch",
            "GET /v1/query/metrics/info/datasets/{dataset}/metrics",
            "POST /v1/query/metrics/info/datasets/{dataset}/metrics",
            "GET /v1/query/metrics/info/datasets/{dataset}/metrics/{metric}/tags",
            "GET /v1/query/metrics/info/datasets/{dataset}/metrics/{metric}/tags/{tag}/values",
            "GET /v1/query/metrics/info/datasets/{dataset}/tags",
            "GET /v1/query/metrics/info/datasets/{dataset}/tags/{tag}/values",
          ],
        },
        {
          name: "rbac|create",
          rules: [
            "POST /v2/rbac/groups",
            "PUT /v2/rbac/groups/{id}",
            "DELETE /v2/rbac/groups/{id}",
            "POST /v2/rbac/roles",
            "PUT /v2/rbac/roles/{id}",
            "DELETE /v2/rbac/roles/{id}",
          ],
        },
        {
          name: "rbac|read",
          rules: [
            "GET /v2/rbac/groups",
            "GET /v2/rbac/groups/{id}",
            "GET /v2/rbac/roles",
            "GET /v2/rbac/roles/{id}",
          ],
        },
        {
          name: "starredQueries|create",
          rules: ["POST /v2/apl-starred-queries"],
        },
        {
          name: "starredQueries|delete",
          rules: ["DELETE /v2/apl-starred-queries/{id}"],
        },
        {
          name: "starredQueries|read",
          rules: [
            "GET /v2/apl-starred-queries",
            "GET /v2/apl-starred-queries/{id}",
          ],
        },
        {
          name: "starredQueries|update",
          rules: ["PUT /v2/apl-starred-queries/{id}"],
        },
        {
          name: "trim|update",
          rules: ["POST /v2/datasets/{dataset_id}/trim"],
        },
        {
          name: "users|create",
          rules: ["POST /v2/users"],
        },
        {
          name: "users|delete",
          rules: ["DELETE /v2/users/{id}"],
        },
        {
          name: "users|read",
          rules: [
            "GET /v1/user",
            "GET /v2/user",
            "GET /v2/users",
            "GET /v2/users/{id}",
          ],
        },
        {
          name: "users|update",
          rules: ["PUT /v2/user", "PUT /v2/users/{id}/role"],
        },
        {
          name: "vacuum|update",
          rules: ["POST /v2/datasets/{dataset_id}/vacuum"],
        },
        {
          name: "views|create",
          rules: ["POST /v2/views"],
        },
        {
          name: "views|delete",
          rules: ["DELETE /v2/views/{id}"],
        },
        {
          name: "views|read",
          rules: ["GET /v2/views", "GET /v2/views/{id}"],
        },
        {
          name: "views|update",
          rules: ["PUT /v2/views/{id}"],
        },
        {
          name: "virtualFields|create",
          rules: ["POST /v2/vfields"],
        },
        {
          name: "virtualFields|delete",
          rules: ["DELETE /v2/vfields/{id}"],
        },
        {
          name: "virtualFields|read",
          rules: ["GET /v2/vfields", "GET /v2/vfields/{id}"],
        },
        {
          name: "virtualFields|update",
          rules: ["PUT /v2/vfields/{id}"],
        },
      ],
    },
  ],
} as const satisfies FirewallConfig;
