// Auto-generated from Browserless API docs.
// Source: https://docs.browserless.io/rest-apis/intro
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:browserless
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const browserlessFirewall: FirewallConfig = {
  name: "browserless",
  description: "Browserless API",
  placeholders: {
    BROWSERLESS_TOKEN: "094632bb-vm00-0000-0000-vm0placeholder",
  },
  apis: [
    {
      base: "https://production-sfo.browserless.io",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.BROWSERLESS_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://production-lon.browserless.io",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.BROWSERLESS_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://production-ams.browserless.io",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.BROWSERLESS_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
};
