// Auto-generated from Calendly API docs.
// Source: https://developer.calendly.com/getting-started
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:calendly
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const calendlyFirewall: FirewallConfig = {
  name: "calendly",
  description: "Calendly API",
  placeholders: {
    CALENDLY_TOKEN: "Vm0PlaceHolder0000000000000000000000000000",
  },
  apis: [
    {
      base: "https://api.calendly.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.CALENDLY_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
};
