// Auto-generated from Close CRM API docs.
// Source: https://developer.close.com/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:close
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const closeFirewall: FirewallConfig = {
  name: "close",
  description: "Close CRM API",
  placeholders: {
    CLOSE_TOKEN: "Vm0PlaceHolder00000000000000000000000000000000a",
  },
  apis: [
    {
      base: "https://api.close.com/api",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.CLOSE_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
};
