// Auto-generated from Cronlytic API docs.
// Source: https://www.cronlytic.com/api-documentation
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:cronlytic
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const cronlyticFirewall: FirewallConfig = {
  name: "cronlytic",
  description: "Cronlytic API",
  placeholders: {
    CRONLYTIC_API_KEY: "vm0placeholderCronlyticApiKey000000000000000000000000a",
    CRONLYTIC_USER_ID: "vm0placeholderCronlyticUserId000000000000000000000000a",
  },
  apis: [
    {
      base: "https://api.cronlytic.com",
      auth: {
        headers: {
          "x-api-key": "${{ secrets.CRONLYTIC_API_KEY }}",
          "x-user-id": "${{ secrets.CRONLYTIC_USER_ID }}",
        },
      },
      permissions: [
        {
          name: "unrestricted",
          description: "Allow all Cronlytic API endpoints",
          rules: ["ANY /{path*}"],
        },
      ],
    },
  ],
};
