// Auto-generated from DeepSeek API docs.
// Source: https://api-docs.deepseek.com/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:deepseek
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const deepseekFirewall = {
  name: "deepseek",
  description: "DeepSeek API",
  placeholders: {
    DEEPSEEK_TOKEN: "sk-c0ffee5afe10ca1c0ffee5afe10ca1c0",
  },
  apis: [
    {
      base: "https://api.deepseek.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.DEEPSEEK_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
