// Auto-generated from Discord API docs.
// Source: https://discord.com/developers/docs/reference#authentication
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:discord
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const discordFirewall: FirewallConfig = {
  name: "discord",
  description: "Discord API",
  placeholders: {
    DISCORD_BOT_TOKEN:
      "Vm0PlaceHolder0000000000.000000.Vm0PlaceHolder0000000000000",
  },
  apis: [
    {
      base: "https://discord.com/api",
      auth: {
        headers: {
          Authorization: "Bot ${{ secrets.DISCORD_BOT_TOKEN }}",
        },
      },
      permissions: [
        {
          name: "unrestricted",
          description: "Allow all endpoints",
          rules: ["ANY /{path*}"],
        },
      ],
    },
  ],
};
