// Auto-generated from DocuSign API docs.
// Source: https://developers.docusign.com/platform/api-endpoint-base-paths/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:docusign
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const docusignFirewall = {
  name: "docusign",
  description: "DocuSign eSignature REST API",
  placeholders: {
    DOCUSIGN_TOKEN:
      "eyJ0eXAiOiJNVCIsImFsZyI6IlJTMjU2In0.CoffeeSafeLocalCoffeeSafeLocal.CoffeeSaf",
  },
  apis: [
    {
      base: "https://www.docusign.net",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.DOCUSIGN_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://na2.docusign.net",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.DOCUSIGN_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://na3.docusign.net",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.DOCUSIGN_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://na4.docusign.net",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.DOCUSIGN_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://eu.docusign.net",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.DOCUSIGN_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://au.docusign.net",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.DOCUSIGN_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://ca.docusign.net",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.DOCUSIGN_TOKEN }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://demo.docusign.net",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.DOCUSIGN_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
