// Auto-generated from ElevenLabs API docs.
// Source: https://elevenlabs.io/docs/api-reference/authentication
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:elevenlabs
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const elevenlabsFirewall = {
  name: "elevenlabs",
  description: "ElevenLabs API",
  placeholders: {
    ELEVENLABS_TOKEN: "c0ffee5afe10ca1c0ffee5afe10ca1c0",
  },
  apis: [
    {
      base: "https://api.elevenlabs.io",
      auth: {
        headers: {
          "xi-api-key": "${{ secrets.ELEVENLABS_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
