// Auto-generated from Explorium API docs.
// Source: https://developers.explorium.ai/reference/introduction
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:explorium
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const exploriumFirewall = {
  name: "explorium",
  description: "Explorium API",
  placeholders: {
    EXPLORIUM_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafe",
  },
  apis: [
    {
      base: "https://api.explorium.ai",
      auth: {
        headers: {
          api_key: "${{ secrets.EXPLORIUM_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
