// Auto-generated from Fireflies.ai API docs.
// Source: https://docs.fireflies.ai/fundamentals/authorization
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:fireflies
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const firefliesFirewall: FirewallConfig = {
  name: "fireflies",
  description: "Fireflies.ai API",
  placeholders: {
    FIREFLIES_TOKEN: "Vm0PlaceHolder00000000000000000000000000000000a",
  },
  apis: [
    {
      base: "https://api.fireflies.ai/graphql",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.FIREFLIES_TOKEN }}",
        },
      },
      permissions: [
        {
          name: "unrestricted",
          description: "Allow all endpoints",
          rules: ["ANY /{path*}"],
        },
      ],
    },
  ],
};
