import type { PermissionNamesOf } from "./index";
import { githubFirewall } from "./github.generated";
import { registerCategories } from "./categories";

const githubCategories: Record<
  PermissionNamesOf<typeof githubFirewall>,
  string
> = {
  // Admin (22)
  "administration:read": "Admin",
  "administration:write": "Admin",
  "organization_administration:read": "Admin",
  "organization_administration:write": "Admin",
  "organization_hooks:read": "Admin",
  "organization_hooks:write": "Admin",
  "organization_self_hosted_runners:read": "Admin",
  "organization_self_hosted_runners:write": "Admin",
  "organization_runner_custom_images:read": "Admin",
  "organization_runner_custom_images:write": "Admin",
  "repository_hooks:read": "Admin",
  "repository_hooks:write": "Admin",
  "organization_personal_access_tokens:read": "Admin",
  "organization_personal_access_tokens:write": "Admin",
  "organization_personal_access_token_requests:read": "Admin",
  "organization_personal_access_token_requests:write": "Admin",
  "organization_custom_org_roles:read": "Admin",
  "organization_custom_properties:admin": "Admin",
  "organization_custom_properties:read": "Admin",
  "organization_custom_properties:write": "Admin",
  "organization_network_configurations:read": "Admin",
  "organization_network_configurations:write": "Admin",

  // Read — all remaining :read permissions
  "actions:read": "Read",
  "actions_variables:read": "Read",
  "artifact_metadata:read": "Read",
  "attestations:read": "Read",
  "blocking:read": "Read",
  "checks:read": "Read",
  "codespaces_lifecycle_admin:read": "Read",
  "codespaces_metadata:read": "Read",
  "codespaces:read": "Read",
  "codespaces_user_secrets:read": "Read",
  "contents:read": "Read",
  "dependabot_secrets:read": "Read",
  "deployments:read": "Read",
  "emails:read": "Read",
  "enterprise_copilot_metrics:read": "Read",
  "enterprise_teams:read": "Read",
  "environments:read": "Read",
  "followers:read": "Read",
  "git_signing_ssh_public_keys:read": "Read",
  "gpg_keys:read": "Read",
  "interaction_limits:read": "Read",
  "issue_fields:read": "Read",
  "issues:read": "Read",
  "issue_types:read": "Read",
  "keys:read": "Read",
  "members:read": "Read",
  "metadata:read": "Read",
  "organization_actions_variables:read": "Read",
  "organization_api_insights:read": "Read",
  "organization_campaigns:read": "Read",
  "organization_codespaces:read": "Read",
  "organization_codespaces_secrets:read": "Read",
  "organization_copilot_agent_settings:read": "Read",
  "organization_copilot_metrics:read": "Read",
  "organization_copilot_seat_management:read": "Read",
  "organization_dependabot_secrets:read": "Read",
  "organization_events:read": "Read",
  "organization_private_registries:read": "Read",
  "organization_projects:read": "Read",
  "organization_secrets:read": "Read",
  "organization_user_blocking:read": "Read",
  "org_copilot_content_exclusion:read": "Read",
  "pages:read": "Read",
  "plan:read": "Read",
  "private_repository_invitations:read": "Read",
  "pull_requests:read": "Read",
  "repository_advisories:read": "Read",
  "secret_scanning_alerts:read": "Read",
  "secrets:read": "Read",
  "security_events:read": "Read",
  "starring:read": "Read",
  "statuses:read": "Read",
  "vulnerability_alerts:read": "Read",
  "watching:read": "Read",

  // Write — all remaining :write permissions
  "actions:write": "Write",
  "actions_variables:write": "Write",
  "artifact_metadata:write": "Write",
  "attestations:write": "Write",
  "blocking:write": "Write",
  "checks:write": "Write",
  "codespaces_lifecycle_admin:write": "Write",
  "codespaces_secrets:write": "Write",
  "codespaces_user_secrets:write": "Write",
  "codespaces:write": "Write",
  "contents:write": "Write",
  "dependabot_secrets:write": "Write",
  "deployments:write": "Write",
  "emails:write": "Write",
  "enterprise_teams:write": "Write",
  "environments:write": "Write",
  "followers:write": "Write",
  "gists:write": "Write",
  "git_signing_ssh_public_keys:write": "Write",
  "gpg_keys:write": "Write",
  "interaction_limits:write": "Write",
  "issue_fields:write": "Write",
  "issues:write": "Write",
  "issue_types:write": "Write",
  "keys:write": "Write",
  "members:write": "Write",
  "organization_actions_variables:write": "Write",
  "organization_campaigns:write": "Write",
  "organization_codespaces_secrets:write": "Write",
  "organization_codespaces_settings:write": "Write",
  "organization_codespaces:write": "Write",
  "organization_copilot_agent_settings:write": "Write",
  "organization_copilot_seat_management:write": "Write",
  "organization_dependabot_secrets:write": "Write",
  "organization_private_registries:write": "Write",
  "organization_projects:write": "Write",
  "organization_secrets:write": "Write",
  "organization_user_blocking:write": "Write",
  "org_copilot_content_exclusion:write": "Write",
  "pages:write": "Write",
  "profile:write": "Write",
  "pull_requests:write": "Write",
  "repository_advisories:write": "Write",
  "repository_custom_properties:write": "Write",
  "secret_scanning_alerts:write": "Write",
  "secrets:write": "Write",
  "security_events:write": "Write",
  "starring:write": "Write",
  "statuses:write": "Write",
  "vulnerability_alerts:write": "Write",
  "workflows:write": "Write",
};

const githubCategoryOrder = ["Read", "Write", "Admin"] as const;

registerCategories("github", {
  categories: githubCategories,
  displayOrder: githubCategoryOrder,
});
