// Auto-generated from Google's Discovery API.
// Source: https://meet.googleapis.com/$discovery/rest?version=v2
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:google-meet
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const googleMeetFirewall = {
  name: "google-meet",
  description: "Google Meet API",
  placeholders: {
    GOOGLE_MEET_TOKEN:
      "ya29.A0CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSa",
  },
  apis: [
    {
      base: "https://meet.googleapis.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.GOOGLE_MEET_TOKEN }}",
        },
      },
      permissions: [
        {
          name: "meetings.space.created",
          description:
            "Create, edit, and see information about your Google Meet conferences created by the app.",
          rules: [
            "GET /v2/conferenceRecords",
            "GET /v2/conferenceRecords/{conferenceRecordsId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/participants",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}/participantSessions",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}/participantSessions/{participantSessionsId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/recordings",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/recordings/{recordingsId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/smartNotes",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/smartNotes/{smartNotesId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/transcripts",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}/entries",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}/entries/{entriesId}",
            "POST /v2/spaces",
            "GET /v2/spaces/{spacesId}",
            "PATCH /v2/spaces/{spacesId}",
            "POST /v2/spaces/{spacesId}:endActiveConference",
          ],
        },
        {
          name: "meetings.space.readonly",
          description:
            "Read information about any of your Google Meet conferences",
          rules: [
            "GET /v2/conferenceRecords",
            "GET /v2/conferenceRecords/{conferenceRecordsId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/participants",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}/participantSessions",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}/participantSessions/{participantSessionsId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/recordings",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/recordings/{recordingsId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/smartNotes",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/smartNotes/{smartNotesId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/transcripts",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}/entries",
            "GET /v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}/entries/{entriesId}",
            "GET /v2/spaces/{spacesId}",
          ],
        },
        {
          name: "meetings.space.settings",
          description:
            "Edit, and see settings for all of your Google Meet calls.",
          rules: ["GET /v2/spaces/{spacesId}", "PATCH /v2/spaces/{spacesId}"],
        },
      ],
    },
  ],
} as const satisfies FirewallConfig;
