// Auto-generated from HubSpot's official OpenAPI specs.
// Source: https://github.com/HubSpot/HubSpot-public-api-spec-collection
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:hubspot
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const hubspotFirewall = {
  name: "hubspot",
  description: "HubSpot API",
  placeholders: {
    HUBSPOT_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCo",
  },
  apis: [
    {
      base: "https://api.hubapi.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.HUBSPOT_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
