// Auto-generated from Instantly API docs.
// Source: https://developer.instantly.ai/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:instantly
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const instantlyFirewall: FirewallConfig = {
  name: "instantly",
  description: "Instantly API",
  placeholders: {
    INSTANTLY_API_KEY: "vm0placeholderInstantlyApiKey000000000000000000000000a",
  },
  apis: [
    {
      base: "https://api.instantly.ai",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.INSTANTLY_API_KEY }}",
        },
      },
      permissions: [],
    },
  ],
};
