// Auto-generated from Intervals.icu API docs.
// Source: https://forum.intervals.icu/t/api-access-to-intervals-icu/609
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:intervals-icu
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const intervalsIcuFirewall: FirewallConfig = {
  name: "intervals-icu",
  description: "Intervals.icu Training API",
  placeholders: {
    INTERVALS_ICU_TOKEN:
      "vm0placeholderIntervalsIcuToken0000000000000000000000a",
  },
  apis: [
    {
      base: "https://intervals.icu",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.INTERVALS_ICU_TOKEN }}",
        },
      },
      permissions: [
        {
          name: "unrestricted",
          description: "Allow all Intervals.icu API endpoints",
          rules: ["ANY /{path*}"],
        },
      ],
    },
  ],
};
