// Auto-generated from Langfuse API docs.
// Source: https://langfuse.com/docs/api
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:langfuse
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const langfuseFirewall = {
  name: "langfuse",
  description: "Langfuse LLM observability and tracing API",
  placeholders: {
    LANGFUSE_PUBLIC_KEY: "pk-lf-c0ffee5a-fe10-ca1c-0ffe-e5afe10ca1c0",
    LANGFUSE_SECRET_KEY: "sk-lf-5afe10ca-1c0f-feec-0ffe-e5afe10ca1c0",
  },
  apis: [
    {
      base: "https://cloud.langfuse.com",
      auth: {
        headers: {
          Authorization:
            "${{ basic(secrets.LANGFUSE_PUBLIC_KEY, secrets.LANGFUSE_SECRET_KEY) }}",
        },
      },
      permissions: [],
    },
    {
      base: "https://us.cloud.langfuse.com",
      auth: {
        headers: {
          Authorization:
            "${{ basic(secrets.LANGFUSE_PUBLIC_KEY, secrets.LANGFUSE_SECRET_KEY) }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
