// Auto-generated from Loops API docs.
// Source: https://loops.so/docs/api-reference/intro
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:loops
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const loopsFirewall: FirewallConfig = {
  name: "loops",
  description: "Loops API",
  placeholders: {
    LOOPS_TOKEN: "00000000000000000000000000000000",
  },
  apis: [
    {
      base: "https://app.loops.so/api/v1",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.LOOPS_TOKEN }}",
        },
      },
      permissions: [
        {
          name: "unrestricted",
          description: "Allow all endpoints",
          rules: ["ANY /{path*}"],
        },
      ],
    },
  ],
};
