// Auto-generated from Loops API docs.
// Source: https://loops.so/docs/api-reference/intro
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:loops
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const loopsFirewall: FirewallConfig = {
  name: "loops",
  description: "Loops API",
  placeholders: {
    LOOPS_TOKEN: "d2d561f5ff80136f69b4b5a31b9fb3c9",
  },
  apis: [
    {
      base: "https://app.loops.so/api",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.LOOPS_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
};
