// Auto-generated from Mercury API docs.
// Source: https://docs.mercury.com/docs/getting-started
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:mercury
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const mercuryFirewall: FirewallConfig = {
  name: "mercury",
  description: "Mercury API",
  placeholders: {
    MERCURY_TOKEN: "vm0placeholderMercuryToken0000000000000000000000000000a",
  },
  apis: [
    {
      base: "https://api.mercury.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.MERCURY_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
};
