// Auto-generated from Microsoft Graph API docs.
// Source: https://learn.microsoft.com/en-us/graph/auth/auth-concepts
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:outlook-calendar
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const outlookCalendarFirewall: FirewallConfig = {
  name: "outlook-calendar",
  description: "Microsoft Graph API (Outlook Calendar)",
  placeholders: {
    OUTLOOK_CALENDAR_TOKEN:
      "vm0placeholderOutlookCalendarToken00000000000000000000a",
  },
  apis: [
    {
      base: "https://graph.microsoft.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.OUTLOOK_CALENDAR_TOKEN }}",
        },
      },
      permissions: [
        {
          name: "unrestricted",
          description: "Allow all Microsoft Graph API endpoints",
          rules: ["ANY /{path*}"],
        },
      ],
    },
  ],
};
