// Auto-generated from PDF4me API docs.
// Source: https://dev.pdf4me.com/apiv2/documentation/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:pdf4me
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const pdf4meFirewall = {
  name: "pdf4me",
  description: "PDF4me Document API",
  placeholders: {
    PDF4ME_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSa",
  },
  apis: [
    {
      base: "https://api.pdf4me.com",
      auth: {
        headers: {
          Authorization: "${{ secrets.PDF4ME_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
