// Auto-generated from Podchaser API docs.
// Source: https://api-docs.podchaser.com/docs/authorization/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:podchaser
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const podchaserFirewall = {
  name: "podchaser",
  description: "Podchaser Podcast API",
  placeholders: {
    PODCHASER_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSafe",
  },
  apis: [
    {
      base: "https://api.podchaser.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.PODCHASER_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
