// Auto-generated from Reddit API docs.
// Source: https://github.com/reddit-archive/reddit/wiki/OAuth2
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:reddit
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const redditFirewall: FirewallConfig = {
  name: "reddit",
  description: "Reddit API",
  placeholders: {
    REDDIT_TOKEN:
      "vm0placeholder00000000000000000000000000000000000000000000000000a",
  },
  apis: [
    {
      base: "https://oauth.reddit.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.REDDIT_TOKEN }}",
        },
      },
      permissions: [
        {
          name: "unrestricted",
          description: "Allow all endpoints",
          rules: ["ANY /{path*}"],
        },
      ],
    },
  ],
};
