// Auto-generated from Replicate API docs.
// Source: https://replicate.com/docs/reference/http
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:replicate
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const replicateFirewall = {
  name: "replicate",
  description: "Replicate",
  placeholders: {
    REPLICATE_API_TOKEN: "r8_CoffeeSafeLocalCoffeeSafeLocalCoffee",
  },
  apis: [
    {
      base: "https://api.replicate.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.REPLICATE_API_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
