import type { PermissionNamesOf } from "./index";
import { slackFirewall } from "./slack.generated";
import { registerCategories } from "./categories";

const slackCategories: Record<
  PermissionNamesOf<typeof slackFirewall>,
  string
> = {
  // Admin (25)
  admin: "Admin",
  "admin.analytics:read": "Admin",
  "admin.app_activities:read": "Admin",
  "admin.apps:read": "Admin",
  "admin.apps:write": "Admin",
  "admin.barriers:read": "Admin",
  "admin.barriers:write": "Admin",
  "admin.conversations:manage_objects": "Admin",
  "admin.conversations:read": "Admin",
  "admin.conversations:write": "Admin",
  "admin.invites:read": "Admin",
  "admin.invites:write": "Admin",
  "admin.roles:read": "Admin",
  "admin.roles:write": "Admin",
  "admin.teams:read": "Admin",
  "admin.teams:write": "Admin",
  "admin.usergroups:read": "Admin",
  "admin.usergroups:write": "Admin",
  "admin.users:read": "Admin",
  "admin.users:write": "Admin",
  "admin.workflows:read": "Admin",
  "admin.workflows:write": "Admin",
  "channels:manage": "Admin",
  "conversations.connect:manage": "Admin",
  "team.billing:read": "Admin",

  // Read (34)
  "bookmarks:read": "Read",
  "calls:read": "Read",
  "canvases:read": "Read",
  "channels:history": "Read",
  "channels:read": "Read",
  "datastore:read": "Read",
  "dnd:read": "Read",
  "emoji:read": "Read",
  "files:read": "Read",
  "groups:history": "Read",
  "groups:read": "Read",
  "hosting:read": "Read",
  "identity:read": "Read",
  "im:history": "Read",
  "im:read": "Read",
  "lists:read": "Read",
  "mpim:history": "Read",
  "mpim:read": "Read",
  "pins:read": "Read",
  "reactions:read": "Read",
  "reminders:read": "Read",
  "remote_files:read": "Read",
  "search:read": "Read",
  "search:read.files": "Read",
  "search:read.im": "Read",
  "search:read.mpim": "Read",
  "search:read.private": "Read",
  "search:read.public": "Read",
  "search:read.users": "Read",
  "stars:read": "Read",
  "team.preferences:read": "Read",
  "team:read": "Read",
  "triggers:read": "Read",
  "usergroups:read": "Read",
  "users.profile:read": "Read",
  "users:read": "Read",
  "users:read.email": "Read",

  // Write (22)
  "bookmarks:write": "Write",
  "calls:write": "Write",
  "canvases:write": "Write",
  "channels:write": "Write",
  "channels:write.invites": "Write",
  "channels:write.topic": "Write",
  "datastore:write": "Write",
  "dnd:write": "Write",
  "files:write": "Write",
  "groups:write": "Write",
  "groups:write.invites": "Write",
  "groups:write.topic": "Write",
  "im:write.topic": "Write",
  "links:write": "Write",
  "lists:write": "Write",
  "pins:write": "Write",
  "reactions:write": "Write",
  "reminders:write": "Write",
  "remote_files:write": "Write",
  "stars:write": "Write",
  "triggers:write": "Write",
  "usergroups:write": "Write",
  "users.profile:write": "Write",
  "users:write": "Write",

  // Send (8)
  "assistant:write": "Send",
  "chat:write": "Send",
  "conversations.connect:write": "Send",
  "im:write": "Send",
  "mpim:write": "Send",
  "mpim:write.topic": "Send",
  "remote_files:share": "Send",

  // Misc (5)
  "channels:join": "Misc",
  client: "Misc",
  no_scopes_required: "Misc",
  openid: "Misc",
  "tokens.basic": "Misc",
};

const slackCategoryOrder = ["Read", "Write", "Send", "Admin", "Misc"] as const;

registerCategories("slack", {
  categories: slackCategories,
  displayOrder: slackCategoryOrder,
});
