// Auto-generated from Streak API docs.
// Source: https://streak.readme.io/docs/authentication
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:streak
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const streakFirewall = {
  name: "streak",
  description: "Streak CRM API",
  placeholders: {
    STREAK_TOKEN: "Coffee5afe10ca1Coffee5afe10ca1Coffee5afe10",
  },
  apis: [
    {
      base: "https://api.streak.com",
      auth: {
        headers: {
          Authorization: "${{ basic(secrets.STREAK_TOKEN, ) }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
