// Auto-generated from Supadata API docs.
// Source: https://docs.supadata.ai/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:supadata
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const supadataFirewall = {
  name: "supadata",
  description: "Supadata API",
  placeholders: {
    SUPADATA_TOKEN: "CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLocalCoffeeSaf",
  },
  apis: [
    {
      base: "https://api.supadata.ai",
      auth: {
        headers: {
          "x-api-key": "${{ secrets.SUPADATA_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
