// Auto-generated from Supadata API docs.
// Source: https://docs.supadata.ai/
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:supadata
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const supadataFirewall: FirewallConfig = {
  name: "supadata",
  description: "Supadata API",
  placeholders: {
    SUPADATA_TOKEN: "vm0placeholderSupadataToken00000000000000000000000000a",
  },
  apis: [
    {
      base: "https://api.supadata.ai",
      auth: {
        headers: {
          "x-api-key": "${{ secrets.SUPADATA_TOKEN }}",
        },
      },
      permissions: [
        {
          name: "unrestricted",
          description: "Allow all Supadata API endpoints",
          rules: ["ANY /{path*}"],
        },
      ],
    },
  ],
};
