// Auto-generated from Tavily API docs.
// Source: https://docs.tavily.com/documentation/api-reference/introduction
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:tavily
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const tavilyFirewall = {
  name: "tavily",
  description: "Tavily API",
  placeholders: {
    TAVILY_TOKEN: "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",
  },
  apis: [
    {
      base: "https://api.tavily.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.TAVILY_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
