// Auto-generated from Twenty CRM API docs.
// Source: https://docs.twenty.com/developers/api-and-webhooks/api
// Regenerate: cd turbo && pnpm -F @vm0/firewalls-generator generate:twenty
//
// DO NOT EDIT THIS FILE MANUALLY.

import type { FirewallConfig } from "../contracts/firewalls";

export const twentyFirewall = {
  name: "twenty",
  description: "Twenty CRM API",
  placeholders: {
    TWENTY_TOKEN:
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJDb2ZmZWVTYWZlTG9jYWxDb2ZmZWVTYWZlTG9jYWxDbyIsInR5cGUiOiJBUElfS0VZIiwid29ya3NwYWNlSWQiOiJDb2ZmZWVTYWZlTG9jYWxDb2YifQ.CoffeeSafeLocalCoffeeSafeLocalCoffeeSafeLo",
  },
  apis: [
    {
      base: "https://api.twenty.com",
      auth: {
        headers: {
          Authorization: "Bearer ${{ secrets.TWENTY_TOKEN }}",
        },
      },
      permissions: [],
    },
  ],
} as const satisfies FirewallConfig;
