export const ROUTES = {
  home: "/",
  selectOrg: "/select-org",
  agents: "/agents",
  agentDetail: "/agents/:id",
  agentChat: "/agents/:id/chat",
  agentIdeas: "/agents/:id/ideas",
  agentPermissions: "/agents/:id/permissions",
  activities: "/activities",
  activityInspect: "/activities/inspect",
  activityDetail: "/activities/:id",
  chatList: "/chats",
  chat: "/chats/:id",
  schedules: "/schedules",
  scheduleDetail: "/schedules/:id",
  queues: "/queues",
  works: "/works",
  ideas: "/ideas",
  connectors: "/connectors",
  directedConnect: "/connectors/:type/connect",
  directedAuthorize: "/connectors/:type/authorize",
  settings: "/settings",
  settingsUsage: "/settings/usage",
  settingsSlack: "/settings/slack",
  onboarding: "/onboarding",
  signInToken: "/sign-in-token",
  phone: "/phone",
  lab: "/_/lab",
  voiceChat: "/voice-chat",
  insights: "/insights",
  internalConnectorLogos: "/__internal-connector-logos",
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RoutePath = (typeof ROUTES)[RouteKey] | `/projects/${string}`;
