export const ROUTES = {
  home: "/",
  agents: "/agents",
  agentDetail: "/agents/:agentId",
  agentChat: "/agents/:agentId/chat",
  agentTalk: "/agents/:agentId/talk",
  agentIdeas: "/agents/:agentId/ideas",
  agentPermissions: "/agents/:agentId/permissions",
  activities: "/activities",
  activityInspect: "/activities/inspect",
  activityDetail: "/activities/:activityRunId",
  chatList: "/chats",
  chat: "/chats/:threadId",
  schedules: "/schedules",
  scheduleDetail: "/schedules/:scheduleId",
  works: "/works",
  ideas: "/ideas",
  connectors: "/connectors",
  directedConnect: "/connectors/:type/connect",
  directedAuthorize: "/connectors/:type/authorize",
  settings: "/settings",
  settingsSlack: "/settings/slack",
  settingsApiKeys: "/settings/api-keys",
  onboarding: "/onboarding",
  signInToken: "/sign-in-token",
  phone: "/phone",
  lab: "/_/lab",
  insights: "/insights",
  usage: "/_/usage",
  internalConnectorLogos: "/__internal-connector-logos",
  reportError: "/runs/:runId/report-error",
  redeemCampaign: "/redeem/:campaign",
  skeleton: "/_/skeleton",
  error: "/_/error",
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RoutePath = (typeof ROUTES)[RouteKey] | `/projects/${string}`;
