import type {
  VisualizationChart,
  VisualizationChartCategory,
} from "../../signals/okou-page/composer-visualization.ts";

export interface VisualizationChartOption {
  readonly id: VisualizationChart;
  readonly category: Exclude<VisualizationChartCategory, "all">;
}

export const FEATURED_VISUALIZATION_CHARTS = [
  "bar",
  "line",
  "donut",
  "scatter",
] as const satisfies readonly VisualizationChart[];

export const VISUALIZATION_CHART_LIBRARY = [
  { id: "bar", category: "comparison" },
  { id: "horizontal-bar", category: "comparison" },
  { id: "grouped-bar", category: "comparison" },
  { id: "stacked-bar", category: "comparison" },
  { id: "percent-stacked-bar", category: "comparison" },
  { id: "waterfall", category: "comparison" },
  { id: "bullet", category: "comparison" },
  { id: "pictorial-bar", category: "comparison" },
  { id: "polar-bar", category: "comparison" },
  { id: "lollipop", category: "comparison" },
  { id: "diverging-bar", category: "comparison" },
  { id: "bar-race", category: "comparison" },
  { id: "line", category: "trend" },
  { id: "smooth-line", category: "trend" },
  { id: "step-line", category: "trend" },
  { id: "area", category: "trend" },
  { id: "stacked-area", category: "trend" },
  { id: "theme-river", category: "trend" },
  { id: "candlestick", category: "trend" },
  { id: "threshold-line", category: "trend" },
  { id: "small-multiples", category: "trend" },
  { id: "animated-timeline", category: "trend" },
  { id: "pie", category: "composition" },
  { id: "donut", category: "composition" },
  { id: "rose", category: "composition" },
  { id: "nested-donut", category: "composition" },
  { id: "funnel", category: "composition" },
  {
    id: "comparison-funnel",
    category: "composition",
  },
  { id: "treemap", category: "composition" },
  { id: "sunburst", category: "composition" },
  { id: "liquid-fill", category: "composition" },
  { id: "scatter", category: "distribution" },
  { id: "bubble", category: "distribution" },
  { id: "ripple-scatter", category: "distribution" },
  { id: "heatmap", category: "distribution" },
  { id: "calendar-heatmap", category: "distribution" },
  { id: "box-plot", category: "distribution" },
  { id: "histogram", category: "distribution" },
  {
    id: "scatter-trendline",
    category: "distribution",
  },
  { id: "strip-plot", category: "distribution" },
  { id: "radar", category: "relationship" },
  {
    id: "parallel-coordinates",
    category: "relationship",
  },
  { id: "sankey", category: "relationship" },
  { id: "network", category: "relationship" },
  { id: "chord", category: "relationship" },
  { id: "flowchart", category: "relationship" },
  { id: "tree", category: "relationship" },
  { id: "radial-tree", category: "relationship" },
  { id: "choropleth-map", category: "map" },
  { id: "geo-scatter", category: "map" },
  { id: "route-map", category: "map" },
  { id: "gauge", category: "metric" },
  { id: "progress-ring", category: "metric" },
  { id: "grade-gauge", category: "metric" },
  { id: "kpi-card", category: "metric" },
  { id: "kpi-sparkline", category: "metric" },
  { id: "word-cloud", category: "more" },
  { id: "gantt", category: "more" },
  { id: "3d-bar", category: "more" },
  { id: "3d-scatter", category: "more" },
  { id: "3d-surface", category: "more" },
  { id: "3d-line", category: "more" },
] as const satisfies readonly VisualizationChartOption[];
